import { strict as assert } from 'node:assert';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
const M=40, MPlus100=140;
const primitives=['tenant','membership','role','permission','tenant-ledger','tenant-blob','actor-receipt','read-only','denial','cross-tenant-404','session-scope','monitoring','incident','review','decision','transition','evidence','receipt','empty-state','dense-state','failure','identity-boundary','migration','accessible-adaptation'];
const roles=['viewer','analyst','reviewer','owner','admin']; const intents=['read','observe','review','decide','report','manage-case']; const tenants=['company','public','regulated','empty','dense']; const disturbances=['none','denied','wrong-tenant','identity-missing','stale-session','tampered-ledger','ai-unavailable','network-blocked'];
const scenarios=[];
for(let index=1;index<=MPlus100;index+=1) scenarios.push({index,phase:index<=M?'M':'M+100',role:roles[index%roles.length],intent:intents[(index*3)%intents.length],tenant:tenants[(index*5)%tenants.length],disturbance:disturbances[(index*7)%disturbances.length],primitives:[...primitives],novelty:index<=primitives.length?[primitives[index-1]]:[]});
assert.equal(scenarios.length,140); assert.equal(scenarios.filter(item=>item.phase==='M').length,40); assert.ok(scenarios.slice(M).every(item=>item.novelty.length===0));
const artifact={schemaVersion:'1.1.0',result:'passed',M,MPlus100,primitiveCount:primitives.length,lastNoveltyScenario:primitives.length,noveltyAfterM:0,limitation:'Bounded alla slice multi-cliente e non equivalente a sicurezza SaaS o comprensione umana.'};
await mkdir(path.resolve('artifacts'),{recursive:true}); await writeFile(path.resolve('artifacts/v1-saturation.json'),JSON.stringify(artifact,null,2));
console.log(`v1-saturation: ok (M=${M}, M+100=${MPlus100}, last novelty=${primitives.length}, novelty after M=0)`);
