import { strict as assert } from 'node:assert';
import { spawn } from 'node:child_process';
import { mkdir, mkdtemp, rm, writeFile } from 'node:fs/promises';
import net from 'node:net'; import os from 'node:os'; import path from 'node:path';
import { deploymentPolicy, readReleaseManifest, sha256 } from './release.mjs';
const root=path.resolve(new URL('..',import.meta.url).pathname); const runtime=await mkdtemp(path.join(os.tmpdir(),'ictc-mc-stability-')); const artifacts=path.join(root,'artifacts'); await mkdir(artifacts,{recursive:true});
const freePort=()=>new Promise((resolve,reject)=>{const server=net.createServer();server.listen(0,'127.0.0.1',()=>{const {port}=server.address();server.close(error=>error?reject(error):resolve(port));});server.on('error',reject)}); const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
let child; async function start(){const port=await freePort(); child=spawn(process.execPath,['v3/server.mjs'],{cwd:root,env:{...process.env,PORT:String(port),ICTC_PORT:String(port),ICTC_HOST:'127.0.0.1',ICTC_RUNTIME_DIR:runtime,ICTC_IDENTITY_MODE:'local-directory'},stdio:['ignore','pipe','pipe']}); let error=''; child.stderr.on('data',chunk=>error+=chunk); const base=`http://127.0.0.1:${port}`; for(let i=0;i<100;i+=1){try{if((await fetch(`${base}/api/health`)).ok)return base}catch{} if(child.exitCode!==null)throw new Error(error); await sleep(50)} throw new Error(`startup timeout ${error}`)}
async function stop(){if(child&&child.exitCode===null){child.kill('SIGTERM');await Promise.race([new Promise(resolve=>child.once('exit',resolve)),sleep(2000)])}}
const headers=(actor,tenant)=>({'content-type':'application/json','x-ictc-actor-id':actor,'x-ictc-tenant-id':tenant});
async function req(base,url,{actor='local-owner',tenant='tenant-demo-company',method='GET',body,expected=null}={}){const response=await fetch(base+url,{method,headers:headers(actor,tenant),body:body===undefined?undefined:JSON.stringify(body)});const value=await response.json();if(expected!==null)assert.equal(response.status,expected,`${url}: ${JSON.stringify(value)}`);else assert.ok(response.ok,`${url}: ${response.status} ${JSON.stringify(value)}`);return value}
const manifest=await readReleaseManifest(); const receipts=[]; let base;
try{
  assert.equal(deploymentPolicy({ICTC_HOST:'0.0.0.0',ICTC_IDENTITY_MODE:'local-directory'}).networkAllowed,false);
  assert.equal(deploymentPolicy({ICTC_HOST:'0.0.0.0',ICTC_IDENTITY_MODE:'trusted-header',ICTC_TRUSTED_IDENTITY_BOUNDARY:'1'}).networkAllowed,true);
  base=await start(); const health=await req(base,'/api/health'); const release=await req(base,'/api/release'); assert.equal(health.version,'1.1.0-rc.1'); assert.equal(release.stabilityClass,'multi-client-pilot-readiness'); assert.equal(release.manifestSha256,sha256(JSON.stringify(manifest)));
  const source=await req(base,'/api/sources',{actor:'local-analyst',method:'POST',body:{title:'Fonte tenant A',url:'https://example.invalid/a',by:'spoof',tenantId:'tenant-demo-public',operatingContext:'public-administration'}}); receipts.push(source.receipt); assert.equal(source.receipt.actorId,'local-analyst'); assert.equal(source.receipt.tenantId,'tenant-demo-company'); assert.equal(source.source.operatingContext,'enterprise');
  await req(base,`/api/sources/${source.source.id}/review`,{actor:'local-analyst',method:'POST',body:{outcome:'accepted'},expected:403});
  const reviewed=await req(base,`/api/sources/${source.source.id}/review`,{actor:'local-reviewer',method:'POST',body:{outcome:'accepted'}}); receipts.push(reviewed.receipt);
  await req(base,`/api/sources/${source.source.id}/review`,{actor:'local-reviewer',tenant:'tenant-demo-public',method:'POST',body:{outcome:'accepted'},expected:404});
  const matter=await req(base,'/api/matters',{actor:'local-reviewer',tenant:'tenant-demo-public',method:'POST',body:{title:'Caso B',kind:'event',summary:'Fatto osservato nel tenant B'}}); receipts.push(matter.receipt); assert.equal(matter.matter.operatingContext,'public-administration');
  const stateA=await req(base,'/api/bootstrap'); const stateB=await req(base,'/api/bootstrap',{tenant:'tenant-demo-public'}); assert.ok(!stateA.matters.some(item=>item.id===matter.matter.id)); assert.ok(stateB.matters.some(item=>item.id===matter.matter.id));
  const sessionA=await req(base,'/api/session',{method:'POST',body:{}}); await req(base,'/api/assistant',{tenant:'tenant-demo-public',method:'POST',body:{sessionId:sessionA.sessionId,question:'stato'},expected:401});
  const ledgerA=await req(base,'/api/runtime/ledger'); const ledgerB=await req(base,'/api/runtime/ledger',{tenant:'tenant-demo-public'}); assert.equal(ledgerA.integrity.ok,true); assert.equal(ledgerB.integrity.ok,true); assert.ok(ledgerA.events.every(event=>event.tenantId==='tenant-demo-company')); assert.ok(ledgerB.events.every(event=>event.tenantId==='tenant-demo-public'));
  assert.ok(receipts.every(item=>item.readbackVerified&&item.actorId&&item.actorRole&&item.tenantId));
  const heads={a:ledgerA.integrity.head,b:ledgerB.integrity.head}; await stop(); base=await start(); assert.equal((await req(base,'/api/runtime/integrity')).head,heads.a); assert.equal((await req(base,'/api/runtime/integrity',{tenant:'tenant-demo-public'})).head,heads.b);
  const artifact={schemaVersion:'1.1.0',generatedAt:new Date().toISOString(),attestationType:'internal-engineering-readiness-attestation',externallyCertified:false,result:'passed',productVersion:'1.1.0-rc.1',stabilityClass:'multi-client-pilot-readiness',metrics:{crossTenantDisclosureCount:0,unauthorizedWriteSuccessCount:0,receiptAttributionRate:1,tenantLedgerIntegrityRate:1,criticalInScopeBlockers:release.blockers.length},limitations:manifest.excludedScope}; await writeFile(path.join(artifacts,'v1-stability-attestation.json'),JSON.stringify(artifact,null,2)); console.log(`v1-stability-audit: ok (${receipts.length} attributed receipts, 2 isolated tenants)`);
} finally {await stop(); await rm(runtime,{recursive:true,force:true})}
