#!/usr/bin/env bash
set -Eeuo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"; V3="$ROOT/v3"; STATE="${ICTC_STATE_DIR:-$ROOT/.ictc}"; RUN="$STATE/run"; LOG="$STATE/logs"; PID="$RUN/v3.pid"; OUT="$LOG/v3.log"; HOST="${ICTC_HOST:-127.0.0.1}"; PORT="${PORT:-${ICTC_PORT:-4173}}"; URL="http://$HOST:$PORT"; RUNTIME="${ICTC_RUNTIME_DIR:-$V3/runtime}"; NO_OPEN="${ICTC_NO_OPEN:-0}"; umask 077
say(){ printf '%s\n' "$*"; }; fail(){ printf 'ICTC: %s\n' "$*" >&2;exit 1; }; alive(){ [ -f "$PID" ]&&kill -0 "$(cat "$PID")" 2>/dev/null; }; health(){ curl -fsS --max-time 2 "$URL/api/health" >/dev/null 2>&1; }
preflight(){ command -v node >/dev/null||fail 'Node.js non trovato';command -v curl >/dev/null||fail 'curl non trovato';[ "$(node -p "Number(process.versions.node.split('.')[0])")" -ge 22 ]||fail 'Node.js 22+ richiesto';[ -f "$V3/server.mjs" ]||fail 'Runtime v3 assente';mkdir -p "$RUN" "$LOG" "$RUNTIME/blobs"; }
open_browser(){ [ "$NO_OPEN" = 1 ]&&return;if [ -n "${BROWSER:-}" ];then "$BROWSER" "$URL" >/dev/null 2>&1 &elif command -v xdg-open >/dev/null;then xdg-open "$URL" >/dev/null 2>&1 &elif command -v open >/dev/null;then open "$URL" >/dev/null 2>&1 &else say "Apri $URL";fi; }
start(){ preflight;if alive;then say "ICTC v3 già attivo: $URL";open_browser;return;fi;(cd "$ROOT"&&PORT="$PORT" ICTC_HOST="$HOST" ICTC_RUNTIME_DIR="$RUNTIME" nohup node v3/server.mjs >>"$OUT" 2>&1 & echo $! >"$PID");for _ in $(seq 1 60);do if health;then say "ICTC v3 attivo: $URL";open_browser;return;fi;sleep .2;done;tail -30 "$OUT" >&2||true;fail 'Avvio non completato'; }
stop(){ if ! alive;then rm -f "$PID";say 'ICTC non attivo';return;fi;kill "$(cat "$PID")" 2>/dev/null||true;sleep .3;rm -f "$PID";say 'ICTC arrestato'; }
status(){ if alive;then say "processo=attivo pid=$(cat "$PID") url=$URL";curl -fsS "$URL/api/runtime/integrity";printf '\n';else say 'processo=non attivo';return 1;fi; }
case "${1:-help}" in start)shift;[ "${1:-}" = '--no-open' ]&&NO_OPEN=1;start;;stop)stop;;restart)stop;start;;status)status;;open)open_browser;;logs)mkdir -p "$LOG";touch "$OUT";tail -f "$OUT";;doctor)preflight;say "node=$(node --version) url=$URL runtime=$RUNTIME";;test|audit)preflight;node "$V3/audit.mjs";;help|-h|--help)echo './ictc-v3.sh start [--no-open] | stop | restart | status | open | logs | doctor | test | audit';;*)fail 'Comando sconosciuto';;esac
