import http from 'node:http';import path from 'node:path';import crypto from 'node:crypto';import {readFile,writeFile,mkdir,stat} from 'node:fs/promises';import {buildState,appendEvent,readLedger,verifyLedger,proposeSourceMetadata,createMatter,buildCapsule,answerFromCapsule,selfDocumentationManifest,nowIso,sha256} from './lib/domain.mjs';
const ROOT=path.resolve(new URL('.',import.meta.url).pathname),APP=path.join(ROOT,'app'),PORT=Number(process.env.PORT||4173),sessions=new Map();
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png'};
const headers=t=>({'content-type':t,'cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer','permissions-policy':'camera=(), microphone=(), geolocation=()','content-security-policy':"default-src 'self'; style-src 'self'; script-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; frame-ancestors 'none'"});
function send(res,status,body,type='application/json; charset=utf-8'){res.writeHead(status,headers(type));res.end(type.startsWith('application/json')?JSON.stringify(body):body)}
async function json(req){let raw='';for await(const c of req){raw+=c;if(raw.length>14_000_000)throw Error('Payload oltre il limite beta')}return raw?JSON.parse(raw):{}}
async function storeBlob(input){const bytes=Buffer.from(input.contentBase64,'base64'),checksum=sha256(bytes),dir=path.join(ROOT,'runtime','blobs');await mkdir(dir,{recursive:true});const location=path.join(dir,checksum);await writeFile(location,bytes);return{checksum,location:`runtime/blobs/${checksum}`}}
async function api(req,res,url){if(req.method==='GET'&&url.pathname==='/api/health')return send(res,200,{ok:true,service:'ictc',version:'2.0.0-beta.2',localSot:true});if(req.method==='GET'&&url.pathname==='/api/bootstrap')return send(res,200,await buildState());if(req.method==='GET'&&url.pathname==='/api/runtime/integrity')return send(res,200,verifyLedger(await readLedger()));if(req.method==='GET'&&url.pathname==='/api/traces'){const s=await buildState();return send(res,200,{traces:s.views.traceCards,generatedAt:nowIso()})}if(req.method==='GET'&&url.pathname==='/api/self/manifest')return send(res,200,{writeAuthority:false,files:await selfDocumentationManifest()});if(req.method==='POST'&&url.pathname==='/api/session'){const id=crypto.randomUUID();sessions.set(id,{createdAt:Date.now(),turns:[],writeAuthority:false});return send(res,201,{sessionId:id,expiresOnClose:true,writeAuthority:false,scopeExpansion:'ui-only'})}
if(req.method==='POST'&&url.pathname==='/api/sources'){const input=await json(req);if(!input.url&&!input.contentBase64)return send(res,400,{error:'Inserire un link o un file'});const blob=input.contentBase64?await storeBlob(input):null,proposal=proposeSourceMetadata(input),sourceId=`src-user-${crypto.randomUUID().slice(0,8)}`,at=nowIso();const source={id:sourceId,ecosystemId:proposal.ecosystemId,title:input.title||input.fileName||input.url,kind:blob?'user-file':'user-link',locator:input.url||blob.location,authorityClass:'candidate-unreviewed',lifecycle:'candidate',lastCheckedAt:at,lastContentChangeAt:at,reviewState:'candidate-awaiting-review',reviewOwner:'Compliance Intake',checksum:blob?.checksum||null,submittedBy:input.submittedBy||'current-user',notes:input.notes||'',aiProposal:proposal};const finding={id:`finding-user-${crypto.randomUUID().slice(0,8)}`,sourceId,jobId:null,findingType:'new-source-proposal',detectedAt:at,statement:'Una persona ha proposto una nuova fonte per ampliare il perimetro conoscitivo.',materiality:'undetermined',aiProposal:proposal,humanState:'awaiting-review'};const r=await appendEvent('source.proposed',{source,finding},input.submittedBy||'human-user','human-submission-plus-ai-proposal');return send(res,201,{source,proposal,epistemicStatus:'candidate',receipt:r.receipt})}
let m=url.pathname.match(/^\/api\/sources\/([^/]+)\/review$/);if(req.method==='POST'&&m){const input=await json(req);if(!['accepted','rejected'].includes(input.outcome))return send(res,400,{error:'Esito review non valido'});const r=await appendEvent('source.reviewed',{sourceId:m[1],outcome:input.outcome,note:input.note||''},input.reviewedBy||'human-reviewer','human-review');return send(res,201,{sourceId:m[1],outcome:input.outcome,epistemicStatus:'human-reviewed',receipt:r.receipt})}
m=url.pathname.match(/^\/api\/findings\/([^/]+)\/review$/);if(req.method==='POST'&&m){const input=await json(req),s=await buildState();if(!s.findings.some(x=>x.id===m[1]))return send(res,404,{error:'Esito non trovato'});if(!['relevant','not-relevant'].includes(input.outcome))return send(res,400,{error:'Esito review non valido'});const r=await appendEvent('finding.reviewed',{findingId:m[1],outcome:input.outcome,note:input.note||''},input.reviewedBy||'human-reviewer','human-review');return send(res,201,{findingId:m[1],outcome:input.outcome,epistemicStatus:'human-reviewed',receipt:r.receipt})}
m=url.pathname.match(/^\/api\/scout-jobs\/([^/]+)\/run$/);if(req.method==='POST'&&m){const input=await json(req),s=await buildState(),existing=s.scoutJobs.find(x=>x.id===m[1]);if(!existing)return send(res,404,{error:'Job non trovato'});const at=nowIso(),job={...existing,lastRunAt:at,nextRunAt:new Date(Date.now()+86400000).toISOString(),lastRunState:input.simulateChange===false?'completed-no-change':'proposal-created'},finding={id:`finding-job-${crypto.randomUUID().slice(0,8)}`,sourceId:s.sources.find(x=>x.ecosystemId===existing.ecosystemId)?.id||null,jobId:m[1],findingType:input.simulateChange===false?'no-change':'content-change',detectedAt:at,statement:input.simulateChange===false?'Il controllo deterministico non ha rilevato differenze rispetto alla versione locale.':'Il controllo deterministico ha rilevato una differenza rispetto alla versione locale.',materiality:'undetermined',aiProposal:input.simulateChange===false?null:{themes:['tema proposto dal job'],summary:'Differenza sintetizzata per la review; impatto non determinato.',confidenceBand:'low'},humanState:input.simulateChange===false?'not-required':'awaiting-review'};const r=await appendEvent('scout.run.completed',{job,finding},input.actor||'scheduler',finding.aiProposal?'deterministic-job-plus-ai-proposal':'deterministic-job');return send(res,201,{job,finding,epistemicStatus:finding.aiProposal?'ai-proposed':'observed',receipt:r.receipt})}
if(req.method==='POST'&&url.pathname==='/api/matters'){const input=await json(req);if(!input.summary?.trim())return send(res,400,{error:'Descrivere cosa è successo'});const matter=createMatter(input),r=await appendEvent('matter.reported',{matter},input.reportedBy||'human-user','human-report');return send(res,201,{matter,epistemicStatus:'reported',receipt:r.receipt})}
m=url.pathname.match(/^\/api\/matters\/([^/]+)\/confirm-owner$/);if(req.method==='POST'&&m){const input=await json(req);if(!input.owner||!input.raci?.accountable||!input.raci?.responsible)return send(res,400,{error:'Owner e RACI minimi sono obbligatori'});const r=await appendEvent('matter.owner.confirmed',{matterId:m[1],owner:input.owner,raci:input.raci},input.actor||'human-owner','human-decision');return send(res,201,{matterId:m[1],epistemicStatus:'human-owned',receipt:r.receipt})}
if(req.method==='POST'&&url.pathname==='/api/assistant'){const input=await json(req);if(!sessions.has(input.sessionId))return send(res,401,{error:'Sessione locale assente o scaduta'});const capsule=buildCapsule(await buildState(),input),result=answerFromCapsule(capsule,input.question);sessions.get(input.sessionId).turns.push({capsuleId:capsule.id,question:input.question,result,at:nowIso()});return send(res,200,{capsule,...result})}return false}
async function handler(req,res){try{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(url.pathname.startsWith('/api/')){if(await api(req,res,url)!==false)return;return send(res,404,{error:'API non trovata'})}const name=url.pathname==='/'?'index.html':url.pathname.replace(/^\//,''),target=path.normalize(path.join(APP,name));if(!target.startsWith(APP))return send(res,403,'Forbidden','text/plain');await stat(target);return send(res,200,await readFile(target),mime[path.extname(target)]||'application/octet-stream')}catch(e){if(e.code==='ENOENT')return send(res,404,'Not found','text/plain');console.error(e);return send(res,500,{error:e.message})}}
const server=http.createServer(handler);server.listen(PORT,'127.0.0.1',()=>console.log(`ICTC ready on http://127.0.0.1:${PORT}`));for(const s of['SIGINT','SIGTERM'])process.on(s,()=>server.close(()=>process.exit(0)));
