import { AsyncLocalStorage } from 'node:async_hooks';
import { randomUUID } from 'node:crypto';
import { asString, canonicalJson, now, redactEndpoint, sha256 } from './domain.mjs';
import { fetchAiEndpoint } from './network-policy.mjs';
import { assertAiBudget, usageSummary } from './enterprise.mjs';
import { validateSchema } from './ai-output-schema.mjs';
import { normalizeAiKeyEnv } from './runtime/ai-secret-policy.mjs';
import { buildAiProviderRequest, providerAuthHeaders, providerContent, providerRequestId, resolveAiProvider } from './runtime/ai-provider-adapters.mjs';
import { validateRnDiscoveryOutput } from './runtime/rn-ai-output.mjs';
import { normalizeRnDiscoveredItem, normalizeRnSourceClasses, rnMiningPrompt } from './runtime/rn-monitoring-policy.mjs';

let stateProvider=null;const governanceContext=new AsyncLocalStorage();
export function configureAiGovernance(provider){stateProvider=typeof provider==='function'?provider:null;}
export function runWithAiGovernance(provider,fn){return governanceContext.run(typeof provider==='function'?provider:null,fn);}
function activeProvider(){return governanceContext.getStore()||stateProvider;}
function governance(){const provider=activeProvider();if(!provider)return null;const value=provider();if(value&&typeof value==='object'&&typeof value.state==='function')return{provider:value,state:value.state()};return{provider:null,state:value};}
function parseJsonContent(content){const text=asString(content,200000),unfenced=text.replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'');try{return JSON.parse(unfenced);}catch{const start=unfenced.indexOf('{'),end=unfenced.lastIndexOf('}');if(start>=0&&end>start)return JSON.parse(unfenced.slice(start,end+1));throw new Error('Il provider AI non ha restituito JSON valido');}}
function estimateUsage(envelope,prompt,inputJson,output,settings){const provider=envelope.usage||{},inputTokens=Number(provider.prompt_tokens??provider.input_tokens??Math.ceil((prompt.length+inputJson.length)/4)),outputTokens=Number(provider.completion_tokens??provider.output_tokens??Math.ceil(canonicalJson(output).length/4)),inputRate=Number(settings.governance?.inputCostPerMillion||0),outputRate=Number(settings.governance?.outputCostPerMillion||0);return{inputTokens,outputTokens,totalTokens:inputTokens+outputTokens,estimatedCostUsd:Number(((inputTokens*inputRate+outputTokens*outputRate)/1000000).toFixed(6)),source:provider.prompt_tokens!=null||provider.input_tokens!=null?'provider':'estimated'};}
function reserveEstimate(prompt,inputJson,settings,maxOutputTokens){const inputTokens=Math.ceil((prompt.length+inputJson.length)/4),inputRate=Number(settings.governance?.inputCostPerMillion||0),outputRate=Number(settings.governance?.outputCostPerMillion||0);return Number(((inputTokens*inputRate+maxOutputTokens*outputRate)/1000000).toFixed(6));}
async function callJsonCore(settings,purpose,systemPrompt,payload,validator,options={}){
  const gov=governance();if(gov?.state)assertAiBudget(gov.state);const profile=resolveAiProvider(settings.llm||{}),endpoint=profile.endpoint,model=profile.model;if(!endpoint||!model)throw Object.assign(new Error('Provider AI non configurato'),{status:409,code:'ai-not-configured'});const keyEnv=normalizeAiKeyEnv(profile.apiKeyEnv),key=keyEnv?process.env[keyEnv]:'';if(keyEnv&&!key)throw Object.assign(new Error(`Variabile ${keyEnv} non disponibile`),{status:409,code:'ai-key-missing'});
  const requestedAt=now(),prompt=`${systemPrompt}\n\nICTC_PURPOSE_RUNTIME:${purpose}`,inputJson=canonicalJson(payload),maxOutputTokens=Math.max(64,Math.min(32768,Number(options.maxOutputTokens||4096))),reservationId=`ai-${randomUUID()}`;let reservation=null,settled=false;
  if(gov?.state&&typeof gov.provider?.reserve==='function'){const usage=usageSummary(gov.state),reservedUsd=reserveEstimate(prompt,inputJson,settings,maxOutputTokens);try{reservation=await gov.provider.reserve({id:reservationId,month:usage.month,budgetUsd:usage.budgetUsd,observedUsageUsd:usage.estimatedCostUsd,reservedUsd,purpose,model});}catch(error){if(error.code==='ai-budget-reservation-exceeded')throw Object.assign(error,{status:429,code:'ai-budget-reservation-exceeded'});throw error;}}
  const request=buildAiProviderRequest(profile,{prompt,inputJson,maxOutputTokens,temperature:settings.llm?.temperature}),controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),Number(options.timeoutMs||45000));let response,responseText='';
  try{response=await fetchAiEndpoint(endpoint,{method:'POST',headers:{...request.headers,...providerAuthHeaders(profile,key)},body:JSON.stringify(request.body),signal:controller.signal});responseText=await response.text();if(!response.ok)throw Object.assign(new Error(`Provider AI: ${response.status}`),{status:502,code:'ai-provider-error',details:responseText.slice(0,1000)});let envelope;try{envelope=JSON.parse(responseText);}catch{throw Object.assign(new Error('Risposta del provider AI non valida'),{status:502,code:'ai-response-invalid'});}const content=providerContent(profile,envelope),parsed=typeof content==='object'&&content!==null?content:parseJsonContent(content),output=validator(parsed),usage=estimateUsage(envelope,prompt,inputJson,output,settings);if(reservation&&typeof gov.provider?.settle==='function'){await gov.provider.settle({id:reservationId,actualUsd:usage.estimatedCostUsd});settled=true;}return{output,trace:{purpose,provider:profile.provider||'custom-openai-compatible',protocol:profile.protocol,endpoint:redactEndpoint(endpoint),model,requestedAt,completedAt:now(),promptSha256:sha256(prompt),inputSha256:sha256(inputJson),outputSha256:sha256(output),providerRequestId:asString(providerRequestId(response,envelope),500),usage,budgetReservation:reservation?{id:reservationId,reservedUsd:reservation.reservedUsd??null,settled:true}:null,limitations:['Output generato da AI e validato solo rispetto al contratto strutturale runtime; contenuto e conclusioni restano da verificare umanamente.','Costi stimati quando il provider non restituisce usage.','La prenotazione atomica limita concorrenza sul budget della persistence corrente; deployment multi-store richiede la stessa semantica nel backend condiviso.']}};
  }catch(error){if(!error.status){const message=error.name==='AbortError'?'Timeout del provider AI':`Provider AI non raggiungibile: ${error.message}`;error=Object.assign(new Error(message),{status:502,code:error.name==='AbortError'?'ai-timeout':'ai-unavailable'});}throw error;}finally{clearTimeout(timeout);if(reservation&&!settled&&typeof gov.provider?.release==='function')await gov.provider.release({id:reservationId}).catch(()=>{});}
}
export function callJson(settings,purpose,systemPrompt,payload,options={}){return callJsonCore(settings,purpose,systemPrompt,payload,value=>validateSchema(purpose,value),options);}
export function callJsonWithValidator(settings,purpose,systemPrompt,payload,validator,options={}){if(typeof validator!=='function')throw Object.assign(new Error('Validator AI richiesto'),{status:500,code:'ai-validator-required'});return callJsonCore(settings,purpose,systemPrompt,payload,validator,options);}
export async function testAiProvider(settings){const profile=resolveAiProvider(settings.llm||{}),result=await callJsonCore(settings,'provider-healthcheck','Sei il test di connettività ICTC. Rispondi esclusivamente con JSON {"ok":true}.',{probe:'ictc-provider-healthcheck'},value=>{if(value?.ok!==true)throw Object.assign(new Error('Il provider non ha confermato il contratto JSON minimo'),{status:502,code:'ai-health-contract'});return{ok:true};},{maxOutputTokens:64,timeoutMs:15000});return{ok:true,provider:profile.provider||'custom-openai-compatible',protocol:profile.protocol,model:profile.model,endpoint:redactEndpoint(profile.endpoint),checkedAt:now(),trace:result.trace};}
function jobProfile(mission){return{jobName:mission.jobName||mission.objective,miningMode:mission.miningMode||'novelty',noveltyBaseline:mission.noveltyBaseline||'last-run',baselineAt:mission.baselineAt||null,jurisdictions:mission.jurisdictions||[],authorities:mission.authorities||[],changeTypes:mission.changeTypes||['new-law','amendment','repeal','guidance','effective-date'],sourceClasses:normalizeRnSourceClasses(mission.sourceClasses,{defaultAll:true}),resultLimit:Number(mission.resultLimit||50),limitation:'La novelty identifica candidati rispetto alla baseline dichiarata; non dimostra completezza, applicabilita o vigenza.'};}
const rnItemContract={title:'string',documentType:'controlled string',authority:'string',jurisdiction:'string',identifier:'string',sourceUrl:'official http(s) URL',publicationDate:'ISO date or empty',effectiveDate:'ISO date or empty',summary:'string',relevance:'string',confidence:'0..1',sourceClass:'one RN-01 source class or empty when uncertain',domainLabels:['GDPR|NIS2|DORA|231/01|81/08|190/2012|other bounded label'],applicationHypothesis:'bounded human-review hypothesis, never applicability decision',semanticConcepts:['minimal concept label'],changeType:'declared change type or empty',noveltyReason:'difference from declared baseline or empty'};
export function createMonitoringPlan(settings,mission){const prompt=rnMiningPrompt(settings.prompts.monitoringPlan,mission);return callJson(settings,'monitoring-plan',prompt,{organization:settings.organization,objective:mission.objective,cadenceHours:mission.cadenceHours,sourceHints:mission.sourceHints,jobProfile:jobProfile(mission),promptOverride:mission.promptOverride||null});}
export async function discoverCompliance(settings,mission,plan,context={}){const prompt=rnMiningPrompt(settings.prompts.complianceDiscovery,mission),raw=await callJsonWithValidator(settings,'compliance-discovery',prompt,{organization:settings.organization,objective:mission.objective,jobProfile:jobProfile(mission),plan,previousIdentifiers:context.previousIdentifiers||[],contributionContext:context.contributionContext||null,outputContract:{items:[rnItemContract]}},value=>validateRnDiscoveryOutput(value,'compliance-discovery')),items=Array.isArray(raw.output.items)?raw.output.items:[],eligible=items.map(item=>normalizeRnDiscoveredItem(item,mission)).filter(Boolean);return{...raw,output:{...raw.output,items:eligible},trace:{...raw.trace,rnPolicy:{sourceClasses:normalizeRnSourceClasses(mission.sourceClasses,{defaultAll:true}),received:items.length,accepted:eligible.length,excluded:items.length-eligible.length,closedWorld:true}}};}
export function enrichContribution(settings,contribution){const mission={sourceClasses:normalizeRnSourceClasses(null,{defaultAll:true}),promptOverride:''},prompt=rnMiningPrompt(settings.prompts.contributionEnrichment,mission);return callJsonWithValidator(settings,'contribution-enrichment',prompt,{organization:settings.organization,contribution:{note:contribution.note,links:contribution.links,text:contribution.text,attachments:contribution.attachments.map(item=>({name:item.name,mime:item.mime,bytes:item.bytes,sha256:item.sha256,trustState:item.trust?.state||'unknown'}))},outputContract:{items:[rnItemContract]},humanReviewBoundary:'AI suggests title, labels, summary, relevance, domain/application hypothesis and semantic concepts. A person verifies or rejects the resulting source candidate.'},value=>validateRnDiscoveryOutput(value,'contribution-enrichment'));}
export function analyzeIncident(settings,incident){return callJson(settings,'incident-analysis',settings.prompts.incidentAnalysis,{organization:settings.organization,originalNarrative:incident.originalNarrative,awarenessAt:incident.awarenessAt,attachments:incident.attachments.map(item=>({name:item.name,mime:item.mime,bytes:item.bytes,sha256:item.sha256,trustState:item.trust?.state||'unknown'})),outputContract:{proposedKind:'event|near-miss|incident|unknown',kindConfidence:'0..1',extractedFacts:['string'],assumptions:['string'],signals:['ongoing|personal-data|malicious|cross-border|technical-detection'],timeline:[{at:'ISO date or empty',event:'string',source:'user|attachment|inference'}],affectedServices:['string'],impact:'string',mitigations:['string'],indicators:['string'],suggestedQuestions:[{label:'string',reason:'string'}]}});}
export function draftIncident(settings,incident,questions){return callJson(settings,'incident-draft',settings.prompts.incidentDraft,{organization:settings.organization,originalNarrative:incident.originalNarrative,awarenessAt:incident.awarenessAt,attachments:incident.attachments.map(item=>({name:item.name,mime:item.mime,sha256:item.sha256,trustState:item.trust?.state||'unknown'})),analysis:incident.analysis,answers:incident.answers,unresolvedQuestions:questions,outputContract:{narrative:'string',factsUsed:['string'],unresolvedPoints:['string'],limitations:['string']}});}
