import json, os, pathlib, traceback
from playwright.sync_api import expect, sync_playwright
ART=pathlib.Path(os.environ.get('ICTC_ARTIFACT_DIR',str(pathlib.Path.cwd()/'artifacts')));ART.mkdir(exist_ok=True)
BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4173').rstrip('/');MOCK=os.environ.get('ICTC_MOCK_URL','http://127.0.0.1:4899').rstrip('/');PHASE='init'
def hdr(role): return {'x-ictc-role':role,'x-ictc-actor-id':f'local-{role}'}
def open_process(page,pid):
    page.locator('.service-nav [data-service="processes"]').click();card=page.locator(f'#procedureHub [data-procedure-id="{pid}"]');card.wait_for(state='visible');card.locator('button').click()
def open_primary(page):
    box=page.locator('#grcPrimaryForm');expect(box).to_have_count(1)
    if box.get_attribute('open') is None: box.locator(':scope > summary').click()
def decide(page,reason='Validazione browser V2',**numbers):
    d=page.locator('#grcDecisionDialog');d.wait_for(state='visible')
    for name,value in numbers.items(): d.locator(f'input[name="{name}"]').fill(str(value))
    d.locator('textarea[name="reason"]').fill(reason);d.get_by_role('button',name='Registra decisione').click();d.wait_for(state='hidden')
def error_out(error):
    payload={'ok':False,'phase':PHASE,'type':type(error).__name__,'message':str(error),'traceback':traceback.format_exc()};(ART/'browser-v2-error.json').write_text(json.dumps(payload,indent=2),encoding='utf8');print(f'::error title=browser-v2-grc-check::{PHASE}: {type(error).__name__}: {error}',flush=True)
try:
  with sync_playwright() as pw:
    launch={'headless':True,'args':['--no-sandbox']}
    if os.environ.get('ICTC_CHROMIUM'): launch['executable_path']=os.environ['ICTC_CHROMIUM']
    browser=pw.chromium.launch(**launch);ctx=browser.new_context(viewport={'width':1440,'height':1000},accept_downloads=True);ctx.add_init_script("try{localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','home')}catch{}")
    page=ctx.new_page();page.set_default_timeout(18000);page_errors=[];page.on('pageerror',lambda e:page_errors.append(str(e)))
    PHASE='entrypoint';page.goto(BASE+'/',wait_until='networkidle');expect(page.locator('html')).to_have_attribute('data-ictc-edition','v2-experimental');expect(page.locator('.service-nav [data-service]')).to_have_count(3);expect(page.locator('.service-nav')).to_contain_text('Oggi');expect(page.locator('.service-nav')).to_contain_text('Processi');expect(page.locator('.service-nav')).to_contain_text('Prove');expect(page.locator('#grcCockpit .grc-kpi')).to_have_count(5);expect(page.locator('#grcCockpit')).to_contain_text('Costruisci il primo inventario')
    PHASE='catalog';page.locator('.service-nav [data-service="processes"]').click();hub=page.locator('#procedureHub[data-procedure-hub="server-derived"]');hub.wait_for(state='visible')
    for pid,code in [('monitoring','RN-01'),('incidents','EC-01'),('evidence','EV-01'),('objects','AO-01'),('coverage','MC-01'),('actions','AP-01'),('risks','RC-01'),('assurance','AR-01')]: assert hub.locator(f'[data-procedure-id="{pid}"][data-process-code="{code}"]').count()==1,(pid,code)
    PHASE='legacy-navigation';open_process(page,'monitoring');expect(page.locator('#monitoringView')).to_be_visible();open_process(page,'incidents');expect(page.locator('#incidentsView')).to_be_visible();page.locator('.service-nav [data-service="proof"]').click();expect(page.locator('#proofView')).to_be_visible()
    PHASE='configure-ai';page.locator('.service-nav [data-service="home"]').click();page.locator('#openSettings').click();form=page.locator('#settingsForm');org=form.locator('[data-settings-section="organization"]');org.locator('summary').click() if org.get_attribute('open') is None else None;form.locator('input[name="organizationName"]').fill('Azienda V2 Browser');form.locator('textarea[name="organizationScope"]').fill('GRC, sicurezza e compliance');form.locator('input[name="jurisdictions"]').fill('Italia, Unione europea');provider=form.locator('[data-settings-section="provider"]');provider.locator('summary').click() if provider.get_attribute('open') is None else None;provider.locator('input[name="endpoint"]').fill(MOCK+'/v1/chat/completions');provider.locator('input[name="model"]').fill('mock-v2');provider.locator('input[name="apiKeyEnv"]').fill('ICTC_LLM_API_KEY');form.get_by_role('button',name='Salva configurazione AI').click();page.locator('#settingsDialog').wait_for(state='hidden')
    PHASE='ao01';open_process(page,'objects');expect(page.locator('#grcWorkspace')).to_contain_text('AO-01');open_primary(page);f=page.locator('[data-grc-form="object"]');f.locator('select[name="type"]').select_option('laptop');f.locator('input[name="name"]').fill('Notebook CFO V2');f.locator('select[name="criticality"]').select_option('high');f.locator('input[name="owner"]').fill('Finance');f.get_by_role('button',name='Registra candidato').click();expect(page.locator('#proofPulse')).to_be_visible();page.locator('[data-object-review="active"]').first.click();decide(page);expect(page.locator('#grcWorkspace')).to_contain_text('Attivo');g=ctx.request.get(BASE+'/api/grc',headers=hdr('admin')).json();obj=next(x for x in g['objects']['objects'] if x['name']=='Notebook CFO V2')
    PHASE='mc01';page.locator('[data-grc-process="coverage"]').first.click();open_primary(page);f=page.locator('[data-grc-form="mapping"]');f.locator('input[name="requirementRef"]').fill('MFA-01');f.locator('textarea[name="requirementLabel"]').fill('MFA richiesta per accessi privilegiati');f.locator('input[name="useAi"]').check();f.get_by_role('button',name='Registra proposta').click();expect(page.locator('#grcWorkspace')).to_contain_text('Proposta AI');page.locator('[data-mapping-decision="gap"]').first.click();decide(page);g=ctx.request.get(BASE+'/api/grc',headers=hdr('admin')).json();assert g['coverage']['gaps']>=1 and g['coverage']['coveragePercent']==0
    PHASE='ap01';page.locator('[data-grc-process="actions"]').first.click();open_primary(page);f=page.locator('[data-grc-form="action"]');f.locator('input[name="title"]').fill('Abilitare MFA privilegiata');f.locator('input[name="owner"]').fill('local-admin');f.locator('input[name="dueAt"]').fill('2099-01-01');f.get_by_role('button',name='Registra azione').click();page.locator('[data-action-ai]').first.click();expect(page.locator('#grcWorkspace')).to_contain_text('proposta AI');page.locator('[data-action-adopt]').first.click();decide(page,priority=4);page.locator('[data-action-progress]').filter(has_text='Avvia').first.click();g=ctx.request.get(BASE+'/api/grc',headers=hdr('admin')).json();a=next(x for x in g['actions']['actions'] if x['title']=='Abilitare MFA privilegiata');assert a['state']=='in-progress' and a['priority']==4
    PHASE='rc01';page.locator('[data-grc-process="risks"]').first.click();expect(page.locator('#grcWorkspace')).to_contain_text('Heatmap validata');open_primary(page);f=page.locator('[data-grc-form="risk"]');f.locator('input[name="title"]').fill('Accesso privilegiato senza MFA');f.locator('textarea[name="description"]').fill('Scenario derivato dal gap MFA');f.locator('input[name="useAi"]').check();f.get_by_role('button',name='Registra scenario').click();g=ctx.request.get(BASE+'/api/grc',headers=hdr('admin')).json();assert g['risks']['aiOverlay'] and sum(sum(row) for row in g['risks']['heatmap'])==0;page.locator('[data-risk-review]').first.click();decide(page,likelihood=4,impact=5);g=ctx.request.get(BASE+'/api/grc',headers=hdr('admin')).json();assert g['risks']['heatmap'][3][4]==1
    PHASE='ar01';page.locator('[data-grc-process="assurance"]').first.click();open_primary(page);f=page.locator('[data-grc-form="assurance"]');f.locator('input[name="title"]').fill('Questionario cliente V2');f.locator('textarea[name="requestText"]').fill('Descrivere MFA e logging con evidenze disponibili.');f.locator('input[name="source"]').fill('Cliente enterprise');f.get_by_role('button',name='Conserva richiesta').click();page.locator('[data-assurance-propose]').first.click();expect(page.locator('.ai-proposal textarea')).to_have_count(2);page.locator('[data-assurance-approve]').first.click();decide(page);g=ctx.request.get(BASE+'/api/grc',headers=hdr('admin')).json();case=next(x for x in g['assurance']['cases'] if x['title']=='Questionario cliente V2');assert case['state']=='approved' and len(case['approvedAnswers'])==2
    PHASE='dashboard-evidence-search';page.locator('.service-nav [data-service="home"]').click();expect(page.locator('#grcCockpit .grc-kpi')).to_have_count(5);z=ctx.request.get(f"{BASE}/api/evidence/grc-object/{obj['id']}.zip",headers=hdr('admin'));assert z.status==200 and z.body()[:4]==b'PK\x03\x04';export=ctx.request.get(BASE+'/api/export/current.json',headers=hdr('admin')).json();assert any(x['type']=='grc-object' and x['id']==obj['id'] for x in export['rows']);page.locator('#globalSearch').fill('Inventario');page.locator('#globalSearchResults [data-global-id="objects"]').click();expect(page.locator('#grcWorkspace')).to_contain_text('AO-01')
    PHASE='role-boundaries';page.locator('#roleSelect').select_option('user');open_process(page,'objects');assert page.locator('[data-object-review]').count()==0;open_process(page,'risks');assert page.locator('[data-risk-review]').count()==0;page.locator('#roleSelect').select_option('auditor');open_process(page,'risks');expect(page.locator('.risk-map')).to_be_visible();assert page.locator('#grcPrimaryForm').count()==0;assert page.locator('[data-risk-review]').count()==0;page.locator('.service-nav [data-service="proof"]').click();expect(page.locator('#proofContent')).to_be_visible();boot=ctx.request.get(BASE+'/api/bootstrap',headers=hdr('auditor')).json();assert boot['experience']['productEdition']=='V2 Experimental' and boot['grc']['readOnly'] is True and boot['exports']['authorization']=='same-as-read';assert not page_errors,page_errors
    checks=['three-item-shell','server-process-catalog','rn-ec-ev-navigation','ao01','mc01-ai-human','ap01-ai-human','rc01-human-heatmap','ar01-ai-human','receipts','evidence','export','search','role-boundaries','one-grc-workspace'];(ART/'browser-v2-grc.json').write_text(json.dumps({'ok':True,'checks':checks,'services':7},indent=2),encoding='utf8');print('browser-v2-grc-check: V2 GRC journey complete',flush=True);browser.close()
except BaseException as error:
  error_out(error);traceback.print_exc();raise
