import json, os, pathlib, traceback
from playwright.sync_api import expect, sync_playwright
from browser_test_support import ensure_onboarded
ROOT=pathlib.Path(__file__).resolve().parents[1]; ART=ROOT/'artifacts'; ART.mkdir(exist_ok=True)
BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4173').rstrip('/'); PHASE='init'
LABELS={'RN-01':'Sorveglia fonti','EC-01':'Gestisci eventi','AO-01':'Verifica inventario','MC-01':'Valuta norme e controlli','AP-01':'Gestisci remediation'}
PROC={'RN-01':('monitoring','#monitoringView','procedure-sequential-rn-ec.js'),'EC-01':('incidents','#incidentsView','procedure-sequential-rn-ec.js'),'AO-01':('objects','#grcWorkspace','grc-workspace-3-2.js'),'MC-01':('coverage','#grcWorkspace','grc-workspace-3-2.js'),'AP-01':('actions','#grcWorkspace','grc-workspace-3-2.js')}
def fail(e):
 (ART/'browser-procedure-finetuning-1-4-error.json').write_text(json.dumps({'ok':False,'phase':PHASE,'type':type(e).__name__,'message':str(e),'traceback':traceback.format_exc()},indent=2),encoding='utf8');print(f'::error title=browser-procedure-finetuning::{PHASE}: {type(e).__name__}: {e}',flush=True)
def open_process(page,code):
 global PHASE
 page.locator('.service-nav [data-service="processes"]').click();card=page.locator(f'#procedureHub [data-process-code="{code}"]');expect(card).to_be_visible();expect(card.locator('.finetune-card-nature')).to_have_count(0);expect(card.locator('.finetune-card-decision')).to_have_count(0);button=card.locator(':scope > footer .procedure-primary');expect(button).to_have_text(LABELS[code]);button.click();pid,root,owner=PROC[code];PHASE=f'{code}-owner-ready'
 page.wait_for_function("""x=>{const r=document.querySelector(x.root),d=r?.querySelector(':scope > .procedure-support-rail > [data-editorial-slot="advanced-context"] > .procedure-anatomy');return !!(r&&r.offsetParent!==null&&r.dataset.editorialOwner===x.owner&&r.dataset.editorialOrderValid==='true'&&r.dataset.compositionSurface===x.pid&&d)}""",arg={'root':root,'owner':owner,'pid':pid})
def no_orphans(page,root):
 bad=page.locator(root).evaluate("r=>[...r.querySelectorAll('button,a[href],summary')].filter(n=>n.offsetParent!==null).filter(n=>!n.dataset.journeyProcess||!n.dataset.journeyStage||!n.dataset.journeyIntent||!n.dataset.journeyAuthority||!n.dataset.journeyEvidenceEffect).map(n=>n.outerHTML.slice(0,220))")
 assert not bad,(root,bad[:10])
def no_overflow(page):
 m=page.evaluate("()=>({w:innerWidth,html:document.documentElement.scrollWidth,body:document.body.scrollWidth})");assert max(m['html'],m['body'])<=m['w']+1,m
def context_closed(page,root):
 detail=page.locator(f'{root} > .procedure-support-rail > [data-editorial-slot="advanced-context"] > .procedure-anatomy');expect(detail).to_have_count(1);expect(detail).not_to_have_attribute('open','');summary=detail.locator(':scope > summary');expect(summary).to_have_attribute('data-journey-intent','inspect-progressive-detail')
def optional_record_facts(cards,needles):
 if cards.count()==0:return
 facts=cards.first.locator('.procedure-record-facts');expect(facts).to_be_visible()
 for needle in needles:expect(facts).to_contain_text(needle)
try:
 with sync_playwright() as pw:
  launch={'headless':True,'args':['--no-sandbox']}
  if os.environ.get('ICTC_CHROMIUM'):launch['executable_path']=os.environ['ICTC_CHROMIUM']
  browser=pw.chromium.launch(**launch);ctx=browser.new_context(viewport={'width':1440,'height':950});ctx.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','processes')");page=ctx.new_page();page.set_default_timeout(30000);writes=[];ensure_onboarded(page,BASE,'admin');page.on('request',lambda req:writes.append({'method':req.method,'url':req.url}) if req.url.startswith(BASE+'/api/') and req.method!='GET' else None);page.goto(BASE+'/?view=processes',wait_until='networkidle')
  PHASE='hub';expect(page.locator('#procedureHub .procedure-card')).to_have_count(7)
  for code,label in LABELS.items():
   c=page.locator(f'#procedureHub [data-process-code="{code}"]');expect(c).to_be_visible();expect(c.locator('.finetune-card-nature')).to_have_count(0);expect(c.locator('.finetune-card-decision')).to_have_count(0);expect(c.locator(':scope > footer .procedure-primary')).to_have_text(label);no_orphans(page,f'#procedureHub [data-process-code="{code}"]')
  PHASE='rn';open_process(page,'RN-01');PHASE='rn';expect(page.locator('#monitoringView > [data-finetune-compass="monitoring"]')).to_have_count(0);context_closed(page,'#monitoringView');no_orphans(page,'#monitoringView');manager=page.locator('#monitoringView [data-open-monitor-manager]');expect(manager).to_have_count(1);expect(manager).to_have_text('Gestisci monitoraggi');manager.click();monitor=page.locator('#monitorManagerDialog');expect(monitor).to_be_visible();expect(monitor.locator('[data-monitor-manager-search]')).to_be_visible();expect(monitor.locator('[data-monitor-manager-count]')).to_be_visible();rows=monitor.locator('[data-monitor-manager-id]');registry=page.locator('#monitoringView > [data-rn-monitoring-secondary][data-a6-registry="monitoring"]');total=int(registry.get_attribute('data-a6-registry-total') or '0');assert rows.count()==total,(rows.count(),total);if rows.count():expect(rows.first.locator('[data-open-plan]')).to_have_text('Apri monitoraggio');monitor.locator('button[aria-label="Chiudi"]').click();expect(monitor).not_to_be_visible()
  PHASE='ec';open_process(page,'EC-01');PHASE='ec';expect(page.locator('#incidentsView > [data-finetune-compass="incidents"]')).to_have_count(0);context_closed(page,'#incidentsView');no_orphans(page,'#incidentsView');page.locator('.procedure-frame:visible .procedure-primary').click();expect(page.locator('#incidentDialog')).to_be_visible();expect(page.locator('#incidentDialog [name="caseTitle"]')).to_be_visible();no_orphans(page,'#incidentDialog');page.locator('#incidentDialog button[aria-label="Chiudi"]').click()
  PHASE='ao';open_process(page,'AO-01');PHASE='ao';expect(page.locator('#grcWorkspace > [data-finetune-compass="objects"]')).to_have_count(0);context_closed(page,'#grcWorkspace');records=page.locator('#grcWorkspace .grc-list');expect(records).to_be_visible();cards=records.locator(':scope > article.procedure-record-card');expect(cards).to_have_count(records.locator(':scope > article').count());expect(page.locator('#grcWorkspace [data-seq-ao-search]')).to_be_visible();expect(page.locator('#grcWorkspace [data-seq-ao-filter]')).to_be_visible();optional_record_facts(cards,['Responsabile','Riesame']);no_orphans(page,'#grcWorkspace')
  PHASE='mc';open_process(page,'MC-01');PHASE='mc';expect(page.locator('#grcWorkspace > [data-finetune-compass="coverage"]')).to_have_count(0);context_closed(page,'#grcWorkspace');expect(page.locator('#grcWorkspace [data-framework-card]')).to_have_count(21);expect(page.locator('#grcWorkspace .finetune-concept-drilldown:visible')).to_have_count(0);scopes=page.locator('#grcWorkspace .market-scope-editor');expect(scopes).to_have_count(21);expect(scopes.first.locator(':scope > summary')).to_be_visible();understand=page.locator('#grcWorkspace [data-open-standard-browser]');expect(understand).to_have_count(21);expect(understand.first).to_have_text('Comprendi standard');understand.first.click();dialog=page.locator('#standardBrowserDialog');expect(dialog).to_be_visible();expect(dialog.locator('[data-standard-nodes]')).to_be_visible();expect(dialog.locator('[data-standard-detail]')).to_be_visible();dialog.locator('button[aria-label="Chiudi"]').click();no_orphans(page,'#grcWorkspace')
  PHASE='ap';open_process(page,'AP-01');PHASE='ap';expect(page.locator('#grcWorkspace > [data-finetune-compass="actions"]')).to_have_count(0);context_closed(page,'#grcWorkspace');records=page.locator('#grcWorkspace .grc-list');expect(records).to_be_visible();cards=records.locator(':scope > article.procedure-record-card');optional_record_facts(cards,['Origine','Prossimo']);no_orphans(page,'#grcWorkspace')
  mobile=browser.new_context(viewport={'width':390,'height':844});mobile.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','processes')");m=mobile.new_page();m.set_default_timeout(30000);mobile_writes=[];ensure_onboarded(m,BASE,'admin');m.on('request',lambda req:mobile_writes.append({'method':req.method,'url':req.url}) if req.url.startswith(BASE+'/api/') and req.method!='GET' else None);m.goto(BASE+'/?view=processes',wait_until='networkidle');PHASE='mobile-hub';no_overflow(m);open_process(m,'AO-01');PHASE='mobile-ao';no_overflow(m);mobile_records=m.locator('#grcWorkspace .grc-list');expect(mobile_records).to_be_visible();mobile_cards=mobile_records.locator(':scope > article.procedure-record-card');optional_record_facts(mobile_cards,['Responsabile','Riesame']);assert not mobile_writes,mobile_writes;mobile.close()
  PHASE='read-only-boundary';assert not writes,writes
  out={'ok':True,'profile':'runtime-contraction+semantic-composition-3.1+s4-a6-ux3','procedures':list(LABELS),'readOnly':True,'emptyAndPopulatedStateTolerant':True,'hubNarrativeNoise':False,'decisionContextProgressive':True,'journeyMetadataPreserved':True,'rn':{'monitorManager':'monitorManagerDialog','granularJobs':True,'legacySchedulerFirstPlane':False},'ec':{'humanCaseTitle':True},'ao':{'sharedRecordFactsWhenPresent':True,'searchFacet':True},'mc':{'frameworks':21,'singleUnderstandStandardEntry':True,'scopePopup':True,'legacyConceptDrilldownVisible':False},'ap':{'sharedOriginAndNextFactsWhenPresent':True},'mobileOverflow':False,'writeCount':len(writes),'evidenceClass':'E2 server-backed browser presentation oracle; read-only and tolerant of empty or populated state; not a stateful business journey, human usability, legal review or independent assurance'};(ART/'browser-procedure-finetuning-1-4.json').write_text(json.dumps(out,indent=2),encoding='utf8');print('browser-procedure-finetuning-a6-ux3: complete',flush=True);ctx.close();browser.close()
except BaseException as e:fail(e);traceback.print_exc();raise
