import json, os, pathlib, traceback
from playwright.sync_api import expect, sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1] if pathlib.Path(__file__).resolve().parent.name=='v3' else pathlib.Path('/tmp')
ART=pathlib.Path(os.environ.get('ICTC_ARTIFACT_DIR', str(pathlib.Path.cwd()/'artifacts')));ART.mkdir(exist_ok=True)
BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4173').rstrip('/');MOCK=os.environ.get('ICTC_MOCK_URL','http://127.0.0.1:4899').rstrip('/');PHASE='initialization'
def headers(role): return {'x-ictc-role':role,'x-ictc-actor-id':f'local-{role}'}
def fail(error):
    payload={'ok':False,'phase':PHASE,'type':type(error).__name__,'message':str(error),'traceback':traceback.format_exc()};(ART/'browser-v2-error.json').write_text(json.dumps(payload,indent=2),encoding='utf8');print(f'::error title=browser-v2-grc-check::{PHASE}: {type(error).__name__}: {error}',flush=True)
def open_process(page,pid):
    page.locator('.service-nav [data-service="processes"]').click();card=page.locator(f'#procedureHub [data-procedure-id="{pid}"]');card.wait_for(state='visible');card.locator('button').click()
def open_primary(page):
    d=page.locator('#grcPrimaryForm');expect(d).to_have_count(1)
    if d.get_attribute('open') is None: d.locator(':scope > summary').click()
def dialogs(page):
    def handle(d):
        m=d.message.lower()
        if 'priorità operativa' in m: d.accept('4')
        elif 'likelihood' in m: d.accept('4')
        elif 'impact' in m: d.accept('5')
        else: d.accept('Validazione browser V2')
    page.on('dialog',handle)
try:
  with sync_playwright() as playwright:
    launch={'headless':True,'args':['--no-sandbox']}
    if os.environ.get('ICTC_CHROMIUM'): launch['executable_path']=os.environ['ICTC_CHROMIUM']
    browser=playwright.chromium.launch(**launch);context=browser.new_context(viewport={'width':1440,'height':1000},accept_downloads=True);context.add_init_script("try{localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','home')}catch{}")
    page=context.new_page();page.set_default_timeout(18000);errors=[];page.on('pageerror',lambda e:errors.append(str(e)));dialogs(page)
    PHASE='v2-entrypoint';page.goto(f'{BASE}/',wait_until='networkidle');expect(page.locator('html')).to_have_attribute('data-ictc-experience','active-1');expect(page.locator('html')).to_have_attribute('data-ictc-edition','v2-experimental');expect(page.locator('.service-nav [data-service]')).to_have_count(3);expect(page.locator('.service-nav')).to_contain_text('Oggi');expect(page.locator('.service-nav')).to_contain_text('Processi');expect(page.locator('.service-nav')).to_contain_text('Prove');assert page.locator('.service-nav [data-service="grc"]').count()==0
    expect(page.locator('#grcCockpit')).to_be_visible();expect(page.locator('#grcCockpit .grc-kpi')).to_have_count(5);expect(page.locator('#grcCockpit')).to_contain_text('Costruisci il primo inventario')
    page.locator('.service-nav [data-service="processes"]').click();hub=page.locator('#procedureHub[data-procedure-hub="server-derived"]');hub.wait_for(state='visible');
    for pid,code in [('monitoring','RN-01'),('incidents','EC-01'),('evidence','EV-01'),('objects','AO-01'),('coverage','MC-01'),('actions','AP-01'),('risks','RC-01'),('assurance','AR-01')]: assert hub.locator(f'[data-procedure-id="{pid}"][data-process-code="{code}"]').count()==1,(pid,code)
    assert hub.locator('[data-procedure-id="administration"]').count()==1
    PHASE='configure-ai';page.locator('.service-nav [data-service="home"]').click();page.locator('#openSettings').click();settings=page.locator('#settingsForm');settings.locator('[data-settings-section="organization"] summary').click() if settings.locator('[data-settings-section="organization"]').get_attribute('open') is None else None;settings.locator('input[name="organizationName"]').fill('Azienda V2 Browser');settings.locator('textarea[name="organizationScope"]').fill('GRC, sicurezza e compliance in Italia e UE');settings.locator('input[name="jurisdictions"]').fill('Italia, Unione europea');provider=settings.locator('[data-settings-section="provider"]');provider.locator('summary').click() if provider.get_attribute('open') is None else None;provider.locator('input[name="endpoint"]').fill(f'{MOCK}/v1/chat/completions');provider.locator('input[name="model"]').fill('mock-v2');provider.locator('input[name="apiKeyEnv"]').fill('ICTC_LLM_API_KEY');settings.get_by_role('button',name='Salva configurazione AI').click();page.locator('#settingsDialog').wait_for(state='hidden')
    PHASE='rn01-regression';open_process(page,'monitoring');mission=page.locator('#missionForm');mission.locator('textarea[name="objective"]').fill('Fonti ufficiali su sicurezza informazioni e cloud UE');mission.locator('select[name="cadence"]').select_option('168');mission.locator('input[name="sourceHints"]').fill('https://eur-lex.europa.eu');mission.get_by_role('button',name='Crea piano').click();page.locator('#planDialog').wait_for(state='visible');page.get_by_role('button',name='Attiva monitoraggio').click();page.locator('[data-close="planDialog"]').click();page.locator('.mission-card').first.get_by_role('button',name='Esegui ora').click();page.locator('[data-open-source]').first.wait_for();boot=context.request.get(f'{BASE}/api/bootstrap',headers=headers('admin')).json();candidate=next(x for x in boot['catalog'] if x['state']=='candidate');page.locator('.service-nav [data-service="home"]').click();page.locator('#homePrimaryAction').click();page.locator('#sourceDialog').wait_for(state='visible');page.locator('#sourceDecisionReason').fill('Fonte ufficiale verificata da operatore umano');page.locator('[data-source-decision="verified"]').click();page.locator('[data-close="sourceDialog"]').click()
    PHASE='ao01';open_process(page,'objects');expect(page.locator('html')).to_have_attribute('data-ictc-workspace','grc');expect(page.locator('#grcWorkspace')).to_contain_text('AO-01');open_primary(page);form=page.locator('[data-grc-form="object"]');form.locator('select[name="type"]').select_option('laptop');form.locator('input[name="name"]').fill('Notebook CFO V2');form.locator('select[name="criticality"]').select_option('high');form.locator('input[name="owner"]').fill('Finance');form.get_by_role('button',name='Registra candidato').click();expect(page.locator('#proofPulse')).to_be_visible();page.locator('[data-object-review="active"]').first.click();expect(page.locator('#grcWorkspace')).to_contain_text('active');g=context.request.get(f'{BASE}/api/grc',headers=headers('admin')).json();obj=next(x for x in g['objects']['objects'] if x['name']=='Notebook CFO V2');assert obj['status']=='active'
    PHASE='mc01-ai-human';page.locator('[data-grc-process="coverage"]').first.click();expect(page.locator('#grcWorkspace')).to_contain_text('MC-01');open_primary(page);form=page.locator('[data-grc-form="mapping"]');form.locator('input[name="requirementRef"]').fill('MFA-01');form.locator('textarea[name="requirementLabel"]').fill('MFA richiesta per accessi privilegiati');form.locator('input[name="useAi"]').check();form.get_by_role('button',name='Registra proposta').click();expect(page.locator('#grcWorkspace')).to_contain_text('Proposta AI');page.locator('[data-mapping-decision="gap"]').first.click();g=context.request.get(f'{BASE}/api/grc',headers=headers('admin')).json();assert g['coverage']['gaps']>=1 and g['coverage']['coveragePercent']==0
    PHASE='ap01-ai-human';page.locator('[data-grc-process="actions"]').first.click();open_primary(page);form=page.locator('[data-grc-form="action"]');form.locator('input[name="title"]').fill('Abilitare MFA privilegiata');form.locator('input[name="owner"]').fill('local-admin');form.locator('input[name="dueAt"]').fill('2099-01-01');form.get_by_role('button',name='Registra azione').click();page.locator('[data-action-ai]').first.click();expect(page.locator('#grcWorkspace')).to_contain_text('proposta AI');page.locator('[data-action-adopt]').first.click();page.locator('[data-action-progress]').filter(has_text='Avvia').first.click();g=context.request.get(f'{BASE}/api/grc',headers=headers('admin')).json();action=next(x for x in g['actions']['actions'] if x['title']=='Abilitare MFA privilegiata');assert action['state']=='in-progress' and action['priority']==4
    PHASE='rc01-ai-human-heatmap';page.locator('[data-grc-process="risks"]').first.click();expect(page.locator('#grcWorkspace')).to_contain_text('Heatmap validata');open_primary(page);form=page.locator('[data-grc-form="risk"]');form.locator('input[name="title"]').fill('Accesso privilegiato senza MFA');form.locator('textarea[name="description"]').fill('Scenario derivato dal gap MFA');form.locator('input[name="useAi"]').check();form.get_by_role('button',name='Registra scenario').click();g=context.request.get(f'{BASE}/api/grc',headers=headers('admin')).json();assert g['risks']['aiOverlay'] and sum(sum(r) for r in g['risks']['heatmap'])==0;page.locator('[data-risk-review]').first.click();g=context.request.get(f'{BASE}/api/grc',headers=headers('admin')).json();assert sum(sum(r) for r in g['risks']['heatmap'])==1;assert g['risks']['heatmap'][3][4]==1
    PHASE='ar01-ai-human';page.locator('[data-grc-process="assurance"]').first.click();open_primary(page);form=page.locator('[data-grc-form="assurance"]');form.locator('input[name="title"]').fill('Questionario cliente V2');form.locator('textarea[name="requestText"]').fill('Descrivere MFA e logging con evidenze disponibili.');form.locator('input[name="source"]').fill('Cliente enterprise');form.get_by_role('button',name='Conserva richiesta').click();page.locator('[data-assurance-propose]').first.click();expect(page.locator('.ai-proposal')).to_be_visible();expect(page.locator('.ai-proposal textarea')).to_have_count(2);page.locator('[data-assurance-approve]').first.click();g=context.request.get(f'{BASE}/api/grc',headers=headers('admin')).json();case=next(x for x in g['assurance']['cases'] if x['title']=='Questionario cliente V2');assert case['state']=='approved' and len(case['approvedAnswers'])==2
    PHASE='dashboard-evidence-search';page.locator('.service-nav [data-service="home"]').click();expect(page.locator('#grcCockpit .grc-kpi')).to_have_count(5);expect(page.locator('#grcCockpit')).to_contain_text('Copertura dichiarata');zipr=context.request.get(f"{BASE}/api/evidence/grc-object/{obj['id']}.zip",headers=headers('admin'));assert zipr.status==200 and zipr.body()[:4]==b'PK\x03\x04';export=context.request.get(f'{BASE}/api/export/current.json',headers=headers('admin')).json();assert any(x['type']=='grc-object' and x['id']==obj['id'] for x in export['rows']);page.locator('#globalSearch').fill('Inventario');page.locator('#globalSearchResults [data-global-kind="procedure"][data-global-id="objects"]').click();expect(page.locator('#grcWorkspace')).to_contain_text('AO-01')
    PHASE='ec01-user-and-role-boundaries';page.locator('#roleSelect').select_option('user');open_process(page,'incidents');page.locator('#openIncident').click();incident=page.locator('#incidentForm');incident.locator('textarea[name="originalNarrative"]').fill('Quasi incidente: email sospetta bloccata prima dell’apertura');incident.get_by_role('button',name='Registra evento').click();page.locator('#incidentWorkspace').wait_for(state='visible');page.locator('[data-close="incidentWorkspace"]').click();open_process(page,'objects');assert page.locator('[data-object-review]').count()==0;open_process(page,'risks');assert page.locator('[data-risk-review]').count()==0
    PHASE='auditor-readonly-proof';page.locator('#roleSelect').select_option('auditor');open_process(page,'risks');expect(page.locator('.risk-map')).to_be_visible();assert page.locator('#grcPrimaryForm').count()==0;assert page.locator('[data-risk-review]').count()==0;page.locator('.service-nav [data-service="proof"]').click();page.locator('#proofContent').wait_for(state='visible');body=context.request.get(f'{BASE}/api/bootstrap',headers=headers('auditor')).json();assert body['experience']['productEdition']=='V2 Experimental';assert body['accessProfile']['mode']=='read-only';assert body['grc']['readOnly'] is True;assert body['decisions']['authority']=='human-decision-projection';assert body['epistemic']['authority']=='runtime-epistemic-projection';assert body['exports']['authorization']=='same-as-read';assert not errors,errors
    checks=['professional-three-item-shell','server-process-catalog','rn01-regression','ec01-regression','ao01-inventory','mc01-ai-proposal-human-gap','ap01-ai-priority-human-adoption','rc01-human-only-heatmap','ar01-ai-draft-human-approval','progressive-disclosure','persistent-todos','receipt-pulse','same-as-read-evidence','role-scoped-search','auditor-read-only','one-grc-workspace'];(ART/'browser-v2-grc.json').write_text(json.dumps({'ok':True,'checks':checks,'productEdition':'V2 Experimental','services':7},indent=2),encoding='utf8');print('browser-v2-grc-check: V2 all-service evidence complete',flush=True);browser.close()
except BaseException as error:
  fail(error);traceback.print_exc();raise
