import json, os, pathlib, traceback
from playwright.sync_api import expect, sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1]; ART=ROOT/'artifacts'; ART.mkdir(exist_ok=True)
BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4173').rstrip('/'); PHASE='init'
P={'RN-01':'monitoring','EC-01':'incidents','AO-01':'grc','MC-01':'grc','AP-01':'grc','RC-01':'grc','AR-01':'grc'}
def fail(e):
 payload={'ok':False,'phase':PHASE,'type':type(e).__name__,'message':str(e),'traceback':traceback.format_exc()}; (ART/'browser-v1-9-error.json').write_text(json.dumps(payload,indent=2),encoding='utf8'); print(f'::error title=browser-v1-9::{PHASE}: {type(e).__name__}: {e}',flush=True)
def processes(page): return page.locator('.service-nav [data-service="processes"]')
def openp(page,code):
 processes(page).click(); c=page.locator(f'#procedureHub [data-process-code="{code}"]'); expect(c).to_be_visible(); expect(c.locator(':scope > footer .primary')).to_have_text('Apri'); c.locator(':scope > footer .primary').click(); page.wait_for_timeout(120)
def no_overflow(page):
 m=page.evaluate('()=>[innerWidth,document.documentElement.scrollWidth,document.body.scrollWidth]'); assert m[1]<=m[0]+1 and m[2]<=m[0]+1,m
def named(page):
 bad=page.locator('button:visible,input:visible,select:visible,textarea:visible').evaluate_all("els=>els.filter(e=>{const direct=e.getAttribute('aria-label')||e.getAttribute('title')||e.getAttribute('placeholder')||e.textContent.trim();const labs=e.labels&&[...e.labels].some(x=>x.textContent.trim());return !(direct||labs)}).map(e=>e.outerHTML.slice(0,180))")
 assert not bad,bad
def painted(page,root='body'):
 bad=page.locator(root).evaluate("r=>[...r.querySelectorAll('button')].filter(e=>{const b=e.getBoundingClientRect();if(!b.width||!b.height)return false;const t=e.textContent.trim();if(!t)return false;const s=getComputedStyle(e);return s.visibility!=='hidden'&&s.display!=='none'&&s.opacity!=='0'&&s.backgroundImage==='none'&&s.color===s.backgroundColor}).map(e=>({text:e.textContent.trim(),cls:e.className,color:getComputedStyle(e).color,bg:getComputedStyle(e).backgroundColor}))")
 assert not bad,bad
def one_scroll_owner(page,root):
 n=page.locator(root).evaluate("r=>[r,...r.querySelectorAll('*')].filter(e=>{const s=getComputedStyle(e),b=e.getBoundingClientRect();return b.width>0&&b.height>0&&/(auto|scroll)/.test(s.overflowY)&&e.scrollHeight>e.clientHeight+2}).length")
 assert n<=1,(root,n)
def body_locked(page): assert page.evaluate("()=>getComputedStyle(document.body).overflow==='hidden'"),page.evaluate("()=>getComputedStyle(document.body).overflow")
try:
 with sync_playwright() as pw:
  launch={'headless':True,'args':['--no-sandbox']}
  if os.environ.get('ICTC_CHROMIUM'): launch['executable_path']=os.environ['ICTC_CHROMIUM']
  browser=pw.chromium.launch(**launch)
  ctx=browser.new_context(viewport={'width':1440,'height':950}); ctx.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','home')")
  page=ctx.new_page(); page.set_default_timeout(30000); errors=[]; page.on('pageerror',lambda e:errors.append(str(e)))
  PHASE='home'; page.goto(BASE+'/',wait_until='networkidle'); expect(page.locator('html')).to_have_attribute('data-ictc-edition','1.2-market-candidate'); expect(page.locator('html')).to_have_attribute('data-ictc-experience-edition','1.9-experience-candidate'); expect(page.locator('.service-nav [data-service="home"]')).to_have_text('Home'); expect(page.locator('.service-nav [data-service="processes"]')).to_have_text('Processi'); expect(page.locator('.service-nav [data-service="proof"]')).to_have_text('Postura Standard & Security ICTC'); named(page); painted(page); page.screenshot(path=str(ART/'ux-v19-home.png'),full_page=True)
  PHASE='command'; page.keyboard.press('Control+K'); expect(page.locator('#globalCommandDialog')).to_be_visible(); expect(page.locator('#globalSearch')).to_be_focused(); t=page.locator('#globalSearchResults').inner_text(); assert all(x in t for x in ['Home','Processi','Postura Standard & Security ICTC']); page.locator('#globalSearch').fill('Rischi'); expect(page.locator('#globalSearchResults')).to_contain_text('Rischi'); named(page); painted(page,'#globalCommandDialog'); one_scroll_owner(page,'#globalCommandDialog'); page.keyboard.press('Escape')
  PHASE='hub'; processes(page).click(); expect(page.locator('#procedureHub .procedure-card')).to_have_count(7)
  for code in P:
   c=page.locator(f'#procedureHub [data-process-code="{code}"]'); expect(c).to_contain_text('Scopo della procedura'); expect(c.locator(':scope > footer .primary')).to_have_count(1)
  named(page); painted(page); page.screenshot(path=str(ART/'ux-v19-processes.png'),full_page=True)
  PHASE='seven'; seen=[]
  for code,surface in P.items():
   PHASE=f'seven:{code}'; openp(page,code); expect(page.locator('html')).to_have_attribute('data-ictc-surface',surface); f=page.locator('.procedure-frame[data-procedure-frame="canonical-1-9"]:visible'); expect(f).to_have_count(1); expect(f).to_contain_text('Scopo della procedura'); expect(f.locator('.procedure-primary')).to_have_count(1); assert page.locator(f'#{surface}View > .workspace-return:visible').count()==0; named(page); painted(page); page.screenshot(path=str(ART/f'ux-v19-{code.lower()}.png'),full_page=True); seen.append(code)
  PHASE='contribution-dialog'; openp(page,'RN-01'); page.locator('.procedure-frame:visible .procedure-primary').click(); expect(page.locator('#contributionDialog')).to_be_visible(); one_scroll_owner(page,'#contributionDialog'); body_locked(page); named(page); painted(page,'#contributionDialog'); page.screenshot(path=str(ART/'ux-v19-contribution-dialog.png'),full_page=True); page.locator('#contributionDialog button[aria-label="Chiudi"]').click()
  PHASE='incident-intake'; openp(page,'EC-01'); page.locator('.procedure-frame:visible .procedure-primary').click(); expect(page.locator('#incidentDialog')).to_be_visible(); one_scroll_owner(page,'#incidentDialog'); body_locked(page); ratio=page.evaluate("()=>{const p=document.querySelector('#incidentDialog .prompt-field').getBoundingClientRect(),b=document.querySelector('#incidentDialog .dialog-body').getBoundingClientRect();return p.width/b.width}"); assert ratio>=.55,ratio; expect(page.locator('#incidentDialog [data-market-event-fields]')).to_be_attached(); assert page.locator('#incidentDialog aside [data-market-event-fields]').count()==1; named(page); painted(page,'#incidentDialog'); page.screenshot(path=str(ART/'ux-v19-incident-intake.png'),full_page=True); page.locator('#incidentDialog textarea[name="originalNarrative"]').fill('Evento osservato durante il test di polish; nessuna conclusione sostanziale viene inferita.'); page.locator('#incidentDialog input[name="awarenessAt"]').fill('2026-08-10T12:00'); page.locator('#incidentDialog button[type="submit"]').click(); expect(page.locator('#incidentDialog')).not_to_be_visible(); page.wait_for_timeout(180)
  PHASE='incident-card-painted'; card=page.locator('#incidentList .incident-card').first; expect(card).to_be_visible(); painted(page,'#incidentList'); expect(card.locator('[data-open-incident]')).to_have_text('Apri'); card.locator('[data-open-incident]').click(); expect(page.locator('#incidentWorkspace')).to_be_visible(); one_scroll_owner(page,'#incidentWorkspace'); body_locked(page); named(page); painted(page,'#incidentWorkspace'); ifq=page.locator('#incidentWorkspace .question-compass');
  if ifq.count() and ifq.is_visible():
   expect(ifq.locator('.refined-question-why')).to_be_attached(); qtop=page.locator('#incidentWorkspace #questionValue').evaluate('e=>e.getBoundingClientRect().top'); assert qtop<850,qtop
  page.screenshot(path=str(ART/'ux-v19-incident-workspace.png'),full_page=True); page.locator('#incidentWorkspace button[aria-label="Chiudi"]').click()
  PHASE='history'; processes(page).click(); risk=page.locator('#procedureHub [data-process-code="RC-01"]'); expect(risk).to_be_visible(); risk.locator(':scope > footer .primary').click(); assert 'view=grc' in page.url and 'procedure=risks' in page.url; page.go_back(wait_until='networkidle'); expect(page.locator('#processesView')).to_be_visible(); page.go_forward(wait_until='networkidle'); expect(page.locator('#grcView')).to_be_visible()
  PHASE='deep-link'; page.goto(BASE+'/?view=grc&procedure=coverage',wait_until='networkidle'); expect(page.locator('.procedure-frame:visible')).to_contain_text('Standard'); expect(page.locator('[data-framework-card]')).to_have_count(21)
  PHASE='standard-browser'; gdpr=page.locator('[data-framework-card="eu-gdpr-2016-679"]'); gdpr.locator('[data-open-standard-browser]').click(); expect(page.locator('#standardBrowserDialog')).to_be_visible(); page.locator('[data-standard-search]').fill('Art. 32'); expect(page.locator('[data-standard-nodes]')).to_contain_text('Art. 32'); one_scroll_owner(page,'#standardBrowserDialog'); named(page); painted(page,'#standardBrowserDialog'); page.screenshot(path=str(ART/'ux-v19-standard-browser.png'),full_page=True); page.locator('#standardBrowserDialog button[aria-label="Chiudi"]').click()
  PHASE='auditor'; ac=browser.new_context(viewport={'width':1280,'height':850}); ac.add_init_script("localStorage.setItem('ictc-role','auditor');localStorage.setItem('ictc-service','processes')"); a=ac.new_page(); a.goto(BASE+'/',wait_until='networkidle'); openp(a,'AP-01'); primary=a.locator('.procedure-frame:visible .procedure-primary'); expect(primary).to_have_text('Consulta record'); before=a.locator('main > .view:not([hidden])').get_attribute('id'); primary.click(); a.wait_for_timeout(120); after=a.locator('main > .view:not([hidden])').get_attribute('id'); assert before==after=='grcView',(before,after); expect(a.locator('#grcWorkspace .grc-body')).to_be_visible(); expect(a.locator('#grcWorkspace .procedure-anatomy')).to_be_visible(); named(a); painted(a); a.screenshot(path=str(ART/'ux-v19-auditor-read.png'),full_page=True); ac.close()
  PHASE='mobile'; mc=browser.new_context(viewport={'width':390,'height':844}); mc.add_init_script("localStorage.setItem('ictc-role','user');localStorage.setItem('ictc-service','home')"); m=mc.new_page(); m.goto(BASE+'/',wait_until='networkidle'); no_overflow(m); expect(m.locator('#globalCommandTrigger')).to_be_visible(); expect(m.locator('.service-nav [data-service="proof"]')).to_have_attribute('aria-label','Postura Standard & Security ICTC'); processes(m).click(); expect(m.locator('#procedureHub .procedure-card')).to_have_count(7); no_overflow(m); named(m); painted(m); m.screenshot(path=str(ART/'ux-v19-mobile.png'),full_page=True); m.keyboard.press('Control+K'); expect(m.locator('#globalCommandDialog')).to_be_visible(); one_scroll_owner(m,'#globalCommandDialog'); no_overflow(m); named(m); painted(m,'#globalCommandDialog'); mc.close()
  PHASE='reduced-motion'; rc=browser.new_context(viewport={'width':1280,'height':850},reduced_motion='reduce'); rc.add_init_script("localStorage.setItem('ictc-role','user');localStorage.setItem('ictc-service','processes')"); r=rc.new_page(); r.goto(BASE+'/',wait_until='networkidle'); v=r.locator('.procedure-card').first.evaluate('e=>[getComputedStyle(e).animationDuration,getComputedStyle(e).transitionDuration]'); assert all(x in ('0s','0ms') for x in v),v; rc.close()
  assert not errors,errors
  out={'ok':True,'semanticEdition':'1.2-market-candidate','experienceEdition':'1.9-experience-candidate','procedures':seen,'history':True,'deepLink':True,'commandPalette':True,'auditorWritePrimary':False,'auditorReadProcedureBound':True,'standardNodeBrowser':True,'mobileOverflow':False,'reducedMotion':True,'accessibleVisibleControls':True,'paintedControls':True,'singleScrollDialogs':True,'incidentNarrativeProminence':True,'postureSurface':'Postura Standard & Security ICTC','screenshots':15,'evidenceClass':'E2-server-backed-browser+polish'}; (ART/'browser-v1-9-experience.json').write_text(json.dumps(out,indent=2),encoding='utf8'); print('browser-v1-9-experience: complete',flush=True); ctx.close(); browser.close()
except BaseException as e:
 fail(e); traceback.print_exc(); raise
