import json, os, pathlib, re, traceback
from playwright.sync_api import expect, sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1]; ART=ROOT/'artifacts'; ART.mkdir(exist_ok=True)
BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4173').rstrip('/'); PHASE='init'
def fail(e):
 p={'ok':False,'phase':PHASE,'type':type(e).__name__,'message':str(e),'traceback':traceback.format_exc()};(ART/'browser-convergent-kernel-error.json').write_text(json.dumps(p,indent=2),encoding='utf8');print(f'::error title=browser-convergent-kernel::{PHASE}: {e}',flush=True)
def api(page,role,path,method='GET',body=None):
 return page.evaluate("""async ({role,path,method,body})=>{const headers={'content-type':'application/json','x-ictc-role':role};const r=await fetch(path,{method,headers,body:body==null?undefined:JSON.stringify(body)});let data=null;try{data=await r.json()}catch{}return {status:r.status,body:data};}""",{'role':role,'path':path,'method':method,'body':body})
def open_process(page,code):
 page.locator('[data-service="processes"]').first.click();card=page.locator(f'#procedureHub [data-process-code="{code}"]');expect(card).to_be_visible();card.locator('.primary').click();page.wait_for_timeout(100)
try:
 with sync_playwright() as pw:
  launch={'headless':True,'args':['--no-sandbox']}
  if os.environ.get('ICTC_CHROMIUM'): launch['executable_path']=os.environ['ICTC_CHROMIUM']
  browser=pw.chromium.launch(**launch);ctx=browser.new_context(viewport={'width':1365,'height':900});ctx.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','home')")
  page=ctx.new_page();page.set_default_timeout(30000);page.goto(BASE+'/',wait_until='networkidle')
  PHASE='bootstrap-kernel';b=api(page,'admin','/api/bootstrap');assert b['status']==200,b;data=b['body'];assert data['projectionContext']['scope']=='actor-visible';assert data['projectionContext']['asOf'];assert data['procedureRegistry']['authority']=='canonical-procedure-registry';assert len(data['procedureRegistry']['procedures'])==7;assert data['metricCatalog']['authority']=='canonical-procedure-registry.metricSpecs';assert all(x.get('drilldown') for x in data['metricCatalog']['metrics']);assert data['subjectVersions']['authority']=='subject-version-index';assert data['epistemic']['metaGrammar']['families']==['observed','derived','proposed','decided','attested']
  PHASE='common-anatomy';codes=['RN-01','EC-01','AO-01','MC-01','AP-01','RC-01','AR-01'];seen=[]
  for code in codes:
   open_process(page,code);box=page.locator('[data-procedure-anatomy]').first;expect(box).to_be_visible();assert box.get_attribute('open') is None;box.locator('summary').click();expect(box.locator('.procedure-anatomy-epistemic span')).to_have_count(5);text=box.inner_text();assert 'Contesto e tracciabilità' in text;assert not re.search(r'\b[a-f0-9]{64}\b',text,re.I);assert 'Apri Evidenze' in text;seen.append(code)
  PHASE='assigned-or-created';act=api(page,'admin','/api/grc/actions','POST',{'title':'Azione non assegnata kernel test','description':'scope test'});assert act['status']==201,act;action_id=act['body']['result']['id'];ub=api(page,'user','/api/bootstrap');assert ub['status']==200;visible=[x['id'] for x in ub['body']['grc']['actions']['actions']];assert action_id not in visible,(action_id,visible)
  PHASE='requirement-scope-and-control-test';obj=api(page,'admin','/api/grc/objects','POST',{'type':'control','name':'Control kernel test','sourceAuthority':'ICTC test','externalReference':'CTRL-KERNEL-1'});assert obj['status']==201,obj;control_id=obj['body']['result']['id'];rev=api(page,'admin',f'/api/grc/objects/{control_id}/review','POST',{'decision':'active','reason':'Attivo per test bounded'});assert rev['status']==200,rev
  mapping=api(page,'admin','/api/grc/mappings','POST',{'requirementRef':'std:eu-gdpr-2016-679:art-32','targetIds':[control_id],'rationale':'Test separazione scope/mapping'});assert mapping['status']==201,mapping;mapping_id=mapping['body']['result']['id'];na=api(page,'admin',f'/api/grc/mappings/{mapping_id}/decision','POST',{'decision':'not-applicable','reason':'Fuori perimetro nel caso di test'});assert na['status']==200,na;assert na['body']['result']['requirementScope']['decision']=='not-applicable';assert na['body']['result']['mapping']['scopeDisposition']=='not-applicable'
  ct=api(page,'admin','/api/control-tests','POST',{'controlId':control_id,'outcome':'pass','method':'Verifica configurazione bounded','evidenceRefs':[f'ictc:grc-object:{control_id}'],'reason':'Test runtime'});assert ct['status']==201,ct;assert ct['body']['result']['outcome']=='pass';assert 'does not establish' in ct['body']['result']['claimBoundary']
  PHASE='subject-version-materialization';b2=api(page,'admin','/api/bootstrap');assert b2['status']==200;assert b2['body']['subjectVersions']['count']>0;assert b2['body']['controlTests']['counts']['pass']>=1;assert b2['body']['grc']['coverage']['notApplicable']>=1
  PHASE='rn-ai-off-manual-parity';draft=api(page,'user','/api/missions/manual-draft','POST',{'objective':'Monitoraggio manuale senza AI','cadence':168,'sourceHints':['Fonte ufficiale']});assert draft['status']==201,draft;mission_id=draft['body']['result']['id'];plan=api(page,'user',f'/api/missions/{mission_id}/manual-plan','POST',{'rationale':'Piano manuale owner scoped','queries':['aggiornamenti normativi'],'preferredSources':['Fonte ufficiale']});assert plan['status']==200,plan;assert plan['body']['result']['planSource']=='human'
  PHASE='evidence-surface';page.locator('[data-service="proof"]').first.click();expect(page.locator('#stableProofView')).to_be_visible();page.screenshot(path=str(ART/'ux-v12-convergent-evidence.png'),full_page=True)
  report={'ok':True,'releaseProfile':'1.2_market_candidate','commonAnatomy':seen,'projectionContext':True,'sameAsReadActionScope':True,'requirementScopeSeparate':True,'controlTestSeparate':True,'subjectVersionMaterialized':True,'rnManualParity':True,'epistemicFamilies':['observed','derived','proposed','decided','attested'],'evidenceClass':'E2-browser-not-independent-human-research'};(ART/'browser-convergent-kernel.json').write_text(json.dumps(report,indent=2),encoding='utf8');print('browser-convergent-kernel: complete',flush=True);ctx.close();browser.close()
except BaseException as e: fail(e);traceback.print_exc();raise
