import json,os,pathlib,traceback
from playwright.sync_api import expect,sync_playwright
ART=pathlib.Path(os.environ.get('ICTC_ARTIFACT_DIR',str(pathlib.Path.cwd()/'artifacts')));ART.mkdir(exist_ok=True);BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4173').rstrip('/');MOCK=os.environ.get('ICTC_MOCK_URL','http://127.0.0.1:4899').rstrip('/');PHASE='init';CODES={'monitoring':'RN-01','incidents':'EC-01','objects':'AO-01','coverage':'MC-01','actions':'AP-01','risks':'RC-01','assurance':'AR-01'}
def hdr(role='admin'):return{'x-ictc-role':role,'x-ictc-actor-id':f'local-{role}'}
def fail(e):
 p={'ok':False,'phase':PHASE,'type':type(e).__name__,'message':str(e),'traceback':traceback.format_exc()};(ART/'browser-v3-error.json').write_text(json.dumps(p,indent=2),encoding='utf8');print(f'::error title=browser-v3-successor::{PHASE}: {type(e).__name__}: {e}',flush=True)
try:
 with sync_playwright() as pw:
  launch={'headless':True,'args':['--no-sandbox']}
  if os.environ.get('ICTC_CHROMIUM'):launch['executable_path']=os.environ['ICTC_CHROMIUM']
  browser=pw.chromium.launch(**launch);ctx=browser.new_context(viewport={'width':1440,'height':1050},accept_downloads=True);ctx.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','home');localStorage.setItem('ictc-ai-assist','on')")
  page=ctx.new_page();page.set_default_timeout(18000);errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
  def req(method,path,data=None,role='admin'):
   r=ctx.request.fetch(BASE+path,method=method,headers=hdr(role),data=data);assert r.ok,(method,path,r.status,r.text());return r
  def guide(pid,text):
   page.locator('.service-nav [data-service="home"]').click();f=page.locator('#v3IntentForm');f.locator('textarea[name="objective"]').fill(text);f.get_by_role('button',name='Suggerisci il processo').click();choices=page.locator('#v3RouteResults [data-v3-guide]');choices.first.wait_for(state='visible');assert 1<=choices.count()<=3;choice=page.locator(f'#v3RouteResults [data-v3-guide="{pid}"]');choice.wait_for(state='visible');choice.click();d=page.locator('#v3ProcedureDialog');d.wait_for(state='visible');expect(page.locator('#v3ProcedureTitle')).to_contain_text(CODES[pid]);expect(page.locator('#v3ProcedureBody')).to_contain_text('Per iniziare');expect(page.locator('#v3ProcedureBody')).to_contain_text('Risultato atteso');expect(page.locator('#v3ProcedureBody')).to_contain_text('Richiede conferma umana');d.get_by_role('button',name='Apri processo').click();d.wait_for(state='hidden')
  PHASE='entry';page.goto(BASE+'/',wait_until='networkidle');expect(page.locator('html')).to_have_attribute('data-ictc-experience','active-1');expect(page.locator('html')).to_have_attribute('data-ictc-edition','v4-1-experimental');expect(page.locator('.service-nav [data-service]')).to_have_count(3);expect(page.locator('#complianceNexus [data-nexus-process]')).to_have_count(7);expect(page.locator('#v3OperationalHome')).to_be_visible();expect(page.locator('#v3IntentForm')).to_be_visible();expect(page.locator('#grcCockpit')).to_be_hidden();expect(page.locator('#v3MetricGrid article')).to_have_count(7)
  PHASE='configure-ai';page.locator('#openSettings').click();form=page.locator('#settingsForm');provider=form.locator('[data-settings-section="provider"]');provider.locator('summary').click() if provider.get_attribute('open') is None else None;provider.locator('input[name="endpoint"]').fill(MOCK+'/v1/chat/completions');provider.locator('input[name="model"]').fill('mock-v4');provider.locator('input[name="apiKeyEnv"]').fill('ICTC_LLM_API_KEY');form.get_by_role('button',name='Salva configurazione AI').click();page.locator('#settingsDialog').wait_for(state='hidden')
  PHASE='guided-catalog';phrases={'monitoring':'Monitorare nuove norme e fonti ufficiali EUR-Lex','incidents':'Registrare un evento e una segnalazione operativa','objects':'Inventariare server firewall e applicazioni cloud','coverage':'Mappare requisiti NIS2 ai controlli e trovare gap','actions':'Creare remediation con responsabile e scadenza','risks':'Valutare scenario di rischio con probabilità e impatto','assurance':'Compilare questionario di assurance del cliente'}
  for pid,text in phrases.items():
   guide(pid,text)
   if pid=='monitoring':expect(page.locator('#monitoringView')).to_be_visible()
   elif pid=='incidents':expect(page.locator('#incidentsView')).to_be_visible()
   else:expect(page.locator('#grcWorkspace')).to_contain_text(CODES[pid]);expect(page.locator('#grcPrimaryForm')).to_have_count(1)
  PHASE='ao';o=req('POST','/api/grc/objects',{'type':'laptop','name':'Notebook CFO successor','criticality':'high','owner':'Finance','sourceAuthority':'Inventory'}).json();oid=o['result']['id'];assert o['receipt']['hash'];req('POST',f'/api/grc/objects/{oid}/review',{'decision':'active','reason':'Validazione umana inventario'})
  PHASE='mc';m=req('POST','/api/grc/mappings/propose',{'requirementRef':'MFA-01','requirementLabel':'MFA per accessi privilegiati','targetIds':[oid]}).json();mid=m['result']['id'];req('POST',f'/api/grc/mappings/{mid}/decision',{'decision':'gap','reason':'Gap verificato da persona'});g=req('GET','/api/grc').json();assert g['coverage']['gaps']>=1 and g['coverage']['coveragePercent']==0
  PHASE='ap';a=req('POST','/api/grc/actions',{'title':'Abilitare MFA privilegiata','owner':'local-admin','dueAt':'2099-01-01'}).json();aid=a['result']['id'];req('POST',f'/api/grc/actions/{aid}/prioritize',{});req('POST',f'/api/grc/actions/{aid}/adopt',{'priority':4,'reason':'Priorità adottata da persona','owner':'local-admin','dueAt':'2099-01-01'});req('POST',f'/api/grc/actions/{aid}/progress',{'state':'in-progress','note':'Avvio umano'});g=req('GET','/api/grc').json();aa=next(x for x in g['actions']['actions'] if x['id']==aid);assert aa['state']=='in-progress' and aa['priority']==4
  PHASE='rc';risk=req('POST','/api/grc/risks/propose',{'title':'Accesso privilegiato senza MFA','description':'Scenario collegato al gap','objectIds':[oid],'actionIds':[aid]}).json();rid=risk['result']['id'];g=req('GET','/api/grc').json();assert any(x['riskId']==rid for x in g['risks']['aiOverlay']);assert sum(sum(row) for row in g['risks']['heatmap'])==0;req('POST',f'/api/grc/risks/{rid}/review',{'likelihood':4,'impact':5,'reason':'Rating validato da persona'});g=req('GET','/api/grc').json();assert g['risks']['heatmap'][3][4]==1
  PHASE='ar';case=req('POST','/api/grc/assurance',{'title':'Questionario cliente successor','requestText':'Descrivere MFA e logging con evidenze disponibili.','source':'Cliente'}).json();cid=case['result']['id'];req('POST',f'/api/grc/assurance/{cid}/propose',{});g=req('GET','/api/grc').json();c=next(x for x in g['assurance']['cases'] if x['id']==cid);answers=[{'questionId':q['id'],'answer':q['draftAnswer'] or 'Risposta verificata','evidenceRefs':q.get('evidenceRefs',[]),'limitations':q.get('limitations',[])} for q in c['aiProposal']['questions']];req('POST',f'/api/grc/assurance/{cid}/approve',{'answers':answers,'reason':'Risposte verificate e approvate da persona'});g=req('GET','/api/grc').json();assert next(x for x in g['assurance']['cases'] if x['id']==cid)['state']=='approved'
  PHASE='insights';before=req('GET','/api/insights').json()['base']['basisSha256'];p=req('POST','/api/insights/propose',{}).json();pid=p['result']['id'];ip=req('GET','/api/insights').json();record=next(x for x in ip['proposals'] if x['id']==pid);assert record['basisSha256']==before and record['envelope']['adoption'] is None;req('POST',f'/api/insights/{pid}/validate',{'reason':'Lettura utile rispetto ai KPI correnti'});after=req('GET','/api/insights').json();assert after['base']['basisSha256']==before;assert next(x for x in after['proposals'] if x['id']==pid)['envelope']['adoption']['authority']=='human';page.reload(wait_until='networkidle');expect(page.locator('#v3AiInsight .v3-ai-badge')).to_contain_text('validata da umano')
  PHASE='trace-evidence';tr=req('GET',f'/api/work/traces/grc-object/{oid}').json();assert tr['processId']=='objects' and tr['completeness']['humanDecision'] is True and tr['evidenceUrl'];z=req('GET',f'/api/evidence/grc-object/{oid}.zip');assert z.body()[:4]==b'PK\x03\x04';export=req('GET','/api/export/current.json').json();assert any(x['type']=='grc-object' and x['id']==oid for x in export['rows'])
  PHASE='roles';u=req('GET','/api/bootstrap',role='user').json();assert u['accessProfile']['mode']!='read-only';aud=req('GET','/api/bootstrap',role='auditor').json();assert aud['reviewInbox']['readOnly'] is True and all(x['readOnly'] for x in aud['work']['queue']['items']);page.locator('#roleSelect').select_option('auditor');page.locator('.service-nav [data-service="proof"]').click();expect(page.locator('#proofContent')).to_be_visible();assert not errors,errors
  checks=['v3-capability-successor','seven-guided-procedures','max-three-candidates','human-launch','ao','mc-ai-human','ap-ai-human','rc-human-heatmap','ar-ai-human','deterministic-insight-human-validation','kpi-no-drift','trace','evidence','export','roles','proof'];(ART/'browser-v3.json').write_text(json.dumps({'ok':True,'checks':checks,'productEdition':'V4.1 Experimental · Enterprise Nexus','services':7},indent=2),encoding='utf8');print('browser-v3-capability-successor: complete',flush=True);browser.close()
except BaseException as e:fail(e);traceback.print_exc();raise
