import json, os, pathlib, traceback
from playwright.sync_api import expect, sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1];ART=ROOT/'artifacts';ART.mkdir(exist_ok=True);BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4173').rstrip('/');MOCK=os.environ.get('ICTC_MOCK_URL','http://127.0.0.1:4899').rstrip('/');PHASE='initialization'
def fail(error):
    payload={'ok':False,'phase':PHASE,'type':type(error).__name__,'message':str(error),'traceback':traceback.format_exc()};(ART/'browser-product-error.json').write_text(json.dumps(payload,indent=2),encoding='utf8');print(f'::error title=browser-product-check::{PHASE}: {type(error).__name__}: {error}',flush=True)
def headers(role): return {'x-ictc-role':role,'x-ictc-actor-id':f'local-{role}'}
def open_process(page,pid):
    page.locator('.service-nav [data-service="processes"]').click();card=page.locator(f'#procedureHub [data-procedure-id="{pid}"]');card.wait_for(state='visible');card.locator('button').click()
try:
  with sync_playwright() as pw:
    launch={'headless':True,'args':['--no-sandbox']}
    if os.environ.get('ICTC_CHROMIUM'): launch['executable_path']=os.environ['ICTC_CHROMIUM']
    browser=pw.chromium.launch(**launch);ctx=browser.new_context(viewport={'width':1440,'height':1000},accept_downloads=True);ctx.add_init_script("try{localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','home')}catch{}")
    page=ctx.new_page();page.set_default_timeout(15000);errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
    PHASE='v3-shell-successor-regression';page.goto(BASE+'/',wait_until='networkidle');expect(page.locator('html')).to_have_attribute('data-ictc-experience','active-1');expect(page.locator('html')).to_have_attribute('data-ictc-edition','v3-experimental');expect(page.locator('.service-nav [data-service]')).to_have_count(3);expect(page.locator('.service-nav')).to_contain_text('Oggi');expect(page.locator('.service-nav')).to_contain_text('Processi');expect(page.locator('.service-nav')).to_contain_text('Prove');expect(page.locator('#v3OperationalHome')).to_be_visible()
    page.locator('.service-nav [data-service="processes"]').click();hub=page.locator('#procedureHub[data-procedure-hub="server-derived"]');hub.wait_for(state='visible');expect(hub.locator('[data-procedure-id]')).to_have_count(9);assert hub.locator('[data-procedure-id="monitoring"][data-process-code="RN-01"]').count()==1;assert hub.locator('[data-procedure-id="incidents"][data-process-code="EC-01"]').count()==1;assert hub.locator('[data-procedure-id="objects"][data-process-code="AO-01"]').count()==1
    PHASE='settings-and-ai';page.locator('.service-nav [data-service="home"]').click();page.locator('#openSettings').click();settings=page.locator('#settingsForm');org=settings.locator('[data-settings-section="organization"]');org.locator('summary').click() if org.get_attribute('open') is None else None;settings.locator('input[name="organizationName"]').fill('Azienda Browser V3');settings.locator('textarea[name="organizationScope"]').fill('Sicurezza delle informazioni in Italia e Unione europea');settings.locator('input[name="jurisdictions"]').fill('Italia, Unione europea');provider=settings.locator('[data-settings-section="provider"]');provider.locator('summary').click() if provider.get_attribute('open') is None else None;provider.locator('input[name="endpoint"]').fill(MOCK+'/v1/chat/completions');provider.locator('input[name="model"]').fill('mock-browser');provider.locator('input[name="apiKeyEnv"]').fill('ICTC_LLM_API_KEY');settings.get_by_role('button',name='Salva configurazione AI').click();page.locator('#settingsDialog').wait_for(state='hidden')
    PHASE='rn01-regression';open_process(page,'monitoring');mission=page.locator('#missionForm');mission.locator('textarea[name="objective"]').fill('Fonti ufficiali sulla sicurezza delle informazioni e servizi cloud in Italia e UE');mission.locator('select[name="cadence"]').select_option('168');mission.locator('input[name="sourceHints"]').fill('https://eur-lex.europa.eu');mission.get_by_role('button',name='Crea piano').click();page.locator('#planDialog').wait_for(state='visible');page.get_by_role('button',name='Attiva monitoraggio').click();page.locator('[data-close="planDialog"]').click();page.locator('.mission-card').first.get_by_role('button',name='Esegui ora').click();source_button=page.locator('[data-open-source]').first;source_button.wait_for();source_button.click();page.locator('#sourceDialog').wait_for(state='visible');page.locator('#sourceDecisionReason').fill('Autorità, URL e identificativo verificati da operatore umano.');page.locator('[data-source-decision="verified"]').click();page.locator('#sourceBody').get_by_text('Accettata nel catalogo',exact=False).first.wait_for();page.locator('[data-close="sourceDialog"]').click()
    admin=ctx.request.get(BASE+'/api/bootstrap',headers=headers('admin')).json();assert admin['experience']['productEdition']=='V3 Experimental';assert admin['experience']['shell']==['home','processes','proof'];assert admin['ontology']['authority']=='runtime';assert admin['decisions']['authority']=='human-decision-projection';assert admin['epistemic']['authority']=='runtime-epistemic-projection';assert admin['exports']['authorization']=='same-as-read';assert admin['work']['routing']['humanLaunchRequired'] is True;assert len(admin['procedures'])==9
    PHASE='ec01-regression';page.locator('#roleSelect').select_option('user');open_process(page,'incidents');page.locator('#openIncident').click();incident=page.locator('#incidentForm');incident.locator('textarea[name="originalNarrative"]').fill('Quasi incidente: email sospetta ricevuta e bloccata prima dell’apertura');incident.get_by_role('button',name='Registra evento').click();page.locator('#incidentWorkspace').wait_for(state='visible');page.locator('[data-close="incidentWorkspace"]').click();page.locator('.incident-card').first.get_by_role('button',name='Dossier ZIP').wait_for()
    PHASE='proof-auditor';page.locator('#roleSelect').select_option('auditor');page.locator('.service-nav [data-service="proof"]').click();page.locator('#proofContent').wait_for(state='visible');expect(page.locator('#proofActor')).to_contain_text('Auditor');boot=ctx.request.get(BASE+'/api/bootstrap',headers=headers('auditor')).json();assert boot['integrity']['ok'] is True;assert boot['accessProfile']['mode']=='read-only';assert boot['grc']['readOnly'] is True;assert boot['exports']['authorization']=='same-as-read';assert boot['work']['queue']['items'] and all(item['readOnly'] for item in boot['work']['queue']['items']);assert not errors,errors
    checks=['one-active-experience','v3-permanent-shell','server-derived-nine-procedures','rn01-regression','human-source-decision','ec01-regression','proof-auditor-read-only','same-as-read-export','work-routing-human-selection'];(ART/'browser-check.json').write_text(json.dumps({'ok':True,'checks':checks,'productEdition':'V3 Experimental','experience':'active-1'},indent=2),encoding='utf8');print('browser-product-check: V1/V2 capability regression preserved under V3',flush=True);browser.close()
except BaseException as error:
  fail(error);traceback.print_exc();raise
