import json, os, pathlib, traceback
from playwright.sync_api import expect, sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1]; ART=ROOT/'artifacts'; ART.mkdir(exist_ok=True)
BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4823').rstrip('/'); EXPECTED_SHA=(os.environ.get('ICTC_EXPECT_BUILD_SHA') or '').strip().lower(); PHASE='init'; RESULTS=[]; WRITES=[]; PAGE_ERRORS=[]
def fail(exc):
 payload={'ok':False,'phase':PHASE,'type':type(exc).__name__,'message':str(exc),'traceback':traceback.format_exc(),'expectedBuildSha':EXPECTED_SHA or None,'results':RESULTS,'writes':WRITES,'pageErrors':PAGE_ERRORS};(ART/'browser-s4-a3-specialized-local-closure-error.json').write_text(json.dumps(payload,indent=2),encoding='utf8');print(f'::error title=browser-s4-a3-specialized-local-closure::{PHASE}: {type(exc).__name__}: {exc}',flush=True)
def open_process(page,code):
 page.locator('.service-nav [data-service="processes"]').click();expect(page.locator('#processesView')).to_be_visible();card=page.locator(f'#procedureHub [data-process-code="{code}"]');expect(card).to_be_visible();card.locator(':scope > footer .procedure-primary,:scope > footer .primary').first.click()
def preserve_open(page,selector):
 detail=page.locator(selector);expect(detail).to_be_visible();detail.evaluate('e=>e.open=true');page.evaluate("document.dispatchEvent(new CustomEvent('ictc:rendered',{detail:{source:'s4-a3-stability-probe'}}))");page.wait_for_timeout(80);assert detail.get_attribute('open') is not None,selector
def proof_child_order(page):
 return page.evaluate("""()=>[...document.querySelector('#proofContent').children].map(n=>n.classList.contains('proof-fact-strip')?'facts':(n.dataset.proofDomain||n.dataset.proofWorkspace||n.dataset.compositionDetail||null)).filter(Boolean)""")
def nav_probe(page,service):
 return page.evaluate("""service=>{const sel=`.service-nav [data-service=\"${service}\"]`,e=document.querySelector(sel),top=document.querySelector('.topbar'),active=document.querySelector('.view:not([hidden])'),dialogs=[...document.querySelectorAll('dialog[open]')].map(d=>({id:d.id||'',cls:String(d.className||''),modal:d.matches(':modal'),rect:(()=>{const r=d.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height}})()}));if(!e)return{service,count:0,activeSurface:document.documentElement.dataset.ictcSurface||null,activeView:active?.id||null,dialogs};const r=e.getBoundingClientRect(),s=getComputedStyle(e),cx=Math.max(0,Math.min(innerWidth-1,r.left+r.width/2)),cy=Math.max(0,Math.min(innerHeight-1,r.top+r.height/2)),hit=document.elementFromPoint(cx,cy),ts=top?getComputedStyle(top):null,tr=top?.getBoundingClientRect();let inert=null;for(let n=e;n;n=n.parentElement){if(n.inert||n.hasAttribute('inert')){inert={tag:n.tagName,id:n.id||'',cls:String(n.className||'')};break}}return{service,count:1,activeSurface:document.documentElement.dataset.ictcSurface||null,activeView:active?.id||null,button:{rect:{x:r.x,y:r.y,w:r.width,h:r.height,top:r.top,right:r.right,bottom:r.bottom,left:r.left},display:s.display,visibility:s.visibility,opacity:s.opacity,pointerEvents:s.pointerEvents,position:s.position,zIndex:s.zIndex,disabled:e.disabled,ariaCurrent:e.getAttribute('aria-current'),connected:e.isConnected},topbar:top?{rect:{x:tr.x,y:tr.y,w:tr.width,h:tr.height},display:ts.display,visibility:ts.visibility,pointerEvents:ts.pointerEvents,position:ts.position,zIndex:ts.zIndex}:null,point:{x:cx,y:cy},hit:hit?{tag:hit.tagName,id:hit.id||'',cls:String(hit.className||''),service:hit.dataset?.service||null,withinButton:e.contains(hit)}:null,dialogs,inert,transitionDirection:document.documentElement.dataset.ictcTransitionDirection||null,activeAnimations:document.getAnimations().filter(a=>a.playState==='running').slice(0,20).map(a=>({target:a.effect?.target?.id||a.effect?.target?.className||a.effect?.target?.nodeName||null,currentTime:a.currentTime,playState:a.playState}))};}""",service)
def assert_pointer_target(probe):
 button=probe.get('button') or {};rect=button.get('rect') or {};hit=probe.get('hit') or {};issues=[]
 if probe.get('count')!=1:issues.append(f"count={probe.get('count')}")
 if not (rect.get('w',0)>0 and rect.get('h',0)>0):issues.append(f"rect={rect.get('w',0)}x{rect.get('h',0)}")
 if button.get('display')=='none':issues.append('display=none')
 if button.get('visibility')=='hidden':issues.append('visibility=hidden')
 if button.get('pointerEvents')=='none':issues.append('pointer=none')
 if button.get('disabled'):issues.append('disabled=1')
 if hit.get('withinButton') is not True:issues.append('hit=0')
 if probe.get('dialogs'):issues.append(f"dialogs={len(probe.get('dialogs') or [])}")
 if probe.get('inert') is not None:issues.append('inert=1')
 if issues:
  hit_name=f"{hit.get('tag','?')}#{hit.get('id','')}.{str(hit.get('cls',''))[:32]}"
  raise AssertionError(f"pointer-target {'|'.join(issues)} hit={hit_name} surf={probe.get('activeSurface')} anim={len(probe.get('activeAnimations') or [])}")
try:
 with sync_playwright() as pw:
  launch={'headless':True,'args':['--no-sandbox']}
  if os.environ.get('ICTC_CHROMIUM'):launch['executable_path']=os.environ['ICTC_CHROMIUM']
  browser=pw.chromium.launch(**launch);ctx=browser.new_context(viewport={'width':1440,'height':1000});ctx.add_init_script("localStorage.setItem('ictc-profile','demo');localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','processes')");page=ctx.new_page();page.set_default_timeout(30000)
  page.on('pageerror',lambda e:PAGE_ERRORS.append(str(e)));page.on('request',lambda r:WRITES.append({'method':r.method,'url':r.url}) if '/api/' in r.url and r.method not in ('GET','HEAD','OPTIONS') else None)
  PHASE='bootstrap';page.goto(BASE+'/?view=processes',wait_until='networkidle');page.wait_for_function("()=>document.documentElement.dataset.nativeSemanticLattice==='3.2.0'")
  PHASE='identity';identity=ctx.request.get(f'{BASE}/api/admin/identity',headers={'X-ICTC-Role':'admin'}).json();build=(identity.get('buildIdentity') or {}).get('build') or {};assert not EXPECTED_SHA or (build.get('sha')==EXPECTED_SHA and build.get('exact') is True and build.get('dirty') is False),(build,EXPECTED_SHA)
  PHASE='MC-primary-intent';open_process(page,'MC-01');page.wait_for_function("()=>document.querySelectorAll('[data-framework-card]').length>0");cards=page.locator('[data-framework-card]');assert cards.count()>0
  for i in range(cards.count()):
   card=cards.nth(i);scope=card.locator('[data-standard-scope]')
   if scope.count(): assert card.locator('button.primary').count()==1,(i,card.locator('button.primary').count())
  assert page.locator('[data-framework-card] [data-open-standard-browser].primary').count()==0
  RESULTS.append({'surface':'MC-01','frameworkCards':cards.count(),'contextualPrimary':'exactly-one-per-actionable-card','referenceAction':'secondary'})
  PHASE='Proof-order';proof_nav=page.locator('.service-nav [data-service="proof"]');proof_nav.evaluate("e=>e.scrollIntoView({block:'center',inline:'center'})");page.wait_for_timeout(180);probe1=nav_probe(page,'proof');assert_pointer_target(probe1);page.wait_for_timeout(80);probe2=nav_probe(page,'proof');assert_pointer_target(probe2);r1=probe1['button']['rect'];r2=probe2['button']['rect'];assert all(abs(r1[k]-r2[k])<=1 for k in ('x','y','w','h')),{'before':probe1,'after':probe2};RESULTS.append({'surface':'A3-nav-probe-before-proof','before':probe1,'after':probe2,'stableGeometry':True,'pointerTargetExposed':True,'explicitUserScroll':True});point=probe2['point'];page.mouse.click(point['x'],point['y']);expect(page.locator('#proofView')).to_be_visible();page.locator('#proofContent').wait_for(state='visible');root=page.locator('#proofView');expected_marker='facts>decisions>trace>evidence-basis>epistemic>external>integrity>method>export';assert root.get_attribute('data-proof-reading-order')==expected_marker
  facts=page.locator('#proofContent > .proof-fact-strip');expect(facts).to_be_visible();assert facts.get_attribute('data-proof-facts')=='non-evaluative';decisions=page.locator('#proofContent > details[data-proof-domain="decisions"]');expect(decisions).to_be_visible();assert decisions.get_attribute('open') is None
  expected_order=['facts','decisions','trace-reconstruction','evidence-basis','epistemic-investigation','external','integrity','interpretation','export'];actual_order=proof_child_order(page);projected=[x for x in actual_order if x in expected_order];assert projected==expected_order,(projected,actual_order)
  preserve_open(page,'#proofContent > details[data-proof-domain="decisions"]');preserve_open(page,'#proofContent > details[data-proof-workspace="trace-reconstruction"]');RESULTS.append({'surface':'Proof','order':expected_marker,'directChildOrder':projected,'factGrammar':'fact-strip','secondaryDefaultClosed':True,'disclosureStable':True})
  PHASE='EP-entry';investigation=page.locator('#proofContent > details[data-proof-workspace="epistemic-investigation"]');investigation.evaluate('e=>e.open=true');action=investigation.locator('[data-service="epistemic"]');expect(action).to_be_visible();action.click();expect(page.locator('#epistemicView')).to_be_visible();page.wait_for_function("()=>document.querySelector('#epistemicSearch')&&document.querySelector('#epistemicView')?.offsetParent!==null")
  PHASE='EP-progressive-default';search=page.locator('#epistemicSearch');expect(search).to_be_visible();advanced=page.locator('#epistemicView details[data-epistemic-a3="advanced-filters"]');technical=page.locator('#epistemicView details[data-epistemic-a3="technical-modes"]');expect(advanced).to_be_visible();expect(technical).to_be_visible();assert advanced.get_attribute('open') is None;assert technical.get_attribute('open') is None;expect(page.locator('[data-epistemic-mode="flat"]')).to_be_hidden();expect(page.locator('[data-epistemic-mode="graph"]')).to_be_hidden();preserve_open(page,'#epistemicView details[data-epistemic-a3="technical-modes"]')
  PHASE='EP-focus-graph';technical=page.locator('#epistemicView details[data-epistemic-a3="technical-modes"]');technical.evaluate('e=>e.open=true');graph_button=page.locator('[data-epistemic-mode="graph"]');expect(graph_button).to_be_visible();graph_button.click();graph=page.locator('.epistemic-graph');expect(graph).to_be_visible();focus=graph.get_attribute('data-epistemic-graph-focus') or '';nodes=int(graph.get_attribute('data-epistemic-graph-node-count') or '0');edges=int(graph.get_attribute('data-epistemic-graph-edge-count') or '0');assert focus and 1<=nodes<=24 and 0<=edges<=48,(focus,nodes,edges);assert page.locator(f'.epistemic-node-list [data-epistemic-node="{focus}"]').count()==1,(focus,nodes);RESULTS.append({'surface':'EP-01','technicalDefaultFrontstage':0,'focus':focus,'nodes':nodes,'edges':edges,'limits':{'nodes':24,'edges':48},'disclosureStable':True})
  PHASE='global';assert WRITES==[],WRITES;assert PAGE_ERRORS==[],PAGE_ERRORS
  report={'ok':True,'slice':'S4-A3','expectedBuildSha':EXPECTED_SHA or None,'runtimeIdentity':identity,'results':RESULTS,'writes':WRITES,'pageErrors':PAGE_ERRORS,'claimBoundary':'E3 exact-head browser DOM/interaction evidence; not human usability, deployment assurance, or enterprise-ready proof.'};(ART/'browser-s4-a3-specialized-local-closure.json').write_text(json.dumps(report,indent=2),encoding='utf8');print(json.dumps(report),flush=True);browser.close()
except BaseException as exc: fail(exc); raise
