import json, os, pathlib, traceback, urllib.parse
from playwright.sync_api import expect, sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1];ART=ROOT/'artifacts';ART.mkdir(exist_ok=True)
BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4807').rstrip('/');EXPECTED_SHA=(os.environ.get('ICTC_EXPECT_BUILD_SHA') or '').strip().lower();PHASE='init';RESULTS=[];NETWORK=[];FAILURES=[];PAGE_ERRORS=[]
PROCEDURES=[('RN-01','monitoring'),('EC-01','incidents'),('AO-01','objects'),('MC-01','coverage'),('AP-01','actions'),('RC-01','risks'),('AR-01','assurance')]
OWNER={'monitoring':'procedure-sequential-rn-ec.js','incidents':'procedure-sequential-rn-ec.js','objects':'grc-workspace-3-2.js','coverage':'grc-workspace-3-2.js','actions':'grc-workspace-3-2.js','risks':'grc-workspace-3-2.js','assurance':'grc-workspace-3-2.js'}
def phase_token(value): return ''.join(ch if ch.isalnum() else '-' for ch in str(value)).strip('-')[:96] or 'none'
def fail(exc):
 payload={'ok':False,'phase':PHASE,'type':type(exc).__name__,'message':str(exc),'traceback':traceback.format_exc(),'expectedBuildSha':EXPECTED_SHA or None,'results':RESULTS,'network':NETWORK,'networkFailures':FAILURES,'pageErrors':PAGE_ERRORS};(ART/'browser-s4-a1-worklist-authority-error.json').write_text(json.dumps(payload,indent=2,ensure_ascii=False),encoding='utf8');print(f'::error title=browser-s4-a1-worklist-authority::{PHASE}: {type(exc).__name__}: {exc}',flush=True)
def api_get(request_context,path,role='admin'):
 response=request_context.get(f'{BASE}{path}',headers={'x-ictc-role':role});
 try: body=response.json()
 except Exception: body={'_raw':response.text()[:500]}
 return {'path':path,'status':response.status,'ok':response.ok,'requestId':response.headers.get('x-request-id'),'body':body}
def close_dialogs(page): page.evaluate("()=>{for(const d of document.querySelectorAll('dialog[open]'))try{d.close()}catch{}}")
def open_process(page,code,pid):
 global PHASE
 close_dialogs(page);PHASE=f'{code}-catalogue-nav';page.locator('.service-nav [data-service="processes"]').click();page.wait_for_function("()=>!document.querySelector('#processesView')?.hidden");PHASE=f'{code}-catalogue-card';card=page.locator(f'#procedureHub [data-process-code="{code}"]');expect(card).to_be_visible();card.locator(':scope > footer .procedure-primary,:scope > footer .primary').first.click();host='#monitoringView' if pid=='monitoring' else '#incidentsView' if pid=='incidents' else '#grcWorkspace';PHASE=f'{code}-surface-commit';page.wait_for_function("([host,code])=>{const h=document.querySelector(host),f=h?.querySelector(':scope > .procedure-frame');return !!(h&&h.offsetParent!==null&&f&&f.querySelector('.procedure-frame-code')?.textContent?.includes(code))}",arg=[host,code]);return host
def audit_one(page,code,pid):
 global PHASE
 host=open_process(page,code,pid);PHASE=f'{code}-attention-slot';slot=page.locator(f'{host} > [data-procedure-attention-slot="{pid}"]');expect(slot).to_have_count(1);section=slot.locator(':scope > [data-procedure-worklist]');expect(section).to_have_count(1);owner=slot.get_attribute('data-attention-slot-owner');assert owner==OWNER[pid],(pid,owner,OWNER[pid]);PHASE=f'{code}-first-operational-order';frame=page.locator(f'{host} > .procedure-frame');rail=page.locator(f'{host} > .procedure-support-rail');context=rail.locator(':scope > [data-editorial-slot="advanced-context"]');reference=rail.locator(':scope > [data-editorial-slot="reference"]');expect(frame).to_have_count(1);expect(rail).to_have_count(1);assert frame.evaluate('(node,rail)=>node.nextElementSibling===rail',rail.element_handle()),f'{pid}: support rail must be immediately below header';expect(context).to_have_count(1);expect(reference).to_have_count(1);assert context.evaluate('(ctx,ref)=>ctx.nextElementSibling===ref',reference.element_handle());assert frame.evaluate('(node,slot)=>node.nextElementSibling===slot',slot.element_handle());assert section.get_attribute('data-placement-owner')==owner
 mount=section.get_attribute('data-a6-ux4-mount') or 'legacy-visible';PHASE=f'{code}-mount-mode'
 if mount=='semantic-bridge':
  assert section.is_hidden(),f'{pid}: semantic worklist bridge must not compete visually';assert page.locator(f'{host}[data-a6-ux4-single-collection="native"]').count()==1;scope=page.locator(f'{host} [data-a6-ux4-scope="{pid}"]');expect(scope).to_be_visible();expect(scope).to_have_value('actionable');assert page.locator(f'{host} [data-a6-ux4-actionable="true"]:visible').count()>0;assert page.locator(f'{host} .procedure-worklist-reveal:visible').count()==0
 else: expect(section).to_be_visible()
 PHASE=f'{code}-typed-target-present';buttons=section.locator('[data-work-item-target]');assert buttons.count()>0;button=buttons.first;subject_id=button.get_attribute('data-work-target-subject-id');subject_type=button.get_attribute('data-work-target-subject-type');action=button.get_attribute('data-work-target-action');assert subject_id and subject_type and action
 PHASE=f'{code}-exact-target-dispatch';button.evaluate('e=>e.click()');page.wait_for_function("el=>!!el.dataset.workTargetResolution",arg=button.element_handle(),timeout=5000);resolution=button.get_attribute('data-work-target-resolution');assert resolution!='unresolved',(pid,subject_type,subject_id,action,resolution);PHASE=f'{code}-exact-target-marker';page.wait_for_function("()=>document.querySelectorAll('[data-work-target-active=\"true\"]').length===1",timeout=5000);active=page.locator('[data-work-target-active="true"]');assert active.get_attribute('data-work-target-subject-id')==subject_id;assert active.get_attribute('data-work-target-action')==action
 RESULTS.append({'code':code,'procedureId':pid,'slotOwner':owner,'mountMode':mount,'target':{'subjectType':subject_type,'subjectId':subject_id,'intendedAction':action,'resolution':resolution},'singleVisibleOperationalCollection':mount=='semantic-bridge'});close_dialogs(page)
try:
 with sync_playwright() as pw:
  launch={'headless':True,'args':['--no-sandbox']};
  if os.environ.get('ICTC_CHROMIUM'):launch['executable_path']=os.environ['ICTC_CHROMIUM']
  browser=pw.chromium.launch(**launch);ctx=browser.new_context(viewport={'width':1440,'height':950});ctx.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','home')");request=ctx.request;PHASE='runtime-health';health=api_get(request,'/api/health');assert health['status']==200;PHASE='runtime-identity';identity=api_get(request,'/api/admin/identity');assert identity['status']==200;build_identity=(identity['body'] or {}).get('buildIdentity') or {};build=build_identity.get('build') or {};assert build_identity.get('authority')=='runtime-build-identity'
  if EXPECTED_SHA: assert build.get('sha')==EXPECTED_SHA,(EXPECTED_SHA,build);assert build.get('exact') is True;assert build.get('dirty') is False
  page=ctx.new_page();page.set_default_timeout(30000);page.on('response',lambda res:NETWORK.append({'method':res.request.method,'path':urllib.parse.urlparse(res.url).path,'status':res.status}) if res.url.startswith(BASE+'/api/') else None);page.on('requestfailed',lambda req:FAILURES.append({'method':req.method,'url':req.url,'failure':req.failure}));page.on('pageerror',lambda exc:PAGE_ERRORS.append(str(exc)));PHASE='bootstrap';page.goto(BASE+'/?view=home',wait_until='domcontentloaded')
  try: page.wait_for_function("()=>Number(document.documentElement.dataset.experienceCycle||0)>0&&document.documentElement.dataset.nativeSemanticLattice==='3.2.0'")
  except BaseException:
   diag=page.evaluate("()=>({cycle:document.documentElement.dataset.experienceCycle||'0',lattice:document.documentElement.dataset.nativeSemanticLattice||'none',composition:document.documentElement.dataset.enduserComposition||'none'})")
   if PAGE_ERRORS: PHASE=f"bootstrap-pageerror-{phase_token(PAGE_ERRORS[-1])}"
   elif str(diag.get('cycle')) in ('','0') and diag.get('lattice')=='3.2.0': PHASE='bootstrap-lifecycle-not-converged'
   elif diag.get('lattice')!='3.2.0': PHASE=f"bootstrap-lattice-{phase_token(diag.get('lattice'))}-composition-{phase_token(diag.get('composition'))}"
   else: PHASE=f"bootstrap-cycle-{phase_token(diag.get('cycle'))}-lattice-{phase_token(diag.get('lattice'))}"
   raise
  for code,pid in PROCEDURES:audit_one(page,code,pid)
  PHASE='aggregate';assert len(RESULTS)==7 and all(r['target']['resolution']!='unresolved' for r in RESULTS);assert not FAILURES,FAILURES;assert not PAGE_ERRORS,PAGE_ERRORS;writes=[x for x in NETWORK if x['method']!='GET'];assert not writes,writes
  report={'ok':True,'slice':'S4-A1','profile':'worklist-presentation-authority','expectedBuildSha':EXPECTED_SHA or None,'runtimeIdentity':build_identity,'procedures':RESULTS,'metrics':{'procedureCoverage':'7/7','exactTargetResolved':'7/7','presentationAuthorityPreserved':True,'integratedMountAccepted':True,'unintendedWrites':0},'network':NETWORK,'pageErrors':PAGE_ERRORS,'claimBoundary':'Exact-head browser evidence that canonical S4-A1 worklist authority can be mounted as a semantic bridge into one native visible collection when every actionable typed target resolves; fallback visibility remains required on partial binding. Not human usability, accessibility certification or enterprise-ready proof.'};(ART/'browser-s4-a1-worklist-authority.json').write_text(json.dumps(report,indent=2,ensure_ascii=False),encoding='utf8');print(json.dumps({'ok':True,'slice':'S4-A1','procedures':7,'exactTargets':7,'integratedMount':True,'writes':0}),flush=True);ctx.close();browser.close()
except BaseException as exc:fail(exc);traceback.print_exc();raise