import json, os, pathlib, traceback
from playwright.sync_api import expect, sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1]; ART=ROOT/'artifacts'; ART.mkdir(exist_ok=True)
BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4173').rstrip('/'); PHASE='init'
PROOF_READING_ORDER='facts>method>decisions>trace>evidence-basis>epistemic>external>integrity>export'
def fail(exc):
 payload={'ok':False,'phase':PHASE,'type':type(exc).__name__,'message':str(exc),'traceback':traceback.format_exc()};(ART/'browser-ui-epistemic-convergence-error.json').write_text(json.dumps(payload,indent=2),encoding='utf8');print(f'::error title=browser-ui-epistemic-convergence::{PHASE}: {type(exc).__name__}: {exc}',flush=True)
def processes(page): return page.locator('.service-nav [data-service="processes"]')
def proof(page): return page.locator('.service-nav [data-service="proof"]')
def open_epistemic(page):
 proof(page).click();expect(page.locator('#proofView')).to_be_visible();page.wait_for_function("expected=>document.querySelector('#proofView')?.dataset.proofReadingOrder===expected",arg=PROOF_READING_ORDER);investigation=page.locator('#proofContent > details[data-proof-workspace="epistemic-investigation"]');expect(investigation).to_have_count(1);expect(page.locator('#proofView #epistemicMetaCard')).to_have_count(0);assert investigation.get_attribute('open') is None;investigation.locator(':scope > summary').click();action=investigation.locator('[data-service="epistemic"]');expect(action).to_be_visible();action.click();expect(page.locator('#epistemicView')).to_be_visible();expect(page.locator('#epistemicTitle')).to_have_text('Relazioni tra decisioni, fonti ed evidenze')
def open_process(page,code):
 processes(page).click();card=page.locator(f'#procedureHub [data-process-code="{code}"]');expect(card).to_be_visible();card.locator(':scope > footer .primary').click();page.wait_for_timeout(100)
def no_overflow(page):
 m=page.evaluate('()=>({inner:innerWidth,html:document.documentElement.scrollWidth,body:document.body.scrollWidth})');assert max(m['html'],m['body'])<=m['inner']+1,m
def open_technical_modes(page):
 detail=page.locator('#epistemicView details[data-epistemic-a3="technical-modes"]');expect(detail).to_be_visible()
 if detail.get_attribute('open') is None: detail.locator(':scope > summary').click()
 expect(detail).to_have_attribute('open','');return detail
def click_mode(page,mode):
 global PHASE
 button=page.locator(f'[data-epistemic-mode="{mode}"]');expect(button).to_be_visible();expect(button).to_be_enabled();target=button.evaluate("""e=>{e.scrollIntoView({block:'center',inline:'nearest'});const r=e.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2,under=document.elementFromPoint(x,y),owner=under?.closest?.('[data-epistemic-mode]'),style=under?getComputedStyle(under):null;return{owner:owner?.dataset.epistemicMode||null,underId:under?.id||'',underClass:typeof under?.className==='string'?under.className:'',underTag:under?.tagName||'',pointerEvents:style?.pointerEvents||'',zIndex:style?.zIndex||'',x,y,inViewport:x>=0&&x<innerWidth&&y>=0&&y<innerHeight};}""")
 if not (target['inViewport'] and target['owner']==mode):
  identity=target['underId'] or (target['underClass'].split()[0] if target['underClass'] else '') or target['underTag'] or 'unknown';PHASE=f'mode-covered-{identity}'[:48];raise AssertionError(f"covered-by={identity};owner={target['owner']};pointer={target['pointerEvents']};z={target['zIndex']};x={target['x']};y={target['y']}")
 button.click()
def selected_node(page):
 return page.evaluate("()=>[...document.querySelectorAll('.epistemic-node-list button')].find(b=>b.getAttribute('aria-pressed')==='true')?.dataset.epistemicNode||null")
def graph_ready(page,require_edges=False):
 graph=page.locator('.epistemic-graph');expect(graph).to_have_attribute('data-enhanced','true');expect(page.locator('.epistemic-graph-canvas g[data-epistemic-node]').first).to_be_visible();focus=graph.get_attribute('data-epistemic-graph-focus') or '';nodes=int(graph.get_attribute('data-epistemic-graph-node-count') or '0');edges=int(graph.get_attribute('data-epistemic-graph-edge-count') or '0');assert focus and 1<=nodes<=24 and 0<=edges<=48,(focus,nodes,edges);assert page.locator(f'.epistemic-node-list [data-epistemic-node="{focus}"]').count()==1
 if require_edges: page.wait_for_function("()=>document.querySelectorAll('.epistemic-graph-edge[data-graph-from][data-graph-to]').length>0")
 return focus,nodes,edges
def projection_graph(page):
 return page.evaluate("""async()=>{const r=await fetch('/api/epistemic-lattice?offset=0&limit=80',{headers:{'x-ictc-role':'admin','x-ictc-actor-id':'browser-ui-convergence'}});if(!r.ok)throw new Error('epistemic projection '+r.status);return await r.json();}""")
def wait_node_detail(page,node_id,atom_ids):
 if node_id in atom_ids:
  page.wait_for_function("id=>[...document.querySelectorAll('.epistemic-node-list button')].some(b=>b.dataset.epistemicNode===id&&b.getAttribute('aria-pressed')==='true')",arg=node_id);expect(page.locator('.epistemic-detail')).to_be_visible();return 'atom'
 page.wait_for_function("id=>document.querySelector('#epistemicGraphReferenceDetail')?.dataset.graphReferenceId===id",arg=node_id);expect(page.locator('#epistemicGraphReferenceDetail')).to_be_visible();return 'reference'
try:
 with sync_playwright() as pw:
  launch={'headless':True,'args':['--no-sandbox']}
  if os.environ.get('ICTC_CHROMIUM'):launch['executable_path']=os.environ['ICTC_CHROMIUM']
  browser=pw.chromium.launch(**launch);ctx=browser.new_context(viewport={'width':1280,'height':900});ctx.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','processes')")
  page=ctx.new_page();page.set_default_timeout(30000);errors=[];capture={'on':False};writes=[]
  page.on('pageerror',lambda e:errors.append(str(e)))
  page.on('request',lambda req:writes.append({'method':req.method,'url':req.url}) if capture['on'] and req.url.startswith(BASE+'/api/') and req.method!='GET' else None)
  PHASE='seed-source';page.goto(BASE+'/?view=processes',wait_until='networkidle');open_process(page,'EC-01');page.locator('.procedure-frame:visible .procedure-primary').click();expect(page.locator('#incidentDialog')).to_be_visible();page.locator('#incidentDialog textarea[name="originalNarrative"]').fill('Evento di convergenza UI usato come source per verificare readiness asincrona e provenance del draft collegato.');page.locator('#incidentDialog input[name="awarenessAt"]').fill('2026-08-11T08:45');page.locator('#incidentDialog button[type="submit"]').click();expect(page.locator('#incidentDialog')).not_to_be_visible();expect(page.locator('#incidentList .incident-card').first).to_be_visible()
  PHASE='cross-create';cross=page.locator('.procedure-cross-tools[data-cross-tools="incidents"] [data-cross-create]');expect(cross).to_be_visible();cross.click();dialog=page.locator('#crossCreateDialog');expect(dialog).to_be_visible();target=page.locator('#crossTarget');submit=page.locator('[data-cross-submit]');expect(target).to_be_enabled();expect(submit).to_be_enabled();targets=target.locator('option').evaluate_all("xs=>xs.map(x=>x.value).filter(Boolean)");assert 'actions' in targets,targets;assert 'incidents' not in targets,targets;target.select_option('actions');page.locator('#crossTitle').fill('Azione draft da convergenza UI');page.locator('#crossDescription').fill('Draft collegato: ownership, priorita e chiusura restano checkpoint AP-01.');submit.click();expect(dialog).not_to_be_visible()
  PHASE='technical-progressive';open_epistemic(page);technical=page.locator('#epistemicView details[data-epistemic-workspace="rules"]');expect(technical).to_be_visible();expect(technical.locator(':scope > summary')).to_have_text('Regole e dettagli della vista');assert technical.get_attribute('open') is None;compression=page.locator('#epistemicCompression');expect(compression).to_be_hidden();technical.locator(':scope > summary').click();expect(compression).to_be_visible();rev=int(compression.get_attribute('data-state-revision') or '0');digest=compression.get_attribute('data-projection-digest') or '';assert rev>0 and len(digest)>=16,(rev,digest);envelopes=compression.locator('[data-envelope-kind]');assert envelopes.count()>0;atom_ids=set()
  for i in range(envelopes.count()): atom_ids.update(x for x in (envelopes.nth(i).get_attribute('data-atom-ids') or '').split(',') if x)
  assert atom_ids
  PHASE='technical-progressive-advanced';advanced=page.locator('#epistemicView details[data-epistemic-a3="advanced-filters"]');expect(advanced).to_be_visible();assert advanced.get_attribute('open') is None;advanced.locator(':scope > summary').click();expect(advanced).to_have_attribute('open','');filter_control=page.locator('#epistemicProcedureFilter');expect(filter_control).to_be_visible()
  PHASE='technical-progressive-envelope';incident_envelope=compression.locator('[data-envelope-kind="procedure"][data-envelope-value="incidents"]');expect(incident_envelope).to_be_visible();incident_envelope.click();expect(filter_control).to_have_value('incidents');filter_control.select_option('');payload=projection_graph(page);nodes_by_id={str(n.get('id')):n for n in payload.get('graph',{}).get('nodes',[])};candidate=None;reference_pair=None
  for edge in payload.get('graph',{}).get('edges',[]):
   a,b=str(edge.get('from') or ''),str(edge.get('to') or '')
   for atom,other in ((a,b),(b,a)):
    if atom in atom_ids and other in nodes_by_id:
     candidate=candidate or atom
     if other not in atom_ids and nodes_by_id.get(other,{}).get('kind') in ('basis-reference','semantic-reference'):reference_pair=(atom,other);break
   if reference_pair:break
  candidate=(reference_pair or (candidate,None))[0];assert candidate,candidate
  PHASE='technical-progressive-rules-close';technical=page.locator('#epistemicView details[data-epistemic-workspace="rules"]');expect(technical).to_be_visible();
  if technical.get_attribute('open') is not None: technical.locator(':scope > summary').click()
  assert technical.get_attribute('open') is None;expect(page.locator('#epistemicCompression')).to_be_hidden()
  PHASE='technical-progressive-advanced-close';advanced=page.locator('#epistemicView details[data-epistemic-a3="advanced-filters"]');expect(advanced).to_be_visible();
  if advanced.get_attribute('open') is not None: advanced.locator(':scope > summary').click()
  assert advanced.get_attribute('open') is None;expect(page.locator('#epistemicProcedureFilter')).to_be_hidden()
  PHASE='technical-progressive-modes-open';modes=open_technical_modes(page);expect(modes.locator('[data-epistemic-mode="flat"]')).to_be_visible();expect(modes.locator('[data-epistemic-mode="graph"]')).to_be_visible()
  PHASE='technical-progressive-modes-overflow';no_overflow(page)
  PHASE='graph-focus-selection';click_mode(page,'flat');candidate_button=page.locator(f'[data-epistemic-atom="{candidate}"]');expect(candidate_button).to_be_visible();candidate_button.click();open_technical_modes(page)
  PHASE='graph-geometry';click_mode(page,'graph');focus,node_count,edge_count=graph_ready(page,require_edges=True);assert focus==candidate,(focus,candidate);assert edge_count>0;visual=page.locator('.epistemic-graph-canvas circle.epistemic-graph-node').first;hit=page.locator('.epistemic-graph-canvas circle.epistemic-graph-hit').first;assert float(visual.get_attribute('r') or 0)==10;assert float(hit.get_attribute('r') or 0)==22;hb=hit.bounding_box();vb=visual.bounding_box();assert hb and vb and hb['width']>=43.5 and vb['width']<hb['width'],(hb,vb);collisions=page.evaluate("""()=>{const circles=[...document.querySelectorAll('.epistemic-graph-node')].map((c,i)=>({i,r:c.getBoundingClientRect()}));return [...document.querySelectorAll('.epistemic-graph-label')].flatMap((t,i)=>{const r=t.getBoundingClientRect();if(!r.width||!r.height)return[];return circles.filter(c=>!(r.right<=c.r.left||r.left>=c.r.right||r.bottom<=c.r.top||r.top>=c.r.bottom)).map(c=>({label:i,node:c.i}));});}""");assert not collisions,collisions;connected=page.evaluate("()=>{const ids=[];for(const l of document.querySelectorAll('.epistemic-graph-edge'))for(const id of [l.dataset.graphFrom,l.dataset.graphTo])if(id&&!ids.includes(id))ids.push(id);return ids;}");assert candidate in connected,connected;atom_connected=[x for x in connected if x in atom_ids];reference_connected=[x for x in connected if x not in atom_ids];seed_id=candidate;drag_id=next(x for x in connected if x!=seed_id);page.evaluate("id=>[...document.querySelectorAll('.epistemic-node-list button')].find(b=>b.dataset.epistemicNode===id)?.click()",seed_id);graph_ready(page,require_edges=True);assert selected_node(page)==seed_id,(selected_node(page),seed_id)
  targetability=page.evaluate("""id=>{const g=[...document.querySelectorAll('.epistemic-graph-canvas g[data-epistemic-node]')].find(x=>x.dataset.epistemicNode===id);if(!g)return null;g.scrollIntoView({block:'center',inline:'center'});const hit=g.querySelector('.epistemic-graph-hit');if(!hit)return null;const r=hit.getBoundingClientRect(),x=r.left+r.width/2,y=r.top+r.height/2,under=document.elementFromPoint(x,y);return{x,y,innerWidth,innerHeight,inViewport:x>=0&&x<innerWidth&&y>=0&&y<innerHeight,hitId:under?.closest?.('g[data-epistemic-node]')?.dataset.epistemicNode||null};}""",drag_id);assert targetability and targetability['inViewport'] and targetability['hitId']==drag_id,targetability
  baseline=page.evaluate("""id=>{const g=[...document.querySelectorAll('.epistemic-graph-canvas g[data-epistemic-node]')].find(x=>x.dataset.epistemicNode===id);const hit=g?.querySelector('.epistemic-graph-hit');const line=[...document.querySelectorAll('.epistemic-graph-edge')].find(l=>l.dataset.graphFrom===id||l.dataset.graphTo===id);if(!g||!hit||!line)return null;const r=hit.getBoundingClientRect(),from=line.dataset.graphFrom===id;return{id,center:{x:r.left+r.width/2,y:r.top+r.height/2},from,x:Number(line.getAttribute(from?'x1':'x2')),y:Number(line.getAttribute(from?'y1':'y2'))};}""",drag_id);assert baseline,drag_id
  capture['on']=True;page.mouse.move(baseline['center']['x'],baseline['center']['y']);page.mouse.down();page.mouse.move(baseline['center']['x']+56,baseline['center']['y']+36,steps=6);page.mouse.up();page.wait_for_timeout(80);capture['on']=False
  after=page.evaluate("""id=>{const g=[...document.querySelectorAll('.epistemic-graph-canvas g[data-epistemic-node]')].find(x=>x.dataset.epistemicNode===id);const line=[...document.querySelectorAll('.epistemic-graph-edge')].find(l=>l.dataset.graphFrom===id||l.dataset.graphTo===id);if(!g||!line)return null;const from=line.dataset.graphFrom===id;return{transform:g.getAttribute('transform')||'',x:Number(line.getAttribute(from?'x1':'x2')),y:Number(line.getAttribute(from?'y1':'y2'))};}""",drag_id);assert after and after['transform'].startswith('translate('),after;assert abs(after['x']-baseline['x'])>20 and abs(after['y']-baseline['y'])>15,(baseline,after);assert selected_node(page)==seed_id,(selected_node(page),seed_id,'drag must not activate node');assert not writes,writes
  reference_observed=False
  if reference_connected:
   PHASE='graph-click-activation';click_id=reference_connected[0];page.evaluate("id=>[...document.querySelectorAll('.epistemic-graph-canvas g[data-epistemic-node]')].find(g=>g.dataset.epistemicNode===id)?.querySelector('.epistemic-graph-node')?.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}))",click_id);assert wait_node_detail(page,click_id,atom_ids)=='reference';ref_detail=page.locator('#epistemicGraphReferenceDetail');expect(ref_detail).to_contain_text(click_id);graph_ready(page,require_edges=True);reference_observed=True
  PHASE='graph-keyboard-activation';keyboard_id=atom_connected[0];page.evaluate("id=>[...document.querySelectorAll('.epistemic-graph-canvas g[data-epistemic-node]')].find(g=>g.dataset.epistemicNode===id)?.focus()",keyboard_id);page.keyboard.press('Enter');assert wait_node_detail(page,keyboard_id,atom_ids)=='atom';graph_ready(page,require_edges=True)
  PHASE='graph-zoom-reset';capture['on']=True;page.locator('[data-graph-zoom="in"]').click();expect(page.locator('[data-graph-zoom-label]')).to_have_text('110%');assert 'scale(1.1)' in (page.locator('.epistemic-graph-canvas svg').get_attribute('style') or '');page.locator('[data-graph-reset]').click();expect(page.locator('[data-graph-zoom-label]')).to_have_text('100%');capture['on']=False;assert not writes,writes;no_overflow(page)
  PHASE='mobile-containment';mc=browser.new_context(viewport={'width':390,'height':844});mc.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','processes')");m=mc.new_page();m.set_default_timeout(30000);m.goto(BASE+'/?view=processes',wait_until='networkidle');open_epistemic(m);td=m.locator('#epistemicView details[data-epistemic-workspace="rules"]');expect(td).to_be_visible();assert td.get_attribute('open') is None;no_overflow(m);open_technical_modes(m);click_mode(m,'graph');graph_ready(m);no_overflow(m);heights=m.locator('.epistemic-graph-controls button').evaluate_all('xs=>xs.map(x=>x.getBoundingClientRect().height)');assert heights and min(heights)>=43.5,heights;mc.close()
  assert not errors,errors
  out={'ok':True,'profile':'ui-epistemic-procedure-convergence+native-semantic-lattice-3.2+s4-a3','metaEntrySurface':'Evidenze ICTC / progressive disclosure after evidence meaning','proofReadingOrder':PROOF_READING_ORDER,'duplicateProofMetaEntry':False,'draftAsyncReadiness':True,'meaningfulTargets':targets,'technicalCompressionPreserved':True,'technicalDefaultOpen':False,'technicalModesProgressive':True,'compressionRevision':rev,'compressionDigest':digest,'reversibleEnvelope':True,'graphFocus':focus,'focusedGraphNodes':node_count,'focusedGraphEdges':edge_count,'focusedGraphLimits':{'nodes':24,'edges':48},'visualNodeRadius':10,'hitRadius':22,'labelNodeCollisions':0,'dragTargetability':True,'dragMovesConnectedEdges':True,'dragDoesNotActivate':True,'referenceClickObserved':reference_observed,'keyboardAtomOpensDetail':True,'graphGesturesWriteCount':len(writes),'mobileOverflow':False,'evidenceClass':'E2-server-backed-browser+focused-one-hop-interaction-falsification'};(ART/'browser-ui-epistemic-convergence.json').write_text(json.dumps(out,indent=2),encoding='utf8');print('browser-ui-epistemic-convergence-s4-a3: complete',flush=True);ctx.close();browser.close()
except BaseException as exc:fail(exc);traceback.print_exc();raise
