import json, os, pathlib, traceback
from playwright.sync_api import expect, sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1]; ART=ROOT/'artifacts'; ART.mkdir(exist_ok=True)
BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4173').rstrip('/'); PHASE='init'
PROCESS_SURFACES={'RN-01':('#monitoringView','monitoring'),'EC-01':('#incidentsView','incidents'),'AO-01':('#grcWorkspace','objects'),'MC-01':('#grcWorkspace','coverage'),'AP-01':('#grcWorkspace','actions'),'RC-01':('#grcWorkspace','risks'),'AR-01':('#grcWorkspace','assurance')}
def fail(exc):
 payload={'ok':False,'phase':PHASE,'type':type(exc).__name__,'message':str(exc),'traceback':traceback.format_exc()};(ART/'browser-information-value-error.json').write_text(json.dumps(payload,indent=2),encoding='utf8');print(f'::error title=browser-information-value::{PHASE}: {type(exc).__name__}: {exc}',flush=True)
def no_overflow(page):
 m=page.evaluate('()=>({inner:innerWidth,html:document.documentElement.scrollWidth,body:document.body.scrollWidth})');assert max(m['html'],m['body'])<=m['inner']+1,m
def open_view(page,view):page.goto(f'{BASE}/?view={view}',wait_until='networkidle')
def open_process(page,code):
 open_view(page,'processes');card=page.locator(f'#procedureHub [data-process-code="{code}"]');expect(card).to_be_visible();card.locator(':scope > footer .procedure-primary,:scope > footer .primary').first.click();selector,surface=PROCESS_SURFACES[code];page.wait_for_function("x=>{const r=document.querySelector(x.selector);return !!(r&&r.offsetParent!==null&&r.dataset.compositionSurface===x.surface&&document.documentElement.dataset.semanticComposition==='3.1.0');}",arg={'selector':selector,'surface':surface})
def assert_above_fold(page,selector,budget=360):
 box=page.locator(selector).first.bounding_box();assert box and box['y']<budget,{'selector':selector,'box':box,'budget':budget}
def open_profile(page):
 menu=page.locator('#stableProfileMenu');expect(menu.locator(':scope > summary')).to_be_visible();
 if menu.get_attribute('open') is None:menu.locator(':scope > summary').click()
try:
 with sync_playwright() as pw:
  launch={'headless':True,'args':['--no-sandbox']}
  if os.environ.get('ICTC_CHROMIUM'):launch['executable_path']=os.environ['ICTC_CHROMIUM']
  browser=pw.chromium.launch(**launch);ctx=browser.new_context(viewport={'width':1280,'height':900});ctx.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','home')")
  page=ctx.new_page();page.set_default_timeout(30000);errors=[];writes=[];page.on('pageerror',lambda e:errors.append(str(e)));page.on('request',lambda req:writes.append({'method':req.method,'url':req.url}) if req.url.startswith(BASE+'/api/') and req.method!='GET' else None)
  PHASE='home';open_view(page,'home');expect(page.locator('#homeTitle')).to_have_text('Attività di compliance');expect(page.locator('#homePulse')).to_be_hidden();expect(page.locator('#ictcManifest')).to_have_count(0);expect(page.locator('#homePriorities')).to_be_visible();assert page.locator('#homePriorities .home-business-priority').count()<=5;assert_above_fold(page,'#homePriorities',430);no_overflow(page)
  PHASE='processes';open_view(page,'processes');expect(page.locator('#processesView [data-surface-information-value]')).to_have_count(0);expect(page.locator('#procedureHub .procedure-card')).to_have_count(7);expect(page.locator('#procedureHub .procedure-card').first).to_have_attribute('data-procedure-frame-variant','row');expect(page.locator('#procedureHub .procedure-signals')).to_have_count(0);assert_above_fold(page,'#procedureHub .procedure-card',330);no_overflow(page)
  PHASE='rn';open_process(page,'RN-01');expect(page.locator('#monitoringView > .procedure-frame')).to_be_visible();expect(page.locator('#monitoringView > .hero')).to_be_hidden();expect(page.locator('#monitoringView [data-finetune-compass]')).to_be_hidden();assert_above_fold(page,'#monitoringView > .section-block',390);no_overflow(page)
  PHASE='ec';open_process(page,'EC-01');expect(page.locator('#incidentsView > .procedure-frame')).to_be_visible();expect(page.locator('#incidentsView > .hero')).to_be_hidden();expect(page.locator('#incidentsView [data-finetune-compass]')).to_be_hidden();assert_above_fold(page,'#incidentsView > .section-block',390);no_overflow(page)
  for code in ['AO-01','MC-01','AP-01','RC-01','AR-01']:
   PHASE=f'grc-{code}';open_process(page,code);frame=page.locator('#grcWorkspace > .procedure-frame');expect(frame).to_be_visible();work=page.locator('#grcWorkspace .grc-list');expect(work).to_be_visible();status=page.locator('#grcWorkspace details[data-composition-detail="process-status"]');expect(status).to_have_count(1);expect(status).not_to_have_attribute('open','');decision=page.locator('#grcWorkspace .procedure-decision-frame .composition-process-context');expect(decision).to_have_count(1);expect(decision).not_to_have_attribute('open','');order=page.evaluate("()=>{const b=document.querySelector('#grcWorkspace .grc-body'),l=b?.querySelector('.grc-list'),k=b?.querySelector('details[data-composition-detail=\"process-status\"]');return !!(b&&l&&k&&[...b.children].indexOf(l)<[...b.children].indexOf(k));}");assert order,code;assert_above_fold(page,'#grcWorkspace .grc-list',430);no_overflow(page)
  PHASE='proof';open_view(page,'proof');expect(page.locator('#proofTitle')).to_have_text('Evidenze ICTC');expect(page.locator('#proofView [data-surface-information-value]')).to_have_count(0);expect(page.locator('#proofContent')).to_be_visible();decision=page.locator('#proofContent > details.proof-section').filter(has_text='Decisioni e tracciabilità');expect(decision).to_have_attribute('open','');expect(page.locator('#proofContent > details[data-composition-detail="proof-reading"]')).not_to_have_attribute('open','');no_overflow(page)
  PHASE='epistemic';open_view(page,'epistemic');expect(page.locator('#epistemicTitle')).to_have_text('Relazioni tra decisioni, fonti ed evidenze');expect(page.locator('#epistemicSummary')).to_be_hidden();expect(page.locator('#epistemicCompression')).to_be_hidden();expect(page.locator('[data-epistemic-mode="explore"]')).to_have_text('Quadro');expect(page.locator('[data-epistemic-mode="flat"]')).to_have_text('Vista tecnica');no_overflow(page)
  PHASE='admin';open_view(page,'home');open_profile(page);page.locator('#stableProfileMenu #openAdminCenter').dispatch_event('click');admin=page.locator('#adminCenter');expect(admin).to_be_visible();expect(admin.locator('#adminCenterTitle')).to_have_text('Amministrazione ICTC');expect(admin.locator('#adminMetrics')).to_be_hidden();expect(admin.locator('#adminAttention').locator('xpath=..')).to_be_visible();tech=admin.locator('details[data-composition-detail="technical-controls"]');expect(tech).to_have_count(1);expect(tech).not_to_have_attribute('open','');page.keyboard.press('Escape')
  PHASE='settings';open_profile(page);page.locator('#stableProfileMenu #openSettings').dispatch_event('click');settings=page.locator('#settingsDialog');expect(settings).to_be_visible();expect(settings.locator('#settingsTitle')).to_have_text('Configurazione AI');expect(settings.locator('details.advanced')).not_to_have_attribute('open','');page.keyboard.press('Escape')
  PHASE='mobile'
  for width in [390,320]:
   mc=browser.new_context(viewport={'width':width,'height':844});mc.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','home')");m=mc.new_page();m.set_default_timeout(30000);open_view(m,'home');expect(m.locator('#homePulse')).to_be_hidden();no_overflow(m);open_view(m,'processes');no_overflow(m);open_process(m,'AO-01');no_overflow(m);mc.close()
  assert not writes,writes;assert not errors,errors
  out={'ok':True,'profile':'semantic-composition-3.1','surfaceCoverage':['home','processes','RN-01','EC-01','AO-01','MC-01','AP-01','RC-01','AR-01','proof','epistemic','admin','settings'],'homeNumericDashboard':False,'procedureWorkAboveFold':True,'technicalDefaultOpen':False,'mobileWidths':[390,320],'mobileOverflow':False,'writeCount':len(writes),'claimBoundary':'Rendered hierarchy/compression evidence only; not human comprehension research, legal compliance, accessibility certification or deployment security.'};(ART/'browser-information-value.json').write_text(json.dumps(out,indent=2),encoding='utf8');print('browser-information-value-3.1: complete');ctx.close();browser.close()
except BaseException as exc:fail(exc);traceback.print_exc();raise