import json, os, pathlib, traceback
from playwright.sync_api import expect, sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1];ART=ROOT/'artifacts';ART.mkdir(exist_ok=True);BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4173').rstrip('/');PHASE='init'
def fail(exc):
 (ART/'browser-ui-epistemic-convergence-error.json').write_text(json.dumps({'ok':False,'phase':PHASE,'type':type(exc).__name__,'message':str(exc),'traceback':traceback.format_exc()},indent=2),encoding='utf8');print(f'::error title=browser-ui-epistemic-convergence::{PHASE}: {type(exc).__name__}: {exc}',flush=True)
def processes(page):return page.locator('.service-nav [data-service="processes"]')
def proof(page):return page.locator('.service-nav [data-service="proof"]')
def open_process(page,code):
 processes(page).click();card=page.locator(f'#procedureHub [data-process-code="{code}"]');expect(card).to_be_visible();card.locator(':scope > footer .primary').click();page.wait_for_timeout(100)
def open_epistemic(page):
 processes(page).click();meta=page.locator('#epistemicMetaCard');expect(meta).not_to_be_visible();proof(page).click();expect(page.locator('#proofView')).to_be_visible();expect(meta).to_be_visible();meta.locator('[data-service="epistemic"]').click();expect(page.locator('#epistemicView')).to_be_visible();expect(page.locator('#epistemicTitle')).to_have_text('Relazioni tra decisioni, fonti ed evidenze')
def no_overflow(page):
 m=page.evaluate('()=>({w:innerWidth,h:document.documentElement.scrollWidth,b:document.body.scrollWidth})');assert max(m['h'],m['b'])<=m['w']+1,m
def graph_ready(page):
 expect(page.locator('.epistemic-graph')).to_have_attribute('data-enhanced','true');expect(page.locator('.epistemic-graph-canvas g[data-epistemic-node]').first).to_be_visible();page.wait_for_function("()=>document.querySelectorAll('.epistemic-graph-edge[data-graph-from],.epistemic-graph-edge[data-graph-to]').length>0")
try:
 with sync_playwright() as pw:
  launch={'headless':True,'args':['--no-sandbox']}
  if os.environ.get('ICTC_CHROMIUM'):launch['executable_path']=os.environ['ICTC_CHROMIUM']
  browser=pw.chromium.launch(**launch);ctx=browser.new_context(viewport={'width':1280,'height':900});ctx.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','processes')");page=ctx.new_page();page.set_default_timeout(30000);errors=[];writes=[];capture={'on':False};page.on('pageerror',lambda e:errors.append(str(e)));page.on('request',lambda r:writes.append({'method':r.method,'url':r.url}) if capture['on'] and r.url.startswith(BASE+'/api/') and r.method!='GET' else None)
  PHASE='seed-source';page.goto(BASE+'/?view=processes',wait_until='networkidle');open_process(page,'EC-01');page.locator('.procedure-frame:visible .procedure-primary').click();expect(page.locator('#incidentDialog')).to_be_visible();page.locator('#incidentDialog textarea[name="originalNarrative"]').fill('Evento di convergenza UI per verificare relazioni e provenance senza conclusioni sostanziali.');page.locator('#incidentDialog input[name="awarenessAt"]').fill('2026-08-11T08:45');page.locator('#incidentDialog button[type="submit"]').click();expect(page.locator('#incidentDialog')).not_to_be_visible();expect(page.locator('#incidentList .incident-card').first).to_be_visible()
  PHASE='cross-create';cross=page.locator('.procedure-cross-tools[data-cross-tools="incidents"] [data-cross-create]');expect(cross).to_be_visible();cross.click();expect(page.locator('#crossCreateDialog')).to_be_visible();page.locator('#crossTarget').select_option('actions');page.locator('#crossTitle').fill('Azione collegata browser epistemic');page.locator('#crossDescription').fill('Draft collegato; ownership, priorità e chiusura restano checkpoint AP-01.');page.locator('[data-cross-submit]').click();expect(page.locator('#crossCreateDialog')).not_to_be_visible()
  PHASE='technical-progressive';open_epistemic(page);technical=page.locator('#epistemicView details[data-composition-detail="epistemic-technical"]');expect(technical).to_be_visible();expect(technical.locator(':scope > summary')).to_have_text('Dettagli tecnici della proiezione');assert technical.get_attribute('open') is None;expect(page.locator('#epistemicCompression')).to_be_hidden();technical.locator(':scope > summary').click();expect(page.locator('#epistemicCompression')).to_be_visible();compression=page.locator('#epistemicCompression');rev=int(compression.get_attribute('data-state-revision') or '0');digest=compression.get_attribute('data-projection-digest') or '';assert rev>0 and len(digest)>=16,(rev,digest);envelopes=compression.locator('[data-envelope-kind]');assert envelopes.count()>0;atom_ids=set();
  for i in range(envelopes.count()):atom_ids.update(x for x in (envelopes.nth(i).get_attribute('data-atom-ids') or '').split(',') if x)
  assert atom_ids;incident=envelopes.locator('[data-envelope-kind="procedure"][data-envelope-value="incidents"]');expect(incident).to_be_visible();incident.click();expect(page.locator('#epistemicProcedureFilter')).to_have_value('incidents');page.locator('#epistemicProcedureFilter').select_option('');technical.locator(':scope > summary').click();expect(compression).to_be_hidden();no_overflow(page)
  PHASE='graph';page.locator('[data-epistemic-mode="graph"]').click();graph_ready(page);visual=page.locator('.epistemic-graph-canvas circle.epistemic-graph-node').first;hit=page.locator('.epistemic-graph-canvas circle.epistemic-graph-hit').first;assert float(visual.get_attribute('r') or 0)==10;assert float(hit.get_attribute('r') or 0)==22;hb=hit.bounding_box();assert hb and hb['width']>=43.5,hb;connected=page.evaluate("()=>{const ids=[];for(const l of document.querySelectorAll('.epistemic-graph-edge'))for(const id of [l.dataset.graphFrom,l.dataset.graphTo])if(id&&!ids.includes(id))ids.push(id);return ids;}");assert len(connected)>1,connected;drag_id=connected[0];baseline=page.evaluate("""id=>{const g=[...document.querySelectorAll('.epistemic-graph-canvas g[data-epistemic-node]')].find(x=>x.dataset.epistemicNode===id);const hit=g?.querySelector('.epistemic-graph-hit');const line=[...document.querySelectorAll('.epistemic-graph-edge')].find(l=>l.dataset.graphFrom===id||l.dataset.graphTo===id);if(!g||!hit||!line)return null;const r=hit.getBoundingClientRect(),from=line.dataset.graphFrom===id;return{center:{x:r.left+r.width/2,y:r.top+r.height/2},x:Number(line.getAttribute(from?'x1':'x2')),y:Number(line.getAttribute(from?'y1':'y2'))};}""",drag_id);assert baseline,drag_id;capture['on']=True;page.mouse.move(baseline['center']['x'],baseline['center']['y']);page.mouse.down();page.mouse.move(baseline['center']['x']+56,baseline['center']['y']+36,steps=6);page.mouse.up();page.wait_for_timeout(80);capture['on']=False;after=page.evaluate("""id=>{const g=[...document.querySelectorAll('.epistemic-graph-canvas g[data-epistemic-node]')].find(x=>x.dataset.epistemicNode===id);const line=[...document.querySelectorAll('.epistemic-graph-edge')].find(l=>l.dataset.graphFrom===id||l.dataset.graphTo===id);if(!g||!line)return null;const from=line.dataset.graphFrom===id;return{transform:g.getAttribute('transform')||'',x:Number(line.getAttribute(from?'x1':'x2')),y:Number(line.getAttribute(from?'y1':'y2'))};}""",drag_id);assert after and after['transform'].startswith('translate('),after;assert abs(after['x']-baseline['x'])>20 or abs(after['y']-baseline['y'])>15,(baseline,after);assert not writes,writes
  PHASE='graph-activation';click_id=connected[-1];page.evaluate("id=>[...document.querySelectorAll('.epistemic-graph-canvas g[data-epistemic-node]')].find(g=>g.dataset.epistemicNode===id)?.querySelector('.epistemic-graph-node')?.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}))",click_id);page.wait_for_timeout(80);assert page.locator('.epistemic-detail:visible,#epistemicGraphReferenceDetail:visible').count()>=1;page.locator('[data-graph-zoom="in"]').click();expect(page.locator('[data-graph-zoom-label]')).to_have_text('110%');page.locator('[data-graph-reset]').click();expect(page.locator('[data-graph-zoom-label]')).to_have_text('100%');assert not writes,writes;no_overflow(page)
  PHASE='mobile';mc=browser.new_context(viewport={'width':390,'height':844});mc.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','processes')");m=mc.new_page();m.set_default_timeout(30000);m.goto(BASE+'/?view=processes',wait_until='networkidle');open_epistemic(m);td=m.locator('#epistemicView details[data-composition-detail="epistemic-technical"]');expect(td).to_be_visible();assert td.get_attribute('open') is None;no_overflow(m);m.locator('[data-epistemic-mode="graph"]').click();graph_ready(m);no_overflow(m);heights=m.locator('.epistemic-graph-controls button').evaluate_all('xs=>xs.map(x=>x.getBoundingClientRect().height)');assert heights and min(heights)>=43.5,heights;mc.close()
  assert not errors,errors
  out={'ok':True,'profile':'ui-epistemic-procedure-convergence+semantic-composition-3.1','technicalCompressionPreserved':True,'technicalDefaultOpen':False,'compressionRevision':rev,'compressionDigest':digest,'reversibleEnvelope':True,'visualNodeRadius':10,'hitRadius':22,'dragMovesConnectedEdges':True,'graphGesturesWriteCount':len(writes),'mobileOverflow':False,'evidenceClass':'E2-server-backed-browser+interaction-falsification'};(ART/'browser-ui-epistemic-convergence.json').write_text(json.dumps(out,indent=2),encoding='utf8');print('browser-ui-epistemic-convergence-3.1: complete',flush=True);ctx.close();browser.close()
except BaseException as exc:fail(exc);traceback.print_exc();raise
