import json,os,pathlib,traceback
from playwright.sync_api import expect,sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1];ART=ROOT/'artifacts';ART.mkdir(exist_ok=True);BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4173').rstrip('/');PHASE='init'
def hdr(role='admin'):return{'content-type':'application/json','x-ictc-role':role,'x-ictc-actor-id':f'local-{role}'}
def fail(e):
 p={'ok':False,'phase':PHASE,'type':type(e).__name__,'message':str(e),'traceback':traceback.format_exc()};(ART/'browser-v4-enterprise-nexus-error.json').write_text(json.dumps(p,indent=2),encoding='utf8');print(f'::error title=browser-v4-enterprise-nexus::{PHASE}: {type(e).__name__}: {e}',flush=True)
try:
 with sync_playwright() as pw:
  launch={'headless':True,'args':['--no-sandbox']}
  if os.environ.get('ICTC_CHROMIUM'):launch['executable_path']=os.environ['ICTC_CHROMIUM']
  browser=pw.chromium.launch(**launch);ctx=browser.new_context(viewport={'width':1440,'height':1000});ctx.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','home');localStorage.setItem('ictc-ai-assist','on')")
  page=ctx.new_page();page.set_default_timeout(18000);errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
  def req(method,path,data=None,role='admin'):
   r=ctx.request.fetch(BASE+path,method=method,headers=hdr(role),data=data);assert r.ok,(method,path,r.status,r.text());return r.json()
  PHASE='business-first-home';page.goto(BASE+'/',wait_until='networkidle');expect(page.locator('html')).to_have_attribute('data-ictc-experience','active-1');expect(page.locator('html')).to_have_attribute('data-ictc-market-experience','enterprise-nexus-1');expect(page.locator('html')).to_have_attribute('data-ictc-edition','v4-experimental');expect(page.locator('.service-nav [data-service]')).to_have_count(3);nexus=page.locator('#complianceNexus');nexus.wait_for(state='visible');expect(nexus).to_contain_text('I processi di compliance gestiti da ICTC');expect(nexus.locator('[data-nexus-process]')).to_have_count(7)
  for code in ['RN-01','EC-01','AO-01','MC-01','AP-01','RC-01','AR-01']:expect(nexus).to_contain_text(code)
  expect(nexus).to_contain_text('Amministratore');expect(page.locator('#nexusAiToggle')).to_contain_text('ON')
  PHASE='direct-process-open';nexus.locator('[data-nexus-process="objects"] [data-v3-guide]').click();guide=page.locator('#v3ProcedureDialog');guide.wait_for(state='visible');expect(page.locator('#v3ProcedureTitle')).to_contain_text('AO-01');guide.get_by_role('button',name='Apri procedura').click();expect(page.locator('#grcWorkspace')).to_be_visible();expect(page.locator('#grcWorkspace')).to_contain_text('AO-01')
  PHASE='ai-off';page.locator('.service-nav [data-service="home"]').click();page.locator('#nexusAiToggle').click();expect(page.locator('#nexusAiToggle')).to_contain_text('OFF');expect(page.locator('#nexusAiStatus')).to_contain_text('Nessun passaggio di business richiede AI');expect(page.locator('#complianceNexus [data-nexus-process]')).to_have_count(7)
  PHASE='manual-monitoring-api';mission=req('POST','/api/missions/manual-draft',{'objective':'Monitorare aggiornamenti normativi NIS2','cadence':'168','sourceHints':'ACN'});mid=mission['result']['id'];boot=req('GET','/api/bootstrap');m=next(x for x in boot['missions'] if x['id']==mid);assert m['state']=='needs-plan' and m.get('executionMode')=='manual' and m.get('planTrace') is None
  req('POST',f'/api/missions/{mid}/manual-plan',{'rationale':'Piano definito da persona','queries':['NIS2 ACN'],'preferredSources':['ACN'],'inclusionCriteria':['fonti ufficiali'],'exclusionCriteria':['blog non verificati']});boot=req('GET','/api/bootstrap');m=next(x for x in boot['missions'] if x['id']==mid);assert m['planSource']=='human' and m['planTrace'] is None
  PHASE='manual-incident-api';inc=req('POST','/api/incidents/manual-intake',{'originalNarrative':'Email sospetta bloccata prima della apertura','awarenessAt':'2026-08-08T20:00:00.000Z','attachments':[]},role='user');iid=inc['result']['id'];userboot=req('GET','/api/bootstrap',role='user');item=next(x for x in userboot['incidents'] if x['id']==iid);assert item['state']=='clarifying' and item.get('analysisMode')=='manual' and item.get('analysisTrace') is None
  PHASE='proof-trace';page.locator('#roleSelect').select_option('auditor');page.locator('.service-nav [data-service="proof"]').click();page.locator('#proofContent').wait_for(state='visible');page.locator('#traceExplorer').wait_for(state='visible');expect(page.locator('#traceExplorer')).to_contain_text('Evidence & Trace Explorer');aud=req('GET','/api/bootstrap',role='auditor');assert aud['accessProfile']['mode']=='read-only';assert aud['grc']['readOnly'] is True;assert all(x['readOnly'] for x in aud['work']['queue']['items']);assert aud['processLandscape']['counts']['businessProcesses']==7
  PHASE='global-search';search=page.locator('#globalSearch');search.fill('Monitoraggio');page.locator('#globalSearchResults').wait_for(state='visible');assert page.locator('#globalSearchResults [data-global-kind]').count()>=1
  assert not errors,errors
  report={'ok':True,'productEdition':'V4 Experimental · Enterprise Nexus','marketExperience':'enterprise-nexus-1','businessProcesses':7,'aiOff':True,'checks':['business-first-home','seven-processes','direct-process-open','profile-visible','ai-off-preserves-processes','manual-monitoring-no-provider','manual-incident-no-provider','auditor-read-only','trace-explorer','global-search']};(ART/'browser-v4-enterprise-nexus.json').write_text(json.dumps(report,indent=2),encoding='utf8');print('browser-v4-enterprise-nexus: complete',flush=True);browser.close()
except BaseException as e:fail(e);traceback.print_exc();raise
