import json, os, pathlib, traceback
from playwright.sync_api import expect, sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1]; ART=ROOT/'artifacts'; ART.mkdir(exist_ok=True)
BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4173').rstrip('/'); PHASE='init'
PROOF_READING_ORDER='facts>decisions>evidence-basis>trace>epistemic>external>integrity>method>export'
def fail(e):
 payload={'ok':False,'phase':PHASE,'type':type(e).__name__,'message':str(e),'traceback':traceback.format_exc()}; (ART/'browser-v2-epistemic-error.json').write_text(json.dumps(payload,indent=2),encoding='utf8'); print(f'::error title=browser-v2-epistemic::{PHASE}: {type(e).__name__}: {e}',flush=True)
def no_overflow(page):
 m=page.evaluate('()=>[innerWidth,document.documentElement.scrollWidth,document.body.scrollWidth]'); assert m[1]<=m[0]+1 and m[2]<=m[0]+1,m
def named(page):
 bad=page.locator('button:visible,input:visible,select:visible,textarea:visible').evaluate_all("els=>els.filter(e=>{const direct=e.getAttribute('aria-label')||e.getAttribute('title')||e.getAttribute('placeholder')||e.textContent.trim();const labs=e.labels&&[...e.labels].some(x=>x.textContent.trim());return !(direct||labs)}).map(e=>e.outerHTML.slice(0,180))"); assert not bad,bad
def processes(page): return page.locator('.service-nav [data-service="processes"]')
def posture(page): return page.locator('.service-nav [data-service="proof"]')
def openp(page,code):
 processes(page).click(); c=page.locator(f'#procedureHub [data-process-code="{code}"]'); expect(c).to_be_visible(); c.locator(':scope > footer .primary').click(); page.wait_for_timeout(100)
def wait_canonical_evidence_entry(page):
 page.wait_for_function("""expected=>{const root=document.querySelector('#proofView'),content=document.querySelector('#proofContent'),entry=content?.querySelector(':scope > details[data-proof-workspace="epistemic-investigation"]');return !!(root&&root.offsetParent!==null&&root.dataset.localCompositionOwner==='proof-workspace-3-2.js'&&root.dataset.proofReadingOrder===expected&&entry&&!root.querySelector('#epistemicMetaCard')&&entry.querySelector('[data-service="epistemic"]'));}""",arg=PROOF_READING_ORDER)
def open_epistemic_entry(page):
 processes(page).click(); expect(page.locator('#procedureHub .procedure-card')).to_have_count(7); posture(page).click(); expect(page.locator('#proofView')).to_be_visible(); wait_canonical_evidence_entry(page); investigation=page.locator('#proofContent > details[data-proof-workspace="epistemic-investigation"]'); expect(investigation).to_have_count(1); expect(page.locator('#proofView #epistemicMetaCard')).to_have_count(0); assert investigation.get_attribute('open') is None; investigation.locator(':scope > summary').click(); action=investigation.locator('[data-service="epistemic"]'); expect(action).to_be_visible(); return action
def open_technical_modes(page):
 detail=page.locator('#epistemicView details[data-epistemic-a3="technical-modes"]');expect(detail).to_be_visible();
 if detail.get_attribute('open') is None:detail.locator(':scope > summary').click()
 expect(detail).to_have_attribute('open','');return detail
def api_status(page,path,role,method='GET',body=None):
 return page.evaluate("""async a=>{const h={'content-type':'application/json','x-ictc-role':a.role,'x-ictc-actor-id':'browser-'+a.role};if(a.method!=='GET'){const b=await fetch('/api/bootstrap',{headers:h});const j=await b.json();h['x-ictc-command-id']='cmd-browser-'+Date.now();h['x-ictc-expected-revision']=String(j.revision||0);}const r=await fetch(a.path,{method:a.method,headers:h,body:a.body?JSON.stringify(a.body):undefined});let payload={};try{payload=await r.json()}catch{}return{status:r.status,payload}}""",{'path':path,'role':role,'method':method,'body':body})
try:
 with sync_playwright() as pw:
  launch={'headless':True,'args':['--no-sandbox']}
  if os.environ.get('ICTC_CHROMIUM'): launch['executable_path']=os.environ['ICTC_CHROMIUM']
  browser=pw.chromium.launch(**launch)
  ctx=browser.new_context(viewport={'width':1440,'height':950}); ctx.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','processes')")
  page=ctx.new_page(); page.set_default_timeout(30000); errors=[]; page.on('pageerror',lambda e:errors.append(str(e)))
  PHASE='surface-primitives'; page.goto(BASE+'/?view=processes',wait_until='networkidle'); expect(page.locator('html')).to_have_attribute('data-ictc-surface-primitives','3.1'); expect(page.locator('#procedureHub .procedure-card')).to_have_count(7); entry=open_epistemic_entry(page); named(page); no_overflow(page); processes(page).click()
  PHASE='seed-incident'; openp(page,'EC-01'); page.locator('.procedure-frame:visible .procedure-primary').click(); expect(page.locator('#incidentDialog')).to_be_visible(); page.locator('#incidentDialog textarea[name="originalNarrative"]').fill('Evento browser V2 usato come source per verificare la cross-referenzialita; nessuna conclusione sostanziale.'); page.locator('#incidentDialog input[name="awarenessAt"]').fill('2026-08-10T12:30'); page.locator('#incidentDialog button[type="submit"]').click(); expect(page.locator('#incidentDialog')).not_to_be_visible(); page.wait_for_timeout(180); expect(page.locator('#incidentList .incident-card').first).to_be_visible()
  PHASE='cross-create'; cross=page.locator('.procedure-cross-tools[data-cross-tools="incidents"] [data-cross-create]'); expect(cross).to_be_visible(); cross.click(); expect(page.locator('#crossCreateDialog')).to_be_visible(); assert page.locator('#crossSource option').count()>0; page.locator('#crossTarget').select_option('actions'); page.locator('#crossTitle').fill('Azione collegata browser V2'); page.locator('#crossDescription').fill('Entry proposta dalla procedura Eventi; priorita e ownership restano da adottare nella procedura Azioni.'); page.locator('[data-cross-submit]').click(); expect(page.locator('#crossCreateDialog')).not_to_be_visible(); expect(page.locator('#proofPulse')).to_be_visible(); named(page); no_overflow(page)
  PHASE='epistemic-flat'; entry=open_epistemic_entry(page); entry.click(); expect(page.locator('#epistemicView')).to_be_visible(); assert 'surface-canvas' in (page.locator('#epistemicView').get_attribute('class') or ''); expect(page.locator('[data-epistemic-mode="explore"]')).to_have_attribute('aria-pressed','true'); open_technical_modes(page);page.locator('[data-epistemic-mode="flat"]').click(); expect(page.locator('#epistemicModeHost .epistemic-table')).to_be_visible(); assert page.locator('#epistemicModeHost tbody tr').count()>0; digest_before=page.locator('#epistemicPageLabel').inner_text(); assert 'digest' in digest_before; expect(page.locator('#epistemicInferencePanel')).to_be_visible(); infer=page.locator('[data-epistemic-infer]'); expect(infer).to_be_disabled(); page.locator('#epistemicAiOn').check(); expect(infer).to_be_enabled(); page.locator('#epistemicAiOn').uncheck(); expect(infer).to_be_disabled(); named(page); no_overflow(page); page.screenshot(path=str(ART/'ux-v20-epistemic-flat.png'),full_page=True)
  PHASE='epistemic-graph'; open_technical_modes(page);page.locator('[data-epistemic-mode="graph"]').click(); expect(page.locator('.epistemic-graph-canvas')).to_be_visible(); expect(page.locator('.epistemic-node-list')).to_be_visible(); assert page.locator('.epistemic-node-list button').count()>0; digest_after=page.locator('#epistemicPageLabel').inner_text(); assert digest_before==digest_after,(digest_before,digest_after); no_overflow(page); page.screenshot(path=str(ART/'ux-v20-epistemic-graph.png'),full_page=True)
  PHASE='human-on-server'; denied=api_status(page,'/api/epistemic-lattice/infer','admin','POST',{'humanOn':False,'mode':'coverage','maxAtoms':30}); assert denied['status']==409,denied; assert denied['payload'].get('code')=='epistemic-human-on-required',denied
  PHASE='user-rbac'; uc=browser.new_context(viewport={'width':1280,'height':850}); uc.add_init_script("localStorage.setItem('ictc-role','user');localStorage.setItem('ictc-service','processes')"); u=uc.new_page(); u.goto(BASE+'/?view=processes',wait_until='networkidle'); expect(u.locator('#procedureHub .procedure-card')).to_have_count(7); assert u.locator('#proofView #epistemicMetaCard').count()==0; d=api_status(u,'/api/epistemic-lattice','user'); assert d['status']==403,d; u.keyboard.press('Control+K'); u.locator('#globalSearch').fill('Reticolo epistemico'); expect(u.locator('#globalSearchResults')).not_to_contain_text('Reticolo epistemico'); u.keyboard.press('Escape'); u.goto(BASE+'/?view=epistemic',wait_until='networkidle'); assert not u.locator('#epistemicView').is_visible(); expect(u.locator('#processesView')).to_be_visible(); uc.close()
  PHASE='auditor-rbac'; ac=browser.new_context(viewport={'width':1280,'height':850}); ac.add_init_script("localStorage.setItem('ictc-role','auditor');localStorage.setItem('ictc-service','processes')"); a=ac.new_page(); a.goto(BASE+'/?view=processes',wait_until='networkidle'); entry=open_epistemic_entry(a); entry.click(); expect(a.locator('#epistemicView')).to_be_visible(); expect(a.locator('#epistemicInferencePanel')).to_be_visible(); openp(a,'AP-01'); assert a.locator('.procedure-cross-tools[data-cross-tools="actions"] [data-cross-create]').count()==0; ac.close()
  PHASE='mobile-epistemic'; mc=browser.new_context(viewport={'width':390,'height':844}); mc.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','processes')"); m=mc.new_page(); m.goto(BASE+'/?view=processes',wait_until='networkidle'); entry=open_epistemic_entry(m); entry.click(); expect(m.locator('#epistemicView')).to_be_visible(); no_overflow(m); open_technical_modes(m);m.locator('[data-epistemic-mode="graph"]').click(); no_overflow(m); expect(m.locator('.epistemic-graph-canvas')).to_be_visible(); m.screenshot(path=str(ART/'ux-v20-epistemic-mobile.png'),full_page=True); mc.close()
  assert not errors,errors
  out={'ok':True,'profile':'2.0-epistemic-lattice-pre-candidate+semantic-composition-3.1+s4-a3','businessProcedures':7,'metaProcedure':'EP-01','metaEntrySurface':'Evidenze ICTC / progressive canonical disclosure after evidence meaning','proofReadingOrder':PROOF_READING_ORDER,'duplicateProofMetaEntry':False,'evidenceEntryReadiness':'condition-based','flatRaw':True,'protoGraph':True,'technicalModesProgressive':True,'sameProjectionDigest':True,'humanOnUiGate':True,'humanOnServerGate':True,'adminAccess':True,'auditorAccess':True,'userDenied':True,'crossProcedureReceipt':True,'mobileOverflow':False,'surfacePrimitiveContract':'3.1','evidenceClass':'E2-server-backed-browser+epistemic-lattice'}; (ART/'browser-v2-epistemic.json').write_text(json.dumps(out,indent=2),encoding='utf8'); print('browser-v2-epistemic: complete',flush=True); ctx.close(); browser.close()
except BaseException as e:
 fail(e); traceback.print_exc(); raise
