import json, os, pathlib, traceback
from playwright.sync_api import expect, sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1]; ART=ROOT/'artifacts'; ART.mkdir(exist_ok=True)
BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4173').rstrip('/'); PHASE='init'
def fail(e):
 p={'ok':False,'phase':PHASE,'type':type(e).__name__,'message':str(e),'traceback':traceback.format_exc()}; (ART/'browser-v1-2-error.json').write_text(json.dumps(p,indent=2),encoding='utf8'); print(f'::error title=browser-v1-2::{PHASE}: {type(e).__name__}: {e}',flush=True)
def shot(page,name): page.screenshot(path=str(ART/name),full_page=True)
def api(page,role,script): return page.evaluate("""async ({role,script})=>{const headers={'content-type':'application/json','x-ictc-role':role,'x-ictc-actor-id':role==='admin'?'local-admin':'local-user'};return await new Function('headers',`return (async()=>{${script}})()` )()}""",{'role':role,'script':script})
def open_process(page,code):
 page.locator('[data-service="processes"]').first.click(); card=page.locator(f'#procedureHub [data-process-code="{code}"]'); expect(card).to_be_visible(); card.locator('.primary').click()
try:
 with sync_playwright() as pw:
  launch={'headless':True,'args':['--no-sandbox']}
  if os.environ.get('ICTC_CHROMIUM'): launch['executable_path']=os.environ['ICTC_CHROMIUM']
  browser=pw.chromium.launch(**launch)
  ctx=browser.new_context(viewport={'width':1440,'height':1000});ctx.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','home')")
  page=ctx.new_page();page.set_default_timeout(25000);errors=[];page.on('pageerror',lambda e:errors.append(str(e)))
  PHASE='market-home';page.goto(BASE+'/',wait_until='networkidle');expect(page.locator('html')).to_have_attribute('data-ictc-edition','1.2-market-candidate');expect(page.locator('html')).to_have_attribute('data-ictc-experience','market-1');expect(page.locator('#homePulse > div')).to_have_count(4);home=page.locator('#homeView').inner_text().lower();assert 'compliance score' not in home and 'maturity score' not in home;shot(page,'ux-v12-home.png')
  PHASE='seven-procedures';page.locator('[data-service="processes"]').first.click();hub=page.locator('#procedureHub');expect(hub.locator('.stable-process-card')).to_have_count(7);expect(hub.locator('[data-process-code="MC-01"] h2')).to_have_text('Standard e Controlli');assert hub.locator('[data-process-code="EV-01"]').count()==0;shot(page,'ux-v12-processes.png')
  PHASE='peer-workspaces';expected={'AO-01':'Inventario di sistemi e oggetti','AP-01':'Azioni correttive','RC-01':'Rischi di compliance','AR-01':'Questionari e verifiche'}
  for code,title in expected.items():
   open_process(page,code);expect(page.locator('.grc-head h1')).to_have_text(title);assert page.locator('.grc-head nav[aria-label="Processi GRC"]').count()==0
  PHASE='standard-library';open_process(page,'MC-01');expect(page.locator('.grc-head h1')).to_have_text('Standard e Controlli');expect(page.locator('[data-framework-card]')).to_have_count(21);text=page.locator('#grcWorkspace').inner_text();assert 'COSO ERM' in text and 'ISO/IEC 27001' in text and 'NIST CSF 2.0' in text;assert 'Obiettivi di controllo condivisi' in text
  gdpr=page.locator('[data-framework-card="eu-gdpr-2016-679"]');gdpr.locator('[data-standard-scope-reason]').fill('Trattamenti di dati personali dichiarati nel perimetro');gdpr.locator('[data-standard-scope]').click();expect(page.locator('[data-framework-card="eu-gdpr-2016-679"] .market-scope')).to_have_text('In perimetro')
  nis2=page.locator('[data-framework-card="eu-nis2-2022-2555"]');nis2.locator('[data-standard-scope-decision]').select_option('reference');nis2.locator('[data-standard-scope-reason]').fill('Benchmark cyber integrato');nis2.locator('[data-standard-scope]').click();expect(page.locator('[data-framework-card="eu-nis2-2022-2555"] .market-scope')).to_have_text('Riferimento');expect(page.locator('.market-objective-row').first).to_be_visible();shot(page,'ux-v12-standards.png')
  panel=page.locator('.market-mapping-panel');expect(panel).to_be_visible();panel.locator('> summary').click();expect(page.locator('#marketFrameworkSelect')).to_be_visible();page.locator('#marketFrameworkSelect').select_option('eu-gdpr-2016-679');expect(page.locator('#marketRequirementSelect')).to_be_enabled();page.locator('#marketRequirementSelect').select_option('std:eu-gdpr-2016-679:art-32');page.locator('.market-mapping-form button[type="submit"]').click();expect(page.locator('.market-mapping-panel .grc-list')).to_contain_text('Art. 32')
  PHASE='inventory-identity';first=api(page,'admin',"const r=await fetch('/api/grc/objects',{method:'POST',headers,body:JSON.stringify({type:'system',name:'ERP market test',sourceAuthority:'CMDB',externalReference:'CI-MARKET-1'})});return {status:r.status,body:await r.json()};");assert first['status']==201,first;dup=api(page,'admin',"const r=await fetch('/api/grc/objects',{method:'POST',headers,body:JSON.stringify({type:'system',name:'ERP duplicate',sourceAuthority:' cmdb ',externalReference:'ci-market-1'})});return {status:r.status,body:await r.json()};");assert dup['status']==409 and dup['body'].get('code')=='grc-object-identity-collision',dup
  PHASE='standard-feature-policy';off=api(page,'admin',"const r=await fetch('/api/admin/procedures',{method:'PUT',headers,body:JSON.stringify({features:{coverage:false}})});return {status:r.status,body:await r.json()};");assert off['status']==200,off;blocked=api(page,'admin',"const r=await fetch('/api/standards/eu-dora-2022-2554/scope',{method:'POST',headers,body:JSON.stringify({decision:'reference',reason:'blocked test'})});return {status:r.status,body:await r.json()};");assert blocked['status']==409 and blocked['body'].get('code')=='procedure-disabled',blocked;api(page,'admin',"const r=await fetch('/api/admin/procedures',{method:'PUT',headers,body:JSON.stringify({features:{coverage:true}})});return {status:r.status};")
  ctx.close()
  PHASE='user-self-service';uctx=browser.new_context(viewport={'width':1280,'height':900});uctx.add_init_script("localStorage.setItem('ictc-role','user');localStorage.setItem('ictc-service','processes')");u=uctx.new_page();u.set_default_timeout(25000);u.goto(BASE+'/',wait_until='networkidle');open_process(u,'RN-01');expect(u.locator('.market-entry-strip')).to_be_visible();expect(u.locator('[data-open-contribution]')).to_contain_text('Aggiungi materiale');expect(u.locator('[data-market-create-monitor]')).to_contain_text('Crea monitoraggio');u.locator('[data-market-create-monitor]').click();expect(u.locator('#missionForm')).to_be_visible();u.locator('#missionForm textarea[name="objective"]').fill('Sorveglia modifiche a requisiti cyber rilevanti');u.locator('#missionForm button[type="submit"]').click();expect(u.locator('#missionsList .market-monitor-card')).to_have_count(1);shot(u,'ux-v12-monitoring-user.png')
  PHASE='near-miss';open_process(u,'EC-01');u.locator('#openIncident').click();expect(u.locator('#incidentForm select[name="eventKind"]')).to_be_visible();u.locator('#incidentForm select[name="eventKind"]').select_option('near-miss');u.locator('#incidentForm select[name="operationalSeverity"]').select_option('medium');u.locator('#incidentForm textarea[name="originalNarrative"]').fill('Tentativo di invio dati al destinatario errato intercettato prima della trasmissione.');u.locator('#incidentForm input[name="awarenessAt"]').fill('2026-08-09T17:00');u.locator('#incidentForm button[type="submit"]').click();expect(u.locator('#incidentList')).to_contain_text('Quasi incidente');shot(u,'ux-v12-near-miss.png');uctx.close()
  PHASE='mobile';mctx=browser.new_context(viewport={'width':390,'height':844});mctx.add_init_script("localStorage.setItem('ictc-role','user');localStorage.setItem('ictc-service','home')");m=mctx.new_page();m.goto(BASE+'/',wait_until='networkidle');expect(m.locator('html')).to_have_attribute('data-ictc-experience','market-1');expect(m.locator('#homePulse > div')).to_have_count(4);m.locator('[data-service="processes"]').first.click();expect(m.locator('#procedureHub .stable-process-card')).to_have_count(7);shot(m,'ux-v12-mobile.png');mctx.close();assert not errors,errors
  report={'ok':True,'releaseProfile':'1.2_market_candidate','processes':7,'openedProcessWorkspaces':['RN-01','EC-01','AO-01','MC-01','AP-01','RC-01','AR-01'],'standards':21,'standardScopeHuman':True,'userOwnedMonitoring':True,'nearMiss':True,'objectIdentityCollisionBlocked':True,'standardFeaturePolicyBlocked':True,'syntheticComplianceScore':False,'screenshots':['ux-v12-home.png','ux-v12-processes.png','ux-v12-standards.png','ux-v12-monitoring-user.png','ux-v12-near-miss.png','ux-v12-mobile.png'],'evidenceClass':'E2-browser-not-independent-human-research'};(ART/'browser-v1-2-market-candidate.json').write_text(json.dumps(report,indent=2),encoding='utf8');print('browser-v1-2-market-candidate: complete',flush=True);browser.close()
except BaseException as e: fail(e);traceback.print_exc();raise
