import json, os, pathlib, traceback, urllib.parse
from playwright.sync_api import expect, sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1];ART=ROOT/'artifacts';ART.mkdir(exist_ok=True)
BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4874').rstrip('/');EXPECTED=(os.environ.get('ICTC_EXPECT_BUILD_SHA') or '').lower();PHASE='init';RESULTS=[];WRITES=[];ERRORS=[]
PROCEDURES=[('RN-01','monitoring','#monitoringView'),('EC-01','incidents','#incidentsView'),('AO-01','objects','#grcWorkspace'),('MC-01','coverage','#grcWorkspace'),('AP-01','actions','#grcWorkspace'),('RC-01','risks','#grcWorkspace'),('AR-01','assurance','#grcWorkspace')]
def fail(exc):
 p={'ok':False,'slice':'S4-A6','executionUnit':'A6-UX4','phase':PHASE,'type':type(exc).__name__,'message':str(exc),'traceback':traceback.format_exc(),'results':RESULTS,'writes':WRITES,'pageErrors':ERRORS};(ART/'browser-s4-a6-ux4-semantic-surface-error.json').write_text(json.dumps(p,indent=2,ensure_ascii=False),encoding='utf8');print(f'::error title=A6-UX4::{PHASE}: {exc}',flush=True)
def no_page_overflow(page,label):
 m=page.evaluate("()=>({inner:innerWidth,html:document.documentElement.scrollWidth,body:document.body.scrollWidth})");assert m['html']<=m['inner']+1 and m['body']<=m['inner']+1,(label,m);RESULTS.append({'oracle':'page-reflow','case':label,'metrics':m})
def no_local_x_overflow(page,selector,label):
 m=page.locator(selector).evaluate("r=>({client:r.clientWidth,scroll:r.scrollWidth,offenders:[...r.querySelectorAll('*')].filter(e=>{const b=e.getBoundingClientRect(),s=getComputedStyle(e);return b.width>0&&b.height>0&&s.display!=='none'&&s.visibility!=='hidden'&&e.scrollWidth>e.clientWidth+2&&!/(hidden|clip)/.test(s.overflowX)}).slice(0,8).map(e=>({tag:e.tagName,cls:String(e.className||''),client:e.clientWidth,scroll:e.scrollWidth,overflow:getComputedStyle(e).overflowX}))})");assert m['scroll']<=m['client']+2 and not m['offenders'],(label,m);RESULTS.append({'oracle':'local-x-overflow','case':label,'metrics':m})
def open_process(page,code,pid,root):
 global PHASE
 PHASE=f'{code}-catalog';page.locator('.service-nav [data-service="processes"]').click();card=page.locator(f'#procedureHub [data-process-code="{code}"]');expect(card).to_be_visible();card.locator(':scope > footer .procedure-primary,:scope > footer .primary').first.click();PHASE=f'{code}-mount';page.wait_for_function("x=>{const r=document.querySelector(x.root),w=r?.querySelector(':scope > [data-procedure-attention-slot=\"'+x.pid+'\"] [data-procedure-worklist]');return !!(r&&r.offsetParent!==null&&document.documentElement.dataset.a6Ux4Semantic==='a6-ux4'&&w?.dataset.a6Ux4Mount)}",arg={'root':root,'pid':pid});return page.locator(root)
def audit_procedure(page,code,pid,root):
 global PHASE
 r=open_process(page,code,pid,root);PHASE=f'{code}-single-collection-mount';section=r.locator(f':scope > [data-procedure-attention-slot="{pid}"] [data-procedure-worklist]');expect(section).to_have_attribute('data-a6-ux4-mount','semantic-bridge');expect(section).to_be_hidden();expect(r).to_have_attribute('data-a6-ux4-single-collection','native');PHASE=f'{code}-single-collection-scope';scope=r.locator(f'[data-a6-ux4-scope="{pid}"]');expect(scope).to_be_visible();expect(scope).to_have_value('actionable');PHASE=f'{code}-single-collection-equivalence';expected=int(r.get_attribute('data-a6-ux4-actionable-count') or '0');missing=int(r.get_attribute('data-a6-ux4-binding-missing') or '0');visible_actionable=r.locator('[data-a6-ux4-actionable="true"]:visible').count();assert missing==0,(code,'typed binding missing',missing);assert visible_actionable==expected,(code,'visible actionable/native mismatch',visible_actionable,expected);assert r.locator('.procedure-worklist-reveal:visible').count()==0
 PHASE=f'{code}-scope-control';scope.select_option('all');assert scope.input_value()=='all';scope.select_option('actionable');assert scope.input_value()=='actionable'
 PHASE=f'{code}-context';anatomy=r.locator('[data-procedure-anatomy][data-a6-ux4-context="canonical"]');expect(anatomy).to_have_count(1);expect(anatomy).to_be_visible();assert r.locator('.procedure-decision-frame details.composition-process-context:visible').count()==0
 refs=r.locator('.procedure-anatomy-standard-head[data-a6-ux4-reference-band="canonical"]')
 if refs.count(): expect(refs.first).to_be_visible()
 PHASE=f'{code}-action-effects';visible=r.locator('button:visible,a[href]:visible,summary:visible');sample=min(visible.count(),30);assert sample>0;assert all(visible.nth(i).get_attribute('data-a6-ux4-effect') for i in range(sample)),(code,'unclassified control')
 if pid=='monitoring':PHASE='RN-01-material-merge';assert r.locator('.contribute-card:visible').count()==0;assert r.locator('[data-a6-ux4-single-column="true"]').count()>=1
 if pid=='incidents':PHASE='EC-01-heading-dedup';assert r.locator('[data-a6-registry="incidents"] .section-head:visible').count()==0
 if pid=='coverage':
  PHASE='MC-01-use-copy';expect(r.locator('[data-framework-card="eu-gdpr-2016-679"] .market-scope')).to_have_text('Uso da dichiarare');PHASE='MC-01-standard-browser';entry=r.locator('[data-open-standard-browser]').first;entry.click();dialog=page.locator('#standardBrowserDialog');expect(dialog).to_be_visible();no_local_x_overflow(page,'#standardBrowserDialog','desktop:standard-dialog');no_local_x_overflow(page,'#standardBrowserDialog .standard-browser-master-detail','desktop:standard-master-detail');node=dialog.locator('[data-standard-node-select]').first;if_strong=node.locator(':scope > strong');span=node.locator(':scope > span');
  if if_strong.count():assert if_strong.inner_text().strip().lower()!=span.inner_text().strip().lower(),(span.inner_text(),if_strong.inner_text())
  close=dialog.locator('button[aria-label="Chiudi"]');box=close.bounding_box();assert box and box['width']>=44 and box['height']>=44,box;close.click()
 no_page_overflow(page,f'desktop:{code}');RESULTS.append({'oracle':'procedure-semantic-questions','code':code,'procedureId':pid,'answers':{'next-action':True,'subject':True,'authority':True,'effect':True,'scope':True,'reference':bool(refs.count()),'claim-boundary':True},'singleVisibleOperationalCollection':True,'actionableCount':expected})
def desktop(browser):
 global PHASE
 ctx=browser.new_context(viewport={'width':1440,'height':950});ctx.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','home')");page=ctx.new_page();page.set_default_timeout(30000);page.on('pageerror',lambda e:ERRORS.append(str(e)));page.on('request',lambda r:WRITES.append({'method':r.method,'path':urllib.parse.urlparse(r.url).path}) if r.url.startswith(BASE+'/api/') and r.method!='GET' else None);PHASE='home';page.goto(BASE+'/?view=home',wait_until='networkidle');page.wait_for_function("()=>document.documentElement.dataset.a6Ux4Semantic==='a6-ux4'");expect(page.locator('#homeTitle')).to_have_text('Integrated Compliance Tower Control');opens=page.locator('#homePriorities .home-priority-open:visible');
 if opens.count():
  assert all('→' not in (opens.nth(i).inner_text() or '') for i in range(opens.count()));svg=opens.first.locator('svg');box=svg.bounding_box();assert not box or max(box['width'],box['height'])<=14.5,box
 no_page_overflow(page,'desktop:home');PHASE='processes';page.locator('.service-nav [data-service="processes"]').click();expect(page.locator('#procedureHub [data-process-code]')).to_have_count(7);no_page_overflow(page,'desktop:processes')
 for code,pid,root in PROCEDURES:audit_procedure(page,code,pid,root)
 PHASE='proof';page.locator('.service-nav [data-service="proof"]').click();page.wait_for_function("()=>document.querySelector('#proofView')?.offsetParent!==null");expect(page.locator('#proofView')).to_have_attribute('data-a6-ux4-claim-scope','repository-observation');page.wait_for_function("()=>{const e=document.querySelector('#proofIntegrity');return e&&/Coerente tecnicamente|Coerenza tecnica da verificare/.test(e.textContent||'')}");expect(page.locator('#proofView .proof-snapshot article').filter(has_text='Vista per ruolo')).to_have_count(1);no_page_overflow(page,'desktop:proof');assert not ERRORS,ERRORS;ctx.close()
def mobile(browser,width,height):
 global PHASE
 ctx=browser.new_context(viewport={'width':width,'height':height});ctx.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','processes')");page=ctx.new_page();page.set_default_timeout(30000);page.goto(BASE+'/?view=processes',wait_until='networkidle');page.wait_for_function("()=>document.documentElement.dataset.a6Ux4Semantic==='a6-ux4'");PHASE=f'mobile-{width}-processes';expect(page.locator('#procedureHub [data-process-code]')).to_have_count(7);no_page_overflow(page,f'mobile-{width}:processes');r=open_process(page,'MC-01','coverage','#grcWorkspace');PHASE=f'mobile-{width}-mc';expect(r.locator('[data-procedure-worklist]')).to_have_attribute('data-a6-ux4-mount','semantic-bridge');entry=r.locator('[data-open-standard-browser]').first;entry.click();dialog=page.locator('#standardBrowserDialog');expect(dialog).to_be_visible();no_local_x_overflow(page,'#standardBrowserDialog',f'mobile-{width}:dialog');no_local_x_overflow(page,'#standardBrowserDialog .standard-browser-master-detail',f'mobile-{width}:master-detail');close=dialog.locator('button[aria-label="Chiudi"]');box=close.bounding_box();assert box and box['width']>=44 and box['height']>=44;close.click();no_page_overflow(page,f'mobile-{width}:mc');ctx.close()
try:
 with sync_playwright() as pw:
  launch={'headless':True,'args':['--no-sandbox']};
  if os.environ.get('ICTC_CHROMIUM'):launch['executable_path']=os.environ['ICTC_CHROMIUM']
  browser=pw.chromium.launch(**launch);desktop(browser);mobile(browser,390,844);mobile(browser,320,800);assert not WRITES,WRITES
  report={'ok':True,'slice':'S4-A6','executionUnit':'A6-UX4','expectedBuildSha':EXPECTED or None,'results':RESULTS,'writes':WRITES,'pageErrors':ERRORS,'landingPages':['Home','Processi di Compliance','RN-01','EC-01','AO-01','MC-01','AP-01','RC-01','AR-01','Evidenze ICTC'],'oracles':['single-visible-operational-collection','typed-native-actionability','zero-work-vacuous-binding','integrated-scope-control','context-dedup','reference-band','action-effect-grammar','RN-material-merge','EC-heading-dedup','standard-browser-dedup','local-x-overflow','page-reflow','mobile-390','mobile-320','read-only-navigation-no-write'],'claimBoundary':'Exact-head Chromium repository UI semantics and geometry only; not representative human usability, accessibility certification, legal/compliance conclusion, deployment effectiveness, enterprise-candidate promotion or enterprise-ready proof.'};(ART/'browser-s4-a6-ux4-semantic-surface.json').write_text(json.dumps(report,indent=2,ensure_ascii=False),encoding='utf8');print(json.dumps({'ok':True,'executionUnit':'A6-UX4','procedures':7,'mobile':[390,320],'writes':0}),flush=True);browser.close()
except BaseException as exc:fail(exc);traceback.print_exc();raise