import json, os, pathlib, traceback
from playwright.sync_api import expect, sync_playwright
ART=pathlib.Path(os.environ.get('ICTC_ARTIFACT_DIR',str(pathlib.Path.cwd()/'artifacts')));ART.mkdir(exist_ok=True)
BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4173').rstrip('/');MOCK=os.environ.get('ICTC_MOCK_URL','http://127.0.0.1:4899').rstrip('/');PHASE='init'
CODES={'monitoring':'RN-01','incidents':'EC-01','objects':'AO-01','coverage':'MC-01','actions':'AP-01','risks':'RC-01','assurance':'AR-01'}
def hdr(role): return {'x-ictc-role':role,'x-ictc-actor-id':f'local-{role}'}
def open_process(page,pid):
    page.locator('.service-nav [data-service="processes"]').click();card=page.locator(f'#procedureHub [data-procedure-id="{pid}"]');card.wait_for(state='visible');card.locator('button').click()
def switch_grc(page,pid):
    workspace=page.locator('#grcWorkspace');workspace.wait_for(state='visible');button=workspace.locator(f'[data-grc-process="{pid}"]');button.wait_for(state='visible');button.click();workspace.wait_for(state='visible')
def open_primary(page):
    box=page.locator('#grcPrimaryForm');expect(box).to_have_count(1)
    if box.get_attribute('open') is None: box.locator(':scope > summary').click()
def decide(page,reason='Validazione umana browser V3',**numbers):
    d=page.locator('#grcDecisionDialog');d.wait_for(state='visible')
    for name,value in numbers.items(): d.locator(f'input[name="{name}"]').fill(str(value))
    d.locator('textarea[name="reason"]').fill(reason);d.get_by_role('button',name='Registra decisione').click();d.wait_for(state='hidden')
def route_guide(page,text,pid):
    page.locator('.service-nav [data-service="home"]').click();form=page.locator('#v3IntentForm');form.locator('textarea[name="objective"]').fill(text);form.get_by_role('button',name='Trova la procedura').click();choices=page.locator('#v3RouteResults [data-v3-guide]');expect(choices).to_have_count(lambda n: 1 <= n <= 3) if False else None
    choice=page.locator(f'#v3RouteResults [data-v3-guide="{pid}"]');choice.wait_for(state='visible');choice.click();dialog=page.locator('#v3ProcedureDialog');dialog.wait_for(state='visible');expect(page.locator('#v3ProcedureTitle')).to_contain_text(CODES[pid]);expect(page.locator('#v3ProcedureBody')).to_contain_text('Ingresso');expect(page.locator('#v3ProcedureBody')).to_contain_text('Uscita attesa');expect(page.locator('#v3ProcedureBody')).to_contain_text('Richiede persona');dialog.get_by_role('button',name='Apri procedura').click();dialog.wait_for(state='hidden')
def error_out(error):
    payload={'ok':False,'phase':PHASE,'type':type(error).__name__,'message':str(error),'traceback':traceback.format_exc()};(ART/'browser-v3-error.json').write_text(json.dumps(payload,indent=2),encoding='utf8');print(f'::error title=browser-v3-all-service::{PHASE}: {type(error).__name__}: {error}',flush=True)
try:
  with sync_playwright() as pw:
    launch={'headless':True,'args':['--no-sandbox']}
    if os.environ.get('ICTC_CHROMIUM'): launch['executable_path']=os.environ['ICTC_CHROMIUM']
    browser=pw.chromium.launch(**launch);ctx=browser.new_context(viewport={'width':1440,'height':1050},accept_downloads=True);ctx.add_init_script("try{localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','home')}catch{}")
    page=ctx.new_page();page.set_default_timeout(20000);page_errors=[];page.on('pageerror',lambda e:page_errors.append(str(e)))
    PHASE='entrypoint';page.goto(BASE+'/',wait_until='networkidle');expect(page.locator('html')).to_have_attribute('data-ictc-edition','v3-experimental');expect(page.locator('.service-nav [data-service]')).to_have_count(3);expect(page.locator('#v3OperationalHome')).to_be_visible();expect(page.locator('#v3IntentForm')).to_be_visible();expect(page.locator('#grcCockpit')).to_be_hidden();expect(page.locator('#v3MetricGrid article')).to_have_count(7)
    route_guide(page,'Inventariare server, firewall e applicazioni cloud rilevanti','objects');expect(page.locator('#grcWorkspace')).to_contain_text('AO-01')
    PHASE='configure-ai';page.locator('.service-nav [data-service="home"]').click();page.locator('#openSettings').click();settings=page.locator('#settingsForm');org=settings.locator('[data-settings-section="organization"]');org.locator('summary').click() if org.get_attribute('open') is None else None;settings.locator('input[name="organizationName"]').fill('Azienda V3 Browser');settings.locator('textarea[name="organizationScope"]').fill('GRC, sicurezza e compliance');settings.locator('input[name="jurisdictions"]').fill('Italia, Unione europea');provider=settings.locator('[data-settings-section="provider"]');provider.locator('summary').click() if provider.get_attribute('open') is None else None;provider.locator('input[name="endpoint"]').fill(MOCK+'/v1/chat/completions');provider.locator('input[name="model"]').fill('mock-v3');provider.locator('input[name="apiKeyEnv"]').fill('ICTC_LLM_API_KEY');settings.get_by_role('button',name='Salva configurazione AI').click();page.locator('#settingsDialog').wait_for(state='hidden')
    PHASE='ao01';open_process(page,'objects');open_primary(page);f=page.locator('[data-grc-form="object"]');f.locator('select[name="type"]').select_option('laptop');f.locator('input[name="name"]').fill('Notebook CFO V3');f.locator('select[name="criticality"]').select_option('high');f.locator('input[name="owner"]').fill('Finance');f.get_by_role('button',name='Registra candidato').click();expect(page.locator('#proofPulse')).to_be_visible();page.locator('#grcWorkspace [data-object-review="active"]').first.click();decide(page);expect(page.locator('#grcWorkspace')).to_contain_text('Attivo');g=ctx.request.get(BASE+'/api/grc',headers=hdr('admin')).json();obj=next(x for x in g['objects']['objects'] if x['name']=='Notebook CFO V3')
    PHASE='mc01';switch_grc(page,'coverage');open_primary(page);f=page.locator('[data-grc-form="mapping"]');f.locator('input[name="requirementRef"]').fill('MFA-01');f.locator('textarea[name="requirementLabel"]').fill('MFA richiesta per accessi privilegiati');f.locator('input[name="useAi"]').check();f.get_by_role('button',name='Registra proposta').click();expect(page.locator('#grcWorkspace')).to_contain_text('Proposta AI');page.locator('#grcWorkspace [data-mapping-decision="gap"]').first.click();decide(page);g=ctx.request.get(BASE+'/api/grc',headers=hdr('admin')).json();assert g['coverage']['gaps']>=1 and g['coverage']['coveragePercent']==0
    PHASE='ap01';switch_grc(page,'actions');open_primary(page);f=page.locator('[data-grc-form="action"]');f.locator('input[name="title"]').fill('Abilitare MFA privilegiata');f.locator('input[name="owner"]').fill('local-admin');f.locator('input[name="dueAt"]').fill('2099-01-01');f.get_by_role('button',name='Registra azione').click();page.locator('#grcWorkspace [data-action-ai]').first.click();expect(page.locator('#grcWorkspace')).to_contain_text('proposta AI');page.locator('#grcWorkspace [data-action-adopt]').first.click();decide(page,priority=4);page.locator('#grcWorkspace [data-action-progress]').filter(has_text='Avvia').first.click();expect(page.locator('#grcWorkspace')).to_contain_text('In corso');g=ctx.request.get(BASE+'/api/grc',headers=hdr('admin')).json();a=next(x for x in g['actions']['actions'] if x['title']=='Abilitare MFA privilegiata');assert a['state']=='in-progress' and a['priority']==4
    PHASE='rc01';switch_grc(page,'risks');expect(page.locator('#grcWorkspace')).to_contain_text('Heatmap validata');open_primary(page);f=page.locator('[data-grc-form="risk"]');f.locator('input[name="title"]').fill('Accesso privilegiato senza MFA');f.locator('textarea[name="description"]').fill('Scenario derivato dal gap MFA');f.locator('input[name="useAi"]').check();f.get_by_role('button',name='Registra scenario').click();g=ctx.request.get(BASE+'/api/grc',headers=hdr('admin')).json();assert g['risks']['aiOverlay'] and sum(sum(row) for row in g['risks']['heatmap'])==0;page.locator('#grcWorkspace [data-risk-review]').first.click();decide(page,likelihood=4,impact=5);g=ctx.request.get(BASE+'/api/grc',headers=hdr('admin')).json();assert g['risks']['heatmap'][3][4]==1
    PHASE='ar01';switch_grc(page,'assurance');open_primary(page);f=page.locator('[data-grc-form="assurance"]');f.locator('input[name="title"]').fill('Questionario cliente V3');f.locator('textarea[name="requestText"]').fill('Descrivere MFA e logging con evidenze disponibili.');f.locator('input[name="source"]').fill('Cliente enterprise');f.get_by_role('button',name='Conserva richiesta').click();page.locator('#grcWorkspace [data-assurance-propose]').first.click();expect(page.locator('#grcWorkspace .ai-proposal textarea')).to_have_count(2);page.locator('#grcWorkspace [data-assurance-approve]').first.click();decide(page);g=ctx.request.get(BASE+'/api/grc',headers=hdr('admin')).json();case=next(x for x in g['assurance']['cases'] if x['title']=='Questionario cliente V3');assert case['state']=='approved' and len(case['approvedAnswers'])==2
    PHASE='rn01-guided';route_guide(page,'Monitorare nuove norme NIS2 e fonti ufficiali EUR-Lex','monitoring');expect(page.locator('#monitoringView')).to_be_visible()
    PHASE='ec01-guided';route_guide(page,'Registrare un possibile data breach e una segnalazione phishing','incidents');expect(page.locator('#incidentsView')).to_be_visible()
    PHASE='insight-board';page.locator('.service-nav [data-service="home"]').click();expect(page.locator('#v3MetricGrid article')).to_have_count(7);before=ctx.request.get(BASE+'/api/insights',headers=hdr('admin')).json()['base']['basisSha256'];page.locator('[data-v3-propose-insight]').click();expect(page.locator('#v3AiInsight .v3-ai-badge')).to_contain_text('AI · proposta');boot=ctx.request.get(BASE+'/api/bootstrap',headers=hdr('admin')).json();proposal=boot['insights']['proposals'][0];assert proposal['basisSha256']==before and proposal['envelope']['adoption'] is None;page.locator(f'[data-v3-validate-insight="{proposal["id"]}"]').click();d=page.locator('#v3InsightDialog');d.wait_for(state='visible');d.locator('textarea[name="reason"]').fill('Lettura coerente con i KPI deterministici e utile per la review umana.');d.get_by_role('button',name='Registra validazione').click();d.wait_for(state='hidden');expect(page.locator('#v3AiInsight .v3-ai-badge')).to_contain_text('validata da umano');after=ctx.request.get(BASE+'/api/insights',headers=hdr('admin')).json();assert after['base']['basisSha256']==before;assert after['proposals'][0]['envelope']['adoption']['authority']=='human'
    PHASE='trace-evidence-export';trace=ctx.request.get(f"{BASE}/api/work/traces/grc-object/{obj['id']}",headers=hdr('admin'));assert trace.status==200;tb=trace.json();assert tb['processId']=='objects' and tb['subject']['id']==obj['id'] and tb['completeness']['humanDecision'] is True and tb['evidenceUrl'];z=ctx.request.get(f"{BASE}/api/evidence/grc-object/{obj['id']}.zip",headers=hdr('admin'));assert z.status==200 and z.body()[:4]==b'PK\x03\x04';export=ctx.request.get(BASE+'/api/export/current.json',headers=hdr('admin')).json();assert any(x['type']=='grc-object' and x['id']==obj['id'] for x in export['rows'])
    PHASE='role-boundaries';page.locator('#roleSelect').select_option('user');open_process(page,'objects');assert page.locator('#grcWorkspace [data-object-review]').count()==0;page.locator('#roleSelect').select_option('auditor');page.locator('.service-nav [data-service="home"]').click();aud=ctx.request.get(BASE+'/api/bootstrap',headers=hdr('auditor')).json();assert aud['work']['queue']['items'] and all(x['readOnly'] for x in aud['work']['queue']['items']);assert aud['reviewInbox']['readOnly'] is True;assert page.locator('[data-v3-propose-insight]').count()==0;page.locator('.service-nav [data-service="proof"]').click();expect(page.locator('#proofContent')).to_be_visible();assert not page_errors,page_errors
    checks=['single-operational-entry','max-three-route-candidates','human-procedure-selection','procedure-guide','ao01','mc01-ai-human','ap01-ai-human','rc01-human-heatmap','ar01-ai-human','rn01-guided','ec01-guided','deterministic-insight-ai-human','kpi-no-drift','procedure-trace','evidence-zip','same-as-read-export','role-boundaries','proof'];(ART/'browser-v3.json').write_text(json.dumps({'ok':True,'checks':checks,'productEdition':'V3 Experimental','services':7},indent=2),encoding='utf8');print('browser-v3-all-service: V3 guided all-service journey complete',flush=True);browser.close()
except BaseException as error:
  error_out(error);traceback.print_exc();raise
