import json,os,pathlib,traceback
from playwright.sync_api import expect,sync_playwright
ROOT=pathlib.Path(__file__).resolve().parents[1];ART=ROOT/'artifacts';ART.mkdir(exist_ok=True);BASE=os.environ.get('ICTC_BASE_URL','http://127.0.0.1:4173').rstrip('/');DEMO=os.environ.get('ICTC_EXPECT_DEMO','0')=='1';MODE='demo' if DEMO else 'standard';PHASE='init'
def no_overflow(p,label):
 m=p.evaluate('()=>({w:innerWidth,h:document.documentElement.scrollWidth,b:document.body.scrollWidth})');assert max(m['h'],m['b'])<=m['w']+1,(label,m)
def open_admin(p):
 menu=p.locator('#stableProfileMenu');expect(menu).to_be_visible();menu.locator(':scope > summary').click();b=p.locator('#stableProfileMenu #openAdminCenter');expect(b).to_be_visible();b.click();expect(p.locator('#adminCenter')).to_be_visible()
try:
 with sync_playwright() as pw:
  launch={'headless':True,'args':['--no-sandbox']};
  if os.environ.get('ICTC_CHROMIUM'):launch['executable_path']=os.environ['ICTC_CHROMIUM']
  browser=pw.chromium.launch(**launch);ctx=browser.new_context(viewport={'width':1440,'height':950});ctx.add_init_script("localStorage.setItem('ictc-role','admin');localStorage.setItem('ictc-service','home')");p=ctx.new_page();p.set_default_timeout(30000);PHASE='desktop';p.goto(BASE,wait_until='networkidle');p.wait_for_function("()=>document.documentElement.dataset.ictcExperienceEdition==='1.9-experience-candidate'")
  expect(p.locator('.service-nav > [data-service]')).to_have_count(3);expect(p.locator('#stableProfileMenu')).to_contain_text('Amministratore');expect(p.locator('#stableProfileMenu')).to_contain_text('Ruolo attivo');f=p.locator('#stableLegalFooter');expect(f).to_be_visible();metric=f.evaluate("e=>({pos:getComputedStyle(e).position,bottom:getComputedStyle(e).bottom,h:e.getBoundingClientRect().height,pad:parseFloat(getComputedStyle(document.body).paddingBottom)||0})");assert metric['pos']=='fixed' and metric['bottom']=='0px' and metric['pad']>=metric['h']-1,metric
  if DEMO:
   card=p.locator('#ictcDemoCard');expect(card).to_be_visible();expect(card).to_contain_text('Suite 2.2');expect(p.locator('#ictcDemoBanner')).to_have_count(0);card.click();d=p.locator('#ictcDemoDialog');expect(d).to_be_visible();expect(d).to_contain_text('Contesto sintetico');expect(d).to_contain_text('188 record positivi');expect(d).to_contain_text('512 mutanti esclusi');expect(d).to_contain_text('demo-suite-2-2');expect(d).to_contain_text('Dimostrazione, non verdetto');assert p.locator('html').get_attribute('data-ictc-demo-projection')=='demo-suite-2-2';d.locator('[data-demo-close]').click()
  else:expect(p.locator('#ictcDemoCard')).to_have_count(0)
  PHASE='admin';open_admin(p);a=p.locator('#adminCenter');expect(a.locator('[data-admin-nav]')).to_have_count(3);expect(a.locator('[data-admin-view]:visible')).to_have_count(1);assert a.locator('[data-admin-scroll-owner]').evaluate("e=>['auto','scroll'].includes(getComputedStyle(e).overflowY)");a.locator('[data-admin-nav="ai"]').click();expect(a.locator('[data-admin-view="ai"]')).to_be_visible();a.locator('[data-admin-nav="identity"]').click();expect(a.locator('[data-admin-view="identity"]')).to_be_visible();a.locator('[data-admin-close]').click()
  PHASE='procedures';p.locator('.service-nav [data-service="processes"]').click();expect(p.locator('#procedureHub [data-process-code]')).to_have_count(7);codes=p.locator('#procedureHub [data-process-code]').evaluate_all('els=>els.map(e=>e.dataset.processCode)');assert codes==['RN-01','EC-01','AO-01','MC-01','AP-01','RC-01','AR-01'],codes
  PHASE='mobile';mctx=browser.new_context(viewport={'width':390,'height':844});mctx.add_init_script("localStorage.setItem('ictc-role','admin')");m=mctx.new_page();m.goto(BASE,wait_until='networkidle');no_overflow(m,'home-390');expect(m.locator('.service-nav > [data-service]')).to_have_count(3);assert m.locator('.stable-header-inner').bounding_box()['height']<=112;open_admin(m);no_overflow(m,'admin-390');expect(m.locator('#adminCenter [data-admin-view]:visible')).to_have_count(1);m.screenshot(path=str(ART/f'shell-admin-demo-2-6-{MODE}.png'),full_page=True);mctx.close()
  out={'ok':True,'profile':'shell-admin-demo-2.6','mode':MODE,'globalNavigationItems':3,'adminPrimarySections':3,'adminVisibleSections':1,'procedureCards':7,'footerPersistent':True,'demoProgressiveDisclosure':DEMO,'demoProjectionAuthority':'demo-suite-2-2' if DEMO else None,'claimBoundary':'Server-backed browser evidence; not human usability research, aesthetic proof, legal compliance, certification or independent assurance.'};(ART/f'browser-shell-admin-demo-2-6-{MODE}.json').write_text(json.dumps(out,indent=2,ensure_ascii=False));print(json.dumps(out,ensure_ascii=False));ctx.close();browser.close()
except BaseException as exc:
 (ART/f'browser-shell-admin-demo-2-6-{MODE}-error.json').write_text(json.dumps({'ok':False,'phase':PHASE,'type':type(exc).__name__,'message':str(exc),'traceback':traceback.format_exc()},indent=2));raise
