#!/usr/bin/env python3
import hashlib,json,os,re,time,urllib.request
from pathlib import Path
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1];PUBLIC=ROOT/'v3'/'public';ART=ROOT/'artifacts';SHOTS=ART/'screenshots';SHOTS.mkdir(parents=True,exist_ok=True);BASE=os.getenv('ICTC_BASE_URL','http://127.0.0.1:4807').rstrip('/')
def get(path):
 with urllib.request.urlopen(BASE+path,timeout=5) as r:return json.loads(r.read().decode())
def bundle():
 model=(PUBLIC/'js'/'journey-model.js').read_text();shell=(PUBLIC/'js'/'journey-shell.js').read_text();model=re.sub(r'\bexport\s+','',model);shell=re.sub(r'^import[^\n]+\n','',shell,count=1);shell=re.sub(r'\bexport\s+','',shell);return model+'\n'+shell+'\nwindow.__journeyBoot=startJourneyShell();'
def html():
 h=(PUBLIC/'index.html').read_text();c=(PUBLIC/'styles.css').read_text();h=re.sub(r'\s*<link rel="stylesheet" href="styles\.css">','',h);h=re.sub(r'\s*<script type="module" src="app\.js"></script>','',h);return h.replace('</head>',f'<style>{c}</style></head>')
def run():
 health=get('/api/health');assert health['ok'] and health['version']=='1.0.0';contract=json.loads((PUBLIC/'persona-journeys.json').read_text());checks=[]
 with sync_playwright() as p:
  launch={'headless':True,'args':['--no-sandbox','--disable-web-security']}
  if os.getenv('ICTC_CHROMIUM_PATH'):launch['executable_path']=os.environ['ICTC_CHROMIUM_PATH']
  browser=p.chromium.launch(**launch);page=browser.new_page(viewport={'width':1440,'height':1100});page.set_content(html(),wait_until='domcontentloaded')
  page.evaluate("""({base,contract})=>{const s=new Map();Object.defineProperty(window,'localStorage',{configurable:true,value:{getItem:k=>s.has(k)?s.get(k):null,setItem:(k,v)=>s.set(k,String(v)),removeItem:k=>s.delete(k)}});const f=window.fetch.bind(window);window.fetch=(i,n={})=>{const v=typeof i==='string'?i:i.url;if(v.endsWith('/persona-journeys.json'))return Promise.resolve(new Response(JSON.stringify(contract),{status:200,headers:{'content-type':'application/json'}}));if(v.startsWith('/api/'))return f(base+v,n);return f(i,n)}}""",{'base':BASE,'contract':contract});page.add_script_tag(content=bundle());page.get_by_role('heading',name='Che cosa devi completare adesso?').wait_for();checks.append('persona-entry')
  page.locator('#main [data-persona="regulatory-analyst"]').click();page.get_by_role('heading',name='Devo qualificare una novità o ampliare il perimetro conoscitivo').wait_for();assert page.locator('#primaryTaskAction').count()==1;assert page.locator('.task-explanation').get_attribute('open') is None;assert page.locator('.queue-disclosure').get_attribute('open') is None;assert page.get_by_text('Projection Stack').count()==0;checks+=['single-primary','progressive-context','old-stack-removed']
  page.get_by_role('button',name='Apri l’oggetto SOT').click();page.locator('#detailDialog').wait_for(state='visible');page.locator('#detailTabMeaning').focus();page.keyboard.press('ArrowRight');assert page.locator('#detailTabProvenance').get_attribute('aria-selected')=='true';page.locator('[data-dialog-close="detailDialog"]').click();checks.append('real-object-and-keyboard-tabs')
  before=get('/api/runtime/ledger')['integrity']['eventCount'];page.locator('#primaryTaskAction').click();page.locator('#choiceForm button[type=submit]').click();page.locator('#checkpointDialog button[value="confirm"]').click();page.locator('.receipt-banner').wait_for(timeout=10000);ledger=get('/api/runtime/ledger');assert ledger['integrity']['ok'] and ledger['integrity']['eventCount']==before+1;assert 'readback verificato' in page.locator('.receipt-banner').inner_text().lower();checks.append('real-write-refresh-receipt')
  page.locator('#comfortOpen').click();page.locator('#textScale').select_option('large');page.locator('#comfortDialog button[value="save"]').click();page.wait_for_function("document.documentElement.dataset.text==='large'");page.keyboard.press('Control+K');page.locator('#searchDialog').wait_for(state='visible');page.locator('[data-dialog-close="searchDialog"]').click();checks+=['comfort-local','keyboard-search']
  page.locator('#personaButton').click();page.locator('#personaDialog [data-persona="auditor"]').click();page.get_by_role('heading',name='Devo ricostruire come è stato prodotto un esito').wait_for();assert 'sola lettura' in page.locator('.task-status').inner_text().lower();checks.append('auditor-read-only')
  page.locator('#personaButton').click();page.locator('#personaDialog [data-persona="regulatory-analyst"]').click();page.wait_for_timeout(4200);shot=SHOTS/'journey-workspace-runtime.png';page.screenshot(path=str(shot),full_page=True);browser.close()
 sha=hashlib.sha256(shot.read_bytes()).hexdigest();assert shot.stat().st_size>50000;report={'schemaVersion':'1.0.0','generatedAt':time.strftime('%Y-%m-%dT%H:%M:%SZ',time.gmtime()),'result':'passed','mode':'runtime-live-set-content','baseUrl':BASE,'checks':checks,'runtime':{'version':health['version'],'readiness':health['readiness']},'screenshot':{'path':'artifacts/screenshots/journey-workspace-runtime.png','bytes':shot.stat().st_size,'sha256':sha},'limitations':['Asset reali inline per compatibilità sandbox; tutte le API sono chiamate sul server reale.','Il test non certifica accessibilità con tecnologie assistive reali.']};ART.mkdir(exist_ok=True);(ART/'journey-browser-check.json').write_text(json.dumps(report,indent=2,ensure_ascii=False));print(f'journey-browser-check: ok (runtime, {len(checks)} checks, {shot.stat().st_size} bytes, {sha[:12]})')
if __name__=='__main__':run()
