export function fixture(overrides = {}) {
  const source={id:'source-src-candidate',label:'Circolare candidata',statement:'Link acquisito; autorevolezza e applicabilità non revisionate.',epistemicStatus:'candidate',producer:{id:'source-projector'},inputs:[{id:'src-candidate'}],limitations:['Catalogazione non equivale ad applicabilità o completezza.'],nextAction:'Completare la review',receiptRef:'hash-source',data:{id:'src-candidate',lifecycle:'candidate'}};
  const finding={id:'finding-finding-1',label:'Differenza osservata',statement:'Il contenuto locale differisce dalla versione osservata.',epistemicStatus:'awaiting-human-review',producer:{id:'diff-projector'},inputs:[{id:'src-acn'}],limitations:['Materialità e impatto non sono determinati automaticamente.'],data:{id:'finding-1',sourceId:'src-acn'}};
  const change={id:'change-change-1',label:'Valutare la variazione osservata',statement:'Impatto ancora da decidere.',epistemicStatus:'awaiting-human-review',producer:{id:'change-projector'},inputs:[{id:'finding-1'}],limitations:['La decisione è contestuale e riesaminabile.'],receiptRef:'hash-change',data:{id:'change-1',state:'impact-to-assess'}};
  const matter={id:'matter-matter-1',label:'Accessi anomali al portale',statement:'Accessi anomali a un portale fornitore.',epistemicStatus:'attention-required',producer:{id:'matter-projector'},inputs:[{id:'matter-1'}],limitations:['Categoria e urgenza iniziali non sono qualificazioni normative definitive.'],data:{id:'matter-1',state:'facts-to-confirm',owner:'Cybersecurity Incident Manager',raci:{accountable:'CISO',responsible:'Incident Response Team',consulted:['DPO'],informed:['Executive Sponsor']}}};
  const trace={id:'trace-monitoring',label:'Presidio normativo',statement:'Catena ricostruita dalla stessa proiezione usata dalla UI.',epistemicStatus:'verified',producer:{id:'trace-projector'},inputs:[{id:'trace-1'}],limitations:['La traccia attesta il processo locale, non la conformità.'],receiptRef:'head-123',data:{steps:[]}};
  const supply={id:'stage-ledger',label:'SOT locale',statement:'4 eventi append-only',epistemicStatus:'verified',producer:{id:'supply-projector'},inputs:[{id:'runtime'}],limitations:['Lo stato descrive il runtime pubblicato, non una garanzia enterprise.'],receiptRef:'head-123',data:{}};
  const objectIndex=Object.fromEntries([source,finding,change,matter,trace,supply].map(x=>[x.id,x]));
  return {meta:{version:'1.0.0',integrity:{ok:true,eventCount:4,head:'head-123'}},release:{version:'1.0.0',readiness:'ready',stabilityClass:'stable-local-single-user',manifestSha256:'abcdef1234567890',claim:'Stabile nello scope locale dichiarato.',excludedScope:['OIDC/RBAC']},sources:[source.data],findings:[finding.data],changes:[change.data],matters:[matter.data],controls:[{id:'control-monitor',label:'Monitoraggio normativo'}],objectIndex,views:{sources:[source],findings:[finding],changes:[change],matters:[matter],controls:[],traces:[trace],supply:[supply]},...overrides};
}
