export function fixture(overrides = {}) {
  const source = { id: 'source-src-candidate', label: 'Circolare candidata', statement: 'Link acquisito; review non completata.', epistemicStatus: 'candidate', producer: { id: 'source-projector' }, inputs: [{ id: 'src-candidate' }], limitations: ['La presenza della fonte non prova applicabilità o completezza.'], nextAction: 'Rivedere la fonte', receiptRef: 'hash-source', data: { id: 'src-candidate', lifecycle: 'candidate', reviewState: 'candidate-awaiting-review', kind: 'user-link' } };
  const activeSource = { id: 'source-src-active', label: 'Fonte monitorata', statement: 'Fonte inclusa nel perimetro locale.', epistemicStatus: 'human-reviewed', producer: { id: 'source-projector' }, inputs: [{ id: 'src-active' }], limitations: ['La fonte inclusa non è automaticamente applicabile.'], nextAction: 'Aprire i collegamenti', receiptRef: 'hash-active', data: { id: 'src-active', lifecycle: 'active', reviewState: 'reviewed', kind: 'monitored-web' } };
  const finding = { id: 'finding-finding-1', label: 'Differenza osservata', statement: 'Il contenuto osservato differisce dalla baseline.', epistemicStatus: 'awaiting-human-review', producer: { id: 'remote-observation-plus-ai-proposal' }, inputs: [{ id: 'src-active' }, { id: 'job-acn' }], limitations: ['Rilevanza e impatto non sono determinati automaticamente.'], nextAction: 'Registrare la review', receiptRef: null, data: { id: 'finding-1', sourceId: 'src-active', jobId: 'job-acn', aiStudy: { status: 'completed' } } };
  const change = { id: 'change-change-1', label: 'Valutare la variazione', statement: 'Impatto ancora da decidere.', epistemicStatus: 'awaiting-human-review', producer: { id: 'change-projector' }, inputs: [{ id: 'finding-1' }], limitations: ['La decisione è contestuale e riesaminabile.'], nextAction: 'Registrare la decisione', receiptRef: 'hash-change', data: { id: 'change-1', state: 'impact-to-assess', findingId: 'finding-1', controlIds: [] } };
  const control = { id: 'control-control-monitor', label: 'Monitoraggio normativo', statement: '0 collegamenti registrati.', epistemicStatus: 'observed', producer: { id: 'coverage-projector' }, inputs: [{ id: 'control-monitor' }], limitations: ['Il collegamento non prova efficacia.'], nextAction: 'Aprire collegamenti', receiptRef: null, data: { id: 'control-monitor' } };
  const job = { id: 'job-job-acn', label: 'Monitoraggio ACN', statement: 'Prossima esecuzione pianificata. Studio AI: completed.', epistemicStatus: 'operational', producer: { id: 'scheduler-projector' }, inputs: [{ id: 'job-acn' }, { id: 'src-active' }], limitations: ['Il monitoraggio propone e non decide.'], nextAction: 'Eseguire ora o attendere', receiptRef: 'hash-job', data: { id: 'job-acn', sourceId: 'src-active', state: 'completed-no-change', enabled: true, nextRunAt: '2026-08-02T06:00:00Z', schedule: { intervalMinutes: 1440 }, lastStudy: { ai: { status: 'completed' } } } };
  const matter = { id: 'matter-matter-1', label: 'Accessi anomali al portale', statement: 'Accessi anomali a un portale fornitore.', epistemicStatus: 'human-owned', producer: { id: 'matter-projector' }, inputs: [{ id: 'matter-1' }], limitations: ['La fase non determina automaticamente obblighi di notifica.'], nextAction: 'Registrare il triage', receiptRef: null, data: { id: 'matter-1', state: 'owned', owner: 'Cybersecurity Incident Manager', raci: { accountable: 'CISO', responsible: 'Incident Response Team', consulted: ['DPO'], informed: ['Executive Sponsor'] }, phaseEvidence: {}, timeline: [] } };
  const objectIndex = Object.fromEntries([source, activeSource, finding, change, control, job, matter].map(item => [item.id, item]));
  const data = {
    meta: { version: '1.0.0', integrity: { ok: true, eventCount: 4, head: 'head-123' }, monitoring: { scheduler: 'active', remoteFetch: 'enabled', aiStudy: 'configured', aiModel: 'fixture-model' } },
    release: { version: '1.0.0', readiness: 'ready', stabilityClass: 'stable-local-single-user' },
    sources: [{ id: 'src-candidate', title: 'Circolare candidata', lifecycle: 'candidate', reviewState: 'candidate-awaiting-review', kind: 'user-link' },{ id: 'src-active', title: 'Fonte monitorata', lifecycle: 'active', reviewState: 'reviewed', kind: 'monitored-web' }],
    findings: [{ id: 'finding-1', sourceId: 'src-active', jobId: 'job-acn', humanState: 'awaiting-review' }],
    changes: [{ id: 'change-1', state: 'impact-to-assess', findingId: 'finding-1', controlIds: [] }],
    jobs: [{ id: 'job-acn', label: 'Monitoraggio ACN', sourceId: 'src-active', state: 'completed-no-change', enabled: true, nextRunAt: '2026-08-02T06:00:00Z', schedule: { intervalMinutes: 1440 }, lastStudy: { ai: { status: 'completed' } } }],
    matters: [{ id: 'matter-1', state: 'owned', owner: 'Cybersecurity Incident Manager', raci: matter.data.raci, phaseEvidence: {}, timeline: [] }],
    controls: [{ id: 'control-monitor', label: 'Monitoraggio normativo' }],
    objectIndex,
    views: { sources:[source,activeSource], findings:[finding], changes:[change], controls:[control], jobs:[job], matters:[matter], semanticGraph:{ nodes:[], edges:[{id:'e0',from:job.id,to:activeSource.id,type:'monitors',label:'osserva'},{id:'e1',from:activeSource.id,to:finding.id,type:'derived-from',label:'ha prodotto'},{id:'e2',from:job.id,to:finding.id,type:'observed-by',label:'ha rilevato'},{id:'e3',from:finding.id,to:change.id,type:'review-created',label:'review apre'}] } },
    ...overrides
  };
  return data;
}
