const LIMIT='Questi criteri sono DoD operativi ICTC e riferimenti a pratiche dichiarate nel repository; non determinano applicabilita legale, conformita organizzativa, efficacia, certificazione o sufficienza probatoria.';
const application=(ref,methodSteps)=>Object.freeze({ref,methodSteps:Object.freeze(methodSteps)});
const dod=(code,label,completion,benchmarks,epistemicFamilies,handoffs,benchmarkApplications)=>Object.freeze({code,label,completion:Object.freeze(completion),benchmarkRefs:Object.freeze(benchmarks),benchmarkApplications:Object.freeze(benchmarkApplications),epistemicFamilies:Object.freeze(epistemicFamilies),handoffs:Object.freeze(handoffs),limitation:LIMIT});

export const PROCEDURE_DOD=Object.freeze({
 monitoring:dod('RN-01','Monitoraggio normativo e fonti',['obiettivo e perimetro registrati','piano attivato da checkpoint umano','materiale originale preservato','fonte verificata o esclusa con motivazione','impatto valutato quando rilevante'],['iso-37301','sre-observability'],['observed','derived','decided'],['objects','coverage','actions','risks'],[application('iso-37301',[1,2,4,5]),application('sre-observability',[2,3,4])]),
 incidents:dod('EC-01','Incidenti e quasi incidenti',['racconto originale e awareness time preservati','tipo evento confermato da persona','chiarimenti/versioni ricostruibili','submission o chiusura motivata','downstream work esplicitamente riconosciuto'],['nist-csf-20','iso-37301'],['observed','derived','decided'],['objects','actions','risks'],[application('nist-csf-20',[1,2,3,4,5]),application('iso-37301',[1,4,5])]),
 objects:dod('AO-01','Inventario di sistemi e oggetti',['identita e autorita source registrate','candidate review umana completata','version digest e relazioni disponibili','reattestation corrente o scadenza visibile','retirement/rejection motivati'],['iso-37301','nist-csf-20'],['observed','derived','decided'],['monitoring','coverage','actions','risks','assurance'],[application('iso-37301',[1,2,4,5]),application('nist-csf-20',[1,3,4])]),
 coverage:dod('MC-01','Standard e Controlli',['standard/versione e source authority dichiarati','scope deciso da persona','mapping proposto distinto da mapping reviewed','ogni nodo applicabile e mapped/gap/unresolved','not-applicable e crosswalk hanno rationale'],['iso-37301','nist-csf-20'],['observed','proposed','derived','decided'],['objects','actions','risks','assurance'],[application('iso-37301',[1,2,3,4,5]),application('nist-csf-20',[1,2,3,4,5])]),
 actions:dod('AP-01','Azioni correttive',['origine e owner registrati','adozione/priorita umana esplicita','stato avanzamento ricostruibile','completion distinta da verified closure','chiusura verificata con evidenza o cancellation motivata'],['iso-37301','sre-observability'],['observed','derived','decided'],['risks','assurance'],[application('iso-37301',[1,2,4,5]),application('sre-observability',[3,4,5])]),
 risks:dod('RC-01','Rischi di compliance',['scenario e binding registrati','rating inerente motivato da persona','trattamento deciso da persona','azioni di mitigazione collegate quando applicabili','residuo e review cadence espliciti'],['iso-37301','nist-csf-20'],['observed','derived','decided'],['actions','assurance','coverage'],[application('iso-37301',[1,2,3,4,5]),application('nist-csf-20',[1,2,3,4,5])]),
 assurance:dod('AR-01','Questionari e verifiche',['richiesta originale preservata','ogni domanda ha disposition esplicita','draft AI resta proposed','evidence refs e limitations sono visibili','response set approvato e versionato da persona'],['iso-37301','gov-design-systems'],['observed','proposed','derived','decided'],['actions','risks','coverage'],[application('iso-37301',[1,2,4,5]),application('gov-design-systems',[2,3,4,5])])
});

export const BUSINESS_PROCEDURE_IDS=Object.freeze(Object.keys(PROCEDURE_DOD));
const HANDOFF_PREDICATES=Object.freeze({
 'monitoring>objects':'observed-change-suggests-governed-object','monitoring>coverage':'observed-change-suggests-requirement-review','monitoring>actions':'observed-change-suggests-remediation','monitoring>risks':'observed-change-suggests-risk-review',
 'incidents>objects':'event-suggests-inventory-review','incidents>actions':'event-suggests-remediation','incidents>risks':'event-suggests-risk-review',
 'objects>monitoring':'governed-object-suggests-monitoring','objects>coverage':'governed-object-suggests-coverage-review','objects>actions':'governed-object-suggests-remediation','objects>risks':'governed-object-suggests-risk-review','objects>assurance':'governed-object-suggests-assurance-work',
 'coverage>objects':'requirement-mapping-suggests-object-review','coverage>actions':'coverage-gap-suggests-remediation','coverage>risks':'coverage-decision-suggests-risk-review','coverage>assurance':'coverage-decision-suggests-assurance-work',
 'actions>risks':'remediation-change-suggests-risk-review','actions>assurance':'remediation-change-suggests-assurance-work',
 'risks>actions':'risk-treatment-suggests-remediation','risks>assurance':'risk-review-suggests-assurance-work','risks>coverage':'risk-review-suggests-coverage-review',
 'assurance>actions':'assurance-gap-suggests-remediation','assurance>risks':'assurance-result-suggests-risk-review','assurance>coverage':'assurance-result-suggests-coverage-review'
});
export const MEANINGFUL_HANDOFFS=Object.freeze(BUSINESS_PROCEDURE_IDS.flatMap(sourceProcedureId=>PROCEDURE_DOD[sourceProcedureId].handoffs.map(targetProcedureId=>Object.freeze({sourceProcedureId,targetProcedureId,predicate:HANDOFF_PREDICATES[`${sourceProcedureId}>${targetProcedureId}`]||'cross-procedure-draft-from'}))));
export function handoffTargets(sourceProcedureId){return MEANINGFUL_HANDOFFS.filter(x=>x.sourceProcedureId===sourceProcedureId).map(x=>x.targetProcedureId);}
export function handoffRelation(sourceProcedureId,targetProcedureId){return MEANINGFUL_HANDOFFS.find(x=>x.sourceProcedureId===sourceProcedureId&&x.targetProcedureId===targetProcedureId)||null;}
