import { strict as assert } from 'node:assert';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = path.resolve(new URL('..', import.meta.url).pathname);
const contract = JSON.parse(await readFile(path.join(root, 'v3/public/core-workspaces.json'), 'utf8'));
const app = await readFile(path.join(root, 'v3/public/app.js'), 'utf8');
const shell = (await Promise.all(['journey-shell.js','journey-shell-common.js','journey-shell-render.js','journey-shell-actions.js'].map(name => readFile(path.join(root, 'v3/public/js', name), 'utf8')))).join('\n');
const model = await readFile(path.join(root, 'v3/public/js/journey-model.js'), 'utf8');
const css = await readFile(path.join(root, 'v3/public/styles.css'), 'utf8');
const api = await readFile(path.join(root, 'v3/lib/api.mjs'), 'utf8');
const monitoring = await readFile(path.join(root, 'v3/lib/monitoring-runtime.mjs'), 'utf8');
const checks = [];
const mark = (name, detail) => checks.push({ name, status: 'passed', detail });
assert.equal(contract.claimClass, 'core-workspace-contract');
assert.deepEqual(contract.workspaces.map(item => item.id), ['monitoring', 'incidents']);
assert.match(contract.primaryQuestion, /gestire/i); assert.equal(contract.incidentPhases.length, 4);
mark('product-boundary', 'Monitoraggio e Incidenti sono le sole aree primarie');
for (const object of contract.visibleObjects) assert.ok(object.id && object.purpose && object.userAction && Array.isArray(object.usedBy));
assert.ok(contract.visibleObjects.some(item => item.id === 'monitoring-job')); assert.ok(contract.visibleObjects.some(item => item.id === 'incident-phase-evidence'));
mark('object-purpose', `${contract.visibleObjects.length} oggetti con scopo e uso espliciti`);
const expected = ['job-create','job-schedule','job-run','source-propose','source-review','finding-review','change-decision','control-map','matter-create','matter-owner','matter-transition'];
assert.deepEqual(contract.actions.filter(item => item.receiptExpected).map(item => item.id).sort(), expected.sort());
for (const token of ['/api/jobs','/schedule','/run','/api/sources','/api/matters','/transition']) assert.ok(api.includes(token) || shell.includes(token), `wiring assente: ${token}`);
assert.match(monitoring, /askAiToStudy/); assert.match(monitoring, /writeFile\(path\.join\(BLOBS/); assert.match(monitoring, /schedulerTick/);
mark('runtime-wiring', 'scheduler, AI configurabile, storage, route e receipt');
assert.match(app, /startJourneyShell/); assert.doesNotMatch(app, /mountEpistemicGuide|mountActionFrames|mountAdvancedUx/);
assert.match(shell, /deriveCoreWorkspace/); assert.match(shell, /fetch\('\/core-workspaces\.json'/); assert.match(shell, /api\('\/api\/bootstrap'/); assert.match(shell, /async function checkpoint/); assert.match(shell, /state\.lastReceipt\s*=\s*result\.receipt/); assert.match(shell, /await refresh\(\)/);
mark('ui-runtime-cycle', 'focus → checkpoint → write → receipt → bootstrap');
for (const token of ['consequence','doesNotMean','evidenceAfter','sourceRefs','availability']) assert.ok(model.includes(token), `attività senza ${token}`);
assert.match(model, /deriveSemanticRows/); assert.match(model, /deriveIncidentRows/);
mark('onto-epistemic-projection', 'scopo, conseguenza, limiti, prova e catene runtime');
assert.match(shell, /Collegamenti tra fonti e decisioni/); assert.match(shell, /Monitoraggi programmati/); assert.match(shell, /Segnalazione.*Triage.*Analisi.*Risposta.*Ripristino.*Lezioni/s); assert.doesNotMatch(shell, /Area 1 di 2|Area 2 di 2|persona/i);
mark('compact-copy', 'copy centrata sui due servizi e sul prossimo passo');
assert.match(css, /--target:44px/); assert.match(css, /prefers-reduced-motion:reduce/); assert.match(css, /forced-colors:active/); assert.match(shell, /ArrowLeft|ArrowRight/);
mark('accessibility', 'target, focus, tastiera, reflow, motion e forced colors');
for (const pattern of [/compliance score/i,/pienamente conforme/i,/nessun rischio/i,/certificato automaticamente/i]) assert.ok(!pattern.test(`${JSON.stringify(contract)}\n${model}\n${shell}`), `overclaim: ${pattern}`);
mark('anti-overclaim', 'nessun verdetto sintetico nelle superfici attive');
const artifactDir = path.join(root, 'artifacts'); await mkdir(artifactDir, { recursive: true });
await writeFile(path.join(artifactDir, 'v3-ux-audit.json'), JSON.stringify({ schemaVersion:'3.0.0',generatedAt:new Date().toISOString(),result:'passed',profile:'two-core-runtime-services',checks }, null, 2));
console.log(`v3-ux-audit: ok (${checks.length} checks, two-core-services)`);
