import { createHash } from 'node:crypto';
import { mkdir, readFile, rename, unlink, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { MAX_ATTACHMENT_BYTES, MAX_ATTACHMENT_TOTAL_BYTES, MAX_ATTACHMENTS, asString, id, now } from '../domain.mjs';
import { attachmentEvidenceUsable, initialAttachmentTrust, normalizeAttachmentTrust } from './attachment-trust.mjs';
function fail(status,code,message,details=null){throw Object.assign(new Error(message),{status,code,details});}
function metadataRows(state){return[...(state.contributions||[]).flatMap(item=>item.attachments||[]),...(state.incidents||[]).flatMap(item=>item.attachments||[])];}
async function unlinkIf(pathname){try{await unlink(pathname);}catch(error){if(error.code!=='ENOENT')throw error;}}
export async function hardenAttachmentStorage(store){
  if(store.__attachmentStorageHardened)return store;const cleanPath=store.attachmentsPath,quarantinePath=path.join(store.root,'quarantine');await mkdir(cleanPath,{recursive:true,mode:0o700});await mkdir(quarantinePath,{recursive:true,mode:0o700});store.quarantinePath=quarantinePath;store.cleanAttachmentsPath=cleanPath;
  store.saveAttachments=async function(files=[]){const inputs=Array.isArray(files)?files:[];if(inputs.length>MAX_ATTACHMENTS)fail(413,'attachment-count',`Troppi allegati: massimo ${MAX_ATTACHMENTS}`);const candidates=[];let totalBytes=0;for(const file of inputs){const name=asString(file.name,240)||'allegato',mime=asString(file.mime,160)||'application/octet-stream',encoded=asString(file.dataBase64,8_000_000).replace(/^data:[^;]+;base64,/,'');const buffer=Buffer.from(encoded,'base64');if(!buffer.length)continue;if(buffer.length>MAX_ATTACHMENT_BYTES)fail(413,'attachment-too-large',`Allegato troppo grande: ${name}`);totalBytes+=buffer.length;if(totalBytes>MAX_ATTACHMENT_TOTAL_BYTES)fail(413,'attachments-total-too-large',`Allegati troppo grandi nel complesso: massimo ${MAX_ATTACHMENT_TOTAL_BYTES} byte`);const attachmentId=id('file'),digest=createHash('sha256').update(buffer).digest('hex');candidates.push({metadata:{id:attachmentId,name,mime,bytes:buffer.length,sha256:digest,storedAt:now(),trust:initialAttachmentTrust(process.env),storage:{schemaVersion:'1.0.0',state:'quarantine',namespace:'quarantine-v1'}},buffer});}const saved=[];try{for(const candidate of candidates){await writeFile(path.join(quarantinePath,candidate.metadata.id),candidate.buffer,{mode:0o600,flag:'wx'});saved.push(candidate.metadata);}return saved;}catch(error){await store.deleteAttachments(saved).catch(()=>{});throw error;}};
  store.deleteAttachments=async function(files=[]){for(const file of files){const attachmentId=asString(file?.id,200);if(!attachmentId)continue;await unlinkIf(path.join(cleanPath,attachmentId));await unlinkIf(path.join(quarantinePath,attachmentId));}};
  store.attachment=async function(idValue,{allowUnsafe=false}={}){const attachmentId=asString(idValue,200),metadata=metadataRows(store.state).find(item=>item.id===attachmentId);if(!metadata)return null;const normalized={...metadata,trust:normalizeAttachmentTrust(metadata.trust)};if(!allowUnsafe&&!attachmentEvidenceUsable({trust:normalized.trust}))fail(423,'attachment-quarantined','Allegato non disponibile finché la quarantena non è risolta',{state:normalized.trust.state});const preferred=normalized.storage?.state==='clean'?cleanPath:normalized.storage?.state==='quarantine'?quarantinePath:cleanPath;let buffer;try{buffer=await readFile(path.join(preferred,attachmentId));}catch(error){if(error.code==='ENOENT'&&preferred!==cleanPath)buffer=await readFile(path.join(cleanPath,attachmentId));else throw error;}return{metadata:normalized,buffer};};
  store.quarantinedAttachment=async function(idValue){return store.attachment(idValue,{allowUnsafe:true});};
  store.promoteAttachment=async function(idValue){const attachmentId=asString(idValue,200);if(!attachmentId)fail(400,'attachment-id-invalid','Allegato non valido');const from=path.join(quarantinePath,attachmentId),to=path.join(cleanPath,attachmentId);try{await rename(from,to);}catch(error){if(error.code==='ENOENT'){try{await readFile(to);return;}catch{} }throw error;}};
  store.demoteAttachment=async function(idValue){const attachmentId=asString(idValue,200);if(!attachmentId)return;const from=path.join(cleanPath,attachmentId),to=path.join(quarantinePath,attachmentId);try{await rename(from,to);}catch(error){if(error.code!=='ENOENT')throw error;}};
  Object.defineProperty(store,'__attachmentStorageHardened',{value:true});return store;
}
