import { createHmac, timingSafeEqual } from 'node:crypto';
import { canonicalJson, sha256 } from '../domain.mjs';
const text=(v,max=1000)=>String(v??'').trim().slice(0,max);
function fail(status,code,message,details=null){throw Object.assign(new Error(message),{status,code,details});}
export function scannerRuntimePosture(env=process.env){const scannerId=text(env.ICTC_ATTACHMENT_SCANNER_ID,200),secret=text(env.ICTC_ATTACHMENT_SCANNER_SECRET,2000),mode=text(env.ICTC_ATTACHMENT_SCANNER_MODE,80).toLowerCase();return{schemaVersion:'1.1.0',configured:mode==='external-attested'&&Boolean(scannerId)&&secret.length>=32,mode,scannerId:scannerId||null,attestationAuthentication:secret.length>=32?'hmac-sha256':'unavailable',tenantBinding:'signed-payload-v1',limitations:['The runtime verifies tenant-bound scanner attestations and enforces quarantine; malware detection quality remains the scanner deployment responsibility.']};}
export function scannerAttestationPayload(metadata,input={},scope={}){return{schemaVersion:'1.1.0',tenantId:text(input.tenantId||scope.tenantId||'local-default',63).toLowerCase(),attachmentId:text(metadata?.id,200),attachmentSha256:text(metadata?.sha256,64).toLowerCase(),verdict:text(input.verdict,20).toLowerCase(),scannerId:text(input.scannerId,200),scannerVersion:text(input.scannerVersion,200),signatureDbVersion:text(input.signatureDbVersion,200),observedAt:text(input.observedAt,100)};}
export function signScannerAttestation(metadata,input,env=process.env,scope={}){const posture=scannerRuntimePosture(env);if(!posture.configured)fail(503,'scanner-not-configured','Scanner non configurato');const payload=scannerAttestationPayload(metadata,{...input,scannerId:input.scannerId||posture.scannerId},scope);return createHmac('sha256',text(env.ICTC_ATTACHMENT_SCANNER_SECRET,2000)).update(canonicalJson(payload)).digest('hex');}
export function verifyScannerAttestation(metadata,input={},env=process.env,nowValue=new Date(),scope={}){
  const posture=scannerRuntimePosture(env);if(!posture.configured)fail(503,'scanner-not-configured','Scanner non configurato');const payload=scannerAttestationPayload(metadata,input,scope);const reasons=[],expectedTenant=text(scope.tenantId||payload.tenantId,63).toLowerCase();
  if(!/^[a-z0-9][a-z0-9-]{0,62}$/.test(payload.tenantId))reasons.push('tenant-id-invalid');if(expectedTenant&&payload.tenantId!==expectedTenant)reasons.push('tenant-id-mismatch');if(payload.attachmentId!==metadata?.id)reasons.push('attachment-id-mismatch');if(payload.attachmentSha256!==String(metadata?.sha256||'').toLowerCase())reasons.push('attachment-digest-mismatch');if(payload.scannerId!==posture.scannerId)reasons.push('scanner-id-mismatch');if(!['clean','rejected'].includes(payload.verdict))reasons.push('verdict-invalid');if(!payload.scannerVersion)reasons.push('scanner-version-missing');if(!payload.signatureDbVersion)reasons.push('signature-db-version-missing');
  const observed=new Date(payload.observedAt).getTime(),now=nowValue.getTime();if(!Number.isFinite(observed))reasons.push('observed-at-invalid');else{if(observed>now+300000)reasons.push('observed-in-future');if(observed<now-86400000)reasons.push('attestation-too-old');}
  const received=text(input.signature,128).toLowerCase(),expected=createHmac('sha256',text(env.ICTC_ATTACHMENT_SCANNER_SECRET,2000)).update(canonicalJson(payload)).digest('hex');const a=Buffer.from(received),b=Buffer.from(expected);if(a.length!==b.length||!a.length||!timingSafeEqual(a,b))reasons.push('signature-invalid');
  if(reasons.length)fail(400,'scanner-attestation-invalid','Attestazione scanner non valida',{reasons});
  return{schemaVersion:'1.1.0',tenantId:payload.tenantId,state:payload.verdict==='clean'?'scan-clean':'scan-rejected',scannerMode:'external-attested',scannerId:payload.scannerId,scannerVersion:payload.scannerVersion,signatureDbVersion:payload.signatureDbVersion,scannedAt:payload.observedAt,scanDigest:sha256(payload),reason:payload.verdict==='clean'?'scanner-attested-clean':'scanner-attested-rejected'};
}
