import { sha256 } from '../domain.mjs';

const UNKNOWN_KINDS=new Set(['unknown','conflict','provisional']);
const POSITION_STANCES=new Set(['support','dissent','alternative','reserved']);
const CONSTRAINT_KINDS=new Set(['time','capacity','dependency','competence','safety','incentive','availability','other']);
const ESCALATION_STATES=new Set(['none','requested','accepted','declined','resolved']);
const EXCEPTION_KINDS=new Set(['waiver','temporary-deviation','compensating-control']);
const RECOVERY_KINDS=new Set(['reopen','correction','supersede']);
const REF_TYPES=new Set(['principal','external','service','role','team']);
const MAX_ITEMS=20;

const text=(value,max=4000)=>{const raw=String(value??'').trim();if(raw.length>max)throw Object.assign(new Error(`Decision context supera il limite di ${max} caratteri`),{status:400,code:'decision-context-text-too-long'});return raw;};
const list=(value,max=MAX_ITEMS)=>{if(!Array.isArray(value))return[];if(value.length>max)throw Object.assign(new Error(`Decision context supera il limite di ${max} elementi`),{status:400,code:'decision-context-list-too-long'});return value;};
const iso=value=>{const raw=text(value,80);if(!raw)return null;const ms=Date.parse(raw);if(Number.isNaN(ms))throw Object.assign(new Error(`Timestamp decision context non valido: ${raw}`),{status:400,code:'decision-context-time-invalid'});return new Date(ms).toISOString();};
const strings=(value,max=20,itemMax=1000)=>[...new Set(list(value,max).map(v=>text(v,itemMax)).filter(Boolean))];
function ref(value){if(!value)return null;const raw=typeof value==='string'?{type:'external',id:value}:value,type=text(raw?.type,40).toLowerCase()||'external',id=text(raw?.id,300);if(!id)return null;if(!REF_TYPES.has(type))throw Object.assign(new Error(`Tipo riferimento decision context non valido: ${type}`),{status:400,code:'decision-context-ref-type-invalid'});return{type,id,...(text(raw?.displayName,300)?{displayName:text(raw.displayName,300)}:{})};}
function normalizeUncertainties(value){return list(value).map(item=>{const kind=text(item?.kind,40).toLowerCase()||'unknown';if(!UNKNOWN_KINDS.has(kind))throw Object.assign(new Error(`Tipo incertezza non valido: ${kind}`),{status:400,code:'decision-context-uncertainty-kind-invalid'});const statement=text(item?.statement,4000);if(!statement)throw Object.assign(new Error('Descrizione incertezza richiesta'),{status:400,code:'decision-context-uncertainty-statement-required'});return{kind,statement,sourceRefs:strings(item?.sourceRefs)};});}
function normalizePositions(value){return list(value).map(item=>{const stance=text(item?.stance,40).toLowerCase()||'reserved';if(!POSITION_STANCES.has(stance))throw Object.assign(new Error(`Posizione non valida: ${stance}`),{status:400,code:'decision-context-position-stance-invalid'});const statement=text(item?.statement,4000);if(!statement)throw Object.assign(new Error('Posizione decisionale richiesta'),{status:400,code:'decision-context-position-statement-required'});return{stance,statement,actorRef:ref(item?.actorRef),basisRefs:strings(item?.basisRefs)};});}
function normalizeConstraints(value){return list(value).map(item=>{const kind=text(item?.kind,40).toLowerCase()||'other';if(!CONSTRAINT_KINDS.has(kind))throw Object.assign(new Error(`Vincolo non valido: ${kind}`),{status:400,code:'decision-context-constraint-kind-invalid'});const statement=text(item?.statement,4000);if(!statement)throw Object.assign(new Error('Descrizione vincolo richiesta'),{status:400,code:'decision-context-constraint-statement-required'});return{kind,statement,expiresAt:iso(item?.expiresAt)};});}
function normalizeHandoffs(value){return list(value,10).map(item=>{const note=text(item?.note,4000),fromRef=ref(item?.fromRef),toRef=ref(item?.toRef);if(!fromRef&&!toRef&&!note)throw Object.assign(new Error('Handoff decision context vuoto'),{status:400,code:'decision-context-handoff-empty'});return{fromRef,toRef,note,acceptedAt:iso(item?.acceptedAt)};});}
function normalizeEscalation(value){if(!value)return null;const status=text(value?.status,40).toLowerCase()||'none';if(!ESCALATION_STATES.has(status))throw Object.assign(new Error(`Stato escalation non valido: ${status}`),{status:400,code:'decision-context-escalation-status-invalid'});const out={status,targetRef:ref(value?.targetRef),reason:text(value?.reason,4000)};if(status!=='none'&&!out.reason)throw Object.assign(new Error('Motivazione escalation richiesta'),{status:400,code:'decision-context-escalation-reason-required'});return out;}
function normalizeException(value){if(!value)return null;const kind=text(value?.kind,40).toLowerCase();if(!EXCEPTION_KINDS.has(kind))throw Object.assign(new Error(`Tipo eccezione non valido: ${kind||'<missing>'}`),{status:400,code:'decision-context-exception-kind-invalid'});const rationale=text(value?.rationale,4000);if(!rationale)throw Object.assign(new Error('Rationale eccezione richiesta'),{status:400,code:'decision-context-exception-rationale-required'});return{kind,rationale,expiresAt:iso(value?.expiresAt),compensatingControlRefs:strings(value?.compensatingControlRefs)};}
function normalizeUrgency(value){if(!value)return null;const reason=text(value?.reason,4000),triggerAt=iso(value?.triggerAt),dueAt=iso(value?.dueAt);if(!reason&&!triggerAt&&!dueAt)throw Object.assign(new Error('Urgenza decision context vuota'),{status:400,code:'decision-context-urgency-empty'});if(triggerAt&&dueAt&&Date.parse(dueAt)<Date.parse(triggerAt))throw Object.assign(new Error('La scadenza non può precedere il trigger'),{status:400,code:'decision-context-urgency-order-invalid'});return{reason,triggerAt,dueAt};}
function normalizeRecovery(value){if(!value)return null;const kind=text(value?.kind,40).toLowerCase();if(!RECOVERY_KINDS.has(kind))throw Object.assign(new Error(`Tipo recovery non valido: ${kind||'<missing>'}`),{status:400,code:'decision-context-recovery-kind-invalid'});const reason=text(value?.reason,4000);if(!reason)throw Object.assign(new Error('Motivazione recovery richiesta'),{status:400,code:'decision-context-recovery-reason-required'});return{kind,priorDecisionRef:text(value?.priorDecisionRef,300)||null,reason};}
export const DECISION_CONTEXT_CLAIM_BOUNDARY='Decision context records declared operating conditions around a human decision. It does not create decision authority, prove the truth of declared facts, excuse an obligation, establish legal applicability or change the business outcome by itself.';
export function normalizeDecisionContext(value){if(value==null||value==='')return null;if(typeof value!=='object'||Array.isArray(value))throw Object.assign(new Error('Decision context deve essere un oggetto'),{status:400,code:'decision-context-invalid'});const out={schemaVersion:'1.0.0',authorityEffect:'NONE',operativeIntent:text(value.operativeIntent,4000),uncertainties:normalizeUncertainties(value.uncertainties),positions:normalizePositions(value.positions),constraints:normalizeConstraints(value.constraints),handoffs:normalizeHandoffs(value.handoffs),escalation:normalizeEscalation(value.escalation),exception:normalizeException(value.exception),urgency:normalizeUrgency(value.urgency),limitations:strings(value.limitations,20,4000),recovery:normalizeRecovery(value.recovery),claimBoundary:DECISION_CONTEXT_CLAIM_BOUNDARY};const material=Boolean(out.operativeIntent||out.uncertainties.length||out.positions.length||out.constraints.length||out.handoffs.length||out.escalation||out.exception||out.urgency||out.limitations.length||out.recovery);return material?out:null;}
export function decisionContextFromInput(input){if(!input||typeof input!=='object')return null;const raw=input.decisionContext??input.input?.decisionContext??null;return normalizeDecisionContext(raw);}
export function decisionContextSha256(value){const normalized=value?.schemaVersion?value:normalizeDecisionContext(value);return normalized?sha256(normalized):null;}
export function withDecisionContext(target,input){const context=normalizeDecisionContext(input?.decisionContext);if(context)target.decisionContext=context;return target;}
