import { sha256 } from '../domain.mjs';
import { bindingsNeedReview, resolveEvidenceRef } from './reference-contract.mjs';
import { effectiveRiskReview, effectiveRiskTreatment } from './grc-risks.mjs';
import { normalizeProjectionContext,projectionBasis } from './projection-context.mjs';
const atMs=value=>{const n=Date.parse(value||'');return Number.isNaN(n)?0:n;};const latest=items=>(items||[]).at(-1)||null;
function item(processId,subjectType,subjectId,title,reason,causes=[],baselineAt=null){return{schemaVersion:'1.2.0',id:`review-needed:${processId}:${subjectId}`,processId,subject:{type:subjectType,id:subjectId},title,reason,causes,baselineAt,derived:true,humanRequired:true,checkpoint:'dependency-review'};}
function closedOriginActions(state,originType,originId,after){return(state.grcActions||[]).filter(action=>action.originType===originType&&action.originId===originId&&action.state==='closed'&&atMs(action.closedAt)>atMs(after));}
function staleBindings(bindings,state){return bindingsNeedReview((bindings||[]).filter(binding=>binding?.type==='grc-object'||binding?.type==='action'),state);}
function staleEvidenceBindings(bindings,state){return(bindings||[]).flatMap(binding=>{if(binding?.scope!=='internal'||!binding.type||!binding.id)return[];const current=resolveEvidenceRef(`ictc:${binding.type}:${binding.id}`,state);if(!current?.usable)return[{...binding,reason:current?.resolution||'missing'}];if(binding.subjectVersionSha256&&current.subjectVersionSha256!==binding.subjectVersionSha256)return[{...binding,reason:'version-changed',currentVersionSha256:current.subjectVersionSha256}];return[];});}
function currentObservationSha(source){const observation=latest(source.observations);return observation?sha256(observation):sha256({id:source.id,title:source.title,updatedAt:source.updatedAt});}
export function dependencyReviewProjection(state,actor={role:'admin',id:'system'},context={}){const ctx=normalizeProjectionContext(actor,{...context,stateRevision:context.stateRevision??state.revision??null}),nowMs=ctx.validAsOfMs,items=[];
for(const object of state.grcObjects||[]){if(object.status!=='active')continue;const due=object.attestationDueAt&&atMs(object.attestationDueAt)<=nowMs;if(due)items.push(item('objects','grc-object',object.id,`Riesamina oggetto: ${object.name}`,'La re-attestation della versione corrente è scaduta o richiesta dopo una modifica.',[{kind:'attestation-due',dueAt:object.attestationDueAt,versionSha256:object.versionSha256}],object.lastAttestedAt));}
for(const mapping of state.grcMappings||[]){if(!['mapped','gap','not-applicable'].includes(mapping.state))continue;const decision=latest(mapping.decisions),staleTargets=staleBindings(decision?.targetBindings||mapping.targetBindings,state),staleEvidence=staleEvidenceBindings(decision?.evidenceBindings||mapping.evidenceBindings,state),closed=closedOriginActions(state,'mapping',mapping.id,decision?.at||mapping.updatedAt),causes=[...staleTargets.map(ref=>({kind:'reference-stale',reference:ref})),...staleEvidence.map(ref=>({kind:'evidence-stale',reference:ref})),...closed.map(action=>({kind:'remediation-closed',actionId:action.id,closedAt:action.closedAt}))];if(causes.length)items.push(item('coverage','mapping',mapping.id,`Riesamina copertura: ${mapping.requirementRef||mapping.requirementLabel}`,'Un target o un’evidenza collegata è cambiata, oppure una remediation del gap è stata verificata dopo l’ultima decisione di copertura.',causes,decision?.at||mapping.updatedAt));}
for(const action of state.grcActions||[]){if(action.state!=='closed')continue;const verification=latest(action.verifications);if(!verification)continue;const staleEvidence=staleEvidenceBindings(verification.evidenceBindings,state);if(staleEvidence.length)items.push(item('actions','action',action.id,`Riesamina chiusura: ${action.title}`,'Una evidenza usata per verificare la chiusura non corrisponde più alla versione legata alla decisione.',staleEvidence.map(ref=>({kind:'evidence-stale',reference:ref})),verification.at));}
for(const risk of state.grcRisks||[]){const review=effectiveRiskReview(risk);if(!review)continue;const treatment=effectiveRiskTreatment(risk,review),stale=staleBindings([...(review.objectBindings||risk.objectBindings||[]),...(review.controlBindings||risk.controlBindings||[])],state),closed=(risk.actionIds||[]).map(id=>(state.grcActions||[]).find(action=>action.id===id)).filter(action=>action?.state==='closed'&&atMs(action.closedAt)>atMs(review.at)),scheduledDue=Boolean(treatment?.reviewAt&&atMs(treatment.reviewAt)<=nowMs),causes=[...stale.map(ref=>({kind:'reference-stale',reference:ref})),...closed.map(action=>({kind:'remediation-closed',actionId:action.id,closedAt:action.closedAt})),...(scheduledDue?[{kind:'scheduled-review-due',reviewAt:treatment.reviewAt,treatmentDecision:treatment.decision,assessmentSha256:treatment.assessmentSha256}]:[])];if(causes.length)items.push(item('risks','risk',risk.id,`Riesamina rischio: ${risk.title}`,'Oggetti o controlli valutati sono cambiati, una remediation è stata verificata oppure è arrivata la data di riesame del trattamento corrente.',causes,review.at));}
for(const assurance of state.grcAssurance||[]){if(assurance.state!=='approved')continue;const approval=latest(assurance.approvals);if(!approval)continue;const staleEvidence=staleEvidenceBindings((assurance.approvedAnswers||[]).flatMap(answer=>answer.evidenceBindings||[]),state);if(staleEvidence.length)items.push(item('assurance','assurance-case',assurance.id,`Riesamina assurance: ${assurance.title}`,'Una evidenza usata nel response set approvato è cambiata o non è più risolvibile rispetto alla versione approvata.',staleEvidence.map(ref=>({kind:'evidence-stale',reference:ref})),approval.at));}
for(const source of state.catalog||[]){if(source.state!=='verified')continue;const impact=latest(source.impactAssessments);if(!impact)continue;const internalRequirements=(impact.requirementBindings||[]).filter(ref=>ref.scope==='internal'),stale=staleBindings([...(impact.affectedObjectBindings||[]),...internalRequirements],state),sourceChanged=impact.sourceObservationSha256&&impact.sourceObservationSha256!==currentObservationSha(source),closed=closedOriginActions(state,'source',source.id,impact.at),causes=[...stale.map(ref=>({kind:'reference-stale',reference:ref})),...(sourceChanged?[{kind:'source-version-changed',currentObservationSha256:currentObservationSha(source)}]:[]),...closed.map(action=>({kind:'remediation-closed',actionId:action.id,closedAt:action.closedAt}))];if(causes.length)items.push(item('monitoring','source',source.id,`Riesamina impatto: ${source.title}`,'La base dell’ultima valutazione d’impatto è cambiata oppure una remediation collegata è stata verificata.',causes,impact.at));}
const counts=items.reduce((acc,current)=>(acc[current.processId]=(acc[current.processId]||0)+1,acc),{});return{schemaVersion:'1.3.0',authority:'runtime-derived-dependency-review',projection:projectionBasis(ctx),readOnly:actor.role==='auditor',items,counts,total:items.length,limitations:['Review-needed è derivato dalla stessa projection basis e non modifica automaticamente decisioni umane precedenti.','Una remediation chiusa genera lavoro di riesame nel processo origine; non converte automaticamente gap o rischio in stato favorevole.','Per RC-01 il clock segue soltanto il trattamento legato alla valutazione effettiva del ciclo corrente; trattamenti di cicli precedenti non generano scadenze fantasma.','Le evidenze interne sono confrontate con la versione legata alla decisione; gli URL esterni utilizzabili devono essere version-bound.','La scadenza di re-attestation o della reviewAt segnala lavoro sulla validAsOf della proiezione e non implica che la decisione precedente sia falsa.']};}
