import { sha256 } from '../domain.mjs';
import { bindingsNeedReview } from './reference-contract.mjs';

const atMs=value=>{const n=Date.parse(value||'');return Number.isNaN(n)?0:n;};
const latest=items=>(items||[]).at(-1)||null;
function item(processId,subjectType,subjectId,title,reason,causes=[],baselineAt=null){return{schemaVersion:'1.0.0',id:`review-needed:${processId}:${subjectId}`,processId,subject:{type:subjectType,id:subjectId},title,reason,causes,baselineAt,derived:true,humanRequired:true,checkpoint:'dependency-review'};}
function closedOriginActions(state,originType,originId,after){return(state.grcActions||[]).filter(action=>action.originType===originType&&action.originId===originId&&action.state==='closed'&&atMs(action.closedAt)>atMs(after));}
function staleBindings(bindings,state){return bindingsNeedReview((bindings||[]).filter(binding=>binding?.type==='grc-object'||binding?.type==='action'),state);}
function currentObservationSha(source){const observation=latest(source.observations);return observation?sha256(observation):sha256({id:source.id,title:source.title,updatedAt:source.updatedAt});}
export function dependencyReviewProjection(state,actor={role:'admin'}){const items=[];
  for(const object of state.grcObjects||[]){if(object.status!=='active')continue;const due=object.attestationDueAt&&atMs(object.attestationDueAt)<=Date.now();if(due)items.push(item('objects','grc-object',object.id,`Riesamina oggetto: ${object.name}`,'La re-attestation della versione corrente è scaduta o richiesta dopo una modifica.',[{kind:'attestation-due',dueAt:object.attestationDueAt,versionSha256:object.versionSha256}],object.lastAttestedAt));}
  for(const mapping of state.grcMappings||[]){if(!['mapped','gap','not-applicable'].includes(mapping.state))continue;const decision=latest(mapping.decisions),stale=staleBindings(decision?.targetBindings||mapping.targetBindings,state),closed=closedOriginActions(state,'mapping',mapping.id,decision?.at||mapping.updatedAt);const causes=[...stale.map(ref=>({kind:'reference-stale',reference:ref})),...closed.map(action=>({kind:'remediation-closed',actionId:action.id,closedAt:action.closedAt}))];if(causes.length)items.push(item('coverage','mapping',mapping.id,`Riesamina copertura: ${mapping.requirementRef||mapping.requirementLabel}`,'Un target collegato è cambiato oppure una remediation del gap è stata verificata dopo l’ultima decisione di copertura.',causes,decision?.at||mapping.updatedAt));}
  for(const risk of state.grcRisks||[]){const review=latest(risk.reviews);if(!review)continue;const stale=staleBindings([...(review.objectBindings||risk.objectBindings||[]),...(review.controlBindings||risk.controlBindings||[])],state),closed=(risk.actionIds||[]).map(id=>(state.grcActions||[]).find(action=>action.id===id)).filter(action=>action?.state==='closed'&&atMs(action.closedAt)>atMs(review.at));const causes=[...stale.map(ref=>({kind:'reference-stale',reference:ref})),...closed.map(action=>({kind:'remediation-closed',actionId:action.id,closedAt:action.closedAt}))];if(causes.length)items.push(item('risks','risk',risk.id,`Riesamina rischio: ${risk.title}`,'Oggetti o controlli valutati sono cambiati oppure una remediation collegata è stata verificata dopo l’ultimo rating.',causes,review.at));}
  for(const source of state.catalog||[]){if(source.state!=='verified')continue;const impact=latest(source.impactAssessments);if(!impact)continue;const internalRequirements=(impact.requirementBindings||[]).filter(ref=>ref.scope==='internal'),stale=staleBindings([...(impact.affectedObjectBindings||[]),...internalRequirements],state),sourceChanged=impact.sourceObservationSha256&&impact.sourceObservationSha256!==currentObservationSha(source),closed=closedOriginActions(state,'source',source.id,impact.at);const causes=[...stale.map(ref=>({kind:'reference-stale',reference:ref})),...(sourceChanged?[{kind:'source-version-changed',currentObservationSha256:currentObservationSha(source)}]:[]),...closed.map(action=>({kind:'remediation-closed',actionId:action.id,closedAt:action.closedAt}))];if(causes.length)items.push(item('monitoring','source',source.id,`Riesamina impatto: ${source.title}`,'La base dell’ultima valutazione d’impatto è cambiata oppure una remediation collegata è stata verificata.',causes,impact.at));}
  const counts=items.reduce((acc,current)=>(acc[current.processId]=(acc[current.processId]||0)+1,acc),{});return{schemaVersion:'1.0.0',authority:'runtime-derived-dependency-review',readOnly:actor.role==='auditor',items,counts,total:items.length,limitations:['Review-needed è derivato dallo stato corrente e non modifica automaticamente decisioni umane precedenti.','Una remediation chiusa genera lavoro di riesame nel processo origine; non converte automaticamente gap o rischio in stato favorevole.','La scadenza di re-attestation segnala lavoro da svolgere e non implica che il record sia falso.']};}
