import { sha256 } from '../domain.mjs';
import { procedureIdForSubject } from './procedure-adapters.mjs';

function legacyFamiliesForAction(action=''){const value=String(action);if(/\.ai\.|ai\./.test(value))return['proposed'];if(/attest/i.test(value))return['attested'];if(/decid|review|approv|adopt|verif|clos|cancel|treat|submit/i.test(value))return['decided'];return['observed'];}
function actorAuthority(actorId,role){if(String(actorId||'').startsWith('system:')||role==='system'||role==='service')return{type:'service',id:String(actorId||'ictc-runtime')};return{type:'principal',id:String(actorId||'unknown')};}
function defaultProducer(event){if(/\.ai\.|ai\./.test(String(event?.action||'')))return{type:'service',id:'ai-provider'};return actorAuthority(event?.actorId,event?.role);}
function explicitEffectFor(event,version,ordinal){const declared=Array.isArray(event?.metadata?.epistemicEffects)?event.metadata.epistemicEffects:[];return declared.find(item=>item?.subjectVersionId===version?.id)||declared.find(item=>item?.subject?.type===version?.subject?.type&&item?.subject?.id===version?.subject?.id)||declared.find(item=>Number(item?.ordinal)===ordinal+1)||null;}
const subjectKey=value=>`${String(value?.type||'')}\u0000${String(value?.id||'')}`;
export function semanticManifest(subjectVersions=[],reviewNeeds=[]){const versions=(subjectVersions||[]).map(item=>({id:item.id,revision:item.revision??null,subject:structuredClone(item.subject||null),predecessorId:item.predecessorId||null,payloadSha256:item.payloadSha256,semanticSchemaVersion:item.semanticSchemaVersion||null,canonicalizationVersion:item.canonicalizationVersion||null})).sort((a,b)=>subjectKey(a.subject).localeCompare(subjectKey(b.subject))||String(a.id).localeCompare(String(b.id))),reviews=(reviewNeeds||[]).map(item=>({id:item.id,processId:item.processId||null,subject:structuredClone(item.subject||null),checkpoint:item.checkpoint||null,causeDigests:[...(item.causeDigests||[])].map(String).sort(),policyVersion:item.policyVersion||null,openedRevision:item.openedRevision??null,status:item.status||null})).sort((a,b)=>String(a.id).localeCompare(String(b.id)));return{schemaVersion:'1.0.0',subjectVersions:versions,reviewNeeds:reviews};}
export function semanticManifestSha256(subjectVersions=[],reviewNeeds=[]){return sha256(semanticManifest(subjectVersions,reviewNeeds));}
export function verifyEpistemicStep(step){if(!step||typeof step!=='object'||!step.stepSha256)return false;const copy=structuredClone(step),expected=copy.stepSha256;delete copy.stepSha256;return sha256(copy)===expected;}
export function buildEpistemicStep(event,subjectVersions=[],reviewNeeds=[]){const effects=(subjectVersions||[]).map((version,ordinal)=>{const declared=explicitEffectFor(event,version,ordinal),producer=structuredClone(declared?.producerRef||declared?.authorityRef||defaultProducer(event)),families=Array.isArray(declared?.families)&&declared.families.length?[...new Set(declared.families.map(String))]:legacyFamiliesForAction(event?.action);return{ordinal:ordinal+1,kind:String(declared?.kind||'subject-versioned'),families,subjectVersionId:version.id,subject:structuredClone(version.subject),payloadSha256:version.payloadSha256,authorityRef:producer,producerRef:producer,basisRefs:structuredClone(declared?.basisRefs||[]),relation:declared?.relation?structuredClone(declared.relation):null,classificationSource:declared?'declared-effect':'legacy-action-fallback'};});for(const review of reviewNeeds||[])effects.push({ordinal:effects.length+1,kind:'review-needed',families:['derived'],reviewNeedRef:review.id,subject:structuredClone(review.subject),causeDigests:structuredClone(review.causeDigests||[]),authorityRef:{type:'service',id:'ictc-review-policy'},producerRef:{type:'service',id:'ictc-review-policy'},basisRefs:structuredClone(review.causes||[]),relation:{predicate:'requires-review-of',object:structuredClone(review.subject)},classificationSource:'review-policy'});if(!effects.length){const producer=defaultProducer(event);effects.push({ordinal:1,kind:event?.action==='integrity.state-bound'?'policy-recorded':'observation-recorded',families:event?.action==='integrity.state-bound'?['attested']:legacyFamiliesForAction(event?.action),subject:structuredClone(event?.subject||null),authorityRef:producer,producerRef:producer,basisRefs:[],relation:null,classificationSource:'legacy-action-fallback'});}const initiator=actorAuthority(event?.actorId,event?.role),step={schemaVersion:'1.3.0',eventId:event.id,revision:event.revision,transactionAt:event.at,semanticManifestSha256:event?.metadata?.semanticManifestSha256||null,procedureContext:{primaryProcedureId:procedureIdForSubject(event?.subject?.type)||null,procedurePolicyVersion:event?.metadata?.procedurePolicyVersion||null,accessPolicyVersion:event?.metadata?.accessPolicyVersion||null},execution:{initiatorRef:initiator,executorRef:{type:'service',id:'ictc-runtime'},originKind:event?.role==='service'||event?.role==='system'?'system-execution':'human-command'},command:{inputSha256:event.inputSha256||null},effects,correlationId:event?.metadata?.correlationId||null,causationEventId:event?.metadata?.causationEventId||null,limitations:['Epistemic effects describe recorded ICTC operations and authority; they do not upgrade observations, AI proposals or evidence into substantive compliance conclusions.','Action-name classification is compatibility fallback only; declared epistemicEffects are the forward semantic write contract.']};step.stepSha256=sha256(step);return step;}
