import { sha256, canonicalJson, safeFilename } from '../domain.mjs';
import { VERSION } from '../version.mjs';
import { visibleState } from './model.mjs';
import { grcProjection } from './grc-projection.mjs';
import { canonicalEvidenceGraph, evidenceForClaim, graphDigest } from './evidence-graph.mjs';
import { buildEvidenceLineageDocument, renderEvidenceFormats } from './evidence-formats.mjs';
import { zipStore } from './zip-store.mjs';
export function csvCell(value){const raw=String(value??''),guarded=/^[\u0000-\u0020]*[=+\-@]/.test(raw)?`'${raw}`:raw;return /[",\n\r]/.test(guarded)?`"${guarded.replace(/"/g,'""')}"`:guarded;}
function viewRows(view,grc){return[...view.missions.map(x=>({type:'monitoring',id:x.id,state:x.state,label:x.objective||'',updatedAt:x.updatedAt||''})),...view.catalog.map(x=>({type:'source',id:x.id,state:x.state,label:x.title||'',updatedAt:x.updatedAt||''})),...view.contributions.map(x=>({type:'material',id:x.id,state:x.state,label:x.note||x.links?.[0]||'',updatedAt:x.updatedAt||x.createdAt||''})),...view.incidents.map(x=>({type:'incident',id:x.id,state:x.state,label:x.finalNarrative||x.originalNarrative||'',updatedAt:x.updatedAt||x.createdAt||''})),...grc.objects.objects.map(x=>({type:'grc-object',id:x.id,state:x.status,label:x.name,updatedAt:x.updatedAt||''})),...grc.coverage.mappings.map(x=>({type:'mapping',id:x.id,state:x.state,label:x.requirementRef||x.requirementLabel,updatedAt:x.updatedAt||''})),...grc.actions.actions.map(x=>({type:'action',id:x.id,state:x.state,label:x.title,updatedAt:x.updatedAt||''})),...grc.risks.risks.map(x=>({type:'risk',id:x.id,state:x.state,label:x.title,updatedAt:x.updatedAt||''})),...grc.assurance.cases.map(x=>({type:'assurance-case',id:x.id,state:x.state,label:x.title,updatedAt:x.updatedAt||''}))];}
export function authorizedCurrentView(store,actor){const view=visibleState(actor,store,VERSION),grc=grcProjection(store.snapshot(),actor),rows=viewRows(view,grc);return{schemaVersion:'2.0.0',generatedAt:new Date().toISOString(),generatedBy:actor.id,generatedForRole:actor.role,revision:view.revision,authorization:'same-as-read',rows,manifest:{rowCount:rows.length,rowsSha256:sha256(canonicalJson(rows)),integrityHead:view.integrity.head||null},limitations:['The export contains only records visible to the current actor and does not expand read authorization.']};}
export function currentViewCsv(exported){const cols=['type','id','state','label','updatedAt'];return[cols.join(','),...exported.rows.map(row=>cols.map(key=>csvCell(row[key])).join(','))].join('\n')+'\n';}
function file(name,data){const buffer=Buffer.isBuffer(data)?data:Buffer.from(data);return{name,data:buffer,sha256:sha256(buffer)};}
function jsonFile(name,value){return file(name,JSON.stringify(value,null,2)+'\n');}
export function evidenceDossier(store,type,id,actor){
  const graph=canonicalEvidenceGraph(store,type,id,actor);if(!graph)return null;
  const bundle=store.evidenceBundle(type,id,actor),decisions=graph.decisionRecords,epistemic=graph.epistemicRecord,graphSha256=graphDigest(graph);
  const receipts=(bundle.events||[]).map(event=>({eventId:event.id,revision:event.revision,at:event.at,action:event.action,actorId:event.actorId,role:event.role,subject:event.subject,previousHash:event.previousHash,hash:event.hash,inputSha256:event.inputSha256,resultSha256:event.resultSha256,stateSha256:event.stateSha256,semanticManifestSha256:event.metadata?.semanticManifestSha256||null,epistemicStepSha256:event.metadata?.epistemicStepSha256||null}));
  const document=buildEvidenceLineageDocument({bundle,graph:{...graph,digest:graphSha256},release:VERSION,actor}),representations=renderEvidenceFormats(document);
  const core=[jsonFile('subject.json',bundle.subject),jsonFile('relations.json',graph.edges),jsonFile('decisions.json',decisions),jsonFile('claims.json',graph.claims),jsonFile('epistemic.json',epistemic),jsonFile('audit.json',bundle.events||[]),jsonFile('receipts.json',receipts),jsonFile('limitations.json',graph.limitations),jsonFile('graph.json',{...graph,digest:graphSha256}),file('receipt.md',representations.md),file('receipt.xml',representations.xml),file('receipt.pdf',representations.pdf)];
  const checksums=core.map(entry=>`${entry.sha256}  ${entry.name}`).join('\n')+'\n';
  const manifest={schemaVersion:'2.1.0',generatedAt:document.generatedAt,generatedBy:actor.id,generatedForRole:actor.role,authorization:'same-as-read',subject:{type,id},graphSha256,evidenceDocumentSchemaVersion:document.schemaVersion,printableFormats:['pdf','xml','md','zip'],files:Object.fromEntries(core.map(entry=>[entry.name,{sha256:entry.sha256,bytes:entry.data.length}])),limitationsCount:graph.limitations.length,claimCount:graph.claims.length,lineageEventCount:document.lineage.length,reverseTraversal:Object.fromEntries(graph.claims.map(item=>[item.id,evidenceForClaim(graph,item.id).map(node=>node.id)]))};
  const files=[jsonFile('manifest.json',manifest),...core,file('checksums.sha256',checksums)];
  return{manifest,graph,document,representations,files,zip:zipStore(files),filename:safeFilename(`ictc-evidence-${type}-${id}.zip`)};
}
