import { asString, now, sha256, uniqueStrings } from '../domain.mjs';
export const DEFAULT_RISK_CONFIG=Object.freeze({likelihood:{min:1,max:5,labels:['Raro','Improbabile','Possibile','Probabile','Quasi certo']},impact:{min:1,max:5,labels:['Trascurabile','Limitato','Significativo','Grave','Critico']}});
const ASSESSMENTS=new Set(['inherent','residual']),TREATMENTS=new Set(['mitigate','accept','avoid','transfer']);
export function riskScore(likelihood,impact){const l=Number(likelihood),i=Number(impact);if(!Number.isFinite(l)||!Number.isFinite(i))throw Object.assign(new Error('Rating numerico richiesto'),{status:400,code:'risk-rating-invalid'});return Math.max(1,Math.min(5,l))*Math.max(1,Math.min(5,i));}
export function riskBand(score){return score>=20?'critical':score>=12?'high':score>=6?'medium':'low';}
export function normalizeRisk(input={},actor,{idFactory,proposalSource='human'}){const title=asString(input.title,1000);if(!title)throw Object.assign(new Error('Titolo scenario richiesto'),{status:400,code:'scenario-title-required'});const createdAt=now(),likelihood=Math.max(1,Math.min(5,Number(input.likelihood||3))),impact=Math.max(1,Math.min(5,Number(input.impact||3)));return{id:idFactory('risk'),title,description:asString(input.description,10000),objectIds:uniqueStrings(input.objectIds,100,200),controlIds:uniqueStrings(input.controlIds,100,200),actionIds:uniqueStrings(input.actionIds,100,200),state:'proposed',proposalSource:proposalSource==='ai'?'ai':'human',proposal:{likelihood,impact,rationale:asString(input.rationale,12000),confidence:Math.max(0,Math.min(1,Number(input.confidence||0)))},reviews:[],treatments:[],createdAt,createdBy:actor.id,updatedAt:createdAt};}
export function reviewRisk(item,input,actor){const assessmentType=asString(input.assessmentType,40).toLowerCase()||'inherent';if(!ASSESSMENTS.has(assessmentType))throw Object.assign(new Error('Tipo valutazione non valido'),{status:400,code:'risk-assessment-type-invalid'});if(assessmentType==='residual'&&!(item.reviews||[]).some(x=>(x.assessmentType||'inherent')==='inherent'))throw Object.assign(new Error('Valuta prima il rischio inerente'),{status:409,code:'risk-inherent-required'});const likelihood=Number(input.likelihood),impact=Number(input.impact);if(!Number.isFinite(likelihood)||!Number.isFinite(impact)||likelihood<1||likelihood>5||impact<1||impact>5)throw Object.assign(new Error('Likelihood e impact 1..5 richiesti'),{status:400,code:'risk-rating-required'});const reason=asString(input.reason,12000);if(!reason)throw Object.assign(new Error('Motivazione rating richiesta'),{status:400,code:'rating-reason-required'});const score=riskScore(likelihood,impact),review={assessmentType,likelihood,impact,score,band:riskBand(score),reason,controlRefs:uniqueStrings(input.controlRefs,100,500),by:actor.id,at:now(),proposalSha256:sha256(item.proposal)};item.reviews.push(review);item.state='reviewed';item.updatedAt=review.at;return item;}
export function effectiveRiskReview(item){const reviews=item.reviews||[];return [...reviews].reverse().find(x=>x.assessmentType==='residual')||[...reviews].reverse().find(x=>(x.assessmentType||'inherent')==='inherent')||null;}
export function decideRiskTreatment(item,input,actor){const review=effectiveRiskReview(item);if(!review)throw Object.assign(new Error('Valuta il rischio prima del trattamento'),{status:409,code:'risk-review-required'});const decision=asString(input.decision,40).toLowerCase();if(!TREATMENTS.has(decision))throw Object.assign(new Error('Trattamento rischio non valido'),{status:400,code:'risk-treatment-invalid'});const reason=asString(input.reason,12000);if(!reason)throw Object.assign(new Error('Motivazione trattamento richiesta'),{status:400,code:'risk-treatment-reason-required'});const treatment={decision,reason,owner:asString(input.owner,300),reviewAt:asString(input.reviewAt,80),by:actor.id,at:now(),assessmentSha256:sha256(review),assessmentType:review.assessmentType||'inherent'};item.treatments=[...(item.treatments||[]),treatment];item.updatedAt=treatment.at;return item;}
export function reviewedRisk(item){const r=effectiveRiskReview(item);return r?{riskId:item.id,title:item.title,assessmentType:r.assessmentType||'inherent',likelihood:r.likelihood,impact:r.impact,score:r.score,band:r.band,reviewedBy:r.by,reviewedAt:r.at,treatment:item.treatments?.at(-1)||null}:null;}
export function riskPortfolioProjection(state,actor){const items=state.grcRisks||[],reviewed=items.map(reviewedRisk).filter(Boolean),heatmap=Array.from({length:5},(_,li)=>Array.from({length:5},(_,ii)=>reviewed.filter(r=>r.likelihood===li+1&&r.impact===ii+1).length));return{schemaVersion:'2.0.0',authority:'human-reviewed-risk-projection',readOnly:actor.role==='auditor',assessmentBasis:'residual-preferred-otherwise-inherent',config:structuredClone(state.grcRiskConfig||DEFAULT_RISK_CONFIG),risks:structuredClone(items),reviewed,aiOverlay:items.filter(r=>r.proposalSource==='ai'&&!r.reviews?.length).map(r=>({riskId:r.id,title:r.title,...r.proposal})),heatmap,counts:{total:items.length,reviewed:reviewed.length,unreviewed:items.length-reviewed.length,untreated:reviewed.filter(r=>!r.treatment).length,mitigate:reviewed.filter(r=>r.treatment?.decision==='mitigate').length,high:reviewed.filter(r=>['high','critical'].includes(r.band)).length},limitations:['La heatmap consolidata usa solo valutazioni umane registrate e preferisce il residual rating quando disponibile.','Le proposte AI sono overlay informativi e non entrano nei KPI finché non vengono validate.','Il trattamento è una decisione umana distinta dal rating.']};}
