import { readFile } from 'node:fs/promises';
import { asString, now, sha256, uniqueStrings } from '../domain.mjs';
const taxonomy=JSON.parse(await readFile(new URL('../object-types.json',import.meta.url),'utf8'));
const OBJECT_TYPES=new Set(Object.values(taxonomy.groups).flat());
export const OBJECT_RELATION_KINDS=Object.freeze(['depends-on','hosted-on','connected-to','supports','provided-by','processes','stores','governed-by']);
export const MAPPING_STATES=Object.freeze(['proposed','mapped','gap','not-applicable','rejected']);
export function objectTaxonomyProjection(){return structuredClone(taxonomy);}
export function normalizeCriticality(value){const v=asString(value,32).toLowerCase();return ['low','medium','high','critical'].includes(v)?v:'medium';}
export function normalizeGrcObject(input={},actor,{idFactory}){const type=asString(input.type,120).toLowerCase();if(!OBJECT_TYPES.has(type))throw Object.assign(new Error(`Tipo oggetto non supportato: ${type||'<missing>'}`),{status:400,code:'grc-object-type-invalid'});const name=asString(input.name,500);if(!name)throw Object.assign(new Error('Nome oggetto richiesto'),{status:400,code:'grc-object-name-required'});const sourceAuthority=asString(input.sourceAuthority,300)||'ICTC working registry';const externalReference=asString(input.externalReference,1000);const owner=asString(input.owner,300);const createdAt=now();const base={id:idFactory('obj'),type,name,description:asString(input.description,5000),status:'candidate',criticality:normalizeCriticality(input.criticality),owner,sourceAuthority,externalReference,tags:uniqueStrings(input.tags,40,120),attributes:input.attributes&&typeof input.attributes==='object'&&!Array.isArray(input.attributes)?structuredClone(input.attributes):{},relations:[],reviews:[],createdAt,createdBy:actor.id,updatedAt:createdAt};base.version=1;base.versionSha256=sha256({id:base.id,type:base.type,name:base.name,criticality:base.criticality,owner:base.owner,sourceAuthority:base.sourceAuthority,externalReference:base.externalReference,relations:base.relations,version:base.version});return base;}
export function reviewGrcObject(object,input,actor){const decision=asString(input.decision,40).toLowerCase();if(!['active','rejected','retired'].includes(decision))throw Object.assign(new Error('Decisione oggetto non valida'),{status:400,code:'grc-object-decision-invalid'});const reason=asString(input.reason,5000);if(!reason)throw Object.assign(new Error('Motivazione richiesta'),{status:400,code:'grc-object-reason-required'});object.status=decision;object.reviews.push({decision,reason,by:actor.id,at:now(),subjectVersionSha256:object.versionSha256});object.updatedAt=now();return object;}
export function relateGrcObject(object,target,input,actor){const kind=asString(input.kind,80).toLowerCase();if(!OBJECT_RELATION_KINDS.includes(kind))throw Object.assign(new Error('Tipo relazione non supportato'),{status:400,code:'grc-relation-kind-invalid'});if(object.id===target.id)throw Object.assign(new Error('Relazione ricorsiva non consentita'),{status:400,code:'grc-relation-self'});if(object.relations.some(r=>r.targetId===target.id&&r.kind===kind))return object;object.relations.push({kind,targetId:target.id,note:asString(input.note,2000),by:actor.id,at:now()});object.version=Number(object.version||1)+1;object.updatedAt=now();object.versionSha256=sha256({id:object.id,type:object.type,name:object.name,criticality:object.criticality,owner:object.owner,sourceAuthority:object.sourceAuthority,externalReference:object.externalReference,relations:object.relations,version:object.version});return object;}
export function objectRegistryProjection(state,actor){const objects=(state.grcObjects||[]).map(item=>({...structuredClone(item),evidenceUrl:`/api/evidence/grc-object/${item.id}`}));return {schemaVersion:'1.0.0',authority:'runtime-working-registry',readOnly:actor.role==='auditor',taxonomy:objectTaxonomyProjection(),objects,counts:{total:objects.length,candidate:objects.filter(x=>x.status==='candidate').length,active:objects.filter(x=>x.status==='active').length,critical:objects.filter(x=>x.criticality==='critical'&&x.status==='active').length},limitations:["L'inventario e' un working registry e non dimostra completezza dell'ambiente reale.",'Source authority ed external reference dichiarano dove risiede la fonte autorevole quando esterna.']};}
export function normalizeMapping(input={},actor,{idFactory,proposalSource='human'}){const requirementLabel=asString(input.requirementLabel,2000);if(!requirementLabel)throw Object.assign(new Error('Elemento del declared universe richiesto'),{status:400,code:'mapping-requirement-required'});const createdAt=now();return{id:idFactory('map'),universe:asString(input.universe,500)||'declared-universe',requirementRef:asString(input.requirementRef,1000),requirementLabel,targetIds:uniqueStrings(input.targetIds,100,200),rationale:asString(input.rationale,10000),evidenceRefs:uniqueStrings(input.evidenceRefs,100,500),confidence:Math.max(0,Math.min(1,Number(input.confidence||0))),proposalSource:proposalSource==='ai'?'ai':'human',state:'proposed',decisions:[],createdAt,createdBy:actor.id,updatedAt:createdAt};}
export function decideMapping(mapping,input,actor){const decision=asString(input.decision,60).toLowerCase();if(!['mapped','gap','not-applicable','rejected'].includes(decision))throw Object.assign(new Error('Decisione mapping non valida'),{status:400,code:'mapping-decision-invalid'});const reason=asString(input.reason,10000);if(!reason)throw Object.assign(new Error('Motivazione mapping richiesta'),{status:400,code:'mapping-reason-required'});mapping.state=decision;mapping.decisions.push({decision,reason,by:actor.id,at:now(),proposalSha256:sha256({requirementRef:mapping.requirementRef,requirementLabel:mapping.requirementLabel,targetIds:mapping.targetIds,rationale:mapping.rationale,proposalSource:mapping.proposalSource})});mapping.updatedAt=now();return mapping;}
export function coverageProjection(state){const mappings=state.grcMappings||[];const decided=mappings.filter(x=>['mapped','gap','not-applicable'].includes(x.state));const applicable=decided.filter(x=>x.state!=='not-applicable');const mapped=applicable.filter(x=>x.state==='mapped');const gaps=applicable.filter(x=>x.state==='gap');const na=decided.filter(x=>x.state==='not-applicable');const unresolved=mappings.filter(x=>!['mapped','gap','not-applicable'].includes(x.state));return{schemaVersion:'1.0.0',authority:'runtime-projection',declared:mappings.length,decided:decided.length,mapped:mapped.length,gaps:gaps.length,notApplicable:na.length,unresolved:unresolved.length,coveragePercent:applicable.length?Number((mapped.length/applicable.length*100).toFixed(1)):null,mappings:structuredClone(mappings),limitations:['La copertura misura esclusivamente il declared universe registrato.','Not-applicable e unresolved restano distinti e non sono trattati come conformi.']};}
