import { timingSafeEqual } from 'node:crypto';
import { readFile, stat } from 'node:fs/promises';
import path from 'node:path';
import { ROLES, asString, canonicalJson, safeFilename, sha256 } from '../domain.mjs';
import { claimsFromHeaders, normalizeIdentitySettings, resolveIdentityClaims } from './identity.mjs';
import { TENANT_ROUTE_CONTEXT } from './tenant-authority.mjs';
import { assertPublicDemoConfiguration, publicDemoActor } from './public-demo.mjs';

const CSP="default-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; img-src 'self' data:; style-src 'self'; script-src 'self'; connect-src 'self'; font-src 'self'";
export function securityHeaders(extra={}){return{'x-content-type-options':'nosniff','x-frame-options':'DENY','referrer-policy':'no-referrer','permissions-policy':'camera=(), microphone=(), geolocation=(), payment=(), usb=()','cross-origin-opener-policy':'same-origin','cross-origin-resource-policy':'same-origin','content-security-policy':CSP,...extra};}
export function httpError(status,message,code='request-failed',details=null){return Object.assign(new Error(message),{status,code,details});}
export function isLoopbackAddress(value){const address=asString(value,200).toLowerCase();return address==='::1'||address==='localhost'||address==='127.0.0.1'||address.startsWith('127.')||address.startsWith('::ffff:127.');}
function secretMatches(received,expected){const left=Buffer.from(asString(received,1000));const right=Buffer.from(asString(expected,1000));return left.length===right.length&&left.length>0&&timingSafeEqual(left,right);}
export function assertSafeRuntimeBinding(host){const publicDemo=assertPublicDemoConfiguration(process.env);if(isLoopbackAddress(host))return;if(publicDemo.enabled)return;const trusted=process.env.ICTC_IDENTITY_MODE==='trusted-header';const explicitlyAllowed=process.env.ICTC_ALLOW_NETWORK_BIND==='1';const proxySecret=asString(process.env.ICTC_TRUSTED_PROXY_SECRET,1000);if(!trusted||!explicitlyAllowed||proxySecret.length<32)throw Object.assign(new Error('Binding di rete rifiutato: usa loopback, Public DEMO esplicita oppure trusted-header con ICTC_ALLOW_NETWORK_BIND=1 e un proxy secret di almeno 32 caratteri'),{code:'unsafe-network-bind'});}
function requestHost(value){return asString(value,500).trim().toLowerCase();}
export function assertBrowserWriteBoundary(request){const method=asString(request?.method,20).toUpperCase();if(!['POST','PUT','PATCH','DELETE'].includes(method))return;const fetchSite=asString(request.headers?.['sec-fetch-site'],40).toLowerCase();if(fetchSite==='cross-site')throw httpError(403,'Richiesta browser cross-site rifiutata','browser-cross-site-write');const origin=asString(request.headers?.origin,1000);if(origin){let originHost='';try{originHost=requestHost(new URL(origin).host);}catch{throw httpError(403,'Origin browser non valido','browser-origin-invalid');}const host=requestHost(request.headers?.host);if(!host||originHost!==host)throw httpError(403,'Origin browser non coerente con l’host ICTC','browser-origin-mismatch',{originHost,host});}}
function assertJsonWriteContentType(request,hasBody){if(!hasBody)return;const method=asString(request?.method,20).toUpperCase();if(!['POST','PUT','PATCH','DELETE'].includes(method))return;const contentType=asString(request.headers?.['content-type'],200).toLowerCase();if(!/^application\/(?:[a-z0-9.+-]+\+)?json(?:\s*;|$)/i.test(contentType))throw httpError(415,'Le scritture API con body richiedono application/json','json-content-type-required');}
function assertTenantRouteActor(request,actor){const context=request?.[TENANT_ROUTE_CONTEXT];if(!context?.enforceMembership)return actor;const tenant=context.tenant||{},actorGroups=new Set((actor.groups||actor.presentedIdentity?.groups||[]).map(value=>String(value))),subjectMatch=(tenant.subjects||[]).includes(actor.id),groupMatch=(tenant.groups||[]).some(group=>actorGroups.has(group));if(!subjectMatch&&!groupMatch)throw httpError(403,'Identità autorizzata non coerente con il tenant risolto','tenant-actor-membership-mismatch',{tenantId:tenant.id||null});return actor;}
export function actorFrom(request,permissions,identitySettings=null){const publicActor=publicDemoActor(permissions,process.env);if(publicActor)return publicActor;const identityMode=process.env.ICTC_IDENTITY_MODE==='trusted-header'?'trusted-header':'local';const remoteAddress=request.socket?.remoteAddress||'';const roleHeader=asString(request.headers['x-ictc-role'],20).toLowerCase();if(identityMode==='local'){if(!isLoopbackAddress(remoteAddress))throw httpError(403,'La modalità locale accetta soltanto connessioni loopback','local-identity-loopback-only');const role=ROLES.includes(roleHeader)?roleHeader:'user';const actorSwitchEnabled=process.env.ICTC_ALLOW_LOCAL_ACTOR_SWITCH==='1';const requestedActor=actorSwitchEnabled?asString(request.headers['x-ictc-actor-id'],160):'';return{id:requestedActor||`local-${role}`,role,identityMode,identityStrategy:'local',permissions:[...permissions[role]]};}const expectedSecret=asString(process.env.ICTC_TRUSTED_PROXY_SECRET,1000);if(expectedSecret.length<32)throw httpError(503,'Proxy di identità non configurato','trusted-proxy-not-configured');if(!secretMatches(request.headers['x-ictc-proxy-secret'],expectedSecret))throw httpError(401,'Richiesta non proveniente dal proxy attendibile','trusted-proxy-required');const config=normalizeIdentitySettings(identitySettings||{});if(config.strategy==='shibboleth')return assertTenantRouteActor(request,resolveIdentityClaims(claimsFromHeaders(request.headers,config),config,permissions));if(!ROLES.includes(roleHeader))throw httpError(401,'Ruolo identità non disponibile','identity-required');const actorId=asString(request.headers['x-ictc-actor-id'],160);if(!actorId)throw httpError(401,'Identificativo identità non disponibile','identity-required');const presentedIdentity=claimsFromHeaders(request.headers,config);return assertTenantRouteActor(request,{id:actorId,role:roleHeader,identityMode,identityStrategy:'legacy-role-header',presentedIdentity:presentedIdentity.subject?presentedIdentity:null,permissions:[...permissions[roleHeader]]});}
export function requirePermission(actor,permission,permissions){if(!permissions[actor.role]?.has(permission))throw httpError(403,'Operazione non consentita','forbidden');}
export function semanticCommandId(request,clientCommandId){const raw=asString(clientCommandId,200);if(!raw)return'';const inputSha256=request.__ictcCommandInputSha256||sha256(null);return sha256(canonicalJson({clientCommandId:raw,method:asString(request.method,20).toUpperCase(),url:asString(request.url,2000),inputSha256}));}
export function commandFrom(request){const rawRevision=request.headers['x-ictc-expected-revision'],clientCommandId=asString(request.headers['x-ictc-command-id'],200),inputSha256=request.__ictcCommandInputSha256||sha256(null);return{id:semanticCommandId(request,clientCommandId),expectedRevision:rawRevision==null||rawRevision===''?null:Number(rawRevision),metadata:{userAgent:asString(request.headers['user-agent'],500),clientCommandId:clientCommandId||null,commandInputSha256:inputSha256}};}
export function json(response,status,body){const payload=JSON.stringify(body);response.writeHead(status,securityHeaders({'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(payload),'cache-control':'no-store'}));response.end(payload);}
export async function bodyJson(request,limit=8_000_000){assertBrowserWriteBoundary(request);const chunks=[];let size=0;for await(const chunk of request){size+=chunk.length;if(size>limit)throw httpError(413,'Richiesta troppo grande','payload-too-large');chunks.push(chunk);}assertJsonWriteContentType(request,chunks.length>0);if(!chunks.length){request.__ictcCommandInputSha256=sha256(null);return{};}try{const parsed=JSON.parse(Buffer.concat(chunks).toString('utf8'));request.__ictcCommandInputSha256=sha256(canonicalJson(parsed));return parsed;}catch{throw httpError(400,'JSON non valido','invalid-json');}}
export function routeMatch(pathname,pattern){const keys=[];const regex=new RegExp(`^${pattern.replace(/:[A-Za-z0-9_]+/g,value=>{keys.push(value.slice(1));return'([^/]+)';})}$`),found=String(pathname||'').match(regex);if(!found)return null;const values=[];for(let index=0;index<keys.length;index++){let decoded;try{decoded=decodeURIComponent(found[index+1]);}catch{throw httpError(400,'Parametro URL non valido','route-param-invalid');}if(/[\/\\\0]/.test(decoded))throw httpError(400,'Parametro URL non valido','route-param-invalid');values.push(decoded);}return Object.fromEntries(keys.map((key,index)=>[key,values[index]]));}
export async function serveStatic(response,pathname,publicRoot,mime){const relative=pathname==='/'?'index.html':pathname.replace(/^\/+/, '');const filePath=path.resolve(publicRoot,relative);const root=path.resolve(publicRoot);if(!filePath.startsWith(`${root}${path.sep}`)&&filePath!==path.join(root,'index.html'))throw httpError(403,'Percorso non consentito','forbidden');try{if(!(await stat(filePath)).isFile())throw new Error('not-file');const content=await readFile(filePath);response.writeHead(200,securityHeaders({'content-type':mime.get(path.extname(filePath))||'application/octet-stream','content-length':content.length,'cache-control':'no-cache'}));response.end(content);}catch(error){if(error?.status)throw error;throw httpError(404,'Risorsa non trovata','not-found');}}
export function sendEvidence(response,bundle,type,idValue){response.writeHead(200,securityHeaders({'content-type':'application/json; charset=utf-8','content-disposition':`attachment; filename="ictc-${safeFilename(type)}-${safeFilename(idValue)}.json"`,'cache-control':'no-store'}));response.end(JSON.stringify(bundle,null,2));}
