import { id, canonicalJson, sha256 } from '../domain.mjs';
import { callJsonWithValidator } from '../ai.mjs';
import { assistEnvelope, adoptAssistEnvelope } from './assist-envelope.mjs';
import { grcProjection } from './grc-projection.mjs';
import { bodyJson, commandFrom, httpError, json, requirePermission, routeMatch } from './http.mjs';
import { procedureAdapterIds } from './procedure-adapters.mjs';
const PROCESS_IDS=new Set(procedureAdapterIds());
function visibleIncidents(state,actor){return (state.incidents||[]).filter(item=>actor.role==='admin'||actor.role==='auditor'||item.createdBy===actor.id);}
export function deterministicInsightBase(state,actor){const grc=grcProjection(state,actor),incidents=visibleIncidents(state,actor);const metrics=[
  {id:'monitoring-active',label:'Monitoraggi attivi',value:(state.missions||[]).filter(x=>x.state==='active').length,processId:'monitoring'},
  {id:'sources-review',label:'Fonti da verificare',value:(state.catalog||[]).filter(x=>x.state==='candidate').length,processId:'monitoring'},
  {id:'incidents-open',label:'Eventi aperti',value:incidents.filter(x=>!['submitted','closed'].includes(x.state)).length,processId:'incidents'},
  {id:'objects-active',label:'Oggetti attivi',value:grc.objects.counts.active,processId:'objects'},
  {id:'coverage-percent',label:'Copertura dichiarata',value:grc.coverage.coveragePercent,processId:'coverage'},
  {id:'coverage-gaps',label:'Gap',value:grc.coverage.gaps,processId:'coverage'},
  {id:'actions-open',label:'Azioni aperte',value:grc.actions.counts.open,processId:'actions'},
  {id:'actions-overdue',label:'Azioni scadute',value:grc.actions.counts.overdue,processId:'actions'},
  {id:'risks-high',label:'Rischi alti',value:grc.risks.counts.high,processId:'risks'},
  {id:'risks-unreviewed',label:'Rischi da validare',value:grc.risks.counts.unreviewed,processId:'risks'},
  {id:'assurance-open',label:'Assurance aperte',value:grc.assurance.counts.intake+grc.assurance.counts.review,processId:'assurance'}
];const signals=[];for(const metric of metrics){const n=Number(metric.value);if(Number.isFinite(n)&&n>0&&['sources-review','incidents-open','coverage-gaps','actions-overdue','risks-high','risks-unreviewed','assurance-open'].includes(metric.id))signals.push({metricId:metric.id,processId:metric.processId,kind:'attention',value:n});}
  const basis={schemaVersion:'3.1.0',authority:'runtime-deterministic-insights',metrics,signals,procedureIdAuthority:'procedure-adapter-registry',limitations:['I valori derivano soltanto dallo stato accessibile al ruolo corrente.','Copertura, rischio e assurance mantengono i propri limiti semantici; nessun KPI equivale a conformità.']};return{...basis,basisSha256:sha256(canonicalJson(basis))};}
function validateProposal(value){if(!value||typeof value!=='object')throw new Error('Insight AI non valido');const summary=String(value.summary||'').slice(0,1200);const observations=Array.isArray(value.observations)?value.observations.slice(0,6).map((item,index)=>{const processId=String(item.processId||'');if(!PROCESS_IDS.has(processId))throw new Error(`processId AI non valido: ${processId}`);return{id:String(item.id||`obs-${index+1}`).slice(0,80),title:String(item.title||'').slice(0,240),rationale:String(item.rationale||'').slice(0,1200),processId,sourceMetricIds:(Array.isArray(item.sourceMetricIds)?item.sourceMetricIds:[]).map(String).slice(0,8)};}):[];return{summary,observations};}
const PROMPT='Analizza esclusivamente i KPI deterministici forniti. Proponi una breve lettura operativa e fino a 6 osservazioni con processId e sourceMetricIds. Non inventare valori, non modificare priorita, non dichiarare conformita, applicabilita o decisioni. Restituisci summary e observations.';
export async function proposeInsight(settings,basis){const ai=await callJsonWithValidator(settings,'v3-dashboard-insight',PROMPT,{basis},validateProposal);const metricIds=new Set(basis.metrics.map(x=>x.id));for(const observation of ai.output.observations)if(observation.sourceMetricIds.some(id=>!metricIds.has(id)))throw Object.assign(new Error('Insight AI cita metriche fuori base deterministica'),{code:'ai-insight-metric-out-of-basis'});return assistEnvelope({purpose:'v3-dashboard-insight',subject:{type:'dashboard-basis',id:basis.basisSha256,version:basis.basisSha256},output:ai.output,trace:ai.trace,limitations:['L’AI propone interpretazioni della base deterministica e non può modificarne i valori.']});}
export function insightProjection(state,actor){const base=deterministicInsightBase(state,actor),proposals=(state.insightProposals||[]).filter(item=>item.scopeRole===actor.role||actor.role==='admin').slice(-8).reverse();return{schemaVersion:'3.1.0',base,proposals,latestValidated:proposals.find(item=>item.envelope?.adoption?.authority==='human')||null,authority:{metrics:'runtime-deterministic-insights',narrative:'ai-assist-only',validation:'human'}};}
export function createInsightRuntime({store,permissions}){return async function handle(request,response,pathname,actor){const method=request.method||'GET';if(method==='GET'&&pathname==='/api/insights'){requirePermission(actor,'read',permissions);json(response,200,insightProjection(store.snapshot(),actor));return true;}if(method==='POST'&&pathname==='/api/insights/propose'){requirePermission(actor,'manage-grc',permissions);await bodyJson(request);const snapshot=store.snapshot(),basis=deterministicInsightBase(snapshot,actor),envelope=await proposeInsight(snapshot.settings,basis),record={id:id('insight'),scopeRole:actor.role,createdBy:actor.id,createdAt:new Date().toISOString(),basisSha256:basis.basisSha256,envelope};const result=await store.mutate(actor,'insight.ai.proposed',{type:'insight-proposal',id:record.id},{basisSha256:basis.basisSha256,proposalSha256:envelope.proposalSha256},draft=>{draft.insightProposals||=[];draft.insightProposals.push(record);return record;},commandFrom(request));json(response,201,result);return true;}const params=routeMatch(pathname,'/api/insights/:id/validate');if(method==='POST'&&params){requirePermission(actor,'manage-grc',permissions);const input=await bodyJson(request),snapshot=store.snapshot(),record=(snapshot.insightProposals||[]).find(x=>x.id===params.id);if(!record)throw httpError(404,'Insight non trovato','not-found');const currentBasis=deterministicInsightBase(snapshot,actor);if(currentBasis.basisSha256!==record.basisSha256)throw httpError(409,'La base KPI è cambiata: genera una nuova proposta','insight-basis-stale');const adopted=adoptAssistEnvelope(record.envelope,{actor,reason:input.reason});const result=await store.mutate(actor,'insight.human.validated',{type:'insight-proposal',id:record.id},{reason:input.reason,basisSha256:record.basisSha256,proposalSha256:record.envelope.proposalSha256},draft=>{const target=(draft.insightProposals||[]).find(x=>x.id===record.id);target.envelope=adopted;target.validatedAt=adopted.adoption.at;target.validatedBy=actor.id;return target;},commandFrom(request));json(response,200,result);return true;}return false;};}
