import { canonicalDecisionProjection } from './decision-projection.mjs';
import { canonicalEpistemicProjection } from './epistemic-projection.mjs';
import { grcProjection } from './grc-projection.mjs';

const TYPE_PROCESS=Object.freeze({'source':'monitoring','incident':'incidents','grc-object':'objects','mapping':'coverage','action':'actions','risk':'risks','assurance-case':'assurance'});
function incidentVisible(actor,item){return actor.role==='admin'||actor.role==='auditor'||item.createdBy===actor.id;}
function subjectRows(state,actor){const grc=grcProjection(state,actor),rows=[];for(const item of state.catalog||[])rows.push(['source',item.id,item]);for(const item of state.incidents||[])if(incidentVisible(actor,item))rows.push(['incident',item.id,item]);for(const item of grc.objects.objects||[])rows.push(['grc-object',item.id,item]);for(const item of grc.coverage.mappings||[])rows.push(['mapping',item.id,item]);for(const item of grc.actions.actions||[])rows.push(['action',item.id,item]);for(const item of grc.risks.risks||[])rows.push(['risk',item.id,item]);for(const item of grc.assurance.cases||[])rows.push(['assurance-case',item.id,item]);return rows;}
function originalFor(type,item){if(type==='source')return{kind:item.internalReference?'internal-master-reference':'observed-source',reference:item.internalReference||item.sourceUrl||item.identifier||null,digest:item.currentVersion?.sha256||item.sha256||null};if(type==='incident')return{kind:'preserved-narrative',reference:item.originalNarrative||null,digest:item.originalSha256||null,attachments:(item.attachments||[]).map(x=>x.sha256)};if(type==='grc-object')return{kind:'governed-object-intake',reference:item.externalReference||item.name,digest:item.versionSha256||item.sha256||null,sourceAuthority:item.sourceAuthority||null};if(type==='mapping')return{kind:'declared-requirement',reference:item.requirementRef||item.requirementLabel,digest:item.versionSha256||item.sha256||null};if(type==='action')return{kind:'action-origin',reference:item.origin||item.title,digest:item.versionSha256||item.sha256||null};if(type==='risk')return{kind:'risk-scenario',reference:item.description||item.title,digest:item.versionSha256||item.sha256||null};if(type==='assurance-case')return{kind:'assurance-request',reference:item.source||item.title,digest:item.requestSha256||null};return{kind:'unknown',reference:null,digest:null};}
function assistFor(type,item){const traces=[];for(const [name,value] of Object.entries(item||{}))if((name==='aiTrace'||name.endsWith('Trace'))&&value&&typeof value==='object')traces.push({field:name,purpose:value.purpose||null,inputSha256:value.inputSha256||null,outputSha256:value.outputSha256||null,limitations:value.limitations||[]});if(type==='incident'&&item.analysis)traces.push({field:'analysis',purpose:item.analysisTrace?.purpose||'incident-analysis',inputSha256:item.analysisTrace?.inputSha256||null,outputSha256:item.analysisTrace?.outputSha256||null,limitations:item.analysisTrace?.limitations||[]});return traces;}
export function procedureTraceGraph(state,actor){const decisions=canonicalDecisionProjection(state,actor).records||[],epistemic=canonicalEpistemicProjection(state,actor).records||[],rows=subjectRows(state,actor);const traces=rows.map(([type,id,item])=>{const processId=TYPE_PROCESS[type],subjectDecisions=decisions.filter(x=>x.subject?.id===id),subjectEpistemic=epistemic.filter(x=>x.subject?.id===id),events=(state.audit||[]).filter(x=>x.subject?.id===id).map(x=>({eventId:x.id,revision:x.revision,action:x.action,at:x.at,actorId:x.actorId,inputSha256:x.inputSha256,resultSha256:x.resultSha256,stateSha256:x.stateSha256,hash:x.hash})),assist=assistFor(type,item),original=originalFor(type,item),evidenceUrl=`/api/evidence/${type==='source'?'catalog':type}/${id}.zip`;return{schemaVersion:'3.0.0',id:`trace:${type}:${id}`,processId,subject:{type,id},original,assist,decisions:subjectDecisions.map(x=>({id:x.id,kind:x.kind,checkpoint:x.checkpoint,authority:x.authority,subjectVersion:x.subjectVersion,at:x.at,by:x.by})),epistemic:subjectEpistemic,auditEvents:events,evidenceUrl,relationGrammar:'runtime-process-kernel',completeness:{original:Boolean(original.reference||original.digest),assist:assist.length>0,humanDecision:subjectDecisions.length>0,audit:events.length>0,evidence:true},limitations:['La traccia ricostruisce record ICTC accessibili al ruolo; non dimostra completezza del mondo esterno.']};});return{schemaVersion:'3.0.0',authority:'runtime-procedure-trace',traces,counts:{subjects:traces.length,withOriginal:traces.filter(x=>x.completeness.original).length,withAssist:traces.filter(x=>x.completeness.assist).length,withHumanDecision:traces.filter(x=>x.completeness.humanDecision).length},limitations:['La proiezione non crea nuove evidenze o decisioni: collega soltanto authority già canoniche.']};}
export function procedureTraceFor(state,actor,type,id){return procedureTraceGraph(state,actor).traces.find(x=>x.subject.type===type&&x.subject.id===id)||null;}
