const PROCEDURES = new Set(['monitoring','incidents','objects','coverage','actions','risks','assurance']);
const clean=value=>value==null?null:String(value).trim()||null;
const unique=values=>[...new Set((Array.isArray(values)?values:values?[values]:[]).map(clean).filter(Boolean))];
function iso(value){const date=value instanceof Date?value:new Date(value||Date.now());if(Number.isNaN(date.getTime()))throw Object.assign(new Error('Projection asOf non valido'),{code:'projection-asof-invalid'});return date.toISOString();}
export function normalizeScopeRef(input='actor-visible'){if(typeof input==='string')return Object.freeze({mode:clean(input)||'actor-visible',organization:null,unit:null,legalEntity:null,jurisdictions:Object.freeze([]),participants:Object.freeze([])});const value=input&&typeof input==='object'?input:{};return Object.freeze({mode:clean(value.mode)||'actor-visible',organization:clean(value.organization||value.organizationId),unit:clean(value.unit||value.unitId),legalEntity:clean(value.legalEntity||value.legalEntityId),jurisdictions:Object.freeze(unique(value.jurisdictions||value.jurisdiction)),participants:Object.freeze(unique(value.participants))});}
export function projectionContext(actor={id:'system',role:'admin'},options={}){const asOf=iso(options.asOf),scopeRef=normalizeScopeRef(options.scopeRef||options.scope||'actor-visible');return Object.freeze({schemaVersion:'1.1.0',actor:Object.freeze({id:String(actor?.id||'unknown'),role:String(actor?.role||'user')}),scope:String(options.scope||scopeRef.mode||'actor-visible'),scopeRef,asOf,asOfMs:Date.parse(asOf),stateRevision:options.stateRevision==null?null:Number(options.stateRevision),procedurePolicyVersion:options.procedurePolicyVersion||null,accessPolicyVersion:options.accessPolicyVersion||'procedure-contract-1.3'});}
export function normalizeProjectionContext(actor,context={}){return context?.asOfMs!=null&&context?.actor&&context?.scopeRef?context:projectionContext(actor,context);}
export function isDue(value,context){if(!value)return false;const when=Date.parse(value);return Number.isFinite(when)&&when<=context.asOfMs;}
function actionAssignedTo(item,actorId){return item?.ownerRef?.id===actorId||item?.owner===actorId||item?.createdBy===actorId;}
export function scopeRefMatches(recordScope,contextScope){if(!recordScope)return true;const record=normalizeScopeRef(recordScope),ctx=normalizeScopeRef(contextScope);for(const key of['organization','unit','legalEntity'])if(ctx[key]&&record[key]&&ctx[key]!==record[key])return false;if(ctx.jurisdictions.length&&record.jurisdictions.length&&!record.jurisdictions.some(value=>ctx.jurisdictions.includes(value)))return false;return true;}
export function canReadProcedureRecord(procedureId,item,context,kind='record'){if(!PROCEDURES.has(procedureId))return false;if(!scopeRefMatches(item?.scopeRef,context.scopeRef))return false;const actor=context.actor;if(actor.role==='admin'||actor.role==='auditor')return true;if(actor.role!=='user')return false;if(item?.scopeRef?.participants?.length&&!item.scopeRef.participants.includes(actor.id))return false;if(procedureId==='incidents'||procedureId==='assurance')return item?.createdBy===actor.id;if(procedureId==='actions')return actionAssignedTo(item,actor.id);if(procedureId==='monitoring'&&kind==='mission')return item?.createdBy===actor.id;return true;}
export function filterProcedureRecords(procedureId,records,context,kind='record'){return(records||[]).filter(item=>canReadProcedureRecord(procedureId,item,context,kind));}
export function projectionBasis(context){return{actorId:context.actor.id,actorRole:context.actor.role,scope:context.scope,scopeRef:structuredClone(context.scopeRef),asOf:context.asOf,stateRevision:context.stateRevision,procedurePolicyVersion:context.procedurePolicyVersion,accessPolicyVersion:context.accessPolicyVersion};}
