const PROCEDURES = new Set(['monitoring','incidents','objects','coverage','actions','risks','assurance']);
function iso(value){const date=value instanceof Date?value:new Date(value||Date.now());if(Number.isNaN(date.getTime()))throw Object.assign(new Error('Projection asOf non valido'),{code:'projection-asof-invalid'});return date.toISOString();}
export function projectionContext(actor={id:'system',role:'admin'},options={}){const asOf=iso(options.asOf);return Object.freeze({schemaVersion:'1.0.0',actor:Object.freeze({id:String(actor?.id||'unknown'),role:String(actor?.role||'user')}),scope:String(options.scope||'actor-visible'),asOf,asOfMs:Date.parse(asOf),stateRevision:options.stateRevision==null?null:Number(options.stateRevision),procedurePolicyVersion:options.procedurePolicyVersion||null,accessPolicyVersion:options.accessPolicyVersion||'procedure-contract-1.3'});}
export function normalizeProjectionContext(actor,context={}){return context?.asOfMs!=null&&context?.actor?context:projectionContext(actor,context);}
export function isDue(value,context){if(!value)return false;const when=Date.parse(value);return Number.isFinite(when)&&when<=context.asOfMs;}
function actionAssignedTo(item,actorId){return item?.ownerRef?.id===actorId||item?.owner===actorId||item?.createdBy===actorId;}
export function canReadProcedureRecord(procedureId,item,context,kind='record'){if(!PROCEDURES.has(procedureId))return false;const actor=context.actor;if(actor.role==='admin'||actor.role==='auditor')return true;if(actor.role!=='user')return false;if(procedureId==='incidents'||procedureId==='assurance')return item?.createdBy===actor.id;if(procedureId==='actions')return actionAssignedTo(item,actor.id);if(procedureId==='monitoring'&&kind==='mission')return item?.createdBy===actor.id;return true;}
export function filterProcedureRecords(procedureId,records,context,kind='record'){return(records||[]).filter(item=>canReadProcedureRecord(procedureId,item,context,kind));}
export function projectionBasis(context){return{actorId:context.actor.id,actorRole:context.actor.role,scope:context.scope,asOf:context.asOf,stateRevision:context.stateRevision,procedurePolicyVersion:context.procedurePolicyVersion,accessPolicyVersion:context.accessPolicyVersion};}
