import { backup as sqliteBackup, DatabaseSync } from 'node:sqlite';
import { createCipheriv, createDecipheriv, createHmac, randomBytes, timingSafeEqual } from 'node:crypto';
import { mkdir, mkdtemp, readFile, rename, rm, stat, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { canonicalJson, sha256 } from '../domain.mjs';
import { verifyStateIntegrity } from '../integrity-binding.mjs';
import { RuntimeStore } from '../runtime-store.mjs';

const text=(v,max=1000)=>String(v??'').trim().slice(0,max);
function fail(code,message,details=null){throw Object.assign(new Error(message),{code,details});}
function safeName(value){const v=text(value,200);if(!/^[a-zA-Z0-9._-]+$/.test(v)||v==='.'||v==='..')fail('recovery-name-invalid','Nome recovery non valido');return v;}
export function environmentRecoveryKeyProvider(env=process.env){return async()=>{const raw=text(env.ICTC_RECOVERY_KEY_BASE64,5000),key=Buffer.from(raw,'base64');if(key.length!==32)fail('recovery-key-missing','ICTC_RECOVERY_KEY_BASE64 deve contenere una chiave di 32 byte');return{key,keyId:text(env.ICTC_RECOVERY_KEY_ID,200)||'env-local-key',source:'environment'};};}
function deriveKey(key,label){return createHmac('sha256',key).update(`ictc-recovery-key-v1:${label}`).digest();}
function encryptBuffer(buffer,key,aad){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv);cipher.setAAD(Buffer.from(aad));const ciphertext=Buffer.concat([cipher.update(buffer),cipher.final()]),tag=cipher.getAuthTag();return{ciphertext,iv:iv.toString('base64'),tag:tag.toString('base64')};}
function decryptBuffer(ciphertext,key,entry){const decipher=createDecipheriv('aes-256-gcm',key,Buffer.from(entry.iv,'base64'));decipher.setAAD(Buffer.from(entry.aad));decipher.setAuthTag(Buffer.from(entry.tag,'base64'));return Buffer.concat([decipher.update(ciphertext),decipher.final()]);}
function signatureMatches(received,expected){const a=Buffer.from(text(received,128).toLowerCase()),b=Buffer.from(text(expected,128).toLowerCase());return a.length===b.length&&a.length>0&&timingSafeEqual(a,b);}
function backupSnapshot(dbPath){let db;try{db=new DatabaseSync(dbPath);const row=db.prepare('SELECT revision,payload FROM snapshot WHERE id=1').get();if(!row)fail('recovery-snapshot-missing','Snapshot SQLite assente nel recovery source');const state=JSON.parse(row.payload);state.audit=db.prepare('SELECT event_json FROM audit ORDER BY revision').all().map(item=>JSON.parse(item.event_json));state.subjectVersions=[];state.epistemicSteps=[];if(Number(row.revision)!==Number(state.revision))fail('recovery-snapshot-revision-mismatch','Revision snapshot incoerente');const integrity=verifyStateIntegrity(state);if(!integrity.ok||!integrity.stateBound)fail('recovery-source-integrity-invalid','Il recovery point non può essere creato da uno stato non integro o non bound',{integrity});return{state,integrity};}finally{try{db?.close();}catch{}}}
function attachmentInventory(state){const byId=new Map(),all=[...(state.contributions||[]).flatMap(item=>item.attachments||[]),...(state.incidents||[]).flatMap(item=>item.attachments||[])];for(const metadata of all){const id=safeName(metadata?.id),digest=text(metadata?.sha256,64).toLowerCase();if(!/^[a-f0-9]{64}$/.test(digest))fail('recovery-attachment-metadata-invalid','Digest allegato non valido',{attachmentId:id});const clean=metadata?.storage?.state==='clean'||['scan-clean','accepted-by-policy'].includes(metadata?.trust?.state),folder=clean?'attachments':'quarantine',entry={id,sha256:digest,bytes:Number(metadata?.bytes||0),logicalPath:`${folder}/${id}`},prior=byId.get(id);if(prior&&(prior.sha256!==entry.sha256||prior.logicalPath!==entry.logicalPath))fail('recovery-attachment-metadata-conflict','Metadati allegato confliggenti',{attachmentId:id});byId.set(id,entry);}return[...byId.values()].sort((a,b)=>a.id.localeCompare(b.id));}
async function referencedAttachment(root,entry){const pathname=path.join(root,...entry.logicalPath.split('/'));let buffer;try{buffer=await readFile(pathname);}catch(error){if(error.code==='ENOENT')fail('recovery-attachment-namespace-mismatch','Allegato referenziato assente dal namespace dichiarato',{attachmentId:entry.id,logicalPath:entry.logicalPath});throw error;}if(sha256(buffer)!==entry.sha256||(entry.bytes>0&&buffer.length!==entry.bytes))fail('recovery-attachment-missing-or-mismatch','Allegato referenziato con digest/size non coerente',{attachmentId:entry.id,sha256:entry.sha256,logicalPath:entry.logicalPath});return buffer;}
export async function createEncryptedRecoveryPoint({store,tenantId='local-default',destinationRoot,keyProvider=environmentRecoveryKeyProvider(),nowValue=new Date()}){
  if(!store?.persistence?.db)fail('recovery-store-required','Store inizializzato richiesto');const started=Date.now(),{key,keyId,source}=await keyProvider();if(!Buffer.isBuffer(key)||key.length!==32)fail('recovery-key-invalid','Recovery key non valida');const encryptionKey=deriveKey(key,'object-encryption'),manifestKey=deriveKey(key,'manifest-authentication');
  const stamp=nowValue.toISOString().replace(/[:.]/g,'-'),name=`ictc-${safeName(tenantId)}-${stamp}`,finalDir=path.join(destinationRoot,name),staging=`${finalDir}.staging-${process.pid}-${randomBytes(4).toString('hex')}`,plainRoot=await mkdtemp(path.join(os.tmpdir(),'ictc-recovery-plain-'));await mkdir(staging,{recursive:true,mode:0o700});
  const plainDb=path.join(plainRoot,'state.sqlite'),entries=[];
  try{
    await sqliteBackup(store.persistence.db,plainDb);const snapshot=backupSnapshot(plainDb),inventory=attachmentInventory(snapshot.state),encryptedDir=path.join(staging,'objects');await mkdir(encryptedDir,{recursive:true,mode:0o700});let ordinal=0;
    const writeObject=async(logicalPath,buffer,declaredSha=null)=>{const plainSha=declaredSha||sha256(buffer);if(sha256(buffer)!==plainSha)fail('recovery-object-digest-mismatch','Oggetto recovery non coincide con inventory',{logicalPath});const aad=`ictc-recovery-v1\n${tenantId}\n${logicalPath}\n${plainSha}`,encrypted=encryptBuffer(buffer,encryptionKey,aad),storedName=`${String(ordinal++).padStart(6,'0')}.enc`;await writeFile(path.join(encryptedDir,storedName),encrypted.ciphertext,{mode:0o600});entries.push({logicalPath,storedName,bytes:buffer.length,sha256:plainSha,ciphertextSha256:sha256(encrypted.ciphertext),algorithm:'aes-256-gcm',iv:encrypted.iv,tag:encrypted.tag,aad});};
    await writeObject('state.sqlite',await readFile(plainDb));for(const item of inventory)await writeObject(item.logicalPath,await referencedAttachment(store.root,item),item.sha256);
    const createdAt=nowValue.toISOString(),integrity=snapshot.integrity,body={schemaVersion:'1.2.0',tenantId,createdAt,keyId,keySource:source,keyDerivation:'hmac-sha256-v1',applicationRevision:Number(snapshot.state.revision||0),auditHead:integrity.head||null,canonicalStateSha256:integrity.canonicalStateSha256,stateBoundToAuditHead:true,attachmentInventoryCount:inventory.length,entries};const signature=createHmac('sha256',manifestKey).update(canonicalJson(body)).digest('hex'),manifest={...body,manifestAuthentication:{algorithm:'hmac-sha256',signature}};await writeFile(path.join(staging,'manifest.json'),JSON.stringify(manifest,null,2)+'\n',{mode:0o600});await mkdir(destinationRoot,{recursive:true,mode:0o700});await rename(staging,finalDir);return{schemaVersion:'1.2.0',ok:true,path:finalDir,tenantId,createdAt,revision:body.applicationRevision,auditHead:body.auditHead,files:entries.length,attachmentInventoryCount:inventory.length,bytes:entries.reduce((s,e)=>s+e.bytes,0),durationMs:Date.now()-started,keyId,claimBoundary:'Repository-local encrypted recovery point. Approved RPO/RTO and off-host durability require deployment evidence.'};
  }catch(error){await rm(staging,{recursive:true,force:true}).catch(()=>{});throw error;}finally{await rm(plainRoot,{recursive:true,force:true}).catch(()=>{});}
}
export async function restoreEncryptedRecoveryPoint({sourceDir,targetRuntimeDir,keyProvider=environmentRecoveryKeyProvider(),StoreClass=RuntimeStore,nowValue=new Date()}){
  const started=Date.now(),manifest=JSON.parse(await readFile(path.join(sourceDir,'manifest.json'),'utf8')),{key,keyId}=await keyProvider();if(!Buffer.isBuffer(key)||key.length!==32)fail('recovery-key-invalid','Recovery key non valida');if(manifest.keyId!==keyId)fail('recovery-key-id-mismatch','Key id non corrispondente al recovery point');const derived=manifest.keyDerivation==='hmac-sha256-v1',encryptionKey=derived?deriveKey(key,'object-encryption'):key,manifestKey=derived?deriveKey(key,'manifest-authentication'):key,signature=manifest.manifestAuthentication?.signature,body=structuredClone(manifest);delete body.manifestAuthentication;const expected=createHmac('sha256',manifestKey).update(canonicalJson(body)).digest('hex');if(!signatureMatches(signature,expected))fail('recovery-manifest-auth-failed','Manifest recovery non autenticato');
  try{await stat(targetRuntimeDir);fail('recovery-target-exists','Il target restore deve essere assente');}catch(error){if(error.code&&error.code!=='ENOENT')throw error;if(!error.code&&error.message)throw error;}
  const staging=`${targetRuntimeDir}.restore-${process.pid}-${randomBytes(4).toString('hex')}`;await mkdir(staging,{recursive:true,mode:0o700});
  try{const seen=new Set(),storedNames=new Set();for(const entry of manifest.entries||[]){if(!['state.sqlite'].includes(entry.logicalPath)&&!/^(attachments|quarantine)\/[a-zA-Z0-9][a-zA-Z0-9._-]*$/.test(entry.logicalPath))fail('recovery-entry-invalid','Entry recovery non valida',{logicalPath:entry.logicalPath});if(seen.has(entry.logicalPath))fail('recovery-entry-duplicate','Entry recovery duplicata',{logicalPath:entry.logicalPath});seen.add(entry.logicalPath);const storedName=safeName(entry.storedName);if(storedNames.has(storedName))fail('recovery-entry-storage-duplicate','Oggetto recovery riutilizzato da più entry',{storedName});storedNames.add(storedName);const ciphertext=await readFile(path.join(sourceDir,'objects',storedName));if(sha256(ciphertext)!==entry.ciphertextSha256)fail('recovery-ciphertext-digest-mismatch','Ciphertext recovery corrotto',{logicalPath:entry.logicalPath});const plain=decryptBuffer(ciphertext,encryptionKey,entry);if(sha256(plain)!==entry.sha256||plain.length!==Number(entry.bytes))fail('recovery-plaintext-digest-mismatch','Plaintext recovery non coincide con il manifest',{logicalPath:entry.logicalPath});const output=path.join(staging,...entry.logicalPath.split('/'));await mkdir(path.dirname(output),{recursive:true,mode:0o700});await writeFile(output,plain,{mode:0o600});}if(!seen.has('state.sqlite'))fail('recovery-database-missing','Recovery point senza state.sqlite');
    const restored=await new StoreClass(staging).init();const integrity=restored.verifyChain(),snapshot=restored.snapshot();if(Number(snapshot.revision)!==Number(manifest.applicationRevision))fail('recovery-revision-mismatch','Revision restore non coincide con manifest');if((integrity.head||null)!==(manifest.auditHead||null))fail('recovery-audit-head-mismatch','Audit head restore non coincide con manifest');if((integrity.canonicalStateSha256||restored.canonicalStateSha256())!==manifest.canonicalStateSha256)fail('recovery-state-digest-mismatch','Digest stato restore non coincide con manifest');if(!integrity.ok||!integrity.stateBound)fail('recovery-integrity-invalid','Restore non supera la verifica di integrità');restored.close();await rename(staging,targetRuntimeDir);const completedAt=new Date().toISOString(),rtoMs=Date.now()-started,rpoSecondsAtRestore=Math.max(0,Math.round((nowValue.getTime()-new Date(manifest.createdAt).getTime())/1000));return{schemaVersion:manifest.schemaVersion||'1.1.0',ok:true,tenantId:manifest.tenantId,targetRuntimeDir,startedAt:new Date(started).toISOString(),completedAt,rtoMs,rpoSecondsAtRestore,revision:manifest.applicationRevision,auditHead:manifest.auditHead,verified:true,claimBoundary:'Measured repository restore evidence; approved enterprise RTO/RPO still requires deployment drill evidence.'};
  }catch(error){await rm(staging,{recursive:true,force:true}).catch(()=>{});throw error;}
}
