import { sha256 } from '../domain.mjs';
import { canReadProcedureRecord,normalizeProjectionContext,projectionBasis } from './projection-context.mjs';
import { procedureIdForSubject } from './procedure-adapters.mjs';
import { resolveCanonicalSubjectAfter } from './subject-adapters.mjs';
import { reconcileReviewNeeds } from './review-need-ledger.mjs';
const DIGEST_KEYS=Object.freeze(['versionSha256','requestSha256','currentFormulationSha256','subjectVersionSha256','proposalSha256','stateSha256','completionSha256','assessmentSha256','answersSha256','draftSha256','formulationSha256','observationSha256','sourceObservationSha256']);export const SUBJECT_VERSION_PROJECTION_LIMIT=5000;
function digestBindings(payload){const out=[],seen=new Set(),add=(kind,value)=>{const s=typeof value==='string'&&/^[a-f0-9]{64}$/i.test(value)?value.toLowerCase():'';if(!s||seen.has(`${kind}:${s}`))return;seen.add(`${kind}:${s}`);out.push({kind,sha256:s});};for(const key of DIGEST_KEYS)add(key,payload?.[key]);for(const listName of['decisions','reviews','verifications','treatments','approvals','formulationVersions','observations'])for(const item of payload?.[listName]||[])for(const key of DIGEST_KEYS)add(`${listName}.${key}`,item?.[key]);return out;}
function previousOccurrence(state,subject){return[...(state.subjectVersions||[])].reverse().find(item=>item.subject?.type===subject.type&&item.subject?.id===subject.id)||null;}
function appendOccurrence(state,{subject,payload,actor,action,at,predecessorResolver}){const resolved=resolveCanonicalSubjectAfter(state,subject,payload),procedureId=resolved?.procedureId||procedureIdForSubject(subject?.type);if(!procedureId)return null;const clean=structuredClone(resolved?.payload??payload);if(!clean||typeof clean!=='object'||Array.isArray(clean))return null;const actualSubject=resolved?.subject||{type:String(subject.type),id:String(subject.id)},payloadSha256=sha256(clean),predecessor=previousOccurrence(state,actualSubject)||predecessorResolver?.(actualSubject)||null,revision=Number(state.revision||0),ordinal=state.subjectVersions.length+1,id=`sv-${actualSubject.type}-${actualSubject.id}-${revision}-${ordinal}`,record={schemaVersion:'2.1.0',id,revision,procedureId,subject:actualSubject,predecessorId:predecessor?.id||null,payloadSha256,digestBindings:digestBindings(clean),payload:clean,createdAt:at,createdBy:actor?.id||'system',action:action||null,sourceAuthority:clean.sourceAuthority||clean.origin?.authority||null,semanticSchemaVersion:resolved?.semanticSchemaVersion||'1.0.0',canonicalizationVersion:resolved?.canonicalizationVersion||'legacy-result-fallback-v1',materializationMode:resolved?'after-state':'legacy-result-fallback'};state.subjectVersions.push(record);return record;}
export function appendSubjectVersion(state,{subject,payload,actor,action,at,predecessorResolver=null}){if(!subject?.type||!subject?.id)return null;state.subjectVersions||=[];reconcileReviewNeeds(state,{at,revision:Number(state.revision||0),policyVersion:'dependency-review@1',context:{asOf:at,stateRevision:state.revision},causeMode:'business',causation:'business-state-change'});const primary=appendOccurrence(state,{subject,payload,actor,action,at,predecessorResolver});if(payload?.requirementScope?.id)appendOccurrence(state,{subject:{type:'requirement-scope',id:payload.requirementScope.id},payload:payload.requirementScope,actor,action,at,predecessorResolver});return primary;}
export function resolveSubjectVersion(state,value){const s=String(value||'').toLowerCase();if(!s)return null;return(state.subjectVersions||[]).find(item=>String(item.id).toLowerCase()===s||item.payloadSha256===s||(item.digestBindings||[]).some(binding=>binding.sha256===s))||null;}
export function subjectVersionIndexProjection(state,actor,context={}){const ctx=normalizeProjectionContext(actor,{...context,stateRevision:context.stateRevision??state.revision??null}),visible=(state.subjectVersions||[]).filter(item=>canReadProcedureRecord(item.procedureId,item.payload||{},ctx,item.subject?.type==='mission'?'mission':'record')),limit=Math.max(1,Math.min(Number(context.limit)||SUBJECT_VERSION_PROJECTION_LIMIT,SUBJECT_VERSION_PROJECTION_LIMIT)),selected=visible.slice(-limit),records=selected.map(item=>({id:item.id,revision:item.revision,procedureId:item.procedureId,subject:item.subject,predecessorId:item.predecessorId||null,payloadSha256:item.payloadSha256,digestBindings:item.digestBindings,createdAt:item.createdAt,createdBy:item.createdBy,action:item.action,sourceAuthority:item.sourceAuthority,semanticSchemaVersion:item.semanticSchemaVersion||null,canonicalizationVersion:item.canonicalizationVersion||null,materializationMode:item.materializationMode||'legacy'}));return{schemaVersion:'2.1.0',authority:'subject-version-working-index',projection:projectionBasis(ctx),count:records.length,totalCount:visible.length,omittedCount:0,truncatedForProjection:visible.length>records.length,retention:{mode:'bounded-working-index-over-append-storage',silentDeletion:false,projectionLimit:SUBJECT_VERSION_PROJECTION_LIMIT,canonicalHistoryLocation:'sqlite.subject_version',archivalPolicy:'deployment-policy'},records,limitations:['Version occurrence identity is distinct from payload digest; repeated attestation or observation may create a new occurrence referencing identical content.','This projection is a bounded working index; canonical append history may contain older occurrences not materialized in the current process state.','Projection limiting and working-set eviction never delete canonical version history.']};}
