const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const S={data:null,view:'radar',session:null,filter:'open',trace:'trace-monitoring'};
const titles={radar:'Radar normativo',changes:'Novità da valutare',sources:'Fonti e scouting',coverage:'Copertura interna',matters:'Eventi e quasi incidenti',trace:'Tracce operative'};
async function api(path,options={}){const r=await fetch(path,{headers:{'content-type':'application/json'},...options});const b=await r.json();if(!r.ok)throw Error(b.error||r.status);return b}
function status(x){return ({observed:'Osservato',verified:'Verificato','attention-required':'Richiede attenzione','awaiting-human-review':'Da valutare','human-reviewed':'Revisionato','human-owned':'Owner confermato','ai-proposed':'Proposta AI',candidate:'Candidato',mapped:'Mappato','operating-declared':'Operatività dichiarata','evidence-available':'Evidenza disponibile'})[x]||x}
function card(o){return `<button class="item" data-envelope="${o.id}"><span class="state ${o.epistemicStatus}">${status(o.epistemicStatus)}</span><b>${esc(o.label)}</b><p>${esc(o.statement)}</p><small>${esc(o.nextAction||o.limitations?.[0]||'')}</small></button>`}
function radar(){const v=S.data.views,h=v.headline;return `<section><header><span class="kicker">Esiti ricostruiti localmente</span><h1>Radar normativo</h1><p>Mostra osservazioni, differenze e review. Non produce un giudizio automatico di conformità.</p></header><article class="hero" data-envelope="${h.id}"><div><span class="kicker">Esito deterministico</span><h2>${esc(h.label)}</h2><p>${esc(h.statement)}</p><button data-nav="changes">Apri la coda</button></div><div class="orb"><strong>${h.data.observedChannels}</strong><span>di ${h.data.configured}<br>canali osservati</span></div></article><div class="grid">${v.proofTiles.map(card).join('')}</div><article class="chain"><span>Origine</span><i>→</i><span>Osservazione</span><i>→</i><span>Differenza</span><i>→</i><span>Proposta</span><i>→</i><span>Decisione</span></article></section>`}
function changes(){const all=S.data.views.findingCards, list=S.filter==='open'?all.filter(x=>x.epistemicStatus==='awaiting-human-review'):all;return `<section><header><span class="kicker">Decisioni umane</span><h1>Novità da valutare</h1><p>Materialità e impatto restano indeterminati finché una persona non conclude la review.</p></header><div class="filters"><button data-change-filter="open">Aperte</button><button data-change-filter="all">Tutte</button></div><div class="list">${list.map(card).join('')||'<p>Nessun esito.</p>'}</div></section>`}
function sources(){return `<section><header><span class="kicker">Perimetro conoscitivo</span><h1>Fonti e scouting</h1><p>Le fonti proposte e i job automatici convergono nella stessa catena, ma solo una review umana modifica il perimetro attivo.</p><button id="addSource">Aggiungi fonte</button></header><h2>Fonti</h2><div class="list">${S.data.views.sourceCards.map(card).join('')}</div><h2>Job</h2><div class="list">${S.data.views.jobCards.map(o=>card(o)+`<button data-run-job="${o.data.id}">Esegui job</button>`).join('')}</div></section>`}
function coverage(){return `<section><header><span class="kicker">Livello astratto</span><h1>Copertura interna</h1><p>Collega obblighi e famiglie di controllo senza confondere mapping ed efficacia.</p></header><div class="list">${S.data.views.coverageCards.map(card).join('')}</div></section>`}
function matters(){return `<section><header><span class="kicker">Segnalazioni e incidenti</span><h1>Eventi</h1><p>Narrazione, fatti, ipotesi, owner e RACI restano separati e tracciati.</p><button id="addMatter">Segnala evento</button></header><div class="list">${S.data.views.matterCards.map(o=>card(o)+(o.epistemicStatus!=='human-owned'?`<button data-confirm-owner="${o.data.id}">Conferma owner</button>`:'')).join('')}</div></section>`}
function trace(){const t=S.data.views.traceCards.find(x=>x.id===S.trace)||S.data.views.traceCards[0];return `<section><header><span class="kicker">Audit trail locale</span><h1>Traccia operativa</h1><p>Ogni riga usa gli stessi oggetti runtime della dashboard.</p></header><div class="trace-tabs">${S.data.views.traceCards.map(x=>`<button data-trace-id="${x.id}">${esc(x.label)}</button>`).join('')}</div><pre>${t.data.steps.map((x,i)=>`${String(i+1).padStart(2,'0')} [${x.status[0]}] ${x.label}\n   ${x.statement}\n   ${x.statusLabel} · ${x.producer}`).join('\n   |\n')}</pre></section>`}
function render(){const f={radar,changes,sources,coverage,matters,trace}[S.view];$('#topTitle').textContent=titles[S.view];$('#main').innerHTML=f();bindDynamic()}
function bindDynamic(){$$('[data-nav]').forEach(b=>b.onclick=()=>{S.view=b.dataset.nav;render()});$$('[data-envelope]').forEach(b=>b.onclick=()=>openDetail(find(b.dataset.envelope)));$$('[data-change-filter]').forEach(b=>b.onclick=()=>{S.filter=b.dataset.changeFilter;render()});$$('[data-trace-id]').forEach(b=>b.onclick=()=>{S.trace=b.dataset.traceId;render()});$$('[data-run-job]').forEach(b=>b.onclick=()=>runJob(b.dataset.runJob));$$('[data-confirm-owner]').forEach(b=>b.onclick=()=>confirmOwner(b.dataset.confirmOwner));$('#addSource')?.addEventListener('click',()=>$('#sourceDialog').showModal());$('#addMatter')?.addEventListener('click',()=>$('#matterDialog').showModal())}
function all(){const v=S.data.views;return [v.headline,...v.proofTiles,...v.sourceCards,...v.findingCards,...v.jobCards,...v.coverageCards,...v.matterCards,...v.traceCards]}
function find(id){return all().find(x=>x.id===id)}
function openDetail(o){if(!o)return;$('#detailContent').innerHTML=`<article class="detail"><button onclick="this.closest('dialog').close()">×</button><span class="state ${o.epistemicStatus}">${status(o.epistemicStatus)}</span><h2>${esc(o.label)}</h2><p>${esc(o.statement)}</p><h3>Come lo sappiamo</h3><p>${esc(o.producer.type)} · ${esc(o.producer.id)}</p><h3>Limiti</h3><ul>${o.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Receipt</h3><code>${esc(o.receiptRef||'non disponibile')}</code>${o.claimClass==='source-record'&&o.epistemicStatus==='candidate'?`<footer><button data-review="accepted">Includi</button><button data-review="rejected">Non includere</button></footer>`:''}${o.claimClass==='finding'&&o.epistemicStatus==='awaiting-human-review'?`<footer><button data-finding-review="relevant">Rilevante</button><button data-finding-review="not-relevant">Non rilevante</button></footer>`:''}</article>`;$('#detailSheet').showModal();$$('[data-review]').forEach(b=>b.onclick=()=>reviewSource(o.data.id,b.dataset.review));$$('[data-finding-review]').forEach(b=>b.onclick=()=>reviewFinding(o.data.id,b.dataset.findingReview))}
async function refresh(){S.data=await api('/api/bootstrap');render()}
async function reviewSource(id,outcome){await api(`/api/sources/${id}/review`,{method:'POST',body:JSON.stringify({outcome,reviewedBy:'utente'})});$('#detailSheet').close();await refresh()}
async function reviewFinding(id,outcome){await api(`/api/findings/${id}/review`,{method:'POST',body:JSON.stringify({outcome,reviewedBy:'utente'})});$('#detailSheet').close();await refresh()}
async function runJob(id){await api(`/api/scout-jobs/${id}/run`,{method:'POST',body:JSON.stringify({simulateChange:true,actor:'scheduler'})});await refresh()}
async function confirmOwner(id){const o=S.data.matters.find(x=>x.id===id);await api(`/api/matters/${id}/confirm-owner`,{method:'POST',body:JSON.stringify({owner:o.owner,raci:o.raci,actor:'utente'})});await refresh()}
async function submitSource(e){e.preventDefault();const d=new FormData(e.currentTarget),file=d.get('file'),p={title:d.get('title'),url:d.get('url'),notes:d.get('notes'),submittedBy:'utente'};if(file?.size){p.fileName=file.name;p.mimeType=file.type;p.contentBase64=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(file)})}await api('/api/sources',{method:'POST',body:JSON.stringify(p)});e.currentTarget.reset();$('#sourceDialog').close();await refresh()}
async function submitMatter(e){e.preventDefault();const d=new FormData(e.currentTarget);await api('/api/matters',{method:'POST',body:JSON.stringify({title:d.get('title'),summary:d.get('summary'),kind:d.get('kind'),severity:d.get('severity'),reportedBy:'utente'})});e.currentTarget.reset();$('#matterDialog').close();await refresh()}
async function ask(e){e.preventDefault();const q=$('#assistantQuestion').value.trim();if(!q)return;const r=await api('/api/assistant',{method:'POST',body:JSON.stringify({sessionId:S.session,scope:S.view,question:q})});$('#assistantMessages').insertAdjacentHTML('beforeend',`<article><small>Proposta AI</small><p>${esc(r.answer)}</p><small>${esc(r.limitations.join(' · '))}</small></article>`);$('#assistantQuestion').value=''}
function bind(){$$('[data-nav]').forEach(b=>b.onclick=()=>{S.view=b.dataset.nav;render()});$('#newSourceTop').onclick=()=>$('#sourceDialog').showModal();$('#newMatterTop').onclick=()=>$('#matterDialog').showModal();$('#openAssistant').onclick=()=>$('#appShell').classList.add('ai-open');$('#closeAssistant').onclick=()=>$('#appShell').classList.remove('ai-open');$('#sourceForm').onsubmit=submitSource;$('#matterForm').onsubmit=submitMatter;$('#assistantForm').onsubmit=ask;$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#commandInput').oninput=e=>{$('#commandResults').innerHTML=all().filter(x=>JSON.stringify(x).toLowerCase().includes(e.target.value.toLowerCase())).slice(0,8).map(card).join('')};$('#openCommand').onclick=()=>$('#commandDialog').showModal()}
(async()=>{S.data=await api('/api/bootstrap');S.session=(await api('/api/session',{method:'POST',body:'{}'})).sessionId;bind();render();const i=await api('/api/runtime/integrity');$('#integrityState').textContent=i.ok?`Catena verificata · ${i.eventCount} eventi`:'Catena non verificata'})().catch(e=>{$('#main').innerHTML=`<h1>ICTC non disponibile</h1><p>${esc(e.message)}</p>`});
