const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const S={data:null,view:'radar',sessionId:null,changeFilter:'open',traceId:'trace-monitoring',sourceMode:'link',lastFocus:null,activeObjectId:null};
const titles={radar:'Radar normativo',changes:'Novità da valutare',sources:'Fonti e scouting',coverage:'Copertura interna',matters:'Eventi e quasi incidenti',trace:'Tracce operative'};
const labels={observed:'Osservato',verified:'Verificato',failed:'Non verificato','attention-required':'Richiede attenzione','awaiting-human-review':'Da valutare','human-reviewed':'Revisionato','human-owned':'Owner confermato','ai-proposed':'Proposta AI',candidate:'Candidato',mapped:'Mappato','operating-declared':'Operatività dichiarata','evidence-available':'Evidenza disponibile'};
async function api(path,opt={}){const r=await fetch(path,{headers:{'content-type':'application/json',...(opt.headers||{})},...opt});let b;try{b=await r.json()}catch{b={error:`Risposta non JSON (${r.status})`}}if(!r.ok)throw Error(b.error||`Errore HTTP ${r.status}`);return b}
function setActivity(stage,title,detail,tone='neutral'){const e=$('#handshake'),icons={ready:'🤲',working:'🫱',reading:'🫲',done:'🤝',error:'!'};e.dataset.tone=tone;$('.hands',e).textContent=icons[stage]||icons.ready;$('strong',e).textContent=title;$('small',e).textContent=detail}
async function perform(label,fn){setActivity('working',label,'Operazione in corso');try{const x=await fn(),h=x?.receipt?.hash||x?.receipt?.ledgerHead;setActivity('done','Operazione registrata',h?`Receipt ${h.slice(0,12)}…`:'Readback completato');return x}catch(e){setActivity('error','Operazione non completata',e.message,'error');console.error(e);return null}}
const status=v=>labels[v]||v;
const card=(o,cls='')=>`<button type="button" class="item ${cls}" data-envelope="${esc(o.id)}"><span class="state ${esc(o.epistemicStatus)}">${esc(status(o.epistemicStatus))}</span><b>${esc(o.label)}</b><p>${esc(o.statement)}</p><small>${esc(o.nextAction||o.limitations?.[0]||'')}</small></button>`;
function all(){const v=S.data.views;return[v.headline,...v.proofTiles,...v.sourceCards,...v.findingCards,...v.jobCards,...v.coverageCards,...v.matterCards,...v.traceCards]}
const find=id=>all().find(x=>x.id===id);
function radar(){const{headline:h,proofTiles:p}=S.data.views;return `<section aria-labelledby="pageTitle"><header class="page-header"><span class="kicker">Esiti ricostruiti localmente</span><h1 id="pageTitle">Radar normativo</h1><p>Mostra osservazioni, differenze e review. Non produce un giudizio automatico di conformità.</p></header><article class="hero"><div><span class="kicker">Esito deterministico</span><h2>${esc(h.label)}</h2><p>${esc(h.statement)}</p><div class="hero-actions"><button type="button" class="button secondary" data-nav="changes">Apri la coda</button><button type="button" class="button secondary" data-envelope="${esc(h.id)}">Come lo sappiamo</button></div></div><div class="orb" aria-label="${h.data.observedChannels} di ${h.data.configured} canali osservati"><strong>${h.data.observedChannels}</strong><span>di ${h.data.configured}<br>canali osservati</span></div></article><div class="grid">${p.map(card).join('')}</div><article class="chain" aria-label="Catena epistemica"><span>Origine</span><i>→</i><span>Osservazione</span><i>→</i><span>Differenza</span><i>→</i><span>Proposta</span><i>→</i><span>Decisione</span></article></section>`}
function changes(){const a=S.data.views.findingCards,f=S.changeFilter==='open'?a.filter(x=>x.epistemicStatus==='awaiting-human-review'):a;return `<section aria-labelledby="pageTitle"><header class="page-header"><span class="kicker">Decisioni umane</span><h1 id="pageTitle">Novità da valutare</h1><p>Materialità e impatto restano indeterminati finché una persona non conclude la review.</p></header><div class="filters" role="group" aria-label="Filtro novità"><button type="button" data-change-filter="open" aria-pressed="${S.changeFilter==='open'}">Aperte</button><button type="button" data-change-filter="all" aria-pressed="${S.changeFilter==='all'}">Tutte</button></div><div class="list">${f.map(card).join('')||'<p class="empty-state">Nessun esito nella vista selezionata.</p>'}</div></section>`}
function sources(){const jobs=S.data.views.jobCards.map(o=>`<div class="item-row">${card(o)}<button type="button" class="button secondary row-action" data-run-job="${esc(o.data.id)}">Esegui job</button></div>`).join('');return `<section aria-labelledby="pageTitle"><header class="page-header with-action"><div><span class="kicker">Perimetro conoscitivo</span><h1 id="pageTitle">Fonti e scouting</h1><p>Solo una review umana modifica il perimetro attivo.</p></div><button type="button" class="button primary" id="addSource">Aggiungi fonte</button></header><h2>Fonti</h2><div class="list">${S.data.views.sourceCards.map(card).join('')}</div><h2>Job programmati</h2><div class="list">${jobs}</div></section>`}
function coverage(){return `<section aria-labelledby="pageTitle"><header class="page-header"><span class="kicker">Livello astratto</span><h1 id="pageTitle">Copertura interna</h1><p>Collega obblighi e famiglie di controllo senza confondere mapping ed efficacia.</p></header><div class="list">${S.data.views.coverageCards.map(card).join('')}</div></section>`}
function matters(){const m=S.data.views.matterCards.map(o=>`<div class="item-row">${card(o)}${o.epistemicStatus!=='human-owned'?`<button type="button" class="button secondary row-action" data-confirm-owner="${esc(o.data.id)}">Conferma owner</button>`:''}</div>`).join('');return `<section aria-labelledby="pageTitle"><header class="page-header with-action"><div><span class="kicker">Segnalazioni e incidenti</span><h1 id="pageTitle">Eventi</h1><p>Narrazione, fatti, ipotesi, owner e RACI restano separati e tracciati.</p></div><button type="button" class="button primary" id="addMatter">Segnala evento</button></header><div class="list">${m}</div></section>`}
function trace(){const t=S.data.views.traceCards.find(x=>x.id===S.traceId)||S.data.views.traceCards[0],lines=t.data.steps.map((x,i)=>`${String(i+1).padStart(2,'0')} [${x.status[0]}] ${x.label}\n   ${x.statement}\n   ${x.statusLabel} · ${x.producer}`).join('\n   |\n');return `<section aria-labelledby="pageTitle"><header class="page-header"><span class="kicker">Audit trail locale</span><h1 id="pageTitle">Traccia operativa</h1><p>Ogni riga usa gli stessi oggetti runtime della dashboard.</p></header><div class="trace-tabs" role="tablist">${S.data.views.traceCards.map(x=>`<button type="button" role="tab" aria-selected="${x.id===t.id}" data-trace-id="${esc(x.id)}">${esc(x.label)}</button>`).join('')}</div><pre tabindex="0" aria-label="${esc(t.label)}">${esc(lines)}</pre></section>`}
function updateNav(){$$('[data-nav]').forEach(b=>{const a=b.dataset.nav===S.view;b.classList.toggle('active',a);if(b.closest('.primary-nav'))a?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')});$('#appShell').dataset.view=S.view;$('#topTitle').textContent=titles[S.view];if(!S.activeObjectId)$('#capsuleLabel').textContent=titles[S.view]}
function render(){const r={radar,changes,sources,coverage,matters,trace};$('#main').innerHTML=r[S.view]();updateNav();bindDynamic()}
function navigate(v,focus=true){if(!titles[v])return;S.view=v;S.activeObjectId=null;render();if(focus)$('#main').focus({preventScroll:true})}
function bindDynamic(){const main=$('#main');$$('[data-nav]',main).forEach(b=>b.onclick=()=>navigate(b.dataset.nav));$$('[data-envelope]',main).forEach(b=>b.onclick=()=>openDetail(b.dataset.envelope));$$('[data-change-filter]',main).forEach(b=>b.onclick=()=>{S.changeFilter=b.dataset.changeFilter;render()});$$('[data-trace-id]',main).forEach(b=>b.onclick=()=>{S.traceId=b.dataset.traceId;render()});$$('[data-run-job]',main).forEach(b=>b.onclick=()=>runJob(b.dataset.runJob));$$('[data-confirm-owner]',main).forEach(b=>b.onclick=()=>confirmOwner(b.dataset.confirmOwner));$('#addSource')?.addEventListener('click',openSourceDialog);$('#addMatter')?.addEventListener('click',openMatterDialog)}
function details(o){const d=o.data||{};if(o.claimClass==='source-record')return `<dl><dt>Origine</dt><dd>${esc(d.origin)}</dd><dt>Ecosistema</dt><dd>${esc(d.ecosystemId)}</dd><dt>Stato review</dt><dd>${esc(d.reviewState)}</dd></dl>`;if(o.claimClass==='matter-state')return `<dl><dt>Owner</dt><dd>${esc(d.owner)}</dd><dt>Stato</dt><dd>${esc(d.workflowState)}</dd><dt>Prossima azione</dt><dd>${esc(d.nextAction)}</dd></dl>`;return `<pre>${esc(JSON.stringify(d,null,2))}</pre>`}
function closeDetail(){$('#detailSheet').close();S.activeObjectId=null;$('#capsuleLabel').textContent=titles[S.view];S.lastFocus?.focus?.()}
function openDetail(id){const o=find(id);if(!o)return;S.lastFocus=document.activeElement;S.activeObjectId=id;$('#capsuleLabel').textContent=o.label;$('#detailContent').innerHTML=`<article class="detail-article"><header><div><span class="state ${esc(o.epistemicStatus)}">${esc(status(o.epistemicStatus))}</span><h2 id="detailTitle">${esc(o.label)}</h2></div><button type="button" class="icon-button" id="closeDetail" aria-label="Chiudi dettaglio">×</button></header><p class="detail-statement">${esc(o.statement)}</p>${details(o)}<section class="provenance"><h3>Come lo sappiamo</h3><dl><dt>Produttore</dt><dd>${esc(o.producer)}</dd><dt>Input</dt><dd>${esc((o.inputRefs||[]).join(', ')||'Nessuno dichiarato')}</dd><dt>Tempo</dt><dd>${esc(o.observedAt)}</dd><dt>Receipt</dt><dd>${esc(o.receiptRef||'Non ancora disponibile')}</dd></dl></section><section class="limits"><h3>Limiti</h3><ul>${(o.limitations||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>${o.claimClass==='source-record'&&o.epistemicStatus!=='human-reviewed'?`<footer><button type="button" class="button primary" data-review="include">Includi</button><button type="button" class="button secondary" data-review="exclude">Escludi</button></footer>`:''}${o.claimClass==='change-finding'&&o.epistemicStatus==='awaiting-human-review'?`<footer><button type="button" class="button primary" data-finding-review="relevant">Rilevante</button><button type="button" class="button secondary" data-finding-review="not-relevant">Non rilevante</button></footer>`:''}</article>`;if($('#commandDialog').open)$('#commandDialog').close();$('#detailSheet').showModal();$('#closeDetail').onclick=closeDetail;$$('[data-review]',$('#detailContent')).forEach(b=>b.onclick=()=>reviewSource(o.data.id,b.dataset.review));$$('[data-finding-review]',$('#detailContent')).forEach(b=>b.onclick=()=>reviewFinding(o.data.id,b.dataset.findingReview))}
async function refresh(){S.data=await api('/api/bootstrap');render();const i=await api('/api/runtime/integrity');$('#integrityState').textContent=i.ok?`Catena verificata · ${i.eventCount} eventi`:`Catena non verificata · ${i.reason||'controllo fallito'}`}
const post=(url,body)=>api(url,{method:'POST',body:JSON.stringify(body)});
async function reviewSource(id,outcome){await perform('Registrazione review fonte',async()=>{const r=await post(`/api/sources/${id}/review`,{outcome,reviewedBy:'utente-demo'});closeDetail();await refresh();return r})}
async function reviewFinding(id,outcome){await perform('Registrazione review novità',async()=>{const r=await post(`/api/findings/${id}/review`,{outcome,reviewedBy:'utente-demo'});closeDetail();await refresh();return r})}
async function runJob(id){await perform('Esecuzione scouting',async()=>{const r=await post(`/api/scout-jobs/${id}/run`,{simulateChange:true,actor:'scheduler-manuale'});await refresh();return r})}
async function confirmOwner(id){const m=S.data.matters.find(x=>x.id===id);if(!m)return;await perform('Conferma owner e RACI',async()=>{const r=await post(`/api/matters/${id}/confirm-owner`,{owner:m.owner,raci:m.raci,actor:'utente-demo'});await refresh();return r})}
function setSourceMode(mode){S.sourceMode=mode;const link=mode==='link';$('#urlField').hidden=!link;$('#fileField').hidden=link;$('#sourceUrl').required=link;$('#sourceFile').required=!link;$$('[data-source-mode]').forEach(b=>{const a=b.dataset.sourceMode===mode;b.classList.toggle('active',a);b.setAttribute('aria-pressed',String(a))})}
function openSourceDialog(){S.lastFocus=document.activeElement;setSourceMode('link');$('#sourceResult').hidden=true;$('#sourceDialog').showModal();$('#sourceTitleInput').focus()}
function openMatterDialog(){S.lastFocus=document.activeElement;$('#matterDialog').showModal();$('#matterTitleInput').focus()}
async function submitSource(e){e.preventDefault();const f=e.currentTarget,d=new FormData(f),file=d.get('file'),p={title:d.get('title'),url:S.sourceMode==='link'?d.get('url'):'',notes:d.get('notes'),submittedBy:'utente-demo'};if(S.sourceMode==='file'&&file?.size){p.fileName=file.name;p.mimeType=file.type;p.contentBase64=await new Promise((ok,no)=>{const r=new FileReader;r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(file)})}await perform('Acquisizione fonte locale',async()=>{const r=await post('/api/sources',p);$('#sourceResult').hidden=false;$('#sourceResult').innerHTML=`<strong>Fonte candidata registrata</strong><span>Receipt ${esc(r.receipt.hash.slice(0,16))}…</span>`;f.reset();setSourceMode('link');await refresh();return r})}
async function submitMatter(e){e.preventDefault();const f=e.currentTarget,d=new FormData(f);await perform('Registrazione evento',async()=>{const r=await post('/api/matters',{title:d.get('title'),summary:d.get('summary'),kind:d.get('kind'),severity:d.get('severity'),reportedBy:'utente-demo'});f.reset();$('#matterDialog').close();await refresh();return r})}
async function askAssistant(e){e.preventDefault();const q=$('#assistantQuestion').value.trim();if(!q)return;await perform('Lettura capsula locale',async()=>{const r=await post('/api/assistant',{sessionId:S.sessionId,scope:S.view,objectId:S.activeObjectId,question:q});$('#assistantMessages').insertAdjacentHTML('beforeend',`<article class="message ai-message"><small>Proposta AI</small><p>${esc(r.answer)}</p><small>${esc(r.limitations.join(' · '))}</small></article>`);$('#assistantQuestion').value='';return r})}
function openAssistant(){S.lastFocus=document.activeElement;$('#appShell').classList.add('ai-open');$('#assistantPanel').setAttribute('aria-hidden','false');$('#openAssistant').setAttribute('aria-expanded','true');$('#openAssistantTop').setAttribute('aria-expanded','true');setTimeout(()=>$('#assistantQuestion').focus(),160)}
function closeAssistant(){$('#appShell').classList.remove('ai-open');$('#assistantPanel').setAttribute('aria-hidden','true');$('#openAssistant').setAttribute('aria-expanded','false');$('#openAssistantTop').setAttribute('aria-expanded','false');S.lastFocus?.focus?.()}
function searchOutcomes(q){const n=q.trim().toLocaleLowerCase('it'),r=(n?all().filter(x=>`${x.label} ${x.statement} ${x.claimClass}`.toLocaleLowerCase('it').includes(n)):all()).slice(0,10);$('#commandResults').innerHTML=r.length?r.map(x=>card(x,'command-result')).join(''):'<p class="empty-state">Nessun oggetto corrispondente.</p>';$$('[data-envelope]',$('#commandResults')).forEach(b=>b.onclick=()=>openDetail(b.dataset.envelope))}
function openCommand(){S.lastFocus=document.activeElement;$('#commandDialog').showModal();$('#commandInput').value='';searchOutcomes('');$('#commandInput').focus()}
function closeCommand(){$('#commandDialog').close();S.lastFocus?.focus?.()}
function toggleMotion(){const r=document.documentElement.dataset.motion!=='reduced';document.documentElement.dataset.motion=r?'reduced':'system';$('#motionToggle').setAttribute('aria-pressed',String(r));$('#motionToggle').textContent=r?'Movimento: ridotto':'Movimento: sistema'}
function bindStatic(){$$('.sidebar [data-nav]').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));$('#newSourceTop').onclick=openSourceDialog;$('#newMatterTop').onclick=openMatterDialog;$('#openAssistant').onclick=$('#openAssistantTop').onclick=openAssistant;$('#closeAssistant').onclick=closeAssistant;$('#sourceForm').onsubmit=submitSource;$('#matterForm').onsubmit=submitMatter;$('#assistantForm').onsubmit=askAssistant;$('#openCommand').onclick=openCommand;$('#closeCommand').onclick=closeCommand;$('#commandInput').oninput=e=>searchOutcomes(e.target.value);$('#motionToggle').onclick=toggleMotion;$$('[data-close]').forEach(b=>b.onclick=()=>{$(`#${b.dataset.close}`).close();S.lastFocus?.focus?.()});$$('[data-source-mode]').forEach(b=>b.onclick=()=>setSourceMode(b.dataset.sourceMode));document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#commandDialog').open?closeCommand():openCommand()}})}
async function bootstrap(){setActivity('reading','Ricostruzione locale','Lettura del seed e del ledger');S.data=await api('/api/bootstrap');S.sessionId=(await post('/api/session',{})).sessionId;bindStatic();render();const i=await api('/api/runtime/integrity');$('#integrityState').textContent=i.ok?`Catena verificata · ${i.eventCount} eventi`:`Catena non verificata · ${i.reason||'controllo fallito'}`;setActivity('ready','Pronto','Nessuna azione in corso')}
bootstrap().catch(e=>{$('#main').innerHTML=`<section class="fatal"><h1>ICTC non disponibile</h1><p>${esc(e.message)}</p><button type="button" class="button primary" id="retryBootstrap">Riprova</button></section>`;$('#retryBootstrap')?.addEventListener('click',()=>location.reload());setActivity('error','Avvio non completato',e.message,'error')});
