import crypto from 'node:crypto';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
const ROOT=path.resolve(new URL('..',import.meta.url).pathname), SEED=path.join(ROOT,'data/seed.json'), LEDGER=path.join(ROOT,'runtime/ledger.jsonl');
export const sha256=v=>crypto.createHash('sha256').update(v).digest('hex');
export const nowIso=()=>new Date().toISOString();
export async function readSeed(){return JSON.parse(await readFile(SEED,'utf8'))}
export async function readLedger(){try{return (await readFile(LEDGER,'utf8')).split('\n').filter(Boolean).map(JSON.parse)}catch(e){if(e.code==='ENOENT')return[];throw e}}
export function verifyLedger(events){let prev='GENESIS';for(const e of events){const {hash,...base}=e;if(e.previousHash!==prev||sha256(JSON.stringify(base))!==hash)return{ok:false,eventCount:events.length,reason:`invalid event ${e.id}`};prev=hash}return{ok:true,eventCount:events.length,head:prev}}
export async function appendEvent(type,payload,actor='system',producer='runtime'){await mkdir(path.dirname(LEDGER),{recursive:true});const events=await readLedger(),previousHash=events.at(-1)?.hash||'GENESIS';const base={id:crypto.randomUUID(),type,actor,producer,at:nowIso(),previousHash,payload};const event={...base,hash:sha256(JSON.stringify(base))};events.push(event);await writeFile(LEDGER,events.map(JSON.stringify).join('\n')+'\n');const readback=(await readLedger()).at(-1);if(readback.hash!==event.hash)throw Error('readback failed');return{event,receipt:{eventId:event.id,eventType:type,hash:event.hash,previousHash,persistedAt:event.at,readbackVerified:true,ledgerHead:event.hash}}}
function apply(seed,events){const s=structuredClone(seed);for(const e of events){const p=e.payload;if(e.type==='source.proposed'){s.sources.push(p.source);s.findings.push(p.finding)}if(e.type==='source.reviewed'){const x=s.sources.find(v=>v.id===p.sourceId);if(x){x.reviewState=p.outcome==='accepted'?'reviewed':'rejected';x.lifecycle=p.outcome==='accepted'?'active':'candidate';x.receiptRef=e.hash}}if(e.type==='finding.reviewed'){const x=s.findings.find(v=>v.id===p.findingId);if(x){x.humanState=p.outcome==='relevant'?'reviewed-relevant':'reviewed-not-relevant';x.receiptRef=e.hash}}if(e.type==='scout.run.completed'){const j=s.scoutJobs.find(v=>v.id===p.job.id);if(j)Object.assign(j,p.job);s.findings.push(p.finding)}if(e.type==='matter.reported')s.matters.push(p.matter);if(e.type==='matter.owner.confirmed'){const x=s.matters.find(v=>v.id===p.matterId);if(x){x.owner=p.owner;x.raci=p.raci;x.workflowState='owned';x.receiptRef=e.hash}}}return s}
const env=(id,label,statement,claimClass,epistemicStatus,producer,inputs,limitations,data={},nextAction=null,receiptRef=null,observedAt=null)=>({id,label,statement,claimClass,epistemicStatus,producer:{type:producer,id:producer},inputs:inputs.map(id=>({type:'record',id})),limitations,nextAction,receiptRef,observedAt,reviewedAt:null,data});
function sourceEnv(x){const st=x.lifecycle==='candidate'?'candidate':x.reviewState==='reviewed'?'human-reviewed':x.reviewState==='change-awaiting-review'?'attention-required':'observed';return env(`source-${x.id}`,x.title,`${x.authorityClass}; ultimo controllo ${x.lastCheckedAt||'non disponibile'}.`,'source-record',st,'source-projection-v2',[x.id],['La presenza nel catalogo non prova applicabilità o completezza.'],x,x.reviewState.includes('awaiting')?'Completare la review':null,x.receiptRef||null,x.lastCheckedAt)}
function findingEnv(x){const st=x.humanState==='awaiting-review'?'awaiting-human-review':x.humanState.startsWith('reviewed')?'human-reviewed':'observed';return env(`finding-${x.id}`,x.findingType==='new-document'?'Nuovo documento osservato':'Differenza osservata',x.statement,'finding',st,x.aiProposal?'deterministic-diff-plus-ai-proposal':'deterministic-diff',[x.id,x.sourceId].filter(Boolean),['Materialità e applicabilità non sono determinate automaticamente.'],x,st==='awaiting-human-review'?'Valutare rilevanza e impatto':null,x.receiptRef||null,x.detectedAt)}
function jobEnv(x){const st=x.lastRunState==='proposal-created'?'ai-proposed':x.lastRunState==='failed'?'failed':'observed';return env(`job-${x.id}`,x.label,`${x.schedule}; ultimo esito ${x.lastRunState}.`,'scout-job',st,'scheduler-projection-v2',[x.id],['Un job può generare una proposta, non modificare il perimetro attivo.'],x,'Eseguire o ispezionare il job',null,x.lastRunAt)}
function coverageEnv(x){return env(`coverage-${x.id}`,x.family,x.statement,'control-coverage',x.coverageState,'coverage-mapping-v2',[x.id],x.limitations,x,'Verificare il livello successivo')}
function matterEnv(x){return env(`matter-${x.id}`,x.title,x.originalNarrative,'matter',x.workflowState==='owned'?'human-owned':'attention-required','matter-projection-v2',[x.id],['La classificazione iniziale non è una qualificazione normativa definitiva.'],x,x.nextAction,x.receiptRef||null,x.reportedAt)}
function traces(state,head){const mk=(id,label,steps)=>env(id,label,'Traccia runtime ricostruita dagli stessi oggetti mostrati nella UI.','runtime-trace','verified','trace-projector-v2',steps.flatMap(x=>x.inputRefs||[]),['La traccia attesta il processo locale, non la conformità legale.'],{steps},null,head);return[
mk('trace-monitoring','Monitoraggio normativo',[{id:'m1',label:'Perimetro',status:'observed',statusLabel:'osservato',statement:`${state.ecosystems.reduce((a,x)=>a+x.configuredChannels,0)} canali configurati`,producer:'seed+ledger',inputRefs:['ecosystems']},{id:'m2',label:'Osservazione',status:'observed',statusLabel:'osservato',statement:`${state.ecosystems.reduce((a,x)=>a+x.observedChannels,0)} canali con esito`,producer:'projection',inputRefs:['sources']},{id:'m3',label:'Differenze',status:'attention-required',statusLabel:'da valutare',statement:`${state.findings.filter(x=>x.humanState==='awaiting-review').length} esiti aperti`,producer:'deterministic diff',inputRefs:['findings']},{id:'m4',label:'Proposte',status:'ai-proposed',statusLabel:'proposta AI',statement:'Sintesi delimitate disponibili',producer:'AI bounded',inputRefs:['findings']},{id:'m5',label:'Review',status:'awaiting-human-review',statusLabel:'decisione umana',statement:'La promozione richiede review',producer:'human gate',inputRefs:['reviews']},{id:'m6',label:'Receipt',status:'verified',statusLabel:'verificato',statement:'Hash-chain locale',producer:'ledger',inputRefs:['ledger']}]),
mk('trace-manual-source','Fonte manuale',[{id:'s1',label:'Input',status:'observed',statusLabel:'ricevuto',statement:'Link o file proposto',producer:'human input',inputRefs:['source']},{id:'s2',label:'Acquisizione',status:'verified',statusLabel:'persistito',statement:'Originale e checksum locali',producer:'blob store',inputRefs:['blob']},{id:'s3',label:'Classificazione',status:'ai-proposed',statusLabel:'proposta',statement:'Ecosistema e temi proposti',producer:'AI bounded',inputRefs:['source']},{id:'s4',label:'Review',status:'awaiting-human-review',statusLabel:'necessaria',statement:'Una persona decide l’inclusione',producer:'human gate',inputRefs:['review']},{id:'s5',label:'Receipt',status:'verified',statusLabel:'verificato',statement:'Decisione registrata',producer:'ledger',inputRefs:['ledger']}]),
mk('trace-scouting','Scouting schedulato',[{id:'j1',label:'Schedule',status:'observed',statusLabel:'configurato',statement:'Job e owner configurati',producer:'scheduler',inputRefs:['jobs']},{id:'j2',label:'Fetch',status:'observed',statusLabel:'osservato',statement:'Acquisizione canale',producer:'fetcher',inputRefs:['sources']},{id:'j3',label:'Confronto',status:'verified',statusLabel:'deterministico',statement:'Checksum e differenze',producer:'diff engine',inputRefs:['findings']},{id:'j4',label:'Proposta',status:'ai-proposed',statusLabel:'proposta',statement:'Sintesi non conclusiva',producer:'AI bounded',inputRefs:['findings']},{id:'j5',label:'Review',status:'awaiting-human-review',statusLabel:'necessaria',statement:'Decisione umana',producer:'human gate',inputRefs:['reviews']}]),
mk('trace-matter','Evento o incidente',[{id:'e1',label:'Racconto',status:'observed',statusLabel:'registrato',statement:'Narrazione originale conservata',producer:'human input',inputRefs:['matters']},{id:'e2',label:'Fatti',status:'attention-required',statusLabel:'da confermare',statement:'Fatti, ipotesi e unknown separati',producer:'matter engine',inputRefs:['facts']},{id:'e3',label:'Owner',status:'human-owned',statusLabel:'responsabilità',statement:'Owner e RACI confermati',producer:'human decision',inputRefs:['raci']},{id:'e4',label:'Valutazioni',status:'awaiting-human-review',statusLabel:'separate',statement:'Privacy, NIS2 e altri percorsi distinti',producer:'workflow',inputRefs:['assessments']},{id:'e5',label:'Receipt',status:'verified',statusLabel:'verificato',statement:'Azioni e decisioni tracciate',producer:'ledger',inputRefs:['ledger']}])];}
export async function buildState(){const seed=await readSeed(),events=await readLedger(),state=apply(seed,events),integrity=verifyLedger(events);const configured=state.ecosystems.reduce((a,x)=>a+x.configuredChannels,0),observed=state.ecosystems.reduce((a,x)=>a+x.observedChannels,0),open=state.findings.filter(x=>x.humanState==='awaiting-review').length,head=integrity.head||'GENESIS';const headline=env('headline-radar','Il presidio locale è attivo',`${observed} di ${configured} canali configurati hanno un esito disponibile; ${open} novità richiedono review.`,'monitoring-summary',open?'attention-required':'observed','monitoring-projector-v2',['ecosystems','sources','findings'],['Non dimostra completezza del perimetro né conformità legale.'],{configured,observedChannels:observed,openFindings:open},open?'Valutare le novità':null,head);const proofTiles=[env('proof-perimeter','Perimetro osservato',`${state.sources.length} fonti censite.`,'monitoring-proof','observed','source-count-v2',['sources'],['Il numero non misura completezza.'],{value:state.sources.length}),env('proof-review','Review aperte',`${open} esiti attendono una persona.`,'monitoring-proof',open?'attention-required':'observed','review-count-v2',['findings'],['La coda non determina materialità.'],{value:open}),env('proof-integrity','Integrità locale',integrity.ok?'Hash-chain coerente.':'Hash-chain non coerente.','monitoring-proof',integrity.ok?'verified':'failed','ledger-verifier-v2',['ledger'],['Integrità tecnica non equivale a correttezza giuridica.'],{value:integrity.ok?'coerente':'errore'},null,head)];return{...state,meta:{...state.meta,version:'2.0.0-beta.2'},views:{headline,proofTiles,sourceCards:state.sources.map(sourceEnv),findingCards:state.findings.map(findingEnv),jobCards:state.scoutJobs.map(jobEnv),coverageCards:state.controlCoverage.map(coverageEnv),matterCards:state.matters.map(matterEnv),traceCards:traces(state,head)}}}
export function proposeSourceMetadata(input){const text=JSON.stringify(input).toLowerCase();const ecosystemId=text.includes('garante')||text.includes('privacy')?'eco-garante':text.includes('acn')||text.includes('nis2')||text.includes('cyber')?'eco-acn':text.includes('eur')||text.includes('ue')?'eco-eu':'eco-it';return{ecosystemId,themes:[...new Set(['normativa',text.includes('nis2')?'NIS2':null,text.includes('privacy')?'privacy':null].filter(Boolean))],summary:'Classificazione proposta per agevolare la review; rilevanza non determinata.',confidenceBand:'low'}}
export function createMatter(input){const text=(input.summary||'').toLowerCase(),consulted=['Legal'];if(/dati|privacy|personali/.test(text))consulted.push('DPO');if(/access|cyber|malware|anom/.test(text))consulted.push('Cybersecurity');return{id:`matter-${crypto.randomUUID().slice(0,8)}`,kind:input.kind||'signal',title:input.title||'Nuova segnalazione',originalNarrative:input.summary,reportedAt:nowIso(),workflowState:'facts-to-confirm',severityPerceived:input.severity||'unknown',owner:/cyber|access|anom/.test(text)?'Cybersecurity Incident Manager':'Compliance Intake',raci:{accountable:'Compliance Owner',responsible:'Triage Team',consulted:[...new Set(consulted)],informed:['Process Owner']},nextAction:'Confermare i fatti minimi e l’owner',deadline:null,facts:[{text:input.summary,state:'reported'}]}}
export function buildCapsule(state,input){const cards=input.objectId?[Object.values(state.views).flat().find?.(x=>x?.id===input.objectId)].filter(Boolean):[state.views.headline,...state.views.findingCards.slice(0,3)];return{id:crypto.randomUUID(),scope:input.scope||'radar',createdAt:nowIso(),writeAuthority:false,items:cards.map(x=>({id:x.id,label:x.label,statement:x.statement,status:x.epistemicStatus,limitations:x.limitations}))}}
export function answerFromCapsule(capsule,question=''){const q=question.toLowerCase();const answer=/conform/.test(q)?'No: gli esiti disponibili attestano operazioni locali e review, non la conformità dell’organizzazione.':`Nella capsula sono presenti ${capsule.items.length} esiti. Posso spiegarne origine, stato e limiti, ma non ampliare autonomamente il contesto.`;return{answer,epistemicStatus:'ai-proposed',citedItemIds:capsule.items.map(x=>x.id),limitations:['Risposta limitata alla capsula locale evocata dalla UI.','Nessuna scrittura o decisione automatica.']}}
export async function selfDocumentationManifest(){return['README.md','AGENTS.md','docs/02_EPISTEMIC_CONTRACT.md','docs/10_LOCAL_AI_CONTRACT.md','server.mjs','lib/domain.mjs']}
