import crypto from 'node:crypto';
import path from 'node:path';
import { readFile, stat } from 'node:fs/promises';
import { append, apply, findCommand, readLedger, RUNTIME, tenantPaths, transitions, verify } from './store.mjs';
import { createBlobStore } from './blob-store.mjs';
import { monitoringCapabilities, runMonitoringJob } from './monitoring-runtime.mjs';
import { createRuntimeModel } from './runtime-model.mjs';
import { project } from './project.mjs';
import { AccessError, accessView, loadAccessDirectory, requirePermission, resolveAccessContext } from './access-context.mjs';

const ROOT = path.resolve(new URL('..', import.meta.url).pathname);
const PUBLIC = path.join(ROOT, 'public');
const sessions = new Map();
const SESSION_TTL_MS = Math.max(60_000, Number(process.env.ICTC_SESSION_TTL_MS || 30 * 60_000));
const SESSION_LIMIT = Math.max(1, Number(process.env.ICTC_SESSION_LIMIT_PER_ACTOR || 8));
const coreContract = JSON.parse(await readFile(path.join(PUBLIC, 'core-workspaces.json'), 'utf8'));
const model = createRuntimeModel(coreContract);
const actionIndex = new Map(coreContract.actions.map(item => [item.id, Object.freeze({ ...item })]));
export const accessDirectory = await loadAccessDirectory();

function actionSpec(actionId) {
  const action = actionIndex.get(actionId);
  if (!action) throw new Error(`Azione runtime non contrattualizzata: ${actionId}.`);
  return action;
}
function enforce(context, actionId) {
  const action = actionSpec(actionId);
  requirePermission(context, action.permission);
  return action;
}
async function persist(context, actionId, payload, options = {}) {
  const action = actionSpec(actionId);
  if (!action.receiptExpected || !action.event) throw new Error(`Azione ${actionId} priva di evento persistibile.`);
  return append(context, action.event, payload, action.producer, { ...options, actionId });
}

const headers = type => ({
  'content-type': type,
  'cache-control': 'no-store',
  'x-content-type-options': 'nosniff',
  'referrer-policy': 'no-referrer',
  'permissions-policy': 'camera=(), microphone=(), geolocation=()',
  'content-security-policy': "default-src 'self'; style-src 'self'; script-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; frame-ancestors 'none'"
});
function send(res, status, value, type = 'application/json; charset=utf-8') { res.writeHead(status, headers(type)); const body=Buffer.isBuffer(value)?value:type.includes('json')?JSON.stringify(value):value; res.end(body); }
async function input(req) { let raw=''; for await(const chunk of req){raw+=chunk;if(raw.length>8_000_000)throw new Error('Payload oltre limite.')} return raw?JSON.parse(raw):{}; }
function requestError(res,error,status=400){const resolvedStatus=Number(error?.status||(error instanceof AccessError?error.status:status));return send(res,resolvedStatus,{error:error.message,code:error.code||'invalid-request'});}
export function requestContext(req,env=process.env){return resolveAccessContext(req,accessDirectory,env);}
const blobStoreFor=context=>createBlobStore({root:tenantPaths(context).blobs,publicPrefix:`runtime/tenants/${context.tenant.id}/blobs`});
export async function buildState(context=requestContext({headers:{}})){requirePermission(context,'read');const events=await readLedger(context);const domain=apply(events,context.tenant);const integrity=verify(events,context);const views=project(domain,integrity);return{...domain,meta:{...domain.meta,integrity,runtime:tenantPaths(context).root,monitoring:monitoringCapabilities(),access:accessView(context,accessDirectory)},views,objectIndex:views.index};}
function scopedInput(value,context){const clean={...value};delete clean.by;delete clean.actor;delete clean.actorId;delete clean.tenant;delete clean.tenantId;clean.operatingContext=context.tenant.organizationType;return clean;}
const requestHeader=(req,name)=>String(req?.headers?.[name]||req?.headers?.[name.toLowerCase()]||'').trim();
function conflict(message,code='state-conflict'){const error=new Error(message);error.status=409;error.code=code;throw error;}
function commandOptions(req,state=null){return{commandId:requestHeader(req,'x-ictc-command-id')||crypto.randomUUID(),expectedHead:requestHeader(req,'x-ictc-expected-head')||state?.meta?.integrity?.head||null};}
async function replayCommand(req,context,eventType){const commandId=requestHeader(req,'x-ictc-command-id');return commandId?findCommand(context,commandId,eventType,context.actor.id):null;}
function pruneSessions(nowValue=Date.now()){for(const[id,session]of sessions)if(session.expiresAt<=nowValue)sessions.delete(id);}
function createSession(context,nowValue=Date.now()){pruneSessions(nowValue);const actorSessions=[...sessions.entries()].filter(([,session])=>session.actorId===context.actor.id&&session.tenantId===context.tenant.id).sort((a,b)=>a[1].createdAt-b[1].createdAt);while(actorSessions.length>=SESSION_LIMIT){const[id]=actorSessions.shift();sessions.delete(id)}const id=crypto.randomUUID();const session={createdAt:nowValue,expiresAt:nowValue+SESSION_TTL_MS,writeAuthority:false,tenantId:context.tenant.id,actorId:context.actor.id};sessions.set(id,session);return{id,session};}
function sessionMatches(session,context,nowValue=Date.now()){if(!session||session.expiresAt<=nowValue)return false;return session.tenantId===context.tenant.id&&session.actorId===context.actor.id;}

async function handleApiInner(req,res,url){let context;try{context=requestContext(req)}catch(error){return requestError(res,error,401)}
if(req.method==='GET'&&url.pathname==='/api/access'){enforce(context,'access-read');return send(res,200,accessView(context,accessDirectory));}
if(req.method==='GET'&&url.pathname==='/api/health')return send(res,200,{ok:true,service:'ictc-v3',version:'3.1.0-readiness',localSot:true,runtime:RUNTIME,access:{tenantAware:true,identityMode:context.identityMode,tenantId:context.tenant.id},monitoring:monitoringCapabilities()});
if(req.method==='GET'&&url.pathname==='/api/bootstrap')return send(res,200,await buildState(context));
if(req.method==='GET'&&url.pathname==='/api/runtime/integrity'){requirePermission(context,'read');return send(res,200,verify(await readLedger(context),context));}
if(req.method==='GET'&&url.pathname==='/api/runtime/ledger'){requirePermission(context,'read');const events=await readLedger(context);return send(res,200,{events:events.slice(-100).reverse().map(({payload,...event})=>event),integrity:verify(events,context)});}
if(req.method==='GET'&&url.pathname==='/api/self/manifest')return send(res,200,{writeAuthority:false,tenantAware:true,identityBoundary:context.identityMode,files:['v3/access-control.json','v3/server.mjs','v3/lib/access-context.mjs','v3/lib/store.mjs','v3/lib/blob-store.mjs','v3/lib/runtime-model.mjs','v3/lib/network-policy.mjs','v3/lib/monitoring-runtime.mjs','v3/lib/project.mjs','v3/lib/api.mjs','v3/public/index.html','v3/public/js/journey-shell.js','v3/public/js/journey-shell-common.js','v3/public/js/journey-shell-render.js','v3/public/js/journey-shell-actions.js']});
let match=url.pathname.match(/^\/api\/objects\/([^/]+)$/);if(req.method==='GET'&&match){requirePermission(context,'read');const state=await buildState(context);const object=state.objectIndex[decodeURIComponent(match[1])];if(!object)return send(res,404,{error:'Oggetto non trovato nel tenant selezionato.'});const edges=state.views.semanticGraph.edges.filter(edge=>edge.from===object.id||edge.to===object.id);const ids=[...new Set(edges.flatMap(edge=>[edge.from,edge.to]).filter(id=>id!==object.id))];return send(res,200,{object,edges,related:ids.map(id=>state.objectIndex[id]).filter(Boolean)});}
if(req.method==='POST'&&url.pathname==='/api/session'){requirePermission(context,'read');const{id,session}=createSession(context);return send(res,201,{sessionId:id,expiresAt:new Date(session.expiresAt).toISOString(),writeAuthority:false,tenantId:context.tenant.id,scopeExpansion:'selected-object-plus-neighbors'});}
if(req.method==='POST'&&url.pathname==='/api/jobs'){enforce(context,'job-create');const value=scopedInput(await input(req),context);try{const state=await buildState(context);const{source,job}=model.createMonitoring(value);const result=await persist(context,'job-create',{source,job},commandOptions(req,state));const persisted=result.event.payload;return send(res,201,{source:persisted.source,job:persisted.job,epistemicStatus:'candidate',receipt:result.receipt});}catch(error){return requestError(res,error)}}
match=url.pathname.match(/^\/api\/jobs\/([^/]+)\/schedule$/);if(req.method==='POST'&&match){enforce(context,'job-schedule');const replay=await replayCommand(req,context,'job.scheduled');if(replay)return send(res,201,{job:replay.event.payload.job,epistemicStatus:replay.event.payload.job.enabled?'human-reviewed':'observed',receipt:replay.receipt});const value=scopedInput(await input(req),context);const state=await buildState(context);const job=state.jobs.find(item=>item.id===match[1]);if(!job)return send(res,404,{error:'Monitoraggio non trovato nel tenant selezionato.'});const source=state.sources.find(item=>item.id===job.sourceId);if(!source||source.lifecycle!=='active')return send(res,409,{error:'Includere la fonte prima di attivare il monitoraggio.',code:'source-review-required'});if(job.enabled)return send(res,409,{error:'Il monitoraggio è già attivo.',code:'state-conflict'});const updated=model.scheduleMonitoring(job,value);const result=await persist(context,'job-schedule',{id:job.id,job:updated},commandOptions(req,state));return send(res,201,{job:result.event.payload.job,epistemicStatus:updated.enabled?'human-reviewed':'observed',receipt:result.receipt});}
match=url.pathname.match(/^\/api\/jobs\/([^/]+)\/run$/);if(req.method==='POST'&&match){enforce(context,'job-run');const value=scopedInput(await input(req),context);try{const command=commandOptions(req);const result=await runMonitoringJob(context,match[1],{trigger:'manual',contentText:value.contentText,...command});return send(res,201,{...result,epistemicStatus:result.finding?'ai-proposed':'observed'});}catch(error){if(error?.status)return requestError(res,error,error.status);return send(res,409,{error:error.message,code:'monitoring-unavailable',capability:'monitoring-run',state:'unavailable'});}}
if(req.method==='POST'&&url.pathname==='/api/sources'){enforce(context,'source-propose');const value=scopedInput(await input(req),context);if(!value.url&&!value.contentBase64&&!String(value.contentText||'').trim())return send(res,400,{error:'Inserire un link o un contenuto testuale.'});try{let blob=null;const blobs=blobStoreFor(context);if(String(value.contentText||'').trim())blob=await blobs.putText(value.contentText);else if(value.contentBase64){const bytes=Buffer.from(value.contentBase64,'base64');const candidateExtension=path.extname(String(value.fileName||'')).toLowerCase();const extension=/^\.[a-z0-9]{1,12}$/.test(candidateExtension)?candidateExtension:'';blob=await blobs.putBytes(bytes,{maxBytes:5_000_000,extension,mediaType:value.mediaType||'application/octet-stream'});}const state=await buildState(context);const{source,finding}=model.createManualSource({...value,binary:Boolean(value.contentBase64)},blob);const result=await persist(context,'source-propose',{source,finding},commandOptions(req,state));const persisted=result.event.payload;return send(res,201,{source:persisted.source,finding:persisted.finding,epistemicStatus:'candidate',receipt:result.receipt});}catch(error){return requestError(res,error)}}
match=url.pathname.match(/^\/api\/sources\/([^/]+)\/review$/);if(req.method==='POST'&&match){enforce(context,'source-review');const replay=await replayCommand(req,context,'source.reviewed');if(replay)return send(res,201,{epistemicStatus:'human-reviewed',receipt:replay.receipt});const value=scopedInput(await input(req),context);const state=await buildState(context);const source=state.sources.find(item=>item.id===match[1]);if(!source)return send(res,404,{error:'Fonte non trovata nel tenant selezionato.'});if(source.reviewState!=='candidate-awaiting-review')conflict('La fonte è già stata revisionata.');if(!['accepted','rejected'].includes(value.outcome))return send(res,400,{error:'Esito non valido.'});const result=await persist(context,'source-review',{id:match[1],outcome:value.outcome},commandOptions(req,state));return send(res,201,{epistemicStatus:'human-reviewed',receipt:result.receipt});}
match=url.pathname.match(/^\/api\/findings\/([^/]+)\/review$/);if(req.method==='POST'&&match){enforce(context,'finding-review');const replay=await replayCommand(req,context,'finding.reviewed');if(replay)return send(res,201,{epistemicStatus:'human-reviewed',receipt:replay.receipt});const value=scopedInput(await input(req),context);const state=await buildState(context);const finding=state.findings.find(item=>item.id===match[1]);if(!finding)return send(res,404,{error:'Differenza non trovata nel tenant selezionato.'});if(finding.humanState!=='awaiting-review')conflict('La differenza è già stata revisionata.');if(!['relevant','not-relevant'].includes(value.outcome))return send(res,400,{error:'Esito non valido.'});const result=await persist(context,'finding-review',{id:match[1],outcome:value.outcome},commandOptions(req,state));return send(res,201,{epistemicStatus:'human-reviewed',receipt:result.receipt});}
match=url.pathname.match(/^\/api\/changes\/([^/]+)\/decide$/);if(req.method==='POST'&&match){enforce(context,'change-decision');const replay=await replayCommand(req,context,'change.decided');if(replay)return send(res,201,{epistemicStatus:'human-reviewed',receipt:replay.receipt});const value=scopedInput(await input(req),context);const state=await buildState(context);const change=state.changes.find(item=>item.id===match[1]);if(!change)return send(res,404,{error:'Decisione non trovata nel tenant selezionato.'});if(change.state!=='impact-to-assess')conflict('L’impatto è già stato deciso.');if(!['monitor','action-required','not-applicable'].includes(value.outcome)||!String(value.rationale||'').trim())return send(res,400,{error:'Decisione e motivazione obbligatorie.'});const result=await persist(context,'change-decision',{id:match[1],outcome:value.outcome,rationale:String(value.rationale).slice(0,3000)},commandOptions(req,state));return send(res,201,{epistemicStatus:'human-reviewed',receipt:result.receipt});}
match=url.pathname.match(/^\/api\/changes\/([^/]+)\/map-control$/);if(req.method==='POST'&&match){enforce(context,'control-map');const replay=await replayCommand(req,context,'change.control.mapped');if(replay)return send(res,201,{epistemicStatus:'mapped',receipt:replay.receipt});const value=scopedInput(await input(req),context);const state=await buildState(context);const change=state.changes.find(item=>item.id===match[1]);if(!change)return send(res,404,{error:'Decisione non trovata nel tenant selezionato.'});if(change.state!=='controls-to-map')conflict('Il collegamento del controllo non è più aperto.');if(change.controlIds?.includes(value.controlId))conflict('Il controllo è già collegato.');if(!state.controls.some(item=>item.id===value.controlId))return send(res,404,{error:'Controllo non trovato.'});const result=await persist(context,'control-map',{id:match[1],controlId:value.controlId,rationale:String(value.rationale||'').slice(0,3000)},commandOptions(req,state));return send(res,201,{epistemicStatus:'mapped',receipt:result.receipt});}
if(req.method==='POST'&&url.pathname==='/api/matters'){enforce(context,'matter-create');const value=scopedInput(await input(req),context);try{const state=await buildState(context);const matter=model.createIncident(value);const result=await persist(context,'matter-create',{matter},commandOptions(req,state));return send(res,201,{matter:result.event.payload.matter,epistemicStatus:'observed',receipt:result.receipt});}catch(error){return requestError(res,error)}}
match=url.pathname.match(/^\/api\/matters\/([^/]+)\/confirm-owner$/);if(req.method==='POST'&&match){enforce(context,'matter-owner');const replay=await replayCommand(req,context,'matter.owner.confirmed');if(replay)return send(res,201,{epistemicStatus:'human-owned',receipt:replay.receipt});const value=scopedInput(await input(req),context);const state=await buildState(context);const matter=state.matters.find(item=>item.id===match[1]);if(!matter)return send(res,404,{error:'Caso non trovato nel tenant selezionato.'});if(matter.state!=='facts-to-confirm')conflict('La responsabilità del caso è già stata confermata.');if(!value.owner||!value.raci?.accountable||!value.raci?.responsible)return send(res,400,{error:'Owner e RACI obbligatori.'});const result=await persist(context,'matter-owner',{id:match[1],owner:value.owner,raci:value.raci},commandOptions(req,state));return send(res,201,{epistemicStatus:'human-owned',receipt:result.receipt});}
match=url.pathname.match(/^\/api\/matters\/([^/]+)\/transition$/);if(req.method==='POST'&&match){enforce(context,'matter-transition');const replay=await replayCommand(req,context,'matter.transitioned');if(replay)return send(res,201,{epistemicStatus:replay.event.payload.to==='closed'?'human-reviewed':'human-owned',phase:replay.event.payload.phase,receipt:replay.receipt});const value=scopedInput(await input(req),context);const state=await buildState(context);const matter=state.matters.find(item=>item.id===match[1]);if(!matter)return send(res,404,{error:'Caso non trovato nel tenant selezionato.'});if(!transitions[matter.state]?.includes(value.to))return send(res,409,{error:`Transizione non consentita da ${matter.state} a ${value.to}.`});try{const{phase,clean}=model.validateIncidentTransition(matter,value.to,value.evidence);const result=await persist(context,'matter-transition',{id:match[1],to:value.to,phase:phase.phase,label:phase.label,evidence:clean},commandOptions(req,state));return send(res,201,{epistemicStatus:value.to==='closed'?'human-reviewed':'human-owned',phase:phase.phase,receipt:result.receipt});}catch(error){return requestError(res,error)}}
if(req.method==='POST'&&url.pathname==='/api/assistant'){requirePermission(context,'read');const value=scopedInput(await input(req),context);const session=sessions.get(value.sessionId);if(!sessionMatches(session,context))return send(res,401,{error:'Sessione assente, scaduta o appartenente a un altro tenant.'});const state=await buildState(context);const object=state.objectIndex[value.objectId]||state.views.headline;const edges=state.views.semanticGraph.edges.filter(edge=>edge.from===object.id||edge.to===object.id);const ids=[...new Set([object.id,...edges.flatMap(edge=>[edge.from,edge.to])])].slice(0,12);const items=ids.map(id=>state.objectIndex[id]).filter(Boolean);const question=String(value.question||'').toLowerCase();const answer=/conform|certificat|sicuri/.test(question)?'No. Gli esiti attestano operazioni e decisioni nel tenant selezionato, non una conclusione generale di conformità.':`L’oggetto “${object.label}” deriva da ${object.producer.id}. Limiti: ${(object.limitations||[]).join(' ')}`;return send(res,200,{answer,epistemicStatus:'ai-proposed',citedItemIds:items.map(item=>item.id),limitations:['Capsula confinata al tenant e alla sessione.','Nessuna scrittura autonoma.'],capsule:{id:crypto.randomUUID(),tenantId:context.tenant.id,writeAuthority:false,items}});}return false;}
export async function handleApi(req,res,url){try{return await handleApiInner(req,res,url)}catch(error){if(error instanceof AccessError||error?.status)return requestError(res,error,error.status);throw error}}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8'};
export async function handleStatic(req,res,url){const name=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1));const target=path.resolve(PUBLIC,name);if(!target.startsWith(PUBLIC+path.sep)&&target!==path.join(PUBLIC,'index.html'))return send(res,403,'Forbidden','text/plain');await stat(target);return send(res,200,await readFile(target),mime[path.extname(target)]||'application/octet-stream');}
export function errorResponse(res,error){if(error.code==='ENOENT')return send(res,404,'Not found','text/plain');if(error instanceof AccessError||error?.status)return requestError(res,error,error.status);console.error(error);return send(res,500,{error:error.message});}
export const apiInternals=Object.freeze({actionSpec,enforce,persist,scopedInput,sessionMatches,blobStoreFor,commandOptions,replayCommand,createSession,pruneSessions,sessions,SESSION_TTL_MS,SESSION_LIMIT});
