import crypto from 'node:crypto';
import path from 'node:path';
import { mkdir, readFile, stat, writeFile } from 'node:fs/promises';
import { append, apply, BLOBS, digest, now, readLedger, RUNTIME, transitions, verify } from './store.mjs';
import { project } from './project.mjs';
const ROOT=path.resolve(new URL('..',import.meta.url).pathname),PUBLIC=path.join(ROOT,'public'),sessions=new Map();
export async function buildState(){const events=await readLedger(),domain=apply(events),integrity=verify(events),views=project(domain,integrity);return{...domain,meta:{...domain.meta,integrity,runtime:RUNTIME},views,objectIndex:views.index}}
const headers=type=>({'content-type':type,'cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer','permissions-policy':'camera=(), microphone=(), geolocation=()','content-security-policy':"default-src 'self'; style-src 'self'; script-src 'self'; img-src 'self' data:; connect-src 'self'; object-src 'none'; frame-ancestors 'none'"});
function send(res,status,value,type='application/json; charset=utf-8'){res.writeHead(status,headers(type));res.end(type.includes('json')?JSON.stringify(value):value)}
async function input(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>8_000_000)throw Error('Payload oltre limite')}return raw?JSON.parse(raw):{}}
function validateUrl(value){if(!value)return null;const url=new URL(value);if(!['http:','https:'].includes(url.protocol))throw Error('Sono ammessi URL HTTP o HTTPS');return url.toString()}
export async function handleApi(req,res,url){
 if(req.method==='GET'&&url.pathname==='/api/health')return send(res,200,{ok:true,service:'ictc-v3',version:'3.0.0-beta.1',localSot:true,runtime:RUNTIME});
 if(req.method==='GET'&&url.pathname==='/api/bootstrap')return send(res,200,await buildState());
 if(req.method==='GET'&&url.pathname==='/api/runtime/integrity')return send(res,200,verify(await readLedger()));
 if(req.method==='GET'&&url.pathname==='/api/runtime/ledger'){const events=await readLedger();return send(res,200,{events:events.slice(-100).reverse().map(({payload,...event})=>event),integrity:verify(events)})}
 if(req.method==='GET'&&url.pathname==='/api/self/manifest')return send(res,200,{writeAuthority:false,files:['v3/server.mjs','v3/lib/store.mjs','v3/lib/project.mjs','v3/lib/api.mjs','v3/public/index.html','v3/public/app.js','v3/public/styles.css','docs/UX_TO_BE_V3.md']});
 let match=url.pathname.match(/^\/api\/objects\/([^/]+)$/);
 if(req.method==='GET'&&match){const state=await buildState(),object=state.objectIndex[decodeURIComponent(match[1])];if(!object)return send(res,404,{error:'Oggetto non trovato'});const edges=state.views.semanticGraph.edges.filter(edge=>edge.from===object.id||edge.to===object.id),ids=[...new Set(edges.flatMap(edge=>[edge.from,edge.to]).filter(id=>id!==object.id))];return send(res,200,{object,edges,related:ids.map(id=>state.objectIndex[id]).filter(Boolean)})}
 if(req.method==='POST'&&url.pathname==='/api/session'){const id=crypto.randomUUID();sessions.set(id,{createdAt:Date.now(),writeAuthority:false});return send(res,201,{sessionId:id,writeAuthority:false,scopeExpansion:'selected-object-plus-neighbors'})}
 if(req.method==='POST'&&url.pathname==='/api/sources'){const value=await input(req);if(!value.url&&!value.contentBase64)return send(res,400,{error:'Inserire un link o un file'});let locator=validateUrl(value.url),checksum=digest(locator||'');if(value.contentBase64){const bytes=Buffer.from(value.contentBase64,'base64');if(bytes.length>5_000_000)return send(res,413,{error:'File oltre 5 MB'});checksum=digest(bytes);await mkdir(BLOBS,{recursive:true});await writeFile(path.join(BLOBS,checksum),bytes);locator=`runtime/blobs/${checksum}`}const id=`src-${crypto.randomUUID().slice(0,8)}`,serialized=JSON.stringify(value),source={id,title:String(value.title||value.fileName||value.url).slice(0,400),ecosystem:/privacy|garante/i.test(serialized)?'Garante Privacy':/acn|nis2|cyber/i.test(serialized)?'ACN e CSIRT Italia':'Da classificare',kind:value.contentBase64?'user-file':'user-link',locator,lifecycle:'candidate',reviewState:'candidate-awaiting-review',owner:'Compliance Intake',lastCheckedAt:now(),checksum},finding={id:`finding-${crypto.randomUUID().slice(0,8)}`,sourceId:id,type:'new-source',statement:'Una persona ha proposto una nuova fonte.',humanState:'awaiting-review',materiality:'undetermined',aiProposal:'Ecosistema proposto; autorevolezza e rilevanza indeterminate.'},result=await append('source.proposed',{source,finding},value.by||'utente','human-input-plus-bounded-ai');return send(res,201,{source,epistemicStatus:'candidate',receipt:result.receipt})}
 match=url.pathname.match(/^\/api\/sources\/([^/]+)\/review$/);
 if(req.method==='POST'&&match){const value=await input(req),state=await buildState();if(!state.sources.some(item=>item.id===match[1]))return send(res,404,{error:'Fonte non trovata'});if(!['accepted','rejected'].includes(value.outcome))return send(res,400,{error:'Esito non valido'});const result=await append('source.reviewed',{id:match[1],outcome:value.outcome},value.by||'reviewer','human-review');return send(res,201,{epistemicStatus:'human-reviewed',receipt:result.receipt})}
 match=url.pathname.match(/^\/api\/findings\/([^/]+)\/review$/);
 if(req.method==='POST'&&match){const value=await input(req),state=await buildState();if(!state.findings.some(item=>item.id===match[1]))return send(res,404,{error:'Differenza non trovata'});if(!['relevant','not-relevant'].includes(value.outcome))return send(res,400,{error:'Esito non valido'});const result=await append('finding.reviewed',{id:match[1],outcome:value.outcome},value.by||'reviewer','human-review');return send(res,201,{epistemicStatus:'human-reviewed',receipt:result.receipt})}
 match=url.pathname.match(/^\/api\/changes\/([^/]+)\/decide$/);
 if(req.method==='POST'&&match){const value=await input(req);if(!['monitor','action-required','not-applicable'].includes(value.outcome)||!String(value.rationale||'').trim())return send(res,400,{error:'Decisione e motivazione obbligatorie'});const result=await append('change.decided',{id:match[1],outcome:value.outcome,rationale:String(value.rationale).slice(0,3000)},value.by||'decision-owner','human-decision');return send(res,201,{epistemicStatus:'human-reviewed',receipt:result.receipt})}
 match=url.pathname.match(/^\/api\/changes\/([^/]+)\/map-control$/);
 if(req.method==='POST'&&match){const value=await input(req),state=await buildState();if(!state.controls.some(item=>item.id===value.controlId))return send(res,404,{error:'Controllo non trovato'});const result=await append('change.control.mapped',{id:match[1],controlId:value.controlId,rationale:String(value.rationale||'').slice(0,3000)},value.by||'control-owner','human-mapping');return send(res,201,{epistemicStatus:'mapped',receipt:result.receipt})}
 if(req.method==='POST'&&url.pathname==='/api/matters'){const value=await input(req);if(!String(value.summary||'').trim())return send(res,400,{error:'Racconto obbligatorio'});const id=`matter-${crypto.randomUUID().slice(0,8)}`,text=String(value.summary),matter={id,title:String(value.title||'Nuova segnalazione').slice(0,300),kind:value.kind||'signal',narrative:text,state:'facts-to-confirm',owner:/cyber|access|anom/i.test(text)?'Cybersecurity Incident Manager':'Compliance Intake',raci:{accountable:'Compliance Owner',responsible:'Triage Team',consulted:[...new Set(['Legal',/dati|privacy/i.test(text)?'DPO':null,/fornitor/i.test(text)?'Procurement':null].filter(Boolean))],informed:['Process Owner']},timeline:[]},result=await append('matter.reported',{matter},value.by||'segnalante','human-report');return send(res,201,{matter,epistemicStatus:'observed',receipt:result.receipt})}
 match=url.pathname.match(/^\/api\/matters\/([^/]+)\/confirm-owner$/);
 if(req.method==='POST'&&match){const value=await input(req);if(!value.owner||!value.raci?.accountable||!value.raci?.responsible)return send(res,400,{error:'Owner e RACI obbligatori'});const result=await append('matter.owner.confirmed',{id:match[1],owner:value.owner,raci:value.raci},value.by||'owner','human-decision');return send(res,201,{epistemicStatus:'human-owned',receipt:result.receipt})}
 match=url.pathname.match(/^\/api\/matters\/([^/]+)\/transition$/);
 if(req.method==='POST'&&match){const value=await input(req),state=await buildState(),matter=state.matters.find(item=>item.id===match[1]);if(!matter)return send(res,404,{error:'Caso non trovato'});if(!transitions[matter.state]?.includes(value.to))return send(res,409,{error:`Transizione non consentita da ${matter.state} a ${value.to}`});const result=await append('matter.transitioned',{id:match[1],to:value.to,label:`Stato ${value.to}`,note:String(value.note||'').slice(0,2000)},value.by||'owner','human-transition');return send(res,201,{epistemicStatus:value.to==='closed'?'human-reviewed':'human-owned',receipt:result.receipt})}
 match=url.pathname.match(/^\/api\/jobs\/([^/]+)\/run$/);
 if(req.method==='POST'&&match){const value=await input(req),state=await buildState(),job=state.jobs.find(item=>item.id===match[1]);if(!job)return send(res,404,{error:'Job non trovato'});const changed=value.changed!==false,finding=changed?{id:`finding-${crypto.randomUUID().slice(0,8)}`,sourceId:state.sources.find(item=>item.ecosystem===job.ecosystem)?.id,type:'content-change',statement:'Il confronto deterministico ha rilevato una differenza.',humanState:'awaiting-review',materiality:'undetermined',aiProposal:'Sintesi delimitata per la review.'}:null,result=await append('job.completed',{job:{...job,state:changed?'proposal-created':'completed-no-change'},finding},'scheduler',changed?'deterministic-plus-bounded-ai':'deterministic');return send(res,201,{epistemicStatus:changed?'ai-proposed':'observed',finding,receipt:result.receipt})}
 if(req.method==='POST'&&url.pathname==='/api/assistant'){const value=await input(req);if(!sessions.has(value.sessionId))return send(res,401,{error:'Sessione assente o scaduta'});const state=await buildState(),object=state.objectIndex[value.objectId]||state.views.headline,edges=state.views.semanticGraph.edges.filter(edge=>edge.from===object.id||edge.to===object.id),ids=[...new Set([object.id,...edges.flatMap(edge=>[edge.from,edge.to])])].slice(0,12),items=ids.map(id=>state.objectIndex[id]).filter(Boolean),question=String(value.question||'').toLowerCase(),answer=/conform|certificat|sicuri/.test(question)?'No. Gli esiti attestano operazioni locali e decisioni registrate, non una conclusione generale di conformità.':`L’oggetto “${object.label}” deriva da ${object.producer.id}. Limiti: ${object.limitations.join(' ')}`;return send(res,200,{answer,epistemicStatus:'ai-proposed',citedItemIds:items.map(item=>item.id),limitations:['Capsula locale della sessione.','Nessuna scrittura autonoma.'],capsule:{id:crypto.randomUUID(),writeAuthority:false,items}})}
 return false;
}
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8'};
export async function handleStatic(req,res,url){const name=url.pathname==='/'?'index.html':decodeURIComponent(url.pathname.slice(1)),target=path.resolve(PUBLIC,name);if(!target.startsWith(PUBLIC+path.sep)&&target!==path.join(PUBLIC,'index.html'))return send(res,403,'Forbidden','text/plain');await stat(target);return send(res,200,await readFile(target),mime[path.extname(target)]||'application/octet-stream')}
export function errorResponse(res,error){if(error.code==='ENOENT')return send(res,404,'Not found','text/plain');console.error(error);return send(res,500,{error:error.message})}
