import crypto from 'node:crypto';
import dns from 'node:dns/promises';
import { append, apply, BLOBS, now, readLedger } from './store.mjs';
import { createBlobStore } from './blob-store.mjs';
import { isPrivateAddress } from './network-policy.mjs';

const blobs = createBlobStore({ root: BLOBS });
const runtimeState = {startedAt:new Date().toISOString(),running:false,inFlight:new Set(),lastTickAt:null,lastError:null,timer:null};
const clampText=(value,maximum=24_000)=>String(value??'').replace(/\u0000/g,'').slice(0,maximum);
const nextRunAt=minutes=>new Date(Date.now()+Math.max(1,Number(minutes)||1440)*60_000).toISOString();
export function monitoringCapabilities(env=process.env){const aiConfigured=Boolean(env.ICTC_AI_ENDPOINT&&env.ICTC_AI_MODEL);return{scheduler:env.ICTC_MONITORING_SCHEDULER==='0'?'disabled':runtimeState.running?'active':'not-started',remoteFetch:env.ICTC_MONITORING_REMOTE==='1'?'enabled':'disabled',aiStudy:aiConfigured?'configured':'unavailable',aiModel:aiConfigured?env.ICTC_AI_MODEL:null,intervalMs:Math.max(250,Number(env.ICTC_SCHEDULER_TICK_MS||60_000)),startedAt:runtimeState.startedAt,lastTickAt:runtimeState.lastTickAt,lastError:runtimeState.lastError}}
async function assertSafeRemoteUrl(rawUrl,env){const url=new URL(rawUrl);if(url.protocol!=='https:'&&!(env.ICTC_ALLOW_PRIVATE_MONITORING==='1'&&url.protocol==='http:'))throw new Error('Il monitoraggio remoto richiede HTTPS. HTTP è ammesso soltanto nel test locale esplicito.');const addresses=await dns.lookup(url.hostname,{all:true});if(!addresses.length)throw new Error('Host del monitoraggio non risolto.');if(env.ICTC_ALLOW_PRIVATE_MONITORING!=='1'&&addresses.some(item=>isPrivateAddress(item.address)))throw new Error('Host privato o loopback non ammesso per il monitoraggio remoto.');return url}
async function fetchObservedContent(source,env){if(env.ICTC_MONITORING_REMOTE!=='1')throw new Error('Acquisizione remota disabilitata. Fornire contenuto osservato oppure abilitare ICTC_MONITORING_REMOTE=1.');const url=await assertSafeRemoteUrl(source.locator,env);const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),Math.max(1000,Number(env.ICTC_MONITORING_TIMEOUT_MS||10_000)));try{const response=await fetch(url,{redirect:'error',signal:controller.signal,headers:{'user-agent':'ICTC/1.0 monitoring-runtime'}});if(!response.ok)throw new Error(`Acquisizione remota fallita: HTTP ${response.status}`);const declared=Number(response.headers.get('content-length')||0);if(declared>1_000_000)throw new Error('Contenuto remoto oltre 1 MB.');const text=clampText(await response.text(),1_000_000);if(!text.trim())throw new Error('Contenuto remoto vuoto.');return{text,contentType:response.headers.get('content-type')||'text/plain',locator:url.toString()}}finally{clearTimeout(timeout)}}
async function askAiToStudy({source,job,text,comparison},env){if(!env.ICTC_AI_ENDPOINT||!env.ICTC_AI_MODEL)return{status:'unavailable',provider:null,model:null,summary:null,limitations:['Provider AI non configurato.','La differenza resta disponibile per review umana senza arricchimento AI.']};const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),Math.max(1000,Number(env.ICTC_AI_TIMEOUT_MS||20_000)));const prompt=['Sei un analista read-only. Non determinare conformità, applicabilità o urgenza.',`Fonte: ${source.title}.`,`Domanda configurata: ${job.studyQuestion||'Riassumi la variazione osservata.'}`,`Confronto digest: ${comparison}.`,'Restituisci JSON con summary (massimo 500 caratteri), reviewQuestion e limitations (array).',`Contenuto osservato:\n${clampText(text,18_000)}`].join('\n');try{const response=await fetch(env.ICTC_AI_ENDPOINT,{method:'POST',signal:controller.signal,headers:{'content-type':'application/json',...(env.ICTC_AI_API_KEY?{authorization:`Bearer ${env.ICTC_AI_API_KEY}`}:{})},body:JSON.stringify({model:env.ICTC_AI_MODEL,temperature:0,response_format:{type:'json_object'},messages:[{role:'system',content:'Produci soltanto una proposta delimitata e citabile.'},{role:'user',content:prompt}]})});if(!response.ok)throw new Error(`AI provider HTTP ${response.status}`);const payload=await response.json();const raw=payload?.choices?.[0]?.message?.content;const parsed=typeof raw==='string'?JSON.parse(raw):raw;if(!parsed?.summary)throw new Error('Risposta AI priva di summary.');return{status:'completed',provider:new URL(env.ICTC_AI_ENDPOINT).origin,model:env.ICTC_AI_MODEL,summary:clampText(parsed.summary,500),reviewQuestion:clampText(parsed.reviewQuestion||'La variazione è rilevante nel contesto locale?',300),limitations:Array.isArray(parsed.limitations)?parsed.limitations.map(item=>clampText(item,300)).slice(0,6):['Proposta da revisionare.']}}catch(error){return{status:'failed',provider:env.ICTC_AI_ENDPOINT,model:env.ICTC_AI_MODEL,summary:null,limitations:[`Studio AI non completato: ${clampText(error.message,240)}`,'La review umana resta obbligatoria.']}}finally{clearTimeout(timeout)}}
export async function runMonitoringJob(jobId,options={},env=process.env){if(runtimeState.inFlight.has(jobId))throw new Error('Monitoraggio già in esecuzione.');runtimeState.inFlight.add(jobId);try{const domain=apply(await readLedger());const job=domain.jobs.find(item=>item.id===jobId);if(!job)throw new Error('Monitoraggio non trovato.');const source=domain.sources.find(item=>item.id===job.sourceId)||domain.sources.find(item=>item.ecosystem===job.ecosystem);if(!source)throw new Error('Fonte collegata al monitoraggio non trovata.');if(source.lifecycle!=='active')throw new Error('La fonte deve essere inclusa prima di attivare il monitoraggio.');const observed=String(options.contentText||'').trim()?{text:clampText(options.contentText,1_000_000),contentType:'text/plain; charset=utf-8',locator:'human-observed-content'}:await fetchObservedContent(source,env);const stored=await blobs.putText(observed.text,{mediaType:observed.contentType});const inputDigest=stored.checksum;const comparison=!job.lastDigest?'baseline-created':job.lastDigest===inputDigest?'unchanged':'changed';const ai=await askAiToStudy({source,job,text:observed.text,comparison},env);const finding=comparison==='changed'?{id:`finding-${crypto.randomUUID().slice(0,8)}`,sourceId:source.id,jobId:job.id,type:'content-change',statement:ai.summary||'Il contenuto osservato differisce dall’ultima baseline registrata.',humanState:'awaiting-review',materiality:'undetermined',aiProposal:ai.status==='completed'?ai.summary:'Studio AI non disponibile o non completato; review umana richiesta.',aiStudy:ai}:null;const completedAt=now();const updatedJob={...job,state:comparison==='changed'?'change-awaiting-review':comparison==='baseline-created'?'baseline-recorded':'completed-no-change',lastRunAt:completedAt,nextRunAt:nextRunAt(job.schedule?.intervalMinutes),lastDigest:inputDigest,lastComparison:comparison,lastStudy:{trigger:options.trigger||'manual',observedAt:completedAt,locator:observed.locator,contentType:stored.mediaType,blobRef:stored.locator,inputDigest,byteLength:stored.byteLength,ai}};const result=await append('job.completed',{job:updatedJob,finding},options.actor||(options.trigger==='scheduled'?'scheduler':'utente'),ai.status==='completed'?'remote-observation-plus-ai-proposal':'remote-observation');return{job:updatedJob,finding,comparison,ai,receipt:result.receipt}}finally{runtimeState.inFlight.delete(jobId)}}
async function recordFailure(job,error){const failedAt=now();const updatedJob={...job,state:'run-failed',lastRunAt:failedAt,nextRunAt:nextRunAt(job.schedule?.intervalMinutes),lastError:clampText(error.message,500)};await append('job.failed',{job:updatedJob,error:{message:updatedJob.lastError,category:'monitoring-runtime'}},'scheduler','monitoring-runtime')}
export async function schedulerTick(env=process.env){runtimeState.lastTickAt=now();runtimeState.lastError=null;const domain=apply(await readLedger());const due=domain.jobs.filter(job=>job.enabled&&job.nextRunAt&&Date.parse(job.nextRunAt)<=Date.now());for(const job of due){try{await runMonitoringJob(job.id,{trigger:'scheduled'},env)}catch(error){runtimeState.lastError=clampText(error.message,500);await recordFailure(job,error)}}return{due:due.length,at:runtimeState.lastTickAt}}
export function startMonitoringScheduler(env=process.env){if(env.ICTC_MONITORING_SCHEDULER==='0'||runtimeState.timer)return;const tickMs=Math.max(250,Number(env.ICTC_SCHEDULER_TICK_MS||60_000));runtimeState.running=true;runtimeState.timer=setInterval(()=>schedulerTick(env).catch(error=>{runtimeState.lastError=clampText(error.message,500)}),tickMs);runtimeState.timer.unref?.()}
export function stopMonitoringScheduler(){if(runtimeState.timer)clearInterval(runtimeState.timer);runtimeState.timer=null;runtimeState.running=false}
