const env=(id,label,statement,claimClass,status,producer,inputs,limitations,data={},nextAction=null,receipt=null)=>({id,label,statement,claimClass,epistemicStatus:status,producer:{type:producer,id:producer},inputs:inputs.map(id=>({type:'record',id})),limitations,nextAction,receiptRef:receipt,data});
export function project(s,integrity){
 const sources=s.sources.map(x=>env(`source-${x.id}`,x.title,`${x.ecosystem}; ultimo controllo ${x.lastCheckedAt||'non disponibile'}.`,'source-record',x.lifecycle==='candidate'?'candidate':x.reviewState==='reviewed'?'human-reviewed':x.reviewState.includes('awaiting')?'attention-required':'observed','source-projector',[x.id],['Catalogazione non equivale ad applicabilità o completezza.'],x,x.lifecycle==='candidate'?'Completare la review':'Aprire la catena',x.receipt));
 const findings=s.findings.map(x=>env(`finding-${x.id}`,x.type==='new-document'?'Nuovo documento osservato':'Differenza osservata',x.statement,'finding',x.humanState==='awaiting-review'?'awaiting-human-review':'human-reviewed','diff-plus-bounded-ai',[x.id,x.sourceId],['Materialità e impatto non sono determinati automaticamente.'],x,x.humanState==='awaiting-review'?'Registrare la review':'Aprire la change story',x.receipt));
 const changes=s.changes.map(x=>env(`change-${x.id}`,x.title,x.decision?`Decisione: ${x.decision.outcome}.`:'Impatto ancora da decidere.','regulatory-change-story',x.state==='impact-to-assess'||x.state==='controls-to-map'?'awaiting-human-review':'human-reviewed','change-projector',[x.id,x.findingId],['La decisione è contestuale e riesaminabile. Il mapping non prova efficacia.'],x,x.state==='impact-to-assess'?'Registrare la decisione':x.state==='controls-to-map'?'Mappare un controllo':'Aprire prove e limiti',x.receipt));
 const controls=s.controls.map(x=>env(`control-${x.id}`,x.label,`${s.coverage.filter(c=>c.controlId===x.id).length} collegamenti astratti registrati.`,'control-family',x.state,'coverage-projector',[x.id],['Famiglia di controllo e mapping non provano progettazione, operatività o efficacia.'],x,'Aprire collegamenti e limiti'));
 const jobs=s.jobs.map(x=>env(`job-${x.id}`,x.label,`Ultimo stato: ${x.state}.`,'scout-job',x.state==='proposal-created'?'ai-proposed':'observed','scheduler-projector',[x.id],['Un job può osservare e proporre, non promuovere o decidere.'],x,'Eseguire il job'));
 const matters=s.matters.map(x=>env(`matter-${x.id}`,x.title,x.narrative,'matter',x.state==='facts-to-confirm'?'attention-required':x.state==='closed'?'human-reviewed':'human-owned','matter-projector',[x.id],['Categoria e urgenza iniziali non sono qualificazioni normative definitive.'],x,x.state==='facts-to-confirm'?'Confermare owner e RACI':x.state==='closed'?'Conservare la catena':'Avanzare una fase',x.receipt));
 const all=[...sources,...findings,...changes,...controls,...jobs,...matters],index=Object.fromEntries(all.map(x=>[x.id,x]));
 const nodes=all.map((x,i)=>({id:x.id,envelopeId:x.id,label:x.label,kind:x.claimClass,status:x.epistemicStatus,x:90+(i%5)*215,y:90+Math.floor(i/5)*125}));const ids=new Set(nodes.map(n=>n.id)),edges=[];const add=(from,to,type,label)=>{if(ids.has(from)&&ids.has(to))edges.push({id:`${type}-${from}-${to}`,from,to,type,label})};
 for(const x of findings){add(`source-${x.data.sourceId}`,x.id,'derived-from','ha prodotto');const job=jobs.find(j=>j.data.ecosystem===s.sources.find(v=>v.id===x.data.sourceId)?.ecosystem);if(job)add(job.id,x.id,'observed-by','ha osservato')}
 for(const x of changes){add(`finding-${x.data.findingId}`,x.id,'review-created','review apre');for(const c of x.data.controlIds||[])add(x.id,`control-${c}`,'covered-by','mappato a')}
 for(const x of sources)add(x.id,'control-control-monitor','governed-by','presidiata da');for(const x of matters){add(x.id,'control-control-incident','handled-by','gestito da');if(/dati|privacy|personali/i.test(x.data.narrative))add(x.id,'control-control-privacy','assessed-by','valutato da');if(/fornitor/i.test(x.data.narrative))add(x.id,'control-control-vendor','assessed-by','valutato da')}
 const traces=[['trace-monitoring','Presidio normativo',[['Perimetro','observed',`${sources.length} fonti`],['Differenze',findings.some(x=>x.epistemicStatus==='awaiting-human-review')?'attention-required':'observed',`${findings.filter(x=>x.epistemicStatus==='awaiting-human-review').length} review`],['Integrità',integrity.ok?'verified':'failed',`${integrity.eventCount} eventi`]]],['trace-source','Nuova conoscenza',[['Input','observed','Link o file'],['Proposta','ai-proposed','Classificazione delimitata'],['Review','awaiting-human-review','Decisione umana'],['Receipt','verified','Readback locale']]],['trace-change','Dalla differenza al controllo',[['Differenza','observed','Confronto'],['Rilevanza','human-reviewed','Review umana'],['Impatto','awaiting-human-review','Decisione'],['Copertura','mapped','Mapping astratto']]],['trace-matter','Evento o quasi incidente',[['Racconto','observed','Narrazione originale'],['Responsabilità','human-owned','Owner e RACI'],['Valutazioni','attention-required','Percorsi distinti'],['Chiusura','awaiting-human-review','Review esplicita']]]].map(([id,label,steps])=>env(id,label,'Catena ricostruita dalla stessa proiezione usata dalla UI.','runtime-trace','verified','trace-projector',steps.map((_,i)=>`${id}-${i}`),['La traccia attesta il processo locale, non la conformità.'],{steps:steps.map(([label,status,statement],i)=>({id:`${id}-${i}`,label,status,statusLabel:status,statement,producer:'runtime-projector',inputRefs:[]}))},null,integrity.head));for(const t of traces)index[t.id]=t;
 const supply=[['stage-ui','Interfaccia umana','Web leggero','operational'],['stage-api','API locale','Node.js HTTP','operational'],['stage-domain','Regole di dominio','Funzioni deterministiche','operational'],['stage-ledger','SOT locale',`${integrity.eventCount} eventi append-only`,integrity.ok?'verified':'failed'],['stage-projection','Proiezione','OutcomeEnvelope','operational'],['stage-ai','Assistente locale','Capsula read-only','bounded'],['stage-remote','Scouting remoto reale','Non presente nella beta','not-implemented']].map(([id,label,statement,status])=>env(id,label,statement,'runtime-stage',status,'supply-chain-projector',[id],['Lo stato descrive il runtime pubblicato, non una garanzia enterprise.'],{technology:statement},'Aprire il dettaglio',integrity.head));for(const x of supply)index[x.id]=x;
 const open=findings.filter(x=>x.epistemicStatus==='awaiting-human-review').length+changes.filter(x=>x.epistemicStatus==='awaiting-human-review').length+matters.filter(x=>x.data.state!=='closed').length;const headline=env('headline-attention','Ci sono decisioni da prendere',`${open} oggetti locali richiedono attenzione distribuita.`,'attention-summary',open?'attention-required':'observed','attention-projector',['findings','changes','matters'],['Il conteggio non rappresenta rischio complessivo o conformità.'],{open},'Scegliere una domanda di lavoro',integrity.head);index[headline.id]=headline;
 const balloons=[...findings.filter(x=>x.epistemicStatus==='awaiting-human-review'),...changes.filter(x=>x.epistemicStatus==='awaiting-human-review'),...matters.filter(x=>x.data.state!=='closed')].slice(0,5).map((x,i)=>({envelopeId:x.id,label:x.label,status:x.epistemicStatus,size:i%3,drift:i%4}));
 const journeys=[['journey-change','Capire cosa è cambiato',[['Parti dall’attenzione','home','Apri un balloon'],['Guarda l’origine','atlas','Apri la catena'],['Decidi la rilevanza','changes','Registra la review'],['Registra l’impatto','changes','Registra la decisione'],['Collega il controllo','changes','Mappa la copertura']]],['journey-source','Aggiungere nuova conoscenza',[['Inserisci link o file','sources','Apri il form'],['Osserva la proposta','sources','Leggi limiti e produttore'],['Completa la review','sources','Includi o escludi']]],['journey-matter','Gestire un evento',[['Racconta con parole normali','matters','Crea il caso'],['Conferma la responsabilità','matters','Conferma owner e RACI'],['Avanza una fase','matters','Registra la transizione'],['Chiudi con review','matters','Conserva prove e limiti']]]].map(([id,label,scenes])=>({id,label,scenes:scenes.map(([title,view,action],i)=>({id:`${id}-${i}`,title,question:title,view,objectType:id.includes('matter')?'matter':id.includes('source')?'source':'finding',action,support:'L’azione usa oggetti runtime e non crea conclusioni implicite.'}))}));
 return{headline,sources,findings,changes,controls,jobs,matters,traces,supply,semanticGraph:{nodes,edges},balloons,journeys,index};
}
