import crypto from 'node:crypto';
import path from 'node:path';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
const ROOT=path.resolve(new URL('..',import.meta.url).pathname);
export const RUNTIME=path.resolve(process.env.ICTC_RUNTIME_DIR||path.join(ROOT,'runtime'));
export const BLOBS=path.join(RUNTIME,'blobs');
const LEDGER=path.join(RUNTIME,'ledger.jsonl');
export const now=()=>new Date().toISOString();
export const digest=v=>crypto.createHash('sha256').update(v).digest('hex');
export const transitions={'facts-to-confirm':['owned'],owned:['assessing'],assessing:['responding'],responding:['closure-review'],'closure-review':['closed'],closed:[]};
export const seed={meta:{tenant:'Azienda Demo',version:'3.0.0-beta.1',disclaimer:'ICTC attesta operazioni locali e decisioni registrate; non certifica automaticamente applicabilità o conformità.'},sources:[
{id:'src-acn',title:'ACN — area NIS2',ecosystem:'ACN e CSIRT Italia',kind:'official-web',lifecycle:'active',reviewState:'change-awaiting-review',owner:'Compliance e Cybersecurity',lastCheckedAt:'2026-07-31T09:20:00Z'},
{id:'src-garante',title:'Garante — violazioni di dati personali',ecosystem:'Garante Privacy',kind:'official-web',lifecycle:'active',reviewState:'change-awaiting-review',owner:'DPO Office',lastCheckedAt:'2026-07-31T09:10:00Z'},
{id:'src-eurlex',title:'EUR-Lex — Regolamento (UE) 2016/679',ecosystem:'Unione europea',kind:'official-law',lifecycle:'active',reviewState:'observed',owner:'Legal e Privacy',lastCheckedAt:'2026-07-31T05:10:00Z'}],findings:[
{id:'finding-acn',sourceId:'src-acn',type:'content-change',statement:'Il contenuto osservato differisce dalla versione locale.',humanState:'awaiting-review',materiality:'undetermined',aiProposal:'Possibile aggiornamento operativo; contenuto da qualificare.'},
{id:'finding-garante',sourceId:'src-garante',type:'new-document',statement:'Un nuovo documento è stato osservato nel canale.',humanState:'awaiting-review',materiality:'undetermined',aiProposal:'Possibile rilevanza per il processo data breach.'}],jobs:[
{id:'job-acn',label:'Osservazione ACN quotidiana',ecosystem:'ACN e CSIRT Italia',state:'proposal-created'},
{id:'job-garante',label:'Osservazione Garante quotidiana',ecosystem:'Garante Privacy',state:'completed-no-change'}],controls:[
{id:'control-monitor',label:'Monitoraggio normativo',state:'evidence-available'},
{id:'control-incident',label:'Gestione incidenti',state:'operating-declared'},
{id:'control-privacy',label:'Valutazione privacy',state:'mapped'},
{id:'control-vendor',label:'Gestione fornitori',state:'mapped'}],matters:[
{id:'matter-near',title:'Allegato errato intercettato',kind:'near-miss',narrative:'Un allegato è stato bloccato prima della consegna esterna.',state:'facts-to-confirm',owner:'Privacy Operations',raci:{accountable:'DPO Office',responsible:'Privacy Operations',consulted:['Legal','IT Security'],informed:['Process Owner']},timeline:[]},
{id:'matter-supplier',title:'Accessi anomali a un portale',kind:'incident',narrative:'Accessi anomali a un portale fornitore con possibile esposizione di dati.',state:'owned',owner:'Cybersecurity Incident Manager',raci:{accountable:'CISO',responsible:'Incident Response Team',consulted:['DPO','Legal','Procurement'],informed:['Executive Sponsor']},timeline:[]}],changes:[],coverage:[]};
export async function readLedger(){try{return(await readFile(LEDGER,'utf8')).split('\n').filter(Boolean).map(JSON.parse)}catch(e){if(e.code==='ENOENT')return[];throw e}}
export function verify(events){let prev='GENESIS';for(const e of events){const{hash,...base}=e;if(e.previousHash!==prev||digest(JSON.stringify(base))!==hash)return{ok:false,eventCount:events.length,reason:`invalid ${e.id}`};prev=hash}return{ok:true,eventCount:events.length,head:prev}}
export async function append(type,payload,actor='system',producer='runtime'){await mkdir(RUNTIME,{recursive:true});const events=await readLedger(),previousHash=events.at(-1)?.hash||'GENESIS';const base={id:crypto.randomUUID(),type,actor,producer,at:now(),previousHash,payload},event={...base,hash:digest(JSON.stringify(base))};events.push(event);await writeFile(LEDGER,events.map(JSON.stringify).join('\n')+'\n');if((await readLedger()).at(-1).hash!==event.hash)throw Error('readback non verificato');return{event,receipt:{eventId:event.id,eventType:type,hash:event.hash,previousHash,persistedAt:event.at,readbackVerified:true,ledgerHead:event.hash}}}
export function apply(events){const s=structuredClone(seed);for(const e of events){const p=e.payload;switch(e.type){case'source.proposed':s.sources.push(p.source);s.findings.push(p.finding);break;case'source.reviewed':{const x=s.sources.find(v=>v.id===p.id);if(x){x.reviewState=p.outcome==='accepted'?'reviewed':'rejected';x.lifecycle=p.outcome==='accepted'?'active':'candidate';x.receipt=e.hash}}break;case'finding.reviewed':{const x=s.findings.find(v=>v.id===p.id);if(x){x.humanState=p.outcome==='relevant'?'reviewed-relevant':'reviewed-not-relevant';x.receipt=e.hash;if(p.outcome==='relevant'&&!s.changes.some(c=>c.findingId===x.id))s.changes.push({id:`change-${x.id}`,findingId:x.id,sourceId:x.sourceId,title:'Valutare la variazione osservata',state:'impact-to-assess',owner:'Compliance Decision Owner',decision:null,controlIds:[],receipt:e.hash})}}break;case'change.decided':{const x=s.changes.find(v=>v.id===p.id);if(x){x.decision={outcome:p.outcome,rationale:p.rationale,by:e.actor,at:e.at};x.state=p.outcome==='action-required'?'controls-to-map':'decision-recorded';x.receipt=e.hash}}break;case'change.control.mapped':{const x=s.changes.find(v=>v.id===p.id);if(x&&!x.controlIds.includes(p.controlId)){x.controlIds.push(p.controlId);x.state='coverage-mapped';x.receipt=e.hash}s.coverage.push({id:`coverage-${e.id}`,changeId:p.id,controlId:p.controlId,state:'mapped',receipt:e.hash})}break;case'matter.reported':s.matters.push(p.matter);break;case'matter.owner.confirmed':{const x=s.matters.find(v=>v.id===p.id);if(x){x.owner=p.owner;x.raci=p.raci;x.state='owned';x.receipt=e.hash;x.timeline.push({at:e.at,label:'Owner e RACI confermati',receipt:e.hash})}}break;case'matter.transitioned':{const x=s.matters.find(v=>v.id===p.id);if(x){x.state=p.to;x.receipt=e.hash;x.timeline.push({at:e.at,label:p.label,note:p.note||'',receipt:e.hash})}}break;case'job.completed':{const j=s.jobs.find(v=>v.id===p.job.id);if(j)Object.assign(j,p.job);if(p.finding)s.findings.push(p.finding)}break}}return s}
