import { strict as assert } from 'node:assert';
import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
const root=path.resolve(new URL('..',import.meta.url).pathname); const artifacts=path.join(root,'artifacts'); await mkdir(artifacts,{recursive:true});
const files=['README.md','CONTRIBUTING.md','SECURITY.md','SUPPORT.md','docs/README.md','docs/DEVELOPMENT.md','docs/TESTING.md','docs/CONFIGURATION.md','docs/DATA_AND_STORAGE.md','docs/OPERATIONS.md','docs/ACCESSIBILITY.md','docs/RUNTIME_AUDIT.md','docs/V1_BUYER_AUDIT.md','docs/V1_STABILITY_DOD.md','docs/CORE_UI_COPY_AUDIT.md','docs/CORE_UI_DESIGN.md','docs/CORE_UI_DOD.md','docs/MULTI_CLIENT_READINESS.md'];
const contents=new Map(); for(const file of files) contents.set(file,await readFile(path.join(root,file),'utf8'));
const checks=[]; const mark=(name,detail)=>checks.push({name,status:'passed',detail});
try{
 const readme=contents.get('README.md'); for(const value of ['## Stato corrente','## Avvio locale','## I due servizi','## Identity boundary','## Verifica','## Limiti','./ictc.sh start','npm run audit:multi-client','npm run release:check']) assert.ok(readme.includes(value),`README senza ${value}`); mark('readme-entrypoint','avvio, due servizi, identity boundary, audit e limiti');
 const journey=contents.get('docs/MULTI_CLIENT_READINESS.md'); for(const value of ['Osserva → Rivedi → Decidi → Collega → Prova','Segnala → Assegna → Valuta → Rispondi → Ripristina → Impara → Prova','M=40','M+100=140','trusted-header']) assert.ok(journey.includes(value),`journey senza ${value}`); mark('multi-client-journeys','due processi minimi, journey comune e saturazione documentati');
 const broken=[]; for(const [file,text] of contents){assert.ok(!/\<repository-url\>|\bTODO\b|\bTBD\b/gi.test(text),`${file}: placeholder`); for(const match of text.matchAll(/\[[^\]]+\]\(([^)]+)\)/g)){const link=match[1];if(/^(https?:|mailto:|#)/.test(link))continue;const local=link.split('#')[0];if(!local)continue;try{await access(path.resolve(path.dirname(path.join(root,file)),local))}catch{broken.push(`${file} -> ${link}`)}}} assert.deepEqual(broken,[]); mark('local-links',`${files.length} documenti senza link locali rotti`);
 const pkg=JSON.parse(await readFile(path.join(root,'package.json'),'utf8')); const all=[...contents.values()].join('\n'); for(const command of new Set([...all.matchAll(/npm run ([a-zA-Z0-9:_-]+)/g)].map(item=>item[1]))) assert.ok(pkg.scripts[command],`script documentato assente: ${command}`); mark('npm-commands','comandi documentati risolti');
 const operations=contents.get('docs/OPERATIONS.md'); for(const command of ['start','stop','status','logs','doctor','audit']) assert.match(operations,new RegExp(`ictc\\.sh ${command}`)); mark('operations','lifecycle locale preservato');
 const dod=contents.get('docs/V1_STABILITY_DOD.md'); assert.match(dod,/ledger, blob e sessioni/i); assert.match(dod,/M=40/); assert.match(dod,/M\+100=140/); assert.match(dod,/non SaaS enterprise/i); mark('readiness-boundary','isolamento, saturazione e limite enterprise espliciti');
 await writeFile(path.join(artifacts,'documentation-audit.json'),JSON.stringify({schemaVersion:'1.5.0',generatedAt:new Date().toISOString(),result:'passed',checks},null,2)); console.log(`docs-audit: ok (${checks.length} checks)`);
}catch(error){await writeFile(path.join(artifacts,'documentation-audit.json'),JSON.stringify({schemaVersion:'1.5.0',generatedAt:new Date().toISOString(),result:'failed',checks,error:error.message},null,2));throw error}
